### PR TITLE
Use GNUInstallDirs in cmake

### PR DESCRIPTION
**Pull request by GrayHatter**
@NicoHood @f8l

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/698)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/698#-:-KbclK3VNtRa0OjEQnMf:bnfp4nl)*

**Comment by f8l** [comment]
I have already applied this [change](https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=blob;f=uTox-git/patches/patch-src_xlib_CMakeLists.txt;h=7712fdb4bf34870f1a0ccee2cb59017d77b431f0;hb=HEAD) to pkgsrc-wip package. It works as desired at least for NetBSD.

**Comment by GrayHatter** [comment]
@NicoHood does this break Arch?

**Comment by cebe** [comment]
:lgtm_strong: works on debian

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/698#-:-KbvtbVaQF1F0gpHXiGj:b-95f5uj)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/698)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/698#-:-Kc8FBS3nOVMrBg1hux6:bnfp4nl)*

**Pull request merged**
