### PR TITLE
Merge in android fixes

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/860)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main_native.h, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiRMO1vOFVRb9nhWxVS:-KiRMO1vOFVRb9nhWxVT:b95xtzq) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/main_native.h#L1)):*
> ```objc
> #ifndef NATIVE_MAIN_H
> ```

Use native/*.h 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/860)*

**Comment by robinlinden** [comment]
Reviewed 18 of 19 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main_native.h, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiRN08qY0V41DBQhPyN:-KiRN08qY0V41DBQhPyO:b-vaepgo) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/main_native.h#L1)):*
> ```objc
> #ifndef NATIVE_MAIN_H
> ```

This really shouldn't be added back. This has been split into sane pieces and is now in native/*.h

---

*[src/android/freetype.h, line 13 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiRNSUv9U4He4TmxNxT:-KiRNSUv9U4He4TmxNxU:b5xgcz8) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/freetype.h#L13)):*
> ```objc
>     uint32_t ucs4;
>     int16_t  x, y;
>     uint16_t width, height, xadvance, xxxx;
> ```

What's xxxx?

---

*[src/android/gl.h, line 9 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiROGEMfbIonQv72wMB:-KiROGEMfbIonQv72wMC:b64jo7y) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/gl.h#L9)):*
> ```objc
> 
> #include <GLES2/gl2.h>
> #define _GNU_SOURCE
> ```

Gross. What's this needed for?

---

*[src/android/windows.h, line 0 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiROoRwkIqZ41qvg6JD:-KiROoRwkIqZ41qvg6JE:b-ipgqbv) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/windows.h#L0)):*
Why commit this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/860)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main_native.h, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiRMO1vOFVRb9nhWxVS:-KiRo6cOJmLugAaa4-xZ:b-hfpv0l) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/main_native.h#L1)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Use native/*.h 
</blockquote></details>

removed

---

*[src/main_native.h, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiRN08qY0V41DBQhPyN:-KiRo7_sTaQ9_lw1WgBJ:b-hfpv0l) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/main_native.h#L1)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This really shouldn't be added back. This has been split into sane pieces and is now in native/*.h
</blockquote></details>

removed

---

*[src/android/freetype.h, line 13 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiRNSUv9U4He4TmxNxT:-KiRnaEKAIAmbnbDPGKz:b-9unzff) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/freetype.h#L13)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

What's xxxx?
</blockquote></details>

no idea, I didn't add it... or at least I don't remember adding it.

---

*[src/android/gl.h, line 9 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiROGEMfbIonQv72wMB:-KiRnjtYsQ7oxMek_8Oa:b-c38jo) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/gl.h#L9)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Gross. What's this needed for?
</blockquote></details>

https://i.imgur.com/iZcUNxH.gif

---

*[src/android/windows.h, line  at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiROoRwkIqZ41qvg6JD:-KiRnx2YaZrZ_U95EpsF:b-9unw5o) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/windows.h#L)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why commit this?
</blockquote></details>

deleted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/860)*

**Comment by robinlinden** [comment]
Reviewed 1 of 19 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/860)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/860#-:-KibcQCDmssUHqusEFaH:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/android/gl.h, line 9 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiROGEMfbIonQv72wMB:-KitYhOxUmKE4hONG6IA:b-octv8l) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/gl.h#L9)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

https://i.imgur.com/iZcUNxH.gif
</blockquote></details>

I'd prefer if we could avoid relying on non-standard extensions where possible. If we can't drop this, we should at least have a comment on what we're using that isn't following the C standard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/860)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/android/gl.h, line 9 at r1](https://reviewable.io:443/reviews/utox/utox/860#-KiROGEMfbIonQv72wMB:-KivKKfROHWWTIV4p-uJ:b-4az0u3) ([raw file](https://github.com/utox/utox/blob/4ff6e81ee8ad92e9b84c4c9ee8b83b5b54d1b6fa/src/android/gl.h#L9)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I'd prefer if we could avoid relying on non-standard extensions where possible. If we can't drop this, we should at least have a comment on what we're using that isn't following the C standard.
</blockquote></details>

Okay, never mind. We already define this in Android's main.h, so I guess it's all GNU already. L~~G~~TM. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/860#-:-KivK_hncrEG7QlrCyiR:bnfp4nl)*

**Pull request merged**
