### PR TITLE
Move av components

### PR DESCRIPTION
**Pull request by dkmoz**
Now toxcore can restart without av threads blocking it

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/960)

### CODE REVIEW

**Comment by dkmoz** [comment]
Just wanted to point out that if you set audio filtering to false and switch the return value in audio_device_in_close from true to false everything works perfectly.

**Comment by robinlinden** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/av/audio.c, line 629 at r1](https://reviewable.io:443/reviews/utox/utox/960#-Ko3fzoAc03lB4kllp4h:-Ko3fzoAc03lB4kllp4i:bsfycrl) ([raw file](https://github.com/utox/utox/blob/07b945d79769e999faf053047b878a220d04cb90/src/av/audio.c#L629)):*
> ```C
>                 case UTOXAUDIO_CHANGE_MIC: {
>                     while (audio_in_ignore()) { continue; }
>                     while (audio_in_device_close()) { continue; }
> ```

Change this to `!audio_in_device_close()` to fix the hang, I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by endoffile78** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/av/audio.c, line 629 at r1](https://reviewable.io:443/reviews/utox/utox/960#-Ko3fzoAc03lB4kllp4h:-Ko924mER9ZN2joK03Gj:bxkfjo0) ([raw file](https://github.com/utox/utox/blob/07b945d79769e999faf053047b878a220d04cb90/src/av/audio.c#L629)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Change this to `!audio_in_device_close()` to fix the hang, I guess.
</blockquote></details>

didn't work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/av/audio.c, line 629 at r1](https://reviewable.io:443/reviews/utox/utox/960#-Ko3fzoAc03lB4kllp4h:-KpZdIhKluYZaPmHj5X1:b-jx0s0g) ([raw file](https://github.com/utox/utox/blob/07b945d79769e999faf053047b878a220d04cb90/src/av/audio.c#L629)):*
<details><summary><i>Previously, dkmoz wrote…</i></summary><blockquote>

didn't work
</blockquote></details>

Any idea of how to fix the hang? Or should I go ahead and merge this anyway since it seems to improve things?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/av/audio.c, line 629 at r1](https://reviewable.io:443/reviews/utox/utox/960#-Ko3fzoAc03lB4kllp4h:-KpZe-5Xl8EWawzADBbj:butozve) ([raw file](https://github.com/utox/utox/blob/07b945d79769e999faf053047b878a220d04cb90/src/av/audio.c#L629)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Any idea of how to fix the hang? Or should I go ahead and merge this anyway since it seems to improve things?
</blockquote></details>

If you change the return value in audio_in_device_close to false and set audio filtering to false it seems to work. That's not a long term solution though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by GrayHatter** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/tox.c, line 18 at r2](https://reviewable.io:443/reviews/utox/utox/960#-KpgB27MGHQsg8Onx3I2:-KpgB27MGHQsg8Onx3I3:b7m8f2r) ([raw file](https://github.com/utox/utox/blob/c2acb5020d121546f88fb06aab4894e98d5025d3/src/tox.c#L18)):*
> ```C
> 
> #include "av/audio.h"
> #include "av/utox_av.h"
> ```

can we drop utox_av.h now?

or av/audio.h or av/video.h... if not what's blocking that?

---

*[src/av/audio.c, line 629 at r1](https://reviewable.io:443/reviews/utox/utox/960#-Ko3fzoAc03lB4kllp4h:-KpgC8lFEzWHJT90GuRw:behabri) ([raw file](https://github.com/utox/utox/blob/07b945d79769e999faf053047b878a220d04cb90/src/av/audio.c#L629)):*
<details><summary><i>Previously, dkmoz wrote…</i></summary><blockquote>

If you change the return value in audio_in_device_close to false and set audio filtering to false it seems to work. That's not a long term solution though
</blockquote></details>

Is the hang when trying to change the mic, or elsewhere?

---

*[src/av/audio.c, line 97 at r2](https://reviewable.io:443/reviews/utox/utox/960#-KpgCdtr6bJNlPY0m7-N:-KpgCdtsBmy6NSA0kYDX:b3fecch) ([raw file](https://github.com/utox/utox/blob/c2acb5020d121546f88fb06aab4894e98d5025d3/src/av/audio.c#L97)):*
> ```C
>     audio_in_handle = NULL;
>     microphone_on = false;
>     return true; /* and the audio thread hangs... */
> ```

This should return false here.

---

*[src/av/utox_av.c, line 54 at r2](https://reviewable.io:443/reviews/utox/utox/960#-KpgBiCxpR-KQCfEzeD8:-KpgBiCyjGPoazK65PXp:bwp9pf8) ([raw file](https://github.com/utox/utox/blob/c2acb5020d121546f88fb06aab4894e98d5025d3/src/av/utox_av.c#L54)):*
> ```C
>                 if (av != NULL) {
>                     // terminate av threads
>                     postmessage_audio(UTOXAUDIO_KILL, 0, 0, NULL);
> ```

There's really no reason to kill/restart these threads, just for a new tox instance. Just update the toxav pointer, unless I'm missing something obvious?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/tox.c, line 18 at r2](https://reviewable.io:443/reviews/utox/utox/960#-KpgB27MGHQsg8Onx3I2:-KphqcHnK4J7pgT5SkwF:bwsjk4p) ([raw file](https://github.com/utox/utox/blob/c2acb5020d121546f88fb06aab4894e98d5025d3/src/tox.c#L18)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

can we drop utox_av.h now?

or av/audio.h or av/video.h... if not what's blocking that?
</blockquote></details>

Nope. Toxcore creates the ToxAV instance and sends it to utox_av control thread. audio.c and video.c define utox_default_bitrate_* used by toxcore so nothing can be dropped.

---

*[src/av/audio.c, line 629 at r1](https://reviewable.io:443/reviews/utox/utox/960#-Ko3fzoAc03lB4kllp4h:-KphrUACqGW1I3HISmQt:bjkqw5x) ([raw file](https://github.com/utox/utox/blob/07b945d79769e999faf053047b878a220d04cb90/src/av/audio.c#L629)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Is the hang when trying to change the mic, or elsewhere?
</blockquote></details>

In utox_audio_thread when audio_in_device_close is getting called

---

*[src/av/audio.c, line 97 at r2](https://reviewable.io:443/reviews/utox/utox/960#-KpgCdtr6bJNlPY0m7-N:-KphrSSclFbyNtqRVM-B:b-896fix) ([raw file](https://github.com/utox/utox/blob/c2acb5020d121546f88fb06aab4894e98d5025d3/src/av/audio.c#L97)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

This should return false here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/av/audio.c, line 88 at r3](https://reviewable.io:443/reviews/utox/utox/960#-KqroEr-1ydNrjzUhSY7:-KqroEr-1ydNrjzUhSY8:bfz0eeg) ([raw file](https://github.com/utox/utox/blob/57a7bf411f6d521cfaadbb733fd96267d8657f72/src/av/audio.c#L88)):*
> ```C
>             audio_in_handle = NULL;
>             microphone_on = false;
>             return false;
> ```

Should this be `true` now? If this function always returns `false`, why are we bothering calling it in a loop until it's `false`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/av/audio.c, line 88 at r3](https://reviewable.io:443/reviews/utox/utox/960#-KqroEr-1ydNrjzUhSY7:-KqsdaQfp5ezuhuszf0t:b-epozm4) ([raw file](https://github.com/utox/utox/blob/57a7bf411f6d521cfaadbb733fd96267d8657f72/src/av/audio.c#L88)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Should this be `true` now? If this function always returns `false`, why are we bothering calling it in a loop until it's `false`?
</blockquote></details>

skel code for opening >1 microphones... we can't yet so we return false (the state of the microphone) because the mic is in deed closed.

in the future, it should return true here, if we count handles to devices.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960#-:-Kqse5Dx8jgswsSRzmnv:bnfp4nl)*

**Comment by robinlinden** [comment]
The av threads are no longer blocking Tox thread restarts, but restarting it still doesn't work well. (Try toggling UDP off and on again ~3 times.)
Any ideas of what the problem is? It might be out of scope, so I'm fine with merging this as is if you're happy with it. Otherwise looking into it would be appreciated.

**Comment by dkmoz** [comment]
@robinlinden 
Yeah that's a weird one. It seems to get stuck in postmessage_toxcore but it's hard to tell whether is out of scope or not.
https://github.com/uTox/uTox/blob/develop/src/tox.c#L59

**Comment by GrayHatter** [comment]
:lgtm: kinda, I signed off on this last change without contex. Looks right, but I didn't confirm (a 2nd time) it didn't conflict with other changes in this pull

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960#-:-Ks-sQOYw0snEkkeVcqW:b-56d11)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/960#-:-Ks-tt11nQlq6_oDTx9w:bnfp4nl)*

**Pull request merged**
