### PR TITLE
Fix avatars

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/481)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/avatar.c, line 127 at r1](https://reviewable.io:443/reviews/utox/utox/481#-KWeHT0vxDFXl3fUWoCI:-KWeHT0wY00YCaXofW_d:bplqqcs) ([raw file](https://github.com/utox/utox/blob/c08203a6a2b98a5601bbd2392969ba325ee7e817/src/avatar.c#L127)):*
> ```C
> bool avatar_on_friend_online(Tox *tox, uint32_t friend_number) {
>     size_t   avatar_size = 0;
>     uint8_t *avatar_data = utox_data_load_avatar(-1, &avatar_size);
> ```

Generate the filename in this function, then use the native function to get the `FILE*` and then read from inside this function.

There's no reason anything outside of this file should know anything about avatars, or how they're saved or loaded.

This is a change from the way it was/is but it's what needs to be done.

Also: do we want to just keep this file in memory, instead of hitting the disk all the time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/481)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 6 files at r2.
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/avatar.c, line 16 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2Yd-lm3DK2uQ9wXhF:-KX2Yd-lm3DK2uQ9wXhG:b-pzn55g) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/avatar.c#L16)):*
> ```C
> }
> 
> bool save_avatar(char hexid[64], const uint8_t *data, size_t length) {
> ```

this was a magic number I needed to replace, it's `TOX_PUBLIC_KEY_SIZE * 2`

---

*[src/avatar.c, line 41 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2YnTSj3LG-S9_yw0W:-KX2YnTSj3LG-S9_yw0X:b-icjfx8) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/avatar.c#L41)):*
> ```C
> }
> 
> uint8_t *load_img_data(char hexid[64], size_t *out_size) {
> ```

ditto here and every where else `TOX_PUBLIC_KEY_SIZE * 2`

---

*[src/avatar.c, line 41 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2Z-LVBdsVnbiHbl04:-KX2Z-LWn4InFc-Gvamj:byt1g1w) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/avatar.c#L41)):*
> ```C
> }
> 
> uint8_t *load_img_data(char hexid[64], size_t *out_size) {
> ```

can we make this static?

---

*[src/file_transfers.c, line 859 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2_JBxmlgxredcMO6s:-KX2_JBypH4ONieVvviO:bv2emev) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/file_transfers.c#L859)):*
> ```C
>             debug("FileTransfer:\tStarting avatar to friend %u.\n", friend_number);
>             file_number = tox_file_send(tox, friend_number, TOX_FILE_KIND_AVATAR, file_data_size, file_id, NULL, 0, &error);
>             debug("FileTransfer:\t, tox_file_send error: %u", error);
> ```

debug_error

---

*[src/main.c, line 423 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2_O0Ht5aXt-KJGMQq:-KX2_O0Ht5aXt-KJGMQr:b-dk2fv1) ([raw file](https://github.com/utox/utox/blob/fb2319d5281a9a1723a72e88363b40a8da8f74de/src/main.c#L423)):*
> ```C
> }
> 
> bool utox_data_save_avatar(uint32_t friend_number, const uint8_t *data, size_t length) {
> ```

weeee merge conflicts with `develop`

no changes needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/481)*

**Comment by GrayHatter** [comment]
@endoffile78 I'll merge this myself, you don't need to bring it up to date with develop. Just clear reviewable and travis.

**Comment by endoffile78** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/avatar.c, line 127 at r1](https://reviewable.io:443/reviews/utox/utox/481#-KWeHT0vxDFXl3fUWoCI:-KX2d9lo0LBdgPhbmEQm:b-896fix) ([raw file](https://github.com/utox/utox/blob/c08203a6a2b98a5601bbd2392969ba325ee7e817/src/avatar.c#L127)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Generate the filename in this function, then use the native function to get the `FILE*` and then read from inside this function.
> 
> There's no reason anything outside of this file should know anything about avatars, or how they're saved or loaded.
> 
> This is a change from the way it was/is but it's what needs to be done.
> 
> Also: do we want to just keep this file in memory, instead of hitting the disk all the time?
</details>
Done.

---

*[src/avatar.c, line 16 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2Yd-lm3DK2uQ9wXhF:-KX2d6TXdJMDvqX9cfxL:b-896fix) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/avatar.c#L16)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> this was a magic number I needed to replace, it's `TOX_PUBLIC_KEY_SIZE * 2`
</details>
Done.

---

*[src/avatar.c, line 41 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2YnTSj3LG-S9_yw0W:-KX2d7LWuyeVLYnq4WLe:b-896fix) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/avatar.c#L41)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> ditto here and every where else `TOX_PUBLIC_KEY_SIZE * 2`
</details>
Done.

---

*[src/avatar.c, line 41 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2Z-LVBdsVnbiHbl04:-KX2d7l-JEVyPg2CTe3Z:b-896fix) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/avatar.c#L41)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> can we make this static?
</details>
Done.

---

*[src/file_transfers.c, line 859 at r2](https://reviewable.io:443/reviews/utox/utox/481#-KX2_JBxmlgxredcMO6s:-KX2dAqC7XAotdX2qktm:b-896fix) ([raw file](https://github.com/utox/utox/blob/5d25874b141fe50930443bc411e155c516ae971d/src/file_transfers.c#L859)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> debug_error
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/481)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/avatar.c, line 80 at r3](https://reviewable.io:443/reviews/utox/utox/481#-KX3-5AnvmXXikM0d5f2:-KX3-5AnvmXXikM0d5f3:bhqal37) ([raw file](https://github.com/utox/utox/blob/d1e5a13a74be0e5cd13a097c9f0020cf92342e38/src/avatar.c#L80)):*
> ```C
> 
> bool avatar_delete(char hexid[TOX_PUBLIC_KEY_SIZE * 2]) {
>     uint8_t name[sizeof("avatars/") + TOX_PUBLIC_KEY_SIZE * 2 + sizeof(".png")];
> ```

use `char` so we don't have to typecast, you can ignore the native_file warning, as that file is changed in develop

---

*[src/avatar.c, line 122 at r3](https://reviewable.io:443/reviews/utox/utox/481#-KX3-RsT2QTTS_Rda8YX:-KX3-RsT2QTTS_Rda8YY:babe4e) ([raw file](https://github.com/utox/utox/blob/d1e5a13a74be0e5cd13a097c9f0020cf92342e38/src/avatar.c#L122)):*
> ```C
> bool avatar_set(AVATAR *avatar, const uint8_t *data, size_t size) {
>     if (!avatar) {
>         debug("Avatars:\t avatar is not allocated.\n");
> ```

`is null`

---

*[src/avatar.h, line 83 at r3](https://reviewable.io:443/reviews/utox/utox/481#-KX3-mA4X0harKb90nAO:-KX3-mA4X0harKb90nAP:b-d4bwjm) ([raw file](https://github.com/utox/utox/blob/d1e5a13a74be0e5cd13a097c9f0020cf92342e38/src/avatar.h#L83)):*
> ```objc
>  * returns false on failure
>  */
> bool save_avatar(char hexid[TOX_PUBLIC_KEY_SIZE * 2], const uint8_t *data, size_t length);
> ```

avatar_save

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/481)*

**Comment by endoffile78** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/avatar.c, line 80 at r3](https://reviewable.io:443/reviews/utox/utox/481#-KX3-5AnvmXXikM0d5f2:-KX4SWG-VEkq0I4EnndU:b-896fix) ([raw file](https://github.com/utox/utox/blob/d1e5a13a74be0e5cd13a097c9f0020cf92342e38/src/avatar.c#L80)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> use `char` so we don't have to typecast, you can ignore the native_file warning, as that file is changed in develop
</details>
Done.

---

*[src/avatar.c, line 122 at r3](https://reviewable.io:443/reviews/utox/utox/481#-KX3-RsT2QTTS_Rda8YX:-KX4SWmxJpdxOqwTeff2:b-896fix) ([raw file](https://github.com/utox/utox/blob/d1e5a13a74be0e5cd13a097c9f0020cf92342e38/src/avatar.c#L122)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> `is null`
</details>
Done.

---

*[src/avatar.h, line 83 at r3](https://reviewable.io:443/reviews/utox/utox/481#-KX3-mA4X0harKb90nAO:-KX4Sb3NFHZbyEYd51hf:b-896fix) ([raw file](https://github.com/utox/utox/blob/d1e5a13a74be0e5cd13a097c9f0020cf92342e38/src/avatar.h#L83)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> avatar_save
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/481)*

**Comment by GrayHatter** [comment]
:lgtm_strong: 

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/avatar.c, line 85 at r4](https://reviewable.io:443/reviews/utox/utox/481#-KX4Vhf2MOCQEGc3UiWZ:-KX4Vhf2MOCQEGc3UiW_:buy5xjj) ([raw file](https://github.com/utox/utox/blob/abfff5b2f1da2214a822f73e7240fa89274917cf/src/avatar.c#L85)):*
> ```C
> 
> #ifdef __WIN32__
>     int name_len = snprintf((char *)name, sizeof("avatars/") + TOX_PUBLIC_KEY_SIZE * 2 + sizeof(".png"),
> ```

drop this typecast

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/481#-:-KX4W39jxD88Zear9nXD:b-uwkowd)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/481)*

**Pull request merged**
