### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/504)

### CODE REVIEW

**Comment by robinlinden** [comment]
In general, try to use uint8_t where the string is likely to be utf8 and char elsewhere.

---

Reviewed 5 of 21 files at r1.
Review status: 5 of 21 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/commands.c, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHbgaGnVjScuARdaCB:-KXHbgaHlhkaPMsj33vu:bofsgq) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/commands.c#L4)):*
> ```C
> #include "commands.h"
> 
> #include "util.h"
> ```

What change to this file required you to include util.h?

---

*[src/commands.c, line 127 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcDSu_0yNzjDtLgdG:-KXHcDSu_0yNzjDtLgdH:b-v5xmv1) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/commands.c#L127)):*
> ```C
> 
>     // wtf??
>     uint8_t * b = (uint8_t *)edit_add_id.data, *a = url_string, *end = url_string + len;
> ```

Should we maybe change the edit struct to store data in uint8_t?

---

*[src/file_transfers.c, line 416 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcemNhaSLSW3njHHY:-KXHcemNhaSLSW3njHHZ:b-kn61ad) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/file_transfers.c#L416)):*
> ```C
> /* Friend has come online, restart our outgoing transfers to this friend. */
> void ft_friend_online(Tox *tox, uint32_t friend_number) {
>     for (unsigned int i = 0; i < MAX_FILE_TRANSFERS; i++) {
> ```

size_t

---

*[src/friend.c, line 79 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcyt3apvlNCbk3bbC:-KXHcyt3apvlNCbk3bbD:b-gof1uv) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L79)):*
> ```C
> 
>     if (metadata->alias_length) {
>         friend_set_alias(&friend[friend_id], (char *)&metadata->data[0], metadata->alias_length);
> ```

Should we maybe change friend_set_alias to take a uint8_t *alias?

---

*[src/friend.c, line 122 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHd6SX6ICW6_9bDLro:-KXHd6SY-5ynZoisfIqy:b-fs51b7) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L122)):*
> ```C
>     size              = tox_friend_get_status_message_size(tox, friend_number, 0);
>     f->status_message = calloc(1, size);
>     tox_friend_get_status_message(tox, friend_number, (uint8_t *)f->status_message, 0);
> ```

Should name, alias, and status_message in the struct utox_friend be uint8_t?

---

*[src/friend.c, line 224 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHfvJLpBn5hyyWnvVw:-KXHfvJLpBn5hyyWnvVx:b3oli5v) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L224)):*
> ```C
> }
> 
> void friend_notify_msg(FRIEND *f, const char *msg, size_t msg_length) {
> ```

Keep this uint8_t since it's likely to be utf8.

---

*[src/friend.c, line 272 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHg1vuNvB2UfYyK8A0:-KXHg1vvyGvkxYlaS-z6:bsi96ni) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L272)):*
> ```C
>     }
> 
>     char     name_cleaned[length];
> ```

uint8_t

---

*[src/friend.c, line 338 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHg4DvqmAkN7Gu2wqR:-KXHg4DvqmAkN7Gu2wqS:bsi96ni) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L338)):*
> ```C
> }
> 
> FRIEND *find_friend_by_name(char *name) {
> ```

uint8_t

---

*[src/friend.c, line 354 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHg5bIiO56bcqhGKTF:-KXHg5bIiO56bcqhGKTG:bsi96ni) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L354)):*
> ```C
>     }
> 
>     char title[UTOX_FRIEND_NAME_LENGTH(f) + 20];
> ```

uint8_t

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504#-:-KXHe_57SIxtp5OXkE39:b-j8jtpl)*

**Comment by endoffile78** [comment]
Review status: 4 of 21 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/commands.c, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHbgaGnVjScuARdaCB:-KXHh7KZj2CZMJcVRdTU:btmjb9y) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/commands.c#L4)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> What change to this file required you to include util.h?
</details>
`string_to_id` and `utox_write_metadata` are defined in util.c, they are both used in commands.c.

---

*[src/file_transfers.c, line 416 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcemNhaSLSW3njHHY:-KXHjS1kPjTGpEA1AoOB:b-896fix) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/file_transfers.c#L416)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> size_t
</details>
Done.

---

*[src/friend.c, line 79 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcyt3apvlNCbk3bbC:-KXHjd1DcdycA1sSGSol:b-v4qnxt) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L79)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Should we maybe change friend_set_alias to take a uint8_t *alias?
</details>
I think that would be a good.

---

*[src/friend.c, line 122 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHd6SX6ICW6_9bDLro:-KXHjfxmJgoQPxfFK7b6:b-u5m1fb) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L122)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Should name, alias, and status_message in the struct utox_friend be uint8_t?
</details>
I think they should be because thats what toxcore uses for it and like you said there could be utf8 in it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Comment by robinlinden** [comment]
Reviewed 11 of 21 files at r1, 1 of 3 files at r2.
Review status: 15 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/file_transfers.c, line 416 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcemNhaSLSW3njHHY:-KXHmBcp9W2eCWyohlGA:bxtswxp) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/file_transfers.c#L416)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary>
> Done.
</details>
Forgot about this line. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Comment by endoffile78** [comment]
Review status: 14 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/commands.c, line 127 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcDSu_0yNzjDtLgdG:-KXHyMZCF7DhIAzHCjPs:b3c6mf6) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/commands.c#L127)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Should we maybe change the edit struct to store data in uint8_t?
</details>
I think that would be good but maybe in a different pr.

---

*[src/file_transfers.c, line 416 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHcemNhaSLSW3njHHY:-KXHyRwYtWUXvCpYsT8H:b-896fix) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/file_transfers.c#L416)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Forgot about this line. 
</details>
Done.

---

*[src/friend.c, line 224 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHfvJLpBn5hyyWnvVw:-KXHySzr42b-9UEnPNC3:b-896fix) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L224)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Keep this uint8_t since it's likely to be utf8.
</details>
Done.

---

*[src/friend.c, line 272 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHg1vuNvB2UfYyK8A0:-KXHyTNDCa21ysgi9suv:b-896fix) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L272)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> uint8_t
</details>
Done.

---

*[src/friend.c, line 338 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHg4DvqmAkN7Gu2wqR:-KXHyThjYj914eV2gNb_:b-896fix) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L338)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> uint8_t
</details>
Done.

---

*[src/friend.c, line 354 at r1](https://reviewable.io:443/reviews/utox/utox/504#-KXHg5bIiO56bcqhGKTF:-KXHyU1ipaeWu-KHQu9m:b-896fix) ([raw file](https://github.com/utox/utox/blob/d20df0aabf36755afd06031321a42f49cdf3a833/src/friend.c#L354)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> uint8_t
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Comment by robinlinden** [comment]
Reviewed 3 of 21 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/friend.h, line 108 at r3](https://reviewable.io:443/reviews/utox/utox/504#-KXI4syx-BkNHVs6PQ9b:-KXI4syx-BkNHVs6PQ9c:bvuqihe) ([raw file](https://github.com/utox/utox/blob/7ce6a9ed2efcd94695b54266c36243fa4878155c/src/friend.h#L108)):*
> ```objc
> void friend_recvimage(FRIEND *f, NATIVE_IMAGE *native_image, uint16_t width, uint16_t height);
> 
> void friend_notify_msg(FRIEND *f, const char *msg, size_t msg_length);
> ```

This `msg` is now `const char*` while the one for `friend_notify_status` is `const uint8_t*`. Make them the same.

---

*[src/friend.h, line 126 at r3](https://reviewable.io:443/reviews/utox/utox/504#-KXI5AlFvk5uxckP7h8g:-KXI5AlFvk5uxckP7h8h:bjprizb) ([raw file](https://github.com/utox/utox/blob/7ce6a9ed2efcd94695b54266c36243fa4878155c/src/friend.h#L126)):*
> ```objc
> 
> /* Notifies the user that a friend is online or offline */
> void friend_notify_status(FRIEND *f, const uint8_t *msg, size_t msg_length, char *state);
> ```

See comment for line 108.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/friend.h, line 108 at r3](https://reviewable.io:443/reviews/utox/utox/504#-KXI4syx-BkNHVs6PQ9b:-KXI5xh0KxA_FH7gU6y6:bb2d3gj) ([raw file](https://github.com/utox/utox/blob/7ce6a9ed2efcd94695b54266c36243fa4878155c/src/friend.h#L108)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> This `msg` is now `const char*` while the one for `friend_notify_status` is `const uint8_t*`. Make them the same.
</details>
LGTM. I misread.

---

*[src/friend.h, line 126 at r3](https://reviewable.io:443/reviews/utox/utox/504#-KXI5AlFvk5uxckP7h8g:-KXI6-jFe3-COEneZ5-u:b-hxzuon) ([raw file](https://github.com/utox/utox/blob/7ce6a9ed2efcd94695b54266c36243fa4878155c/src/friend.h#L126)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> See comment for line 108.
</details>
LGTM. See Line 108.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504#-:-KXI690a0BWNjFgrrD2U:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 21 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/commands.h, line 12 at r4](https://reviewable.io:443/reviews/utox/utox/504#-KXJ5ETNs2qEck5a2t34:-KXJ5ETNs2qEck5a2t35:bspql3y) ([raw file](https://github.com/utox/utox/blob/73cd3f7639d507673371b6f7de6dde82e02db77b/src/commands.h#L12)):*
> ```objc
>  * TODO, make sure the file exists.
>  */
> int slash_send_file(FRIEND *friend_handle, const char *filepath);
> ```

we need to change this to pass the string to the native_ functions. Otherwise this high a high likelihood of breaking windows if the filename in UTF8

---

*[src/tox.c, line 149 at r4](https://reviewable.io:443/reviews/utox/utox/504#-KXJ6MJcKMp4QxJ2N9hH:-KXJ6MJdyQ6cy7XAJ0by:bcwdd4u) ([raw file](https://github.com/utox/utox/blob/73cd3f7639d507673371b6f7de6dde82e02db77b/src/tox.c#L149)):*
> ```C
> 
>     self.name_length = tox_self_get_name_size(tox);
>     tox_self_get_name(tox, (uint8_t *)self.name);
> ```

self.name should probably become uint8_t as well

---

*[src/tox.c, line 288 at r4](https://reviewable.io:443/reviews/utox/utox/504#-KXJ6ZYbJ5FulvkOqcQ_:-KXJ6TNzOkPdz4-oW_EM:b-z9tnk) ([raw file](https://github.com/utox/utox/blob/73cd3f7639d507673371b6f7de6dde82e02db77b/src/tox.c#L288)):*
> ```C
> }
> 
> static void log_callback(Tox *UNUSED(tox), TOX_LOG_LEVEL UNUSED(level), const char *UNUSED(file), uint32_t UNUSED(line), const char *func,
> ```

FYI this whole function could really use some TLC it would be nice to add this as a full feature thing we could use. (Don't worry about this yet... For now it's still out of scope)

---

*[src/av/audio.c, line 732 at r4](https://reviewable.io:443/reviews/utox/utox/504#-KXJ7Gbce7sVWdBoNrle:-KXJ7Gbd087bn5Z9kaiX:b-1oubc3) ([raw file](https://github.com/utox/utox/blob/73cd3f7639d507673371b6f7de6dde82e02db77b/src/av/audio.c#L732)):*
> ```C
> 
>                 if (voice) {
>                     size_t i, active_call_count = 0;
> ```

FYI fine for now, but needs a rewrite soon-ish

---

*[src/ui/edits.c, line 142 at r4](https://reviewable.io:443/reviews/utox/utox/504#-KXJ7Wt_bNwPYPCEYv_4:-KXJ7Wt_bNwPYPCEYv_5:blj19t4) ([raw file](https://github.com/utox/utox/blob/73cd3f7639d507673371b6f7de6dde82e02db77b/src/ui/edits.c#L142)):*
> ```C
>         }
> 
>         char *nick      = (char *)p->name;
> ```

reverse this typecast, these are all group names and at least one will be UTF8

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 21 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 21 files at r1, 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/504)*

**Pull request merged**
