### PR TITLE
Add assembly info on Windows

### PR DESCRIPTION
**Pull request by redmanmale**
Fix for #869.

It looks like this:
pic

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/880)

### CODE REVIEW

**Comment by redmanmale** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/utox.rc, line 9 at r1](https://reviewable.io:443/reviews/utox/utox/880#-KipVdwCF1AztydiDRtx:-KipVdwD8SrxByoZPhr4:bb14iva) ([raw file](https://github.com/utox/utox/blob/ffa2c7d45d26d012ef52718ed54da4a2c9164052/src/windows/utox.rc#L9)):*
> ```
> 
> // TODO FIXME: That's not OK, I know.
> #include <../../../src/branding.h>
> ```

I know it's bad, but I couldn't done it differently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by GrayHatter** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/windows/utox.rc, line 9 at r1](https://reviewable.io:443/reviews/utox/utox/880#-KipVdwCF1AztydiDRtx:-Kipd4mN3ZvvMy69RCHE:bqzwblf) ([raw file](https://github.com/utox/utox/blob/ffa2c7d45d26d012ef52718ed54da4a2c9164052/src/windows/utox.rc#L9)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

I know it's bad, but I couldn't done it differently.
</blockquote></details>

this fails travis, try just `#include "../branding.h"` and see if that makes travis happy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by redmanmale** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/utox.rc, line 9 at r1](https://reviewable.io:443/reviews/utox/utox/880#-KipVdwCF1AztydiDRtx:-Kipiq9xhKMkIKoVZ_VL:b-896fix) ([raw file](https://github.com/utox/utox/blob/ffa2c7d45d26d012ef52718ed54da4a2c9164052/src/windows/utox.rc#L9)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this fails travis, try just `#include "../branding.h"` and see if that makes travis happy
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by GrayHatter** [comment]
:lgtm:

+@robinlinden confirm and merge

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880#-:-KipuctBRkOClr-MY5Hy:b-yrncsx)*

**Comment by robinlinden** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/branding.h.in, line 20 at r2](https://reviewable.io:443/reviews/utox/utox/880#-KipuwWvBPG5zWakp7TS:-KipuwWvBPG5zWakp7TT:bv1eliv) ([raw file](https://github.com/utox/utox/blob/743b4b7e8bbf512f9f4652f0190c011b62734f59/src/branding.h.in#L20)):*
> ```
> // Assembly info
> #define UTOX_FILE_DESCRIPTION "The lightweight Tox client"
> #define UTOX_COPYRIGHT "Copyleft 2017 uTox Contributors. Some Rights Reserved."
> ```

Is it intentional that every word is capitalized? Looks really odd in my opinion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/branding.h.in, line 20 at r2](https://reviewable.io:443/reviews/utox/utox/880#-KipuwWvBPG5zWakp7TS:-KipvrdRnJKRFQfhqvvt:bs6ozxz) ([raw file](https://github.com/utox/utox/blob/743b4b7e8bbf512f9f4652f0190c011b62734f59/src/branding.h.in#L20)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Is it intentional that every word is capitalized? Looks really odd in my opinion.
</blockquote></details>

No, I just copied that part from the macos info.
Is `Copyleft 2017 uTox contributors. Some rights reserved.` better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/branding.h.in, line 20 at r2](https://reviewable.io:443/reviews/utox/utox/880#-KipuwWvBPG5zWakp7TS:-KipwMIq7d4jtZHB0Z1q:b-d2t6of) ([raw file](https://github.com/utox/utox/blob/743b4b7e8bbf512f9f4652f0190c011b62734f59/src/branding.h.in#L20)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

No, I just copied that part from the macos info.
Is `Copyleft 2017 uTox contributors. Some rights reserved.` better?
</blockquote></details>

I like that version more. :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by robinlinden** [comment]
Tried it. Works fine. :lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880#-:-KipxBWGjKaxqS9rr_y1:b-hwx9cg)*

**Comment by redmanmale** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/branding.h.in, line 20 at r2](https://reviewable.io:443/reviews/utox/utox/880#-KipuwWvBPG5zWakp7TS:-Kipy1QRmGFoXZZXoXWX:b-896fix) ([raw file](https://github.com/utox/utox/blob/743b4b7e8bbf512f9f4652f0190c011b62734f59/src/branding.h.in#L20)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I like that version more. :P
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/880#-:-KipyVVz7XH7Gg3jr6pl:bnfp4nl)*

**Pull request merged**
