### PR TITLE
Fix POSIX native_get_file.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/526)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/android/main.c, line 202 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYWackCkY1r-yyByBks:-KYWackDbDB2D0cYynuA:bzgai7q) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L202)):*
> ```C
> // one would fix this.
> static void mode_from_file_opts(UTOX_FILE_OPTS opts, char *mode) {
>     if (opts & UTOX_FILE_OPTS_READ) {
> ```

Is there a reason this is seperated from the append and write checks. Same for the one in the posix file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/android/main.c, line 199 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXR0GsBjELS3qHRMDq:-KYXR0GsBjELS3qHRMDr:b-ew14yy) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L199)):*
> ```C
> 
> // TODO: DRY. This function exists in both posix/filesys.c and in android/main.c
> // Make a posix native_get_file that you pass a complete path to instead of letting it construct
> ```

FYI -- android is strange, so it's probably better to not try to mix posix with android.

---

*[src/android/main.c, line 201 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXSB7UX85I-5czrCGZ:-KYXRV771oPYysAQ5oCx:bfjowf3) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L201)):*
> ```C
> // Make a posix native_get_file that you pass a complete path to instead of letting it construct
> // one would fix this.
> static void mode_from_file_opts(UTOX_FILE_OPTS opts, char *mode) {
> ```

why is this a function?

---

*[src/android/main.c, line 202 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYWackCkY1r-yyByBks:-KYXQVM0zXz5vuB5L0_m:bp3rafg) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L202)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Is there a reason this is seperated from the append and write checks. Same for the one in the posix file.
</blockquote></details>

yes, because it's over written later if it's wrong. Where as in an else if, the latter will take precedence, and + will be appended if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/android/main.c, line 199 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXR0GsBjELS3qHRMDq:-KYY7V-w0ufQxa1_lqX2:bcuivfx) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L199)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

FYI -- android is strange, so it's probably better to not try to mix posix with android.
</blockquote></details>

In a lot of (our) cases the logic of the functions is identical. The main difference is that Android has a stupid folder hierarchy. 

See e.g. `native_remove_file`, `native_get_file` and `flush_file`

---

*[src/android/main.c, line 201 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXSB7UX85I-5czrCGZ:-KYY7jd1R-xkC1KLTtXC:b-3iolo8) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L201)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why is this a function?
</blockquote></details>

To make native_get_file half the length and easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/android/main.c, line 201 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXSB7UX85I-5czrCGZ:-KYayAbNiYrnt1DxaGhA:b-do3b3m) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L201)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

To make native_get_file half the length and easier to read.
</blockquote></details>

I personally like it being a function. I agree with @robinlinden that it makes it easier to read.

---

*[src/android/main.c, line 202 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYWackCkY1r-yyByBks:-KYay4Nuv-hc3St--7lH:b2nhktp) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L202)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yes, because it's over written later if it's wrong. Where as in an else if, the latter will take precedence, and + will be appended if needed.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526#-:-KYayYjOsI98Wn4gOmRC:bnfp4nl)*

**Comment by endoffile78** [comment]
I just noticed that it doesn't compile on windows and OSX.

:lgtm_cancel: 

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526#-:-KYaylrZJsKwtb8ddZBZ:bt67evz)*

**Comment by robinlinden** [comment]
Fixed the incorrect function declarations and native_create_dir missing from cocoa, so it passes Travis now.

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526#-:-KYdZKMXKcWfuG_od4sA:bj72icd)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r3.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526#-:-KYd_IS06Hnl6MSBpsUb:bnfp4nl)*

**Comment by endoffile78** [comment]
Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Comment by GrayHatter** [comment]
+@endoffile78 yours to approve

---

Reviewed 1 of 2 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.h, line 313 at r3](https://reviewable.io:443/reviews/utox/utox/526#-KYezG-kp6CkyJOcJdXD:-KYezG-l9wivcuqWksSL:bxklfq1) ([raw file](https://github.com/utox/utox/blob/59555460618ab9a2e2a97051c2a3e40a20b3e2ad/src/main.h#L313)):*
> ```objc
> 
> 
> FILE *native_get_file(const char *name, size_t *size, UTOX_FILE_OPTS opts);
> ```

conflicts with other pull, needs to be uint8_t

---

*[src/android/main.c, line 199 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXR0GsBjELS3qHRMDq:-KYezOEroJ0ClVsgrxbh:b-qukw7u) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L199)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

In a lot of (our) cases the logic of the functions is identical. The main difference is that Android has a stupid folder hierarchy. 

See e.g. `native_remove_file`, `native_get_file` and `flush_file`
</blockquote></details>

I'm all for it, but not in this pull.  We'll take a week and update/work on android

---

*[src/android/main.c, line 201 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXSB7UX85I-5czrCGZ:-KYezUm9R0Q-QA12foHL:bd3t9vm) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L201)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

I personally like it being a function. I agree with @robinlinden that it makes it easier to read.
</blockquote></details>

LGTM just rename it opts to sysmode or something like that naming should be WHATYOUGIVE_to_WHATYOUGET

---

*[src/windows/filesys.c, line 40 at r3](https://reviewable.io:443/reviews/utox/utox/526#-KYezrRL-0H4H4wp2FhU:-KYezrRM-weib8Yn6kQD:b-7icc07) ([raw file](https://github.com/utox/utox/blob/59555460618ab9a2e2a97051c2a3e40a20b3e2ad/src/windows/filesys.c#L40)):*
> ```C
> }
> 
> FILE *native_get_file(const char *name, size_t *size, UTOX_FILE_OPTS opts) {
> ```

uint8

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526#-:-KYf--ICr-RPJpNS5kYf:b-s69a3x)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Comment by robinlinden** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/main.h, line 313 at r3](https://reviewable.io:443/reviews/utox/utox/526#-KYezG-kp6CkyJOcJdXD:-KYfdlwOCJ5R54RAAgkk:b-896fix) ([raw file](https://github.com/utox/utox/blob/59555460618ab9a2e2a97051c2a3e40a20b3e2ad/src/main.h#L313)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

conflicts with other pull, needs to be uint8_t
</blockquote></details>

Done.

---

*[src/android/main.c, line 199 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXR0GsBjELS3qHRMDq:-KYf_6sceMEJ7EUzW6iy:b-pbdqz3) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L199)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I'm all for it, but not in this pull.  We'll take a week and update/work on android
</blockquote></details>

Agreed.

---

*[src/android/main.c, line 201 at r1](https://reviewable.io:443/reviews/utox/utox/526#-KYXSB7UX85I-5czrCGZ:-KYfcE3q4Sc5X2rDSvyg:b-896fix) ([raw file](https://github.com/utox/utox/blob/ee2aa73e741e5422370e5941904d710524aec499/src/android/main.c#L201)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

LGTM just rename it opts to sysmode or something like that naming should be WHATYOUGIVE_to_WHATYOUGET
</blockquote></details>

Done.

---

*[src/windows/filesys.c, line 40 at r3](https://reviewable.io:443/reviews/utox/utox/526#-KYezrRL-0H4H4wp2FhU:-KYfcmKJoYdl8Duf-xCu:b-896fix) ([raw file](https://github.com/utox/utox/blob/59555460618ab9a2e2a97051c2a3e40a20b3e2ad/src/windows/filesys.c#L40)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

uint8
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Comment by GrayHatter** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526#-:-KYgPqHhupsb7rit_nEc:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/526)*

**Pull request merged**
