### PR TITLE
Fix avatars, and mkdir for posix

### PR DESCRIPTION
**Pull request by GrayHatter**
Merge after #603

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/604)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/604#-:-Ka5k9U0iiUxQnR4xWD4:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 25 of 25 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/file_transfers.c, line 369 at r1](https://reviewable.io:443/reviews/utox/utox/604#-Ka2vEccqTO7FvnRerYT:-Ka2vEcdQUqJGk3NHCxB:b9p32em) ([raw file](https://github.com/utox/utox/blob/cece6955e3b681a4c3fe3350e5fa7ccfac446bd4/src/file_transfers.c#L369)):*
> ```C
>         case FILE_TRANSFER_STATUS_BROKEN:
>         case FILE_TRANSFER_STATUS_COMPLETED:
>         case FILE_TRANSFER_STATUS_KILLED: {
> ```

Add a default case here for the unknown states.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/604#-:-Ka6RqJdhniLjamPubE9:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/file_transfers.c, line 369 at r1](https://reviewable.io:443/reviews/utox/utox/604#-Ka2vEccqTO7FvnRerYT:-Ka6jLRZ1vaDeyk3GTe3:b-5plts3) ([raw file](https://github.com/utox/utox/blob/cece6955e3b681a4c3fe3350e5fa7ccfac446bd4/src/file_transfers.c#L369)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Add a default case here for the unknown states.
</blockquote></details>

We don't need to, with the typedef'd enum, we'd get a warning about unhandled cases. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/604)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/file_transfers.c, line 369 at r1](https://reviewable.io:443/reviews/utox/utox/604#-Ka2vEccqTO7FvnRerYT:-Ka6jaKjdCV-fwSNQRsS:b-dnqz3p) ([raw file](https://github.com/utox/utox/blob/cece6955e3b681a4c3fe3350e5fa7ccfac446bd4/src/file_transfers.c#L369)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

We don't need to, with the typedef'd enum, we'd get a warning about unhandled cases. 
</blockquote></details>

Ah, I only looked at the previous code and the debug_error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/604)*

**Pull request merged**
