### PR TITLE
Fix chat export crash on macOS. Fixes #1030

### LINKED ISSUE #1030: Crash while exporting chat history at macOS
# Crash while exporting chat history at macOS

- [Steps to reproduce](#steps-to-reproduce)
- [Details](#details)
- [System Crash Report](#system-crash-report-compact)
- [Source code (actual)](#source-code-actual)

## Steps to reproduce
In `Contacts` list: Context menu - `Friend Settings`
- `Export Chatlog as plain text`
- Set file name in `Save` dialog
- **Crash**

## Details

Crash after `button_export_chatlog_on_mup`:
- `button_export_chatlog_on_mup`
- `fread`
- `flockfile`

## System Crash Report (compact)

```
Process:               utox [XXXX]
Path:                  /Applications/uTox.app/Contents/MacOS/utox
Identifier:            io.utox.future
Version:               0.16.1 (0.16.1)
Code Type:             X86-64 (Native)
```

```
OS Version:            Mac OS X 10.11.6
```

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000068
Exception Note:        EXC_CORPSE_NOTIFY
```

```
VM Regions Near 0x68:
-->
    __TEXT                 0000000100000000-00000001001f9000 [ 2020K] r-x/rwx SM=COW  /Applications/uTox.app/Contents/MacOS/utox
```

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_c.dylib             	0x00007fff91d8c09e flockfile + 4
1   libsystem_c.dylib             	0x00007fff91d8ddf6 fread + 31
2   io.utox.future                	0x0000000100193913 button_export_chatlog_on_mup + 851
3   io.utox.future                	0x000000010005d319 button_mup + 41
4   io.utox.future                	0x000000010001b673 panel_mup + 35
5   io.utox.future                	0x000000010001b68b panel_mup + 59
6   io.utox.future                	0x000000010001b68b panel_mup + 59
7   io.utox.future                	0x000000010001b68b panel_mup + 59
8   io.utox.future                	0x000000010001b68b panel_mup + 59
9   io.utox.future                	0x000000010001b68b panel_mup + 59

```

## Source code (actual)
- [src/layout/settings.c](../blob/5e3fb3fe51278f38baf71eeafd06ff6e4ba39cb8/src/layout/settings.c)
```c
static void button_export_chatlog_on_mup(void) {
    FRIEND *f = flist_get_friend();
    if (!f) {
        LOG_ERR("Settings", "Could not get selected friend.");
        return;
    }
    utox_export_chatlog_init(f->number);
}
```
- [src/chatlog.c](../blob/5e3fb3fe51278f38baf71eeafd06ff6e4ba39cb8/src/chatlog.c)
```c
void utox_export_chatlog_init(uint32_t friend_number) {
    native_export_chatlog_init(friend_number);
}

```
- [src/cocoa/interaction.m](../blob/5c72785efa807739f4b004ec8ab3bc0abf7d4bd8/src/cocoa/interaction.m)

```Objective-C
void native_export_chatlog_init(uint32_t fid) {

    FRIEND *f = get_friend(fid);

    <...>

    if (ret == NSFileHandlingPanelOKButton) {
        NSURL *destination = picker.URL;
        // FIXME: might be leaking
        utox_export_chatlog(fid, strdup(destination.path.UTF8String));
    }
}
```

- [src/chatlog.c](../blob/5e3fb3fe51278f38baf71eeafd06ff6e4ba39cb8/src/chatlog.c)
```c
void utox_export_chatlog(char hex[TOX_PUBLIC_KEY_SIZE * 2], FILE *dest_file) {
    if (!dest_file) {
        return;
    }

    LOG_FILE_MSG_HEADER header;
    FILE *file = chatlog_get_file(hex, false);

    struct tm *tm_curr;
    struct tm_tmp {
        int tm_year;
        int tm_mon;
        int tm_mday;
    } tm_prev = { .tm_mday = 1};

    while (fread(&header, sizeof(header), 1, file) == 1) {

        tm_curr = localtime(&header.time);

        char buffer[128];
        if (tm_curr->tm_year > tm_prev.tm_year
            || (tm_curr->tm_year == tm_prev.tm_year && tm_curr->tm_mon > tm_prev.tm_mon)
            || (tm_curr->tm_year == tm_prev.tm_year && tm_curr->tm_mon == tm_prev.tm_mon && tm_curr->tm_mday > tm_prev.tm_mday))
        {
            size_t len = strftime(buffer, 128,  "Day has changed to %A %B %d %Y\n", tm_curr);
            fwrite(buffer, len, 1, dest_file);
        }

        /* Write Timestamp */
        fprintf(dest_file, "[%02d:%02d]", tm_curr->tm_hour, tm_curr->tm_min);
        tm_prev.tm_year = tm_curr->tm_year;
        tm_prev.tm_mon = tm_curr->tm_mon;
        tm_prev.tm_mday = tm_curr->tm_mday;

        int c;
        if (header.msg_type == MSG_TYPE_NOTICE) {
            fseek(file, header.author_length, SEEK_CUR);
        } else {
            /* Write Author */
            fwrite(" <", 2, 1, dest_file);
            for (size_t i = 0; i < header.author_length; ++i) {
                c = fgetc(file);
                if (c != EOF) {
                    fputc(c, dest_file);
                }
            }
            fwrite(">", 1, 1, dest_file);
        }

        /* Write text */
        fwrite(" ", 1, 1, dest_file);
        for (size_t i = 0; i < header.msg_length; ++i) {
            c = fgetc(file);
            if (c != EOF) {
                fputc(c, dest_file);
            }
        }
        c = fgetc(file); /* the newline char */
        fputc(c, dest_file);
    }

    fclose(file);
    fclose(dest_file);
}
```

### PR DESCRIPTION
**Pull request by publicarray**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1031)

### CODE REVIEW

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/interaction.m, line 917 at r1](https://reviewable.io:443/reviews/utox/utox/1031#-Kt6OcVEwcyEI4zv7Agl:-Kt6OcVFmCJZDu8zXuKf:b-pcs1yp) ([raw file](https://github.com/utox/utox/blob/62b02bb949a25b4c96d7facefc9434eaa9ea6267/src/cocoa/interaction.m#L917)):*
> ```objc
>         FILE *file = utox_get_file_simple(destination.path.UTF8String, UTOX_FILE_OPTS_WRITE | UTOX_FILE_OPTS_MKDIR);
>         if (!file) {
>             LOG_ERR("Cocoa", "Could write to file: %s", destination.path.UTF8String);
> ```

Could **not** write to file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1031)*

**Comment by robinlinden** [comment]
:lgtm_strong: (aside from what redmanmale already pointed out)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1031#-:-Kt6cQVFkVdWDgBQngEZ:b58p9gb)*

**Comment by publicarray** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/interaction.m, line 917 at r1](https://reviewable.io:443/reviews/utox/utox/1031#-Kt6OcVEwcyEI4zv7Agl:-Kt8XRVg5ppon_of6Lo3:b-896fix) ([raw file](https://github.com/utox/utox/blob/62b02bb949a25b4c96d7facefc9434eaa9ea6267/src/cocoa/interaction.m#L917)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Could **not** write to file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1031)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1031#-:-KtARjclN6EM9gAnOnUj:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1031)*

**Pull request merged**
