### PR TITLE
Allow users to log errors to a file

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/737)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737#-:-KcthzTgPV81rAv8c6a4:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/logging.c, line 17 at r1](https://reviewable.io:443/reviews/utox/utox/737#-KcwjtqpI2vGtkni9R2j:-KcwjtqpI2vGtkni9R2k:bq1fcos) ([raw file](https://github.com/utox/utox/blob/7af2c90a2965cc0b98b00278f0b807f82d696d0d/src/logging.c#L17)):*
> ```C
> 
>     if (settings.debug_file) {
>         file = fopen(settings.debug_file, "a+");
> ```

this would mean to open and close the file each time a message is logged, right? that would mean a lot of IO, we should better open that file once and then append to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737#-:-KcwlEJUTOuyeBnOREx3:bnfp4nl)*

**Comment by endoffile78** [comment]
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/logging.c, line 17 at r1](https://reviewable.io:443/reviews/utox/utox/737#-KcwjtqpI2vGtkni9R2j:-Kcy_Oj5kDaPoT48M29w:b-896fix) ([raw file](https://github.com/utox/utox/blob/7af2c90a2965cc0b98b00278f0b807f82d696d0d/src/logging.c#L17)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

this would mean to open and close the file each time a message is logged, right? that would mean a lot of IO, we should better open that file once and then append to it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737#-:-KcyqkZ0wWhkt4FvroIK:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737#-:-Kd1NI9sKSAZ2QdscW_E:b-jbsf8z)*

**Comment by GrayHatter** [comment]
I need to review this, IIRC there's a better way to do this

**Comment by GrayHatter** [comment]
Reviewed 4 of 9 files at r1, 4 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/logging.c, line 14 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7PP_o-X2qYTNhguYr:-Kd7PP_o-X2qYTNhguYs:b332wjv) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/logging.c#L14)):*
> ```C
> void debug(const char *fmt, ...){
>     va_list list;
>     FILE *file = stderr;
> ```

drop this, just use `settings.debug_file` through out this function

---

*[src/main.c, line 257 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7OwJsq48XndKJjgzv:-Kd7OwJsq48XndKJjgzw:bhu399w) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/main.c#L257)):*
> ```C
>                 settings.debug_file = fopen(optarg, "a+");
>                 if (!settings.debug_file) {
>                     LOG_NORM("Could not open %s. Logging to stderr.\n", optarg);
> ```

and then reset to `stdout`

---

*[src/settings.c, line 60 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7OSvSs6vlT-9umT_F:-Kd7OSvTQoJKHxgDz9Zu:b6s8uhi) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/settings.c#L60)):*
> ```C
> 
>     .verbose = LOG_LVL_ERROR,
>     .debug_file = NULL,
> ```

this is where you set it to `stdout`

---

*[src/cocoa/main.m, line 482 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7P14pHwfU8qDMjptP:-Kd7P14pHwfU8qDMjptQ:bi6gneq) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/cocoa/main.m#L482)):*
> ```objc
>     LOG_TRACE(__FILE__, "clean exit" );
> 
>     if (settings.debug_file) {
> ```

DRY create `utox_raze(void);`in src/main.c and then add it just before each main() exits.

---

*[src/windows/main.c, line 1102 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7PAvEPz0q6yUx6zjb:-Kd7PAvEPz0q6yUx6zjc:b-k29q4l) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/windows/main.c#L1102)):*
> ```C
>     LOG_INFO("uTox", "Clean exit." );
> 
>     if (settings.debug_file) {
> ```

DRY use `utox_raze()`

---

*[src/xlib/main.c, line 1025 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7PF3pBviuUv0zd7Y9:-Kd7PF3pBviuUv0zd7YA:b2nhcva) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/xlib/main.c#L1025)):*
> ```C
>     LOG_ERR("XLIB", "XLIB main:\tClean exit\n");
> 
>     if (settings.debug_file) {
> ```

DRY

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737)*

**Comment by endoffile78** [comment]
Review status: 4 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/logging.c, line 14 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7PP_o-X2qYTNhguYr:-Kd7a9yOgMm598PC2nK_:b-896fix) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/logging.c#L14)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

drop this, just use `settings.debug_file` through out this function
</blockquote></details>

Done.

---

*[src/main.c, line 257 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7OwJsq48XndKJjgzv:-Kd7aAdp-8IVW-JGgd54:b-896fix) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/main.c#L257)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

and then reset to `stdout`
</blockquote></details>

Done.

---

*[src/settings.c, line 60 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7OSvSs6vlT-9umT_F:-Kd7aCDxUwBt30VVQa1T:b-896fix) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/settings.c#L60)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this is where you set it to `stdout`
</blockquote></details>

Done.

---

*[src/cocoa/main.m, line 482 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7P14pHwfU8qDMjptP:-Kd7aFUB9qqxQoq5mJJ4:b-896fix) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/cocoa/main.m#L482)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

DRY create `utox_raze(void);`in src/main.c and then add it just before each main() exits.
</blockquote></details>

Done.

---

*[src/windows/main.c, line 1102 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7PAvEPz0q6yUx6zjb:-Kd7aGGuQDvxo66MiQp1:b-896fix) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/windows/main.c#L1102)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

DRY use `utox_raze()`
</blockquote></details>

Done.

---

*[src/xlib/main.c, line 1025 at r2](https://reviewable.io:443/reviews/utox/utox/737#-Kd7PF3pBviuUv0zd7Y9:-Kd7aGz7SGE-5QWNBs1s:b-896fix) ([raw file](https://github.com/utox/utox/blob/01ec90699c90fbe9b68a2edcb709ee5f5caa41cf/src/xlib/main.c#L1025)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

DRY
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737#-:-Kd7c__4vyMMYUvBcFOp:bnfp4nl)*

**Comment by GrayHatter** [comment]
@endoffile78 you broke windows

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 647 at r4](https://reviewable.io:443/reviews/utox/utox/737#-KdCaM9QggLEcoELMlyn:-KdCaM9QggLEcoELMlyo:bltmsrt) ([raw file](https://github.com/utox/utox/blob/1fcd3b6acd42702db55adfcb3d72c27eb36bc587/src/xlib/main.c#L647)):*
> ```C
>     bool   skip_updater, from_updater;
> 
>     // Load settings before calling utox_init()
> ```

Is this a TODO?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737#-:-KdCaSyWjLgwfzNo2U4A:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 647 at r4](https://reviewable.io:443/reviews/utox/utox/737#-KdCaM9QggLEcoELMlyn:-KdCb-8pGbue6jZnhKsG:bjxlmaa) ([raw file](https://github.com/utox/utox/blob/1fcd3b6acd42702db55adfcb3d72c27eb36bc587/src/xlib/main.c#L647)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Is this a TODO?
</blockquote></details>

no, I'll remove it in my sweep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/737)*

**Pull request merged**
