### PR TITLE
Cleanup includes

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/646)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/dns.c, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/646#-KbOuc0fqesQ2rjoQTX3:-KbOuc0fqesQ2rjoQTX4:bvfa73v) ([raw file](https://github.com/utox/utox/blob/c7779266703cbccf5710aa210da30deb9f020a2b/src/dns.c#L5)):*
> ```C
> #include "logging_native.h"
> #include "macros.h"
> #include "main.h"
> ```

This is included twice now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/646)*

**Comment by endoffile78** [comment]
Review status: 3 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/dns.c, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/646#-KbOuc0fqesQ2rjoQTX3:-KbXm2gBWVbcGzcFX1k-:b-896fix) ([raw file](https://github.com/utox/utox/blob/c7779266703cbccf5710aa210da30deb9f020a2b/src/dns.c#L5)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This is included twice now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/646)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/dns.c, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/646#-KbOuc0fqesQ2rjoQTX3:-KbXmM9-jkoqHiTxmivk:blmhr3a) ([raw file](https://github.com/utox/utox/blob/c7779266703cbccf5710aa210da30deb9f020a2b/src/dns.c#L5)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

From 2 to 0. :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/646#-:-KbXmXSDuW2olb29Uzst:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 4 of 11 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/646#-:-KbZWPUe_pB4ZE_OqhBZ:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/646#-:-Kb__4GKd9DTuCyqTdrh:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/646#-:-KbaW3aPG93dsBkG_trT:bnfp4nl)*

**Pull request merged**
