### PR TITLE
v0.11.1 to master

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/560)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/560)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/560#-:-KZTDMH80DoUyUlCu27U:bg7igkv)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/560#-:-KZTDSvTjYmaKO3If85f:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/560#-:-KZTEit7mw50DgTzrS2j:bnfp4nl)*

**Pull request merged**
