### PR TITLE
Remove old debug macros

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/750)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

will conflict with @cebe's pull, but it'll be trival. No reason not to merge

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/750#-:-Kd7S_kmtpUyYYUZZB2j:b-fkeygi)*

**Comment by cebe** [comment]
:lgtm: @grayhatter merge this, I will rebase my PR then.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/750#-:-Kd7bshh7D0wqgg9kpsr:bjhc6iq)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/750#-:-Kd7cQERqqg16tx4TgJz:bnfp4nl)*

**Comment by GrayHatter** [comment]
@endoffile78 re-rebase?

**Pull request merged**
