### PR TITLE
Write '\0' instead of 0 in ft_decon_resumeable

### LINKED ISSUE #556: passing a null pointer for dereference, presumably not intentional
src/file_transfers.c:

157: fwrite(0, 1, size, file);

(the first argument to fwrite() is expected to be a pointer)

### PR DESCRIPTION
**Pull request by robinlinden**
Fixes #556

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/559)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/559#-:-KZT437Lfte_ZQxvwFO1:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/559#-:-KZT6nnzj5S1vT7OscS4:bnfp4nl)*

**Comment by x368** [comment]
Dear developers, all three of you, are you serious? One of you may have been distracted or tired and made an error (twice) but the "correction" went through a "review" of to others. You do not want this fact posted elsewhere but next time I see such kind of an error in tox I _will_ do.

Your code has been "improved" from `fwrite(0, .....) ` to `fwrite('\0', 1, size, file);`

The first argument to fwrite() is a _pointer_ and you pass an integer which is 0, in both cases.

This seems to be wrong in another sense too: whatever array you give as the first argument, it must be at least as large as the size argument. If you mean to overwrite the file, this is a completely wrong try to implement it.

**Comment by GrayHatter** [comment]
You're worng is this case. The code as it is no. Is correct. I can explain why if you'd like?

**Comment by x368** [comment]
sure I would appreciate your explanation

**Comment by GrayHatter** [comment]
Ah, you are correct. My understanding of fwrite was incorrect. You have my apologies.

**Comment by x368** [comment]
Thanks. Apologies accepted.

**Comment by x368** [comment]
Btw you did not have to apologize. To question each other's judgement is no offence. I was upset by the regrettable state and management of the particular code, not by your remark.
Good we now agree on the technical matter.
Thanks for your work on uTox! It has many nice qualities. I hope it matures to be able to function as a reliable, serious tool.

**Pull request merged**
