### PR TITLE
Fixed Hanging GUI when changing network settings

### LINKED ISSUE #544: GUI freeze when I try to change network settings 0.9.7
1. extract utox_windows_x86-64.zip
2. open utox.exe
3. GO to network tab, click IPv6's green square, next UDP, next Proxy's "disable" box, and click IPv6.
4. GUI freeze! (tested twice, happened twice)

### PR DESCRIPTION
**Pull request by cebe**
In case of an error in `init_toxcore()` currently `tox_thread_init`
is not set to `1` causing the thread calling `tox_settingschanged()` to wait forever in
[this loop](https://github.com/uTox/uTox/blob/1835eae7a96a1335f781308b0afa730ab3647483/src/tox.c#L211-L213).

There are two error situations, the first is simple, waiting for
password input before tox can connect. The second is fatal error when
utox is unable to create a tox instance. The last one was failing here.
It is now fixed by handling this case in an exctra condition in
`toxcore_thread()`.

I have also fixed the error condition in `init_toxcore()` to fail only
if `*tox == NULL`, the other parts of the condition make no sense.

Additionally the Toggle of the UDP button got inverted when setting a
proxy, this is fixed by updating the button at the same time when
updating the setting.

Also disabling the UDP button when enabling proxy makes sense to avoid
creating impossible config combination.

Finally in the error sitatuation a link is created from the "Not
Connected" message to the network tab to allow adjusting the settings
quickly.

fixes #544

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/569)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569#-:-KZXTVkQPYmr2cddqUsN:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 6 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[langs/en.h, line 380 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDvQKRRK2WIrGPQeH:-KZYDvQKRRK2WIrGPQeI:b-2ovpah) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/langs/en.h#L380)):*
> ```objc
> 
> msgid(NOT_CONNECTED_ERROR)
> msgstr("Adjust network settings")
> ```

Either of these needs to change the text doesn't' really match the event, or the NAME of the text.

perhaps `NOT_CONNECTED_NOTICE` because it's not describing an error, it's telling you how to fix it.

or `incompatible network settings`

Either way, what the code in question is actually doing it trying to create a toxcore instance. It has no bearing on if toxcore will actually connect. ONLY if toxcore is able to run with these settings.

---

*[src/main.h, line 173 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDp8pCmopYijCOZ2j:-KZYDp8pCmopYijCOZ2k:be6uyqa) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/main.h#L173)):*
> ```objc
> 
> /* Super global vars */
> volatile bool tox_thread_init, tox_thread_error, utox_av_ctrl_init, utox_audio_thread_init, utox_video_thread_init;
> ```

I don't like super globals, but it seems unavoidable in this case.

---

*[src/tox.c, line 364 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYAyVIjoZyJcrea8NF:-KZYAyVJDX6Yr-mpsiTA:bm4oxn0) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L364)):*
> ```C
>     if (*tox == NULL) {
>         if (settings.force_proxy) {
>             debug("\t\tError #%u, Not going to try without proxy because of user settings.\n", tox_new_err);
> ```

this should be `debug_error` or at least `debug_notice`

---

*[src/tox.c, line 377 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYC9S54a2JUNeUKI8W:-KZYC9S54a2JUNeUKI8X:bwua4sp) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L377)):*
> ```C
> 
>         if (*tox == NULL) {
>             debug("\t\tError #%u, Going to try without IPv6.\n", tox_new_err);
> ```

shouldn't we try dropping ipv6 first, before attempting to drop the proxy?

The proxy could be important safety measure.

---

*[src/tox.c, line 448 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYCQktICRy1WC7J0d9:-KZYCQktICRy1WC7J0dA:b-aobduz) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L448)):*
> ```C
>             // fatal failure, unable to create tox instance
>             debug_error("Tox:\tUnable to create Tox Instance (%d)\n", toxcore_init_err);
>             // set init to true because other code is waiting for it.
> ```

I don't like this. we shouldn't set init without it actually being initialized. Do you know how hard it would be to rewrite the sections that depend on this section to ignore init when needed?

My concern is that now uTox is lying about it's current state. Saying that toxcore is initialized when it's not. 

---

*[src/ui/dropdowns.c, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDSo3St9F4z4z7PXu:-KZYDSo3St9F4z4z7PXv:bp2o7af) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/ui/dropdowns.c#L10)):*
> ```C
> #include "../theme.h"
> #include "../util.h"
> #include "switches.h"
> ```

this should be on a line of it's own above all includes in the higher directiory

```
#include "dropdowns.h"
 
#include "switches.h"

#include "../av/utox_av.h"
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[langs/en.h, line 380 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDvQKRRK2WIrGPQeH:-KZYMzCAl8aNSk2SfWNh:b-mejehb) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/langs/en.h#L380)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Either of these needs to change the text doesn't' really match the event, or the NAME of the text.

perhaps `NOT_CONNECTED_NOTICE` because it's not describing an error, it's telling you how to fix it.

or `incompatible network settings`

Either way, what the code in question is actually doing it trying to create a toxcore instance. It has no bearing on if toxcore will actually connect. ONLY if toxcore is able to run with these settings.
</blockquote></details>

I think UI-wise the "Adjust network settings" is fine, it implies that because of the network settings you are not connected + it allows the necessary action when clicking on it. So I would rename it to `ADJUST_NETWORK_SETTINGS`?
I chose this name to have similarity of the tag to `NOT_CONNECTED` message which is shown directly above it.

---

*[src/main.h, line 173 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDp8pCmopYijCOZ2j:-KZYNw-gYBqOWg3USJKY:bwdv9mv) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/main.h#L173)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I don't like super globals, but it seems unavoidable in this case.
</blockquote></details>

we could combine the state into `tox_thread_init`so it would be an integer that is 0 when initializing, 1 if ok, 2 if error. That would at least avoid the case where you forget what it means.

---

*[src/tox.c, line 364 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYAyVIjoZyJcrea8NF:-KZYOLuv2qfwfGel5LHE:bbjv7hx) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L364)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this should be `debug_error` or at least `debug_notice`
</blockquote></details>

sure, did not know that these exist :)

---

*[src/tox.c, line 377 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYC9S54a2JUNeUKI8W:-KZYOUR9qeYfhz4gD9-O:b6lj5j4) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L377)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

shouldn't we try dropping ipv6 first, before attempting to drop the proxy?

The proxy could be important safety measure.
</blockquote></details>

I have no knowledge about how it is handled in toxcore internally but if the proxy needs ipv6 to work it does not make sense to drop IPv6 first.
Also this code is only executed if you set the proxy to "fallback". When setting the proxy to always, utox is not trying to do any connection without the proxy. That behavior is fine imo.

---

*[src/tox.c, line 448 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYCQktICRy1WC7J0d9:-KZYPH-n8Aw2JAIHSiXR:b-460gk1) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L448)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I don't like this. we shouldn't set init without it actually being initialized. Do you know how hard it would be to rewrite the sections that depend on this section to ignore init when needed?

My concern is that now uTox is lying about it's current state. Saying that toxcore is initialized when it's not. 
</blockquote></details>

the thing with the current code of utox is that it is written in a way that assumes tox is always there. there is and init state of the tox thread and also connected. we have no state that indicates an offline mode caused by incorrect settings. This error state is now available via `tox_thread_error` but as said above could be combined into one variable.

---

*[src/ui/dropdowns.c, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDSo3St9F4z4z7PXu:-KZYPo26CjenFWXV1j-P:b32wtd) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/ui/dropdowns.c#L10)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this should be on a line of it's own above all includes in the higher directiory

```
#include "dropdowns.h"
 
#include "switches.h"

#include "../av/utox_av.h"
...
```
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[langs/en.h, line 380 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDvQKRRK2WIrGPQeH:-KZ_9TuaPtpaNz-bNdnD:b-71vzqa) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/langs/en.h#L380)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

I think UI-wise the "Adjust network settings" is fine, it implies that because of the network settings you are not connected + it allows the necessary action when clicking on it. So I would rename it to `ADJUST_NETWORK_SETTINGS`?
I chose this name to have similarity of the tag to `NOT_CONNECTED` message which is shown directly above it.
</blockquote></details>

how about `NOT_CONNECTED_SETTINGS` then it reads as NOT_CONNECTED_because_of_your_SETTINGS

---

*[src/main.h, line 173 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDp8pCmopYijCOZ2j:-KZ_9cMxuJZrtInzssUi:bvd1j89) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/main.h#L173)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

we could combine the state into `tox_thread_init`so it would be an integer that is 0 when initializing, 1 if ok, 2 if error. That would at least avoid the case where you forget what it means.
</blockquote></details>

@cebe that sounds good, make it a typedef enum instead. I'm totally okay with that.

---

*[src/tox.c, line 377 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYC9S54a2JUNeUKI8W:-KZ_9o7xcA2bEl67cUq6:bhxx5cz) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L377)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

I have no knowledge about how it is handled in toxcore internally but if the proxy needs ipv6 to work it does not make sense to drop IPv6 first.
Also this code is only executed if you set the proxy to "fallback". When setting the proxy to always, utox is not trying to do any connection without the proxy. That behavior is fine imo.
</blockquote></details>

I agree, this is fine then.

---

*[src/tox.c, line 448 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYCQktICRy1WC7J0d9:-KZ_9vOzY7OU7l4xVnzv:b-swewop) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L448)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

the thing with the current code of utox is that it is written in a way that assumes tox is always there. there is and init state of the tox thread and also connected. we have no state that indicates an offline mode caused by incorrect settings. This error state is now available via `tox_thread_error` but as said above could be combined into one variable.
</blockquote></details>

I agree, per the above comment, use an enum, and I'll be happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569)*

**Comment by cebe** [comment]
Review status: 1 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[langs/en.h, line 380 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDvQKRRK2WIrGPQeH:-K_1gsTvFxvzRpy2xoQV:b-896fix) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/langs/en.h#L380)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

how about `NOT_CONNECTED_SETTINGS` then it reads as NOT_CONNECTED_because_of_your_SETTINGS
</blockquote></details>

Done.

---

*[src/main.h, line 173 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDp8pCmopYijCOZ2j:-K_1ngZxIEMSBcj4o3fX:b-896fix) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/main.h#L173)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

@cebe that sounds good, make it a typedef enum instead. I'm totally okay with that.
</blockquote></details>

Done.

---

*[src/tox.c, line 364 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYAyVIjoZyJcrea8NF:-K_1oFBUavGoLh7d_O1X:b-896fix) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L364)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

sure, did not know that these exist :)
</blockquote></details>

Done.

---

*[src/tox.c, line 448 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYCQktICRy1WC7J0d9:-K_1oOESfTvUo51Cwi73:b-896fix) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/tox.c#L448)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I agree, per the above comment, use an enum, and I'll be happy.
</blockquote></details>

Done.

---

*[src/ui/dropdowns.c, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/569#-KZYDSo3St9F4z4z7PXu:-K_1ofYHB5Qc1NRZB4Vg:b-896fix) ([raw file](https://github.com/utox/utox/blob/d5bbe6271ab898bd2862ba1495b4670b214529dc/src/ui/dropdowns.c#L10)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569)*

**Comment by GrayHatter** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.h, line 183 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_1u-7RhJX_5kYSPlpM:-K_1u-7ScHfHJTzi9iVp:bobqt49) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/main.h#L183)):*
> ```objc
>     // this means a tox instance may have not been created
>     UTOX_TOX_THREAD_INIT_ERROR = 2,
> } tox_thread_init;
> ```

make this a typedef enum

and volatile shouldn't be needed

---

*[src/tox.c, line 444 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2ZiObw5ltwwIM8dO9:-K_2ZiOcDgy1-QTYkE28:bj8b3v9) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/tox.c#L444)):*
> ```C
>         reconfig = 0;
> 
>         toxcore_init_err = init_toxcore(&tox);
> ```

BTW, this might read better as a `switch (init_toxcore()) {`

your call

---

*[src/ui/buttons.c, line 61 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2_IxiWC96nqo-DVgb:-K_2_IxiWC96nqo-DVgc:b-7ah796) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/ui/buttons.c#L61)):*
> ```C
> static void button_name_on_mup(void) {
>     flist_selectsettings();
>     if (tox_thread_init != UTOX_TOX_THREAD_INIT_SUCCESS) {
> ```

did you test how these work with a password?

---

*[src/ui/switch.c, line 107 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2_ckmyAZ6-jKPbPUp:-K_2_ckniE3HjhlbSc0m:b-qzfg9o) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/ui/switch.c#L107)):*
> ```C
>         return 1;
>     }
>     if (s->mousedown) {
> ```

drop the above, and `if (s->mousedown && !s->disabled) {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569)*

**Comment by robinlinden** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569)*

**Comment by cebe** [comment]
Review status: 12 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.h, line 183 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_1u-7RhJX_5kYSPlpM:-KaZ3ofXH3SjaUAlpilM:b-896fix) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/main.h#L183)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

make this a typedef enum

and volatile shouldn't be needed
</blockquote></details>

Done.

---

*[src/tox.c, line 444 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2ZiObw5ltwwIM8dO9:-KaZ48n36osqcDHqsBUg:bqe8wsw) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/tox.c#L444)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW, this might read better as a `switch (init_toxcore()) {`

your call
</blockquote></details>

not really, it can be -2, !=0, or else

---

*[src/ui/buttons.c, line 61 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2_IxiWC96nqo-DVgb:-KaZ5o4SffmGVOeVuQl1:b-1kz0h8) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/ui/buttons.c#L61)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

did you test how these work with a password?
</blockquote></details>

yes, works fine. The main issue with a password is that you have to re-enter it again as soon as you change a network setting. But other than that it works fine.

---

*[src/ui/switch.c, line 107 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2_ckmyAZ6-jKPbPUp:-KaZ4v4NypZ3TTZT_fcm:b-2y87g9) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/ui/switch.c#L107)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

drop the above, and `if (s->mousedown && !s->disabled) {`
</blockquote></details>

Done. kept the reset of mousedown.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/buttons.c, line 61 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2_IxiWC96nqo-DVgb:-KaZmqO61vSJ3hboxrxl:bexl8mq) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/ui/buttons.c#L61)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

yes, works fine. The main issue with a password is that you have to re-enter it again as soon as you change a network setting. But other than that it works fine.
</blockquote></details>

we'll accept that for now

---

*[src/ui/switch.c, line 107 at r2](https://reviewable.io:443/reviews/utox/utox/569#-K_2_ckmyAZ6-jKPbPUp:-KaZmwoGzsB_jsATJNod:bb6ywmx) ([raw file](https://github.com/utox/utox/blob/2b1faf468fac5b80e7a5ca96806a130e7d55f126/src/ui/switch.c#L107)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

Done. kept the reset of mousedown.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569#-:-KaZn-zGvippCE8msJ9l:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/569#-:-KaZnyL6X4oivX_7sRIW:bnfp4nl)*

**Pull request merged**
