### PR TITLE
Don't use old Toxcore

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1153)

### CODE REVIEW

**Comment by GrayHatter** [comment]
No

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1153#-:-L3AcO2b0aRcI-FOJh1n:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1153#-:-L3HwqmOb1uAJHsFTg5L:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1153#-:-L72MYSR6-esvla0C_7H:bnfp4nl)*

**Comment by robinlinden** [comment]
This PR is part of #1157 now.

**Pull request closed without merging**
