### PR TITLE
Add ability to change nospam

### LINKED ISSUE #406: [feature request] Ability to change «nospam» part of ToxID from µTox UI.
### Existing behaviour

Tox ID now shown as a single line of hex digits, without distinction between _public key_, _nospam_ and _checksum_ parts.
### Intended behaviour
- [ ] Different parts of ToxID are either shown separately, separated with spaces (dashes, colons, other symbols), or highlited with different colours, while still maintaining the ability to copy ToxID as a whole.
- [ ] There is a message, that explains parts of ToxID and their intended purpose to the user, as well as the repercussions of changing _nospam_ value.
- [ ] There is a control, that lets users generate random _nospam_ in one click.
- [ ] There is a control, that lets users set their _nospam_ manually.
### For bonus points
- [ ] Ability to change _nospam_ by schedule (once in _n_ hours/days/weeks, etc.), or on every _n_ –th client start.

### PR DESCRIPTION
**Pull request by endoffile78**
Closes #406 

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/513)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/buttons.c, line 405 at r1](https://reviewable.io:443/reviews/utox/utox/513#-KXSHhEqbaApGfYKI-gz:-KXSHhEqbaApGfYKI-h-:b-9zyk8p) ([raw file](https://github.com/utox/utox/blob/7606f969752fc4448273a0371d57a0612560f5fb/src/ui/buttons.c#L405)):*
> ```C
> }
> 
> static void button_change_nospam_onpress(void) {
> ```

Should we require a confirmation or at least display some information about what this does before changing the user's nospam?

---

*[src/ui/edits.c, line 610 at r1](https://reviewable.io:443/reviews/utox/utox/513#-KXSGDRPDYCVKxANZ1cQ:-KXSGDRPDYCVKxANZ1cR:b-yz57a8) ([raw file](https://github.com/utox/utox/blob/7606f969752fc4448273a0371d57a0612560f5fb/src/ui/edits.c#L610)):*
> ```C
>     edit_nospam = {.length            = sizeof(uint32_t) * 2,
>                    .data              = self.nospam_str,
>                    .readonly          = 1,
> ```

Make these true or false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by endoffile78** [comment]
Review status: 4 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/ui/buttons.c, line 405 at r1](https://reviewable.io:443/reviews/utox/utox/513#-KXSHhEqbaApGfYKI-gz:-KXSPirzt5gE--A7ZTuT:b-304dmv) ([raw file](https://github.com/utox/utox/blob/7606f969752fc4448273a0371d57a0612560f5fb/src/ui/buttons.c#L405)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Should we require a confirmation or at least display some information about what this does before changing the user's nospam?
</details>
I dont think thats needed because your tox id is updated immediately and changing nospam only prevents friend requests from people who have your old id.

---

*[src/ui/edits.c, line 610 at r1](https://reviewable.io:443/reviews/utox/utox/513#-KXSGDRPDYCVKxANZ1cQ:-KXSQ6Vca9hZDE9Ja-Da:b-896fix) ([raw file](https://github.com/utox/utox/blob/7606f969752fc4448273a0371d57a0612560f5fb/src/ui/edits.c#L610)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Make these true or false.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by robinlinden** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/avatar.c, line 228 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXTVevfFbxBqWTBncpS:-KXTVevgfLezFHE1b2HJ:bfeb9bc) ([raw file](https://github.com/utox/utox/blob/9435a27c715fea2cdb4ced8957a283909c8b82ba/src/avatar.c#L228)):*
> ```C
> }
> 
> bool avatar_move(char *current, char *new) {
> ```

`new` is a reserved word in C++. Maybe `bool avatar_move(char *from, char *to)`? Or current and destination? Anything but new, pretty much.

---

*[src/avatar.h, line 95 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXTWAi_n-dImP5WXXNy:-KXTWAia4jgIM-cIsuSD:b4dixsk) ([raw file](https://github.com/utox/utox/blob/9435a27c715fea2cdb4ced8957a283909c8b82ba/src/avatar.h#L95)):*
> ```objc
> bool avatar_init_self(void);
> 
> /* Moves the avatar to the new.png */
> ```

Missing a space between new and .png

---

*[src/avatar.h, line 96 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXT_LGEJ7dkI4hm3OCg:-KXT_LGF6A4u9Gg9KuJC:b-vj8w0h) ([raw file](https://github.com/utox/utox/blob/9435a27c715fea2cdb4ced8957a283909c8b82ba/src/avatar.h#L96)):*
> ```objc
> 
> /* Moves the avatar to the new.png */
> bool avatar_move(char *current, char *new);
> ```

uint8_t instead of char

---

*[src/ui/buttons.c, line 608 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXT_v_ocQt0mSuj8Uow:-KXT_v_ocQt0mSuj8Uox:b-rj5ci9) ([raw file](https://github.com/utox/utox/blob/9435a27c715fea2cdb4ced8957a283909c8b82ba/src/ui/buttons.c#L608)):*
> ```C
> 
> BUTTON button_revert_nospam = {
>     .nodraw       = true,
> ```

Add `.disabled = true,` and use that in `button_revert_nospam_onpress` and `button_change_nospam_onpress` in addition to `nodraw`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by endoffile78** [comment]
Review status: 14 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/avatar.c, line 228 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXTVevfFbxBqWTBncpS:-KXUXRJBFm135M4LVnt0:b-896fix) ([raw file](https://github.com/utox/utox/blob/2acfd65fe74cd4f19d08f564dab0de38eff0177d/src/avatar.c#L228)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> `new` is a reserved word in C++. Maybe `bool avatar_move(char *from, char *to)`? Or current and destination? Anything but new, pretty much.
</details>
Done.

---

*[src/avatar.h, line 95 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXTWAi_n-dImP5WXXNy:-KXUXSNzTi_Rb8dSLHpo:b-896fix) ([raw file](https://github.com/utox/utox/blob/2acfd65fe74cd4f19d08f564dab0de38eff0177d/src/avatar.h#L95)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Missing a space between new and .png
</details>
Done.

---

*[src/avatar.h, line 96 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXT_LGEJ7dkI4hm3OCg:-KXUXT57qFbzCMZjNapg:b-896fix) ([raw file](https://github.com/utox/utox/blob/2acfd65fe74cd4f19d08f564dab0de38eff0177d/src/avatar.h#L96)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> uint8_t instead of char
</details>
Done.

---

*[src/ui/buttons.c, line 608 at r2](https://reviewable.io:443/reviews/utox/utox/513#-KXT_v_ocQt0mSuj8Uow:-KXUXU6mCIIv7lajhyD8:b-896fix) ([raw file](https://github.com/utox/utox/blob/2acfd65fe74cd4f19d08f564dab0de38eff0177d/src/ui/buttons.c#L608)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Add `.disabled = true,` and use that in `button_revert_nospam_onpress` and `button_change_nospam_onpress` in addition to `nodraw`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513#-:-KXXh-U9Hg1-UcKEVtMK:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 5 of 8 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/posix/filesys.c, line 62 at r4](https://reviewable.io:443/reviews/utox/utox/513#-KYjsXkDyQdD_Oyv-Hc5:-KYjsXkDyQdD_Oyv-Hc6:b-848pqd) ([raw file](https://github.com/utox/utox/blob/07cd09a5f686dacf7fd0c2c290cbcb7d946a5eda/src/posix/filesys.c#L62)):*
> ```C
> }
> 
> bool native_move_file(char *current_name, char *new_name) {
> ```

const uint8_t *

---

*[src/windows/filesys.c, line 183 at r4](https://reviewable.io:443/reviews/utox/utox/513#-KYjschISpd0kAR5aYWH:-KYjschISpd0kAR5aYWI:b-848pqd) ([raw file](https://github.com/utox/utox/blob/07cd09a5f686dacf7fd0c2c290cbcb7d946a5eda/src/windows/filesys.c#L183)):*
> ```C
> }
> 
> bool native_move_file(char *current_name, char *new_name) {
> ```

const uint8_t *

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by endoffile78** [comment]
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/posix/filesys.c, line 62 at r4](https://reviewable.io:443/reviews/utox/utox/513#-KYjsXkDyQdD_Oyv-Hc5:-KYk3l1pRjlhdy1mygvJ:b-896fix) ([raw file](https://github.com/utox/utox/blob/07cd09a5f686dacf7fd0c2c290cbcb7d946a5eda/src/posix/filesys.c#L62)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

const uint8_t *
</blockquote></details>

Done.

---

*[src/windows/filesys.c, line 183 at r4](https://reviewable.io:443/reviews/utox/utox/513#-KYjschISpd0kAR5aYWH:-KYk3lxdsTSM8VvNyQFz:b-896fix) ([raw file](https://github.com/utox/utox/blob/07cd09a5f686dacf7fd0c2c290cbcb7d946a5eda/src/windows/filesys.c#L183)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

const uint8_t *
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by robinlinden** [comment]
`native_move_file` is missing from Android. :lgtm_cancel: 

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/avatar.c, line 176 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrTBYiXe-N3qAn3BvF:-KYrTBYjEgBut71hsrrI:b5ycxn) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.c#L176)):*
> ```C
> }
> 
> bool avatar_move(uint8_t *source, uint8_t *dest) {
> ```

`const uint8_t *`

---

*[src/avatar.c, line 177 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrU5HbtY6u6KMgpL9y:-KYrU5HbtY6u6KMgpL9z:bqk9h3g) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.c#L177)):*
> ```C
> 
> bool avatar_move(uint8_t *source, uint8_t *dest) {
>     char current_name[sizeof("avatars/") + TOX_PUBLIC_KEY_SIZE * 2 + sizeof(".png")] = { 0 };
> ```

A lot of paths in uTox are null terminated. Do these need to be?

---

*[src/avatar.c, line 180 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrRSIvylysAE5MNxQv:-KYrRSIvylysAE5MNxQw:bzdijif) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.c#L180)):*
> ```C
>     char new_name[sizeof("avatars/") + TOX_PUBLIC_KEY_SIZE * 2 + sizeof(".png")] = { 0 };
> 
> #ifdef __WIN32__
> ```

Remove the Windows #ifdef. We're only using Linux-style paths in uTox.

---

*[src/avatar.h, line 105 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrUDHFhPPiJyE8RDXJ:-KYrUDHFhPPiJyE8RDXK:b5ycxn) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.h#L105)):*
> ```objc
> 
> /* Moves the avatar to its new name */
> bool avatar_move(uint8_t *source, uint8_t *dest);
> ```

`const uint8_t *`

---

*[src/tox.c, line 579 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrUaLSkXz7bnxhmWnG:-KYrUaLSkXz7bnxhmWnH:b-th3w5l) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/tox.c#L579)):*
> ```C
>              */
>             tox_self_set_status(tox, param1);
>             save_needed = 1;
> ```

`true`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513#-:-KYrRKOjurRe6ue1IZSU:bxu4dwv)*

**Comment by endoffile78** [comment]
Review status: 7 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/avatar.c, line 176 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrTBYiXe-N3qAn3BvF:-KYsISeve9HiCMRk_OWk:b-896fix) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.c#L176)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`const uint8_t *`
</blockquote></details>

Done.

---

*[src/avatar.c, line 177 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrU5HbtY6u6KMgpL9y:-KYsIgrpvzFAIjrsip1K:bibo4d9) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.c#L177)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

A lot of paths in uTox are null terminated. Do these need to be?
</blockquote></details>

I did it because GrayHatter has had problems before with windows throwing a fit if the variable isn't initiliazed before using sprintf/snprintf.

---

*[src/avatar.c, line 180 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrRSIvylysAE5MNxQv:-KYsISB3Bxn1_mtGyIM4:b-896fix) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.c#L180)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Remove the Windows #ifdef. We're only using Linux-style paths in uTox.
</blockquote></details>

Done.

---

*[src/avatar.h, line 105 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrUDHFhPPiJyE8RDXJ:-KYsIU2BjOYbG2DxE5Hz:b-896fix) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/avatar.h#L105)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`const uint8_t *`
</blockquote></details>

Done.

---

*[src/tox.c, line 579 at r5](https://reviewable.io:443/reviews/utox/utox/513#-KYrUaLSkXz7bnxhmWnG:-KYsIUcWPgadhSBbU667:b-896fix) ([raw file](https://github.com/utox/utox/blob/97d81e2b83265948ca5b3fe8e3103c696d0f2814/src/tox.c#L579)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`true`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513#-:-KZCQvl4Rnt9FnCwBd1d:bnfp4nl)*

**Comment by GrayHatter** [comment]
This is something of a UX concern for me. So I'm going to withhold review and judgement until the settings page UI, that @endoffile78  is currently working on gets merged first. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513#-:-KZLduYikPrwtQ0ozbLb:b-4mjway)*

**Comment by robinlinden** [comment]
Reviewed 12 of 12 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by robinlinden** [comment]
:lgtm_strong: 

---

Reviewed 25 of 25 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513#-:-Kb2Xr4Gj9uHdTK_5APx:b-uwkowd)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 12 files at r1, 25 of 25 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main.h, line 269 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3gPwGKay_5dYdTtEm:-Kb3gPwGKay_5dYdTtEn:b-nuniu1) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/main.h#L269)):*
> ```objc
>     uint32_t nospam;
>     uint32_t old_nospam;
>     char nospam_str[sizeof(uint32_t) * 2];
> ```

BTW, does toxcore not expose this size in the API? If it does, we should use it, if it doesn't we should file a bug upstream.

---

*[src/tox_callbacks.c, line 19 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3hVBddG_4FSCRlVqU:-Kb3hVBddG_4FSCRlVqV:b-7j8oc4) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/tox_callbacks.c#L19)):*
> ```C
>                                     void *UNUSED(userdata)) {
> 
>     if(settings.block_friend_requests){
> ```

style

---

*[src/tox_callbacks.c, line 20 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3hX5lOM0Ol7qNxn0H:-Kb3hX5lOM0Ol7qNxn0I:b-gwaww9) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/tox_callbacks.c#L20)):*
> ```C
> 
>     if(settings.block_friend_requests){
>         debug_info("Friend request ignored.\n");
> ```

warning

---

*[src/ui/buttons.c, line 437 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3i4pnDIAK7BFgKLiX:-Kb3i4pnDIAK7BFgKLiY:bjddbjt) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/ui/buttons.c#L437)):*
> ```C
> static void button_change_nospam_on_mup(void) {
>     button_revert_nospam.disabled = false;
>     long int nospam = rand();
> ```

use `newspam`

---

*[src/ui/buttons.c, line 441 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3hxG9w8a_dkLztH-t:-Kb3hxG9w8a_dkLztH-u:b1d0gv7) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/ui/buttons.c#L441)):*
> ```C
>     self.nospam = (uint32_t)nospam;
>     sprintf(self.nospam_str, "%X", self.nospam);
>     postmessage_toxcore(TOX_SELF_CHANGE_NOSPAM, (uint32_t)nospam, 0, NULL);
> ```

you can only send a u16 through postmessage.

The simplest thing would likely be to do all of this logic inside the tox thread anyways; so there's less to pass. (It also abstracts the tox logic from the ui/* code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by endoffile78** [comment]
Review status: 21 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main.h, line 269 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3gPwGKay_5dYdTtEm:-Kb3v6y78mHjF4Y6M1qV:b901lqv) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/main.h#L269)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW, does toxcore not expose this size in the API? If it does, we should use it, if it doesn't we should file a bug upstream.
</blockquote></details>

Toxcore does'nt expose the size.

---

*[src/tox_callbacks.c, line 19 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3hVBddG_4FSCRlVqU:-Kb3v3Hvtwr2oGPut2Z7:b-896fix) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/tox_callbacks.c#L19)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

style
</blockquote></details>

Done.

---

*[src/tox_callbacks.c, line 20 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3hX5lOM0Ol7qNxn0H:-Kb3v3ofCs0nx_paRGGy:b-896fix) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/tox_callbacks.c#L20)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

warning
</blockquote></details>

Done.

---

*[src/ui/buttons.c, line 437 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3i4pnDIAK7BFgKLiX:-Kb3v4fZIKrIoYoqGWFa:b-896fix) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/ui/buttons.c#L437)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

use `newspam`
</blockquote></details>

Done.

---

*[src/ui/buttons.c, line 441 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3hxG9w8a_dkLztH-t:-Kb3v5NEkd0BjO_K7qCa:b-896fix) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/ui/buttons.c#L441)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

you can only send a u16 through postmessage.

The simplest thing would likely be to do all of this logic inside the tox thread anyways; so there's less to pass. (It also abstracts the tox logic from the ui/* code
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.h, line 269 at r8](https://reviewable.io:443/reviews/utox/utox/513#-Kb3gPwGKay_5dYdTtEm:-Kb41O7Ralf2hZA7wnT6:bb2n99b) ([raw file](https://github.com/utox/utox/blob/220d85c3b3dc46081acddae2014445ac14ee5b0d/src/main.h#L269)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Toxcore does'nt expose the size.
</blockquote></details>

OK I've already opened an issue aswell

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/513#-:-Kb42_XbVsYO_dYbEFem:bnfp4nl)*

**Pull request merged**
