### PR TITLE
Add xlib native_get_file option to delete file.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/512)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 313 at r1](https://reviewable.io:443/reviews/utox/utox/512#-KXRv0Re-1HAMfk1rhLG:-KXRv0RfVfbtS8Eh9uyu:bir8qzh) ([raw file](https://github.com/utox/utox/blob/025196275134d2f13d588ba552b876338499eb33/src/xlib/main.c#L313)):*
> ```C
> 
>     if (flag & UTOX_FILE_OPTS_DELETE) {
>         remove(path);
> ```

and return;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512#-:-KXRvDOiQPilPY7yfV-Z:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 313 at r1](https://reviewable.io:443/reviews/utox/utox/512#-KXRv0Re-1HAMfk1rhLG:-KXRvTyxFMNSM0MeX6RX:b-896fix) ([raw file](https://github.com/utox/utox/blob/025196275134d2f13d588ba552b876338499eb33/src/xlib/main.c#L313)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> and return;
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 312 at r3](https://reviewable.io:443/reviews/utox/utox/512#-KXS0TjegtyKAJsIbpEc:-KXS0TjfsWAaTPwDHsgc:b-36yi49) ([raw file](https://github.com/utox/utox/blob/625fa82c281b6a7b402547a0f268f55c8657c55d/src/xlib/main.c#L312)):*
> ```C
>     }
> 
>     if (flag & UTOX_FILE_OPTS_DELETE) {
> ```

`==`, we don't want to check if it exists, we want to be sure you don't delete, and try to read through a programming error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by GrayHatter** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512#-:-KXS0bT1Q5pAeKV__195:b8b79qu)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 312 at r3](https://reviewable.io:443/reviews/utox/utox/512#-KXS0TjegtyKAJsIbpEc:-KXS3lU7y6UrZBx6x5Hn:bpaadqg) ([raw file](https://github.com/utox/utox/blob/625fa82c281b6a7b402547a0f268f55c8657c55d/src/xlib/main.c#L312)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> `==`, we don't want to check if it exists, we want to be sure you don't delete, and try to read through a programming error
</details>
Added a check for UTOX_FILE_OPTS_DELETE in combination with other arguments at the top of the function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/xlib/main.c, line 312 at r3](https://reviewable.io:443/reviews/utox/utox/512#-KXS0TjegtyKAJsIbpEc:-KXS43FhQlIJUlu9Fzy4:b1z64lp) ([raw file](https://github.com/utox/utox/blob/625fa82c281b6a7b402547a0f268f55c8657c55d/src/xlib/main.c#L312)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Added a check for UTOX_FILE_OPTS_DELETE in combination with other arguments at the top of the function.
</details>
I'd roll this into that first check, make it an else if and make it `==` there's no reason not to be explicit here

---

*[src/xlib/main.c, line 307 at r4](https://reviewable.io:443/reviews/utox/utox/512#-KXS3tQ4ggY2WRIWaS_s:-KXS3tQ4ggY2WRIWaS_t:bxruuce) ([raw file](https://github.com/utox/utox/blob/9584928d07d86afd8d7844c8f94091d6cb8a2fc4/src/xlib/main.c#L307)):*
> ```C
> 
>     if (flag > UTOX_FILE_OPTS_DELETE) {
>         debug("NATIVE:\tDon't call native_get_file with UTOX_FILE_OPTS_DELETE in combination with other options.\n");
> ```

`debug_error` when it something unexpected or causes the fxn to exit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by robinlinden** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/xlib/main.c, line 312 at r3](https://reviewable.io:443/reviews/utox/utox/512#-KXS0TjegtyKAJsIbpEc:-KXS4qiMrZeaYwMFJNhH:bk8x99g) ([raw file](https://github.com/utox/utox/blob/625fa82c281b6a7b402547a0f268f55c8657c55d/src/xlib/main.c#L312)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> I'd roll this into that first check, make it an else if and make it `==` there's no reason not to be explicit here
</details>
Fair enough. I was trying to keep it consistent with all the other flag checks in the function.

---

*[src/xlib/main.c, line 307 at r4](https://reviewable.io:443/reviews/utox/utox/512#-KXS3tQ4ggY2WRIWaS_s:-KXS4qDvlBU2EvKf6ypY:b-896fix) ([raw file](https://github.com/utox/utox/blob/9584928d07d86afd8d7844c8f94091d6cb8a2fc4/src/xlib/main.c#L307)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> `debug_error` when it something unexpected or causes the fxn to exit
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 315 at r5](https://reviewable.io:443/reviews/utox/utox/512#-KXS5t6BGhq_IxRtIq5b:-KXS5t6Clm9tGJcxbyKR:b-7nkdhb) ([raw file](https://github.com/utox/utox/blob/86aaa1d19596bb7f0d2ddc9d40a56fbf3f927642/src/xlib/main.c#L315)):*
> ```C
>         debug_error("NATIVE:\tDon't call native_get_file with UTOX_FILE_OPTS_DELETE in combination with other options.\n");
>         return NULL;
>     } else if ((flag & UTOX_FILE_OPTS_DELETE) == UTOX_FILE_OPTS_DELETE) {
> ```

`    } else if (flag == UTOX_FILE_OPTS_DELETE) {`

your way will strip other flags. Granted we did check above, but fuket, lets check a 2nd time!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by robinlinden** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 315 at r5](https://reviewable.io:443/reviews/utox/utox/512#-KXS5t6BGhq_IxRtIq5b:-KXS97CrMa1eEgsGcjoW:b-896fix) ([raw file](https://github.com/utox/utox/blob/86aaa1d19596bb7f0d2ddc9d40a56fbf3f927642/src/xlib/main.c#L315)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> `    } else if (flag == UTOX_FILE_OPTS_DELETE) {`
> 
> your way will strip other flags. Granted we did check above, but fuket, lets check a 2nd time!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/512#-:-KXS9U0nsujjHt3WN2sU:bnfp4nl)*

**Pull request merged**
