### PR TITLE
fix potential crash on macOS when video input == nil

### PR DESCRIPTION
**Pull request by publicarray**
My webcam in my mac has problems sometimes :stuck_out_tongue_closed_eyes:

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/930)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/video.m, line 77 at r1](https://reviewable.io:443/reviews/utox/utox/930#-Kl7qXjQcNqBIjyPHOK5:-Kl7qXjRX7ELqBnFepjP:bld4ndd) ([raw file](https://github.com/utox/utox/blob/7020ce612dbb0d14d7f5207090f74f0e798e59ce/src/cocoa/video.m#L77)):*
> ```objc
>             }
> 
>             NSError *       error = NULL;
> ```

BTW While you're working in the OSX code, can you please try and fix these formatting atrocities that clang-format added in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/930#-:-Kl7qggCMitvA1XdqoaI:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/930#-:-Kl89J7RMCjrCMoRnRHf:bnfp4nl)*

**Comment by publicarray** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/video.m, line 77 at r1](https://reviewable.io:443/reviews/utox/utox/930#-Kl7qXjQcNqBIjyPHOK5:-Kl8ByvrFkGMZaBEdGFm:b-byewsv) ([raw file](https://github.com/utox/utox/blob/7020ce612dbb0d14d7f5207090f74f0e798e59ce/src/cocoa/video.m#L77)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW While you're working in the OSX code, can you please try and fix these formatting atrocities that clang-format added in?
</blockquote></details>

I was wondering what this weird formating was. I aim to submit a new PR for format fixes soonish ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/930)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/930#-:-Kl8J54UavUGKD_XYUvj:bnfp4nl)*

**Pull request merged**
