### PR TITLE
Fix Windows warnings and exporting chatlogs as plaintext on Windows.

### PR DESCRIPTION
**Pull request by robinlinden**
The problem with exporting chatlogs was that Windows uTox was using the `friend_number` instead of the `id_str`.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/739)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/filesys.c, line 69 at r1](https://reviewable.io:443/reviews/utox/utox/739#-KcuM2oKeJ2ilmU9H7Ig:-KcuM2oLdvdFiSZKVL4_:b-kj1eh4) ([raw file](https://github.com/utox/utox/blob/f4ffd9bfa31ba41a7de88617d3f3d160fa68b37f/src/windows/filesys.c#L69)):*
> ```C
>     }
> 
>     uint8_t *tmp_path = calloc(1, strlen((char *)name) + 1);
> ```

Is this ever freed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739)*

**Comment by robinlinden** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/filesys.c, line 69 at r1](https://reviewable.io:443/reviews/utox/utox/739#-KcuM2oKeJ2ilmU9H7Ig:-KcuP-hPHw2WPxU3Wfnn:bp5wvwn) ([raw file](https://github.com/utox/utox/blob/f4ffd9bfa31ba41a7de88617d3f3d160fa68b37f/src/windows/filesys.c#L69)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Is this ever freed?
</blockquote></details>

It is now. Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739#-:-KcuUEykQGX6yn8T_YAR:bnfp4nl)*

**Comment by GrayHatter** [comment]
needs rebase

**Comment by GrayHatter** [comment]
@endoffile78

**Comment by robinlinden** [comment]
Rebased and also fixed the const problem in src/main.c.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739#-:-Kd8uN2uBSQfiLVGgb2x:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 6 files at r1, 5 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/windows/dnd.c, line 94 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCiJ_zlTLIPnfa8sEz:-KdCiJa-Jewo78U-4uoq:bu14znq) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/dnd.c#L94)):*
> ```C
>             }
> 
>             uint8_t *path = calloc(1, UTOX_FILE_NAME_LENGTH * sizeof(uint8_t));
> ```

why is this better?

---

*[src/windows/filesys.c, line 69 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCj-9eYjfrcypuEyTv:-KdCj-9eYjfrcypuEyTw:b77os9g) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/filesys.c#L69)):*
> ```C
>     }
> 
>     uint8_t *tmp_path = calloc(1, strlen((char *)name) + 1);
> ```

way too many typecasts below, make this char, and typecast once at the end.

---

*[src/windows/filesys.c, line 70 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCiYyeVqMSOwpGebqm:-KdCiYyfjDNEpBh7RJ9N:b-ujo1yt) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/filesys.c#L70)):*
> ```C
> 
>     uint8_t *tmp_path = calloc(1, strlen((char *)name) + 1);
>     strcpy((char *)tmp_path, (char *)name);
> ```

no `strdup()`

---

*[src/windows/main.c, line 807 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCjXy1Y73Nd2SKWnL7:-KdCjXy1Y73Nd2SKWnL8:bhoe2y0) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/main.c#L807)):*
> ```C
>         int          len = GetModuleFileName(hModule, path, MAX_PATH);
>         unsigned int i;
>         for (i = len - 1; path[i] != '\\'; --i)
> ```

these make me nervous, comment pls

---

*[src/windows/main.c, line 947 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCjc_Q0lSqmMmYW9n_:-KdCjc_Q0lSqmMmYW9na:b-9hjnr8) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/main.c#L947)):*
> ```C
>     LOG_INFO("uTox", "Clean exit." );
> 
>     // TODO: This should be a non-zero value determined by a message's wParam.
> ```

That's stupid... oh windoof, okay makes sense then :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739)*

**Comment by robinlinden** [comment]
Review status: 2 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/windows/dnd.c, line 94 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCiJ_zlTLIPnfa8sEz:-KdMEj2nMHbnS3M04Zp6:bu6l50p) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/dnd.c#L94)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why is this better?
</blockquote></details>

I think it's nicer to allocate for 1 string of x characters rather than strlen() allocations of size 1. It's even prettier if you need to allocate for more than 1 string.

---

*[src/windows/filesys.c, line 69 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCj-9eYjfrcypuEyTv:-KdNoJpj8rSlka92ODl-:b-896fix) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/filesys.c#L69)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

way too many typecasts below, make this char, and typecast once at the end.
</blockquote></details>

Done.

---

*[src/windows/filesys.c, line 70 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCiYyeVqMSOwpGebqm:-KdMF3l8CqXNLYQxbEIp:b9ie86k) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/filesys.c#L70)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no `strdup()`
</blockquote></details>

I forgot that function exists. Switching it over does some weird things. (Maybe Windows-only behaviour?) I preferred the original solution, but up to you.

---

*[src/windows/main.c, line 807 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCjXy1Y73Nd2SKWnL7:-KdNi-wcVS9oDw6W4isC:b-896fix) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/main.c#L807)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

these make me nervous, comment pls
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r5, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739#-:-KdNvVPZJH2sLyDoz7O0:bnfp4nl)*

**Comment by cebe** [comment]
This conflicts with my test PR (https://github.com/uTox/uTox/pull/757), will rebase after this one is merged.

---

Reviewed 1 of 6 files at r3, 1 of 2 files at r4, 4 of 5 files at r5, 8 of 9 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/messages.c, line 1554 at r6](https://reviewable.io:443/reviews/utox/utox/739#-KdO231iS8zSXETrK2Bh:-KdO231iS8zSXETrK2Bi:b67rhax) ([raw file](https://github.com/utox/utox/blob/01706e8e0a07eab7da08fe850b2065fc29b87e15/src/messages.c#L1554)):*
> ```C
>         if (names && (i != m->sel_start_msg || m->sel_start_position == 0)) {
>             if (m->is_groupchat) {
>                 memcpy(p, msg->via.grp.msg, msg->via.grp.author_length);
> ```

I am not sure what this code is doing in detail but copying `msg` with the `author_length` instead of `msg_length` looks really wrong to me.
If this is correct, it should have a comment explaining what is going on.

---

*[src/windows/dnd.c, line 94 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCiJ_zlTLIPnfa8sEz:-KdO2rJBhT3uaLFym5Et:bafy410) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/dnd.c#L94)):*
> sizeof(uint8_t)

isn't this per definition 1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739#-:-KdO3Y8kvCsNWVYcyLC9:b-41r228)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/messages.c, line 1554 at r6](https://reviewable.io:443/reviews/utox/utox/739#-KdO231iS8zSXETrK2Bh:-KdO8G8R7RBZy4YGuh_-:b-ml6a0i) ([raw file](https://github.com/utox/utox/blob/01706e8e0a07eab7da08fe850b2065fc29b87e15/src/messages.c#L1554)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

I am not sure what this code is doing in detail but copying `msg` with the `author_length` instead of `msg_length` looks really wrong to me.
If this is correct, it should have a comment explaining what is going on.
</blockquote></details>

Good catch! And fixed! That's a bug in develop that no one has noticed. :D

---

*[src/windows/dnd.c, line 94 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCiJ_zlTLIPnfa8sEz:-KdO8O-Srdr8uQQoU4cg:bx7m4zy) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/dnd.c#L94)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

> sizeof(uint8_t)

isn't this per definition 1?
</blockquote></details>

It is. Dropped that part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 5 files at r5, 8 of 9 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/messages.c, line 1554 at r6](https://reviewable.io:443/reviews/utox/utox/739#-KdO231iS8zSXETrK2Bh:-KdOf9MHcO6TnUHHpy_0:bblz1j8) ([raw file](https://github.com/utox/utox/blob/01706e8e0a07eab7da08fe850b2065fc29b87e15/src/messages.c#L1554)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Good catch! And fixed! That's a bug in develop that no one has noticed. :D
</blockquote></details>

FYI 

It wasn't a bug until messages.h got the union. That's a VERY nice catch @cebe thank you!

---

*[src/windows/filesys.c, line 70 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCiYyeVqMSOwpGebqm:-KdOchv2OpFTUf-ZmHno:bad6zmm) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/filesys.c#L70)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I forgot that function exists. Switching it over does some weird things. (Maybe Windows-only behaviour?) I preferred the original solution, but up to you.
</blockquote></details>

LGTM either way, do what you'd like, or think is easier to read/maintain.

---

*[src/windows/main.c, line 807 at r4](https://reviewable.io:443/reviews/utox/utox/739#-KdCjXy1Y73Nd2SKWnL7:-KdOgCubgnuPzAFdqzGR:bysczjl) ([raw file](https://github.com/utox/utox/blob/514eb4eb87f08aa946c3dcf35b2d4ed724e79878/src/windows/main.c#L807)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, in the future, it can be a `; // trailing comment` Fewer lines of source it always better :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739)*

**Comment by GrayHatter** [comment]
:lgtm:

+@cebe merge when ready

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739#-:-KdOmGpWUjYgq_vh3RZJ:bpg24je)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739#-:-KdP1gCNbnZFi4XRpp0f:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/739#-:-KdPTtfHm7DdDM9JS4YT:bnfp4nl)*

**Pull request merged**
