### PR TITLE
Lots of native function things.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/511)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/cocoa/main.m, line 229 at r2](https://reviewable.io:443/reviews/utox/utox/511#-KYSPO2RcYxk-QNFpqiY:-KYSPO2RcYxk-QNFpqiZ:b-uc696c) ([raw file](https://github.com/utox/utox/blob/1122a7197b0d572d9fc88303c469146db8802ecf/src/cocoa/main.m#L229)):*
> ```objc
> }
> 
> // Exactly the same in src/cocoa/main.m and src/xlib/main.c
> ```

clearly we need `src/posix/`

---

*[src/windows/filesys.c, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/511#-KYSPaj5oh2qpOCF_1fC:-KYSPaj5oh2qpOCF_1fD:b-mx74kj) ([raw file](https://github.com/utox/utox/blob/1122a7197b0d572d9fc88303c469146db8802ecf/src/windows/filesys.c#L125)):*
> ```C
>         case ERROR_FILE_EXISTS:
>         case ERROR_ALREADY_EXISTS:
>             debug_info("NATIVE:\tCreated path: `%s` - %d\n", filepath, error);
> ```

notice

---

*[src/windows/filesys.c, line 180 at r2](https://reviewable.io:443/reviews/utox/utox/511#-KYSPcNBw0LK2BmcBr4L:-KYSPcNBw0LK2BmcBr4M:b-4yr6dt) ([raw file](https://github.com/utox/utox/blob/1122a7197b0d572d9fc88303c469146db8802ecf/src/windows/filesys.c#L180)):*
> ```C
>     }
>     return true;
> }
> ```

newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/511)*

**Comment by robinlinden** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/cocoa/main.m, line 229 at r2](https://reviewable.io:443/reviews/utox/utox/511#-KYSPO2RcYxk-QNFpqiY:-KYSUIt3x-59Oku61bpz:b-896fix) ([raw file](https://github.com/utox/utox/blob/1122a7197b0d572d9fc88303c469146db8802ecf/src/cocoa/main.m#L229)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

clearly we need `src/posix/`
</blockquote></details>

Done.

---

*[src/windows/filesys.c, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/511#-KYSPaj5oh2qpOCF_1fC:-KYST3yfhXgwLLKP6Chk:b-896fix) ([raw file](https://github.com/utox/utox/blob/1122a7197b0d572d9fc88303c469146db8802ecf/src/windows/filesys.c#L125)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

notice
</blockquote></details>

Done.

---

*[src/windows/filesys.c, line 180 at r2](https://reviewable.io:443/reviews/utox/utox/511#-KYSPcNBw0LK2BmcBr4L:-KYST3jjzQDPyeZJLqp6:b-896fix) ([raw file](https://github.com/utox/utox/blob/1122a7197b0d572d9fc88303c469146db8802ecf/src/windows/filesys.c#L180)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/511)*

**Comment by GrayHatter** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/posix/filesys.c, line 52 at r3](https://reviewable.io:443/reviews/utox/utox/511#-KYSVT6y-USeoL_94YKF:-KYSVT6zDUBEbNlEyN64:b-7zmfi1) ([raw file](https://github.com/utox/utox/blob/893995e80db5e5af630febfab654a7b64cb5f1df/src/posix/filesys.c#L52)):*
> ```C
> 
>     return fp;
> }
> ```

you need a better editor... newline at eof

---

*[src/windows/filesys.c, line 181 at r3](https://reviewable.io:443/reviews/utox/utox/511#-KYSVZvYbgbF0A2WoXK2:-KYSVZvYbgbF0A2WoXK3:b-e5l9gz) ([raw file](https://github.com/utox/utox/blob/893995e80db5e5af630febfab654a7b64cb5f1df/src/windows/filesys.c#L181)):*
> ```C
>     
>     return true;
> }
> ```

that's a good place too, but I meant at end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/511)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/511#-:-KYSXateZv6bTM8M8g1l:bnfp4nl)*

**Pull request merged**
