### PR TITLE
Add error checks to A/V and Xlib drawing

### PR DESCRIPTION
**Pull request by redmanmale**
Probably fixes some crashes in A/V.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1174)

### CODE REVIEW

**Comment by GrayHatter** [comment]
2 issues
1 note

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/av/audio.c, line 874 at r1](https://reviewable.io:443/reviews/utox/utox/1174#-L3dedXkgttitiZIVtdh:-L3dedXl2or-GsIPD4gy:bay6fok) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/audio.c#L874)):*
> ```C
>                             if (!f) {
>                                 LOG_ERR("uToxAV", "Unable to get friend when sending audio frame %u", i);
>                                 break;
> ```

continue here

---

*[src/av/utox_av.c, line 492 at r1](https://reviewable.io:443/reviews/utox/utox/1174#-L3demoeLOfs0mZBtgEo:-L3demof8Kg_Je1NUir8:b-n1sxpd) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/utox_av.c#L492)):*
> ```C
>     FRIEND *f = get_friend(friend_number);
>     if (!f) {
>         LOG_ERR("uToxAV", "Unable to get friend when A/V call accepted %u", friend_number);
> ```

FYI Consider making this fatal

---

*[src/av/video.c, line 295 at r1](https://reviewable.io:443/reviews/utox/utox/1174#-L3deug5ybUn3yhPa8Pr:-L3deug5ybUn3yhPa8Ps:b-w5rigq) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/video.c#L295)):*
> ```C
>                         FRIEND *f = get_friend(i);
>                         if (!f) {
>                             LOG_DEBUG("uToxVideo", "Could not get friend to send him video frame %lu", i);
> ```

This should at the very least be err_warn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1174#-:-L3dfG7AW2amWVQUgkRE:b-x8p72a)*

**Comment by redmanmale** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/av/audio.c, line 874 at r1](https://reviewable.io:443/reviews/utox/utox/1174#-L3dedXkgttitiZIVtdh:-L3iYx6ilI4kDUdSXGSa:b-896fix) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/audio.c#L874)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

continue here
</blockquote></details>

Done.

---

*[src/av/utox_av.c, line 492 at r1](https://reviewable.io:443/reviews/utox/utox/1174#-L3demoeLOfs0mZBtgEo:-L3iYztdA1wZKuupQpel:b-dvt11u) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/utox_av.c#L492)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

FYI Consider making this fatal
</blockquote></details>

I think it's better not to crash.

---

*[src/av/video.c, line 295 at r1](https://reviewable.io:443/reviews/utox/utox/1174#-L3deug5ybUn3yhPa8Pr:-L3iYzFSWZNoOixtBWfz:b-896fix) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/video.c#L295)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

This should at the very least be err_warn.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1174)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1174#-:-L3ts8R0xj_tpDu2t-i7:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/av/utox_av.c, line 492 at r1](https://reviewable.io:443/reviews/utox/utox/1174#-L3demoeLOfs0mZBtgEo:-L4gJAZyLHJ_sQt3IMRV:b-hnrkwc) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/utox_av.c#L492)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

I think it's better not to crash.
</blockquote></details>

crash != exit.

But I can't think of a valid state uTox could enter where toxcore would send us a callback for a friend we don't know exists. At the very least this would be an error state we need to handle, so what do you think is the best way to solve for this invalid state?

---

*[src/av/video.c, line 294 at r2](https://reviewable.io:443/reviews/utox/utox/1174#-L4gJlsDOyLMubPhZk88:-L4gJlsDOyLMubPhZk89:bya77z0) ([raw file](https://github.com/utox/utox/blob/c8f5984e4ad805faa34c74b8b25929f535b8ac3c/src/av/video.c#L294)):*
> ```C
> 
>                         FRIEND *f = get_friend(i);
>                         if (!f) {
> ```

this will never happen, SEND_VIDEO_FRAME uses `get_friend(i)`

@robinlinden @endoffile78 thoughts on how we should handle this issue?

I suggest get_friend() should emit a warning if it's called and no friend is found. We'd still need to handle said error states elsewhere, but issues like line 288 above won't be silently ignored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1174)*

**Comment by redmanmale** [comment]
It's been a while... Can we merge this?

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: 2 open discussions remaining

---

*[src/av/video.c, line 294 at r2](https://reviewable.io/reviews/utox/utox/1174#-L4gJlsDOyLMubPhZk88:-LEzAyIK5iqy2CbwNYKq:b-jgo79v) ([raw file](https://github.com/utox/utox/blob/d2850b9ef799e26993217ee2cbfdc1b9f4a96f49/src/av/video.c#L294)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this will never happen, SEND_VIDEO_FRAME uses `get_friend(i)`

@robinlinden @endoffile78 thoughts on how we should handle this issue?

I suggest get_friend() should emit a warning if it's called and no friend is found. We'd still need to handle said error states elsewhere, but issues like line 288 above won't be silently ignored.
</blockquote></details>

`get_friend` already has a warning, if a friend isn't found than it does a `LOG_WARN`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1174#-:-LEzAxRg1iWpFSwxOAgu:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: 1 open discussion remaining

---

*[src/av/utox_av.c, line 492 at r1](https://reviewable.io/reviews/utox/utox/1174#-L3demoeLOfs0mZBtgEo:-LEzivEt-ZomHwP80QVt:b-op7xo3) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/utox_av.c#L492)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

crash != exit.

But I can't think of a valid state uTox could enter where toxcore would send us a callback for a friend we don't know exists. At the very least this would be an error state we need to handle, so what do you think is the best way to solve for this invalid state?
</blockquote></details>

Yeah, this needs to be fatal error. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1174)*

**Comment by redmanmale** [comment]
Review status: 1 file needs 2 more reviewers, 1 open discussion remaining, missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---

*[src/av/utox_av.c, line 492 at r1](https://reviewable.io/reviews/utox/utox/1174#-L3demoeLOfs0mZBtgEo:-LF1DYPr09sX4y4jE1S3:b-896fix) ([raw file](https://github.com/utox/utox/blob/7d87e188b59f0824c06a6e563304fd102f9b5431/src/av/utox_av.c#L492)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Yeah, this needs to be fatal error. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1174)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: 1 file needs 1 more reviewer, missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1174#-:-LFcTwqsC2e0-xj9bEnt:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! undefined

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1174#-:-LFha87g9_0h7Sm0dZb6:bnfp4nl)*

**Pull request merged**
