### PR TITLE
Remove more things from main.h

### PR DESCRIPTION
**Pull request by robinlinden**
Remove more things from main.h
Decrease minimum width
Update stb and follow the instructions for it.
Drop a few main.h includes

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/894)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm: 

Next time make 2 commits, one for your changes, the 2nd for stbi?

---

Reviewed 6 of 17 files at r1.
Review status: 6 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-KiweK7CI2bOUgEf7Rs3:b-wxn90n)*

**Comment by GrayHatter** [comment]
Reviewed 11 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/native/audio.h, line 14 at r1](https://reviewable.io:443/reviews/utox/utox/894#-KiwfCnAyU9aDLXdmECZ:-KiwfCnBJG-gqaFpvGOo:b-v5ryxk) ([raw file](https://github.com/utox/utox/blob/1ec9add07b1c3a0aaba3922600e905bbbe88c956/src/native/audio.h#L14)):*
> ```objc
> 
> 
> #if defined __ANDROID__
> ```

why is this in a new ifdef?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/native/audio.h, line 14 at r1](https://reviewable.io:443/reviews/utox/utox/894#-KiwfCnAyU9aDLXdmECZ:-KiyVoKp6smOCOHEfCIK:bn8umf3) ([raw file](https://github.com/utox/utox/blob/1ec9add07b1c3a0aaba3922600e905bbbe88c956/src/native/audio.h#L14)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why is this in a new ifdef?
</blockquote></details>

It's not. We use that in 9 places across 8 files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894)*

**Comment by endoffile78** [comment]
Reviewed 16 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 29 of 29 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/native/audio.h, line 14 at r1](https://reviewable.io:443/reviews/utox/utox/894#-KiwfCnAyU9aDLXdmECZ:-Kj3yigfhuor5mq6Xe2X:bnqfi8p) ([raw file](https://github.com/utox/utox/blob/1ec9add07b1c3a0aaba3922600e905bbbe88c956/src/native/audio.h#L14)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

It's not. We use that in 9 places across 8 files.
</blockquote></details>

no, I mean, does it need to be in an ifdef?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-Kj3zPvHpfvzbIOKyJh-:bnfp4nl)*

**Comment by GrayHatter** [comment]
+@endoffile78

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-KjEIyQlxBEvxM0l8u5s:bgs4sb9)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-KjGir325t_GropuVofo:bnfp4nl)*

**Comment by endoffile78** [comment]
Needs to be rebased

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/native/audio.h, line 14 at r1](https://reviewable.io:443/reviews/utox/utox/894#-KiwfCnAyU9aDLXdmECZ:-KjgL9dBI0xIY0ECD_Yt:bfx4u2d) ([raw file](https://github.com/utox/utox/blob/1ec9add07b1c3a0aaba3922600e905bbbe88c956/src/native/audio.h#L14)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no, I mean, does it need to be in an ifdef?
</blockquote></details>

@robinlinden 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/native/audio.h, line 14 at r1](https://reviewable.io:443/reviews/utox/utox/894#-KiwfCnAyU9aDLXdmECZ:-Kk0QvS2-LN9M2PEdy2n:b-t7npkx) ([raw file](https://github.com/utox/utox/blob/1ec9add07b1c3a0aaba3922600e905bbbe88c956/src/native/audio.h#L14)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

@robinlinden 
</blockquote></details>

This code doesn't *have* to be behind an ifdef, but trying to use them anywhere that isn't Android-only wouldn't compile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894)*

**Comment by endoffile78** [comment]
Needs to be rebased.

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/native/audio.h, line 14 at r1](https://reviewable.io:443/reviews/utox/utox/894#-KiwfCnAyU9aDLXdmECZ:-Kl2CLmjjrErlK_v32Ty:b-hztxr9) ([raw file](https://github.com/utox/utox/blob/1ec9add07b1c3a0aaba3922600e905bbbe88c956/src/native/audio.h#L14)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This code doesn't *have* to be behind an ifdef, but trying to use them anywhere that isn't Android-only wouldn't compile.
</blockquote></details>

OK, this is fine for now then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894)*

**Comment by GrayHatter** [comment]
merging is fine too

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-Kl2CRxaqGvls370hK22:b-renbu4)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-Ks-x8kSa9ltPPPYl4z8:bnfp4nl)*

**Comment by GrayHatter** [comment]
changing assignes

-@robinlinden 
+@grayhatter 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-Ks-xGHd2bgUrPxPQ8oy:b-95p44m)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/894#-:-Ks-yO8wr68R0WS3CBbs:bnfp4nl)*

**Pull request merged**
