### PR TITLE
Rename onpress to on_mup

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/589)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/589#-:-KZsciP9XoR8VjhMExEi:bnfp4nl)*

**Comment by cebe** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/button.c, line 131 at r1](https://reviewable.io:443/reviews/utox/utox/589#-KZsd9-Uxfk7R-5owzcG:-KZsd9-V1DhPNlNw8g8z:b-2pms5) ([raw file](https://github.com/utox/utox/blob/a921512fa54f573aa3c7b80472efa3fbfc1f4559/src/ui/button.c#L131)):*
> ```C
> }
> 
> bool button_mright(BUTTON *b) {
> ```

right click behaves different from left click as it does not check for `b->mousedown`. not a change in this PR but why is that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/589)*

**Comment by cebe** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/589#-:-KZsdnGNCmf9I0iFaltW:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/ui/buttons.c, line 694 at r1](https://reviewable.io:443/reviews/utox/utox/589#-KZsdXwbD9zxVcRX4dJx:-KZsdXwbD9zxVcRX4dJy:byor325) ([raw file](https://github.com/utox/utox/blob/a921512fa54f573aa3c7b80472efa3fbfc1f4559/src/ui/buttons.c#L694)):*
> ```C
>         .button_text = {.i18nal = STR_ADD },
>         .update  = button_setcolors_success,
>         .on_mup = button_add_device_to_self_mdown,
> ```

lhs: `mup`, rhs: `mdown`?

---

*[src/ui/switch.c, line 105 at r1](https://reviewable.io:443/reviews/utox/utox/589#-KZsdwpLYCbKUu9rkdg3:-KZsdwpMY7JK3SpSGn_p:b-8gvdjt) ([raw file](https://github.com/utox/utox/blob/a921512fa54f573aa3c7b80472efa3fbfc1f4559/src/ui/switch.c#L105)):*
> ```C
>         if (s->mouseover) {
>             s->switch_on = !s->switch_on;
>             s->on_mup();
> ```

This is a bit of a weird construction now. `if (s->mousedown) { if (s->mouseover) { s->on_mup(); } }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/589)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ui/button.c, line 131 at r1](https://reviewable.io:443/reviews/utox/utox/589#-KZsd9-Uxfk7R-5owzcG:-KZseg3t_uhpg0gbCDgM:b94h871) ([raw file](https://github.com/utox/utox/blob/a921512fa54f573aa3c7b80472efa3fbfc1f4559/src/ui/button.c#L131)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

right click behaves different from left click as it does not check for `b->mousedown`. not a change in this PR but why is that?
</blockquote></details>

answered in IRC

---

*[src/ui/buttons.c, line 694 at r1](https://reviewable.io:443/reviews/utox/utox/589#-KZsdXwbD9zxVcRX4dJx:-KZsehZ9Cb_COe2mEZSJ:b6qsu15) ([raw file](https://github.com/utox/utox/blob/a921512fa54f573aa3c7b80472efa3fbfc1f4559/src/ui/buttons.c#L694)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

lhs: `mup`, rhs: `mdown`?
</blockquote></details>

mdown used to do stuff, I've changed it to mup, because that makes more sense.

I can fix this but then I'd have to rebase. I suggest we fix this on the next go around?

---

*[src/ui/switch.c, line 105 at r1](https://reviewable.io:443/reviews/utox/utox/589#-KZsdwpLYCbKUu9rkdg3:-KZserGH3RVxCJAD51_l:b-wwrni0) ([raw file](https://github.com/utox/utox/blob/a921512fa54f573aa3c7b80472efa3fbfc1f4559/src/ui/switch.c#L105)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This is a bit of a weird construction now. `if (s->mousedown) { if (s->mouseover) { s->on_mup(); } }`
</blockquote></details>

It's correct, if m-down we always have to do stuff, but only call the switch function if mouseover is true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/589)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/589#-:-KZsfpfJAzfJjAzAZ5Mn:bnfp4nl)*

**Pull request merged**
