### PR TITLE
Gitlab

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/773)

### CODE REVIEW

**Comment by cebe** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitlab-ci.yml, line 24 at r1](https://reviewable.io:443/reviews/utox/utox/773#-KdgMt7k2KL643XXq1R3:-KdgMt7k2KL643XXq1R4:bpoveva) ([raw file](https://github.com/utox/utox/blob/35808072d3deeef1c376626d209ec0e00c4b8912/.gitlab-ci.yml#L24)):*
> ```YAML
>     - ./travis/windows-before.sh
>   script:
>     - ./travis/windows-script.sh
> ```

why is osx not in here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/773)*

**Comment by GrayHatter** [comment]
Review status: 0 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitlab-ci.yml, line 24 at r1](https://reviewable.io:443/reviews/utox/utox/773#-KdgMt7k2KL643XXq1R3:-KdgQdgVfyuYde1MTxSw:b-p9pl23) ([raw file](https://github.com/utox/utox/blob/35808072d3deeef1c376626d209ec0e00c4b8912/.gitlab-ci.yml#L24)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

why is osx not in here?
</blockquote></details>

is now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/773)*

**Comment by GrayHatter** [comment]
Reviewed 36 of 40 files at r2.
Review status: 24 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/773)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 40 of 40 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/773#-:-KdgRgip7ePVOLlJB16m:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 40 of 40 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[extra/travis/env.sh, line 6 at r2](https://reviewable.io:443/reviews/utox/utox/773#-KdganetxsnL2ohJL6Nr:-KdganetxsnL2ohJL6Ns:b-np8qah) ([raw file](https://github.com/utox/utox/blob/a3e859f719ea84ca64f71ba5e26d4fe6fa78845e/extra/travis/env.sh#L6)):*
> ```Shell
> 
> export TOXCORE_REPO=TokTok/c-toxcore
> export CACHE_DIR=$CACHE_DIR
> ```

Should still be `$HOME/cache` if Travis is to function, but per IRC with @grayhatter, that won't be done in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/773#-:-KdglLxaZAVXUMFTcntt:bnfp4nl)*

**Pull request merged**
