### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by eclipseo**
Add Opus dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1090)

### CODE REVIEW

**Comment by GrayHatter** [comment]
@eclipseo welcome, and thanks for the PR.

Is opus a uTox dependency, or only a toxcore one? @redmanmale @robinlinden do you guys know off the top of your head?

**Comment by redmanmale** [comment]
Opus is required by toxcore if you need audio/video support.

**Comment by robinlinden** [comment]
@GrayHatter We do require it: https://github.com/uTox/uTox/blob/develop/src/av/CMakeLists.txt#L18
@eclipseo Thank you very much for the PR!

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1090#-:-KwRR805BGs3GJ_A-734:bnfp4nl)*

**Comment by robinlinden** [comment]
@eclipseo Can you check the box in the bottom right that will allow me to make changes to your branch? I need to rebase it so Travis passes.

**Comment by eclipseo** [comment]
Done, I think.

**Comment by robinlinden** [comment]
@eclipseo Yeah, that did it. Thank you very much. :) Travis should pass now.

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1090)*

**Pull request merged**
