### PR TITLE
Allow changing nospam manually

### LINKED ISSUE #708: Manual change nospam
Please add ability to change nospam field manually, do not allow entering non working characters.

### PR DESCRIPTION
**Pull request by endoffile78**
Fixes #708 

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/723)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723#-:-KcQ4qkbQyFX1NOLqxNj:bnfp4nl)*

**Comment by GrayHatter** [comment]
nightmare conflict with #550 (Custom Windows and Notifications popups) 

---

Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723#-:-KcWbpkW_qYW1kWRpNof:b2bxmdg)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Comment by GrayHatter** [comment]
probably can't be rebased, likely needs a manual rewrite sorry @endoffile78

**Comment by robinlinden** [comment]
Reviewed 3 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 6 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/layout/settings.c, line 576 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlPS_kba1t90MLupY:-KdOlPS_kba1t90MLupZ:b-drh7jn) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L576)):*
> ```C
> static void button_change_nospam_on_mup(void) {
>     button_revert_nospam.disabled = false;
>     long int nospam = rand() + rand();
> ```

don't you mean `rand() | rand() << 16`?

---

*[src/layout/settings.c, line 1105 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlY68zxu2yz0jDQhY:-KdOlY698t1B8bxh71c3:bpd861j) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L1105)):*
> ```C
>             edit_proxy_port_data[8],
>             edit_profile_password_data[65535],
>             edit_nospam_data[sizeof(uint8_t) * 2];
> ```

sizeof u16

---

*[src/layout/settings.c, line 1220 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlqDLrohq7BBtAJgj:-KdOlqDLrohq7BBtAJgk:b-vhep3l) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L1220)):*
> ```C
> 
> EDIT edit_nospam = {
>     .maxlength            = sizeof(uint32_t) * 2,
> ```

NOPE NOPE NOPE, nahuhh

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Comment by endoffile78** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/layout/settings.c, line 576 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlPS_kba1t90MLupY:-KdOpevtXerOh-YG0MpH:b-896fix) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L576)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

don't you mean `rand() | rand() << 16`?
</blockquote></details>

Done.

---

*[src/layout/settings.c, line 1105 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlY68zxu2yz0jDQhY:-KdOpfamjPJu7mImGe88:bbokdpp) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L1105)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

sizeof u16
</blockquote></details>

Should of been uin32_t not sure what I was thinking.

---

*[src/layout/settings.c, line 1220 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlqDLrohq7BBtAJgj:-KdOpkprA8cvUFOdsTPs:b-xe1wxq) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L1220)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

NOPE NOPE NOPE, nahuhh
</blockquote></details>

AFAIK that is the right length. Nospam size is uint32_t.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Comment by GrayHatter** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/layout/settings.c, line 1220 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlqDLrohq7BBtAJgj:-KdOq1noXi46mIEImtB9:b-tw60u2) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L1220)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

AFAIK that is the right length. Nospam size is uint32_t.
</blockquote></details>

yeah, you fixed this by the above, still could go out of sync. how about `sizeof edit_nospam_data`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Comment by endoffile78** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layout/settings.c, line 1220 at r3](https://reviewable.io:443/reviews/utox/utox/723#-KdOlqDLrohq7BBtAJgj:-KdOqgf1uOiT3sS0xDLj:b-896fix) ([raw file](https://github.com/utox/utox/blob/6fba23d8221e856e2729ae8012c21f0c26c0d233/src/layout/settings.c#L1220)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yeah, you fixed this by the above, still could go out of sync. how about `sizeof edit_nospam_data`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/layout/settings.c, line 1216 at r5](https://reviewable.io:443/reviews/utox/utox/723#-KdOqvFZBOEiQXSam9l2:-KdOqvFZBOEiQXSam9l3:bjgqb4e) ([raw file](https://github.com/utox/utox/blob/f0c9f3da6425c22f90a7519f938410118a02b806/src/layout/settings.c#L1216)):*
> ```C
>         return;
>     }
>     postmessage_toxcore(TOX_SELF_CHANGE_NOSPAM, nospam, 0, NULL);
> ```

This is u16 on windows, you'll have to malloc and send the pointer, or do some bitshift magic :/

Or you can just do the strtol in the toxcore thread, sending the pointer to `edit_nospam_data`, but that's asking for a bug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/layout/settings.c, line 1216 at r5](https://reviewable.io:443/reviews/utox/utox/723#-KdOqvFZBOEiQXSam9l2:-KdOs0eeGYVBo2riWxQY:bj3tu1v) ([raw file](https://github.com/utox/utox/blob/f0c9f3da6425c22f90a7519f938410118a02b806/src/layout/settings.c#L1216)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

This is u16 on windows, you'll have to malloc and send the pointer, or do some bitshift magic :/

Or you can just do the strtol in the toxcore thread, sending the pointer to `edit_nospam_data`, but that's asking for a bug
</blockquote></details>

LGTM, I confused postmessage_toxcore with postmessage_utox

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723#-:-KdOs8gTkcflriQmFu2G:bnfp4nl)*

**Comment by cebe** [comment]
Reviewed 2 of 6 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/723)*

**Pull request merged**
