### PR TITLE
Let cmake update the man file version.

### PR DESCRIPTION
**Pull request by robinlinden**
Month isn't being autogenerated since these files are checked into git and month doesn't only change when we make a new release.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/987)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utox.1, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/987#-KrMyo9nH5w6tIPZ5Mn8:-KrMyo9nH5w6tIPZ5Mn9:b8zhk17) ([raw file](https://github.com/utox/utox/blob/eabb8a4170443d78abfdd4703cd8ce488763c5d9/src/utox.1#L1)):*
> ```Roff
> .TH UTOX "1" "January 2017" "µTox 0.15.0"
> ```

Current month?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/987#-:-KrMysp1-Xdf7bzcPyxB:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/987#-:-KrRLapH6mIJg8uiWrod:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utox.1, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/987#-KrMyo9nH5w6tIPZ5Mn8:-Ks-vjhjjEtB495meFCM:b-9xfp2v) ([raw file](https://github.com/utox/utox/blob/eabb8a4170443d78abfdd4703cd8ce488763c5d9/src/utox.1#L1)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Current month?
</blockquote></details>

done in extra commit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/987)*

**Comment by robinlinden** [comment]
:lgtm: 

---

Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/987#-:-Ks00M3SNi7w-OE9e0Ta:bg7igkv)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/987#-:-Ks00ZmQevMKw6-1bZf4:bnfp4nl)*

**Pull request merged**
