### PR TITLE
Fix switches

### LINKED ISSUE #576: Wrong text when hovering on buttons
Picture tells everything, just hover cursor on those buttons. Just a cosmetic bug nothing more.
cosmetic2
cosmetic1

### PR DESCRIPTION
**Pull request by cebe**
-  fix duplicate declaration in switch.h 
-  ~~fixed order of audio filtering and status notification switches~~

~~fixes - #576~~

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/577)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui.c, line 145 at r1](https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZfb6zItPYmle3PcHqb:b-pwobia) ([raw file](https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145)):*
> ```C
>     CREATE_SWITCH(audible_notifications, SCALE(-10) - BM_SWITCH_WIDTH, SCALE(0), BM_SWITCH_WIDTH,BM_SWITCH_HEIGHT);
>     CREATE_SWITCH(push_to_talk, SCALE(-10) - BM_SWITCH_WIDTH, SCALE(30), BM_SWITCH_WIDTH,BM_SWITCH_HEIGHT);
> #ifdef AUDIO_FILTERING
> ```

Can you do this in a way similar to https://github.com/uTox/uTox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui/draw_helpers.c#L433 so that there's not a blank space in the settings if AUDIO_FILTERING isn't enabled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui.c, line 145 at r1](https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZfhc-Pg3CBuJLMvjwE:b3m1h3y) ([raw file](https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Can you do this in a way similar to https://github.com/uTox/uTox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui/draw_helpers.c#L433 so that there's not a blank space in the settings if AUDIO_FILTERING isn't enabled?
</blockquote></details>

Audio filtering is a compile option, is there a reason we shouldn't push it down to the bottom of the list in every case?

Also be aware of #574 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui.c, line 145 at r1](https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZfiuD6KQthfTCrd0g9:b-csn1zi) ([raw file](https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Audio filtering is a compile option, is there a reason we shouldn't push it down to the bottom of the list in every case?

Also be aware of #574 
</blockquote></details>

It might not always make sense at the bottom of the list. It didn't last time I messed around with it. 

Another benefit of using a construction like the one in draw_helpers.c is that you don't have to manually type in and change all offsets if you're adding something to the middle of the list. Lower risk of human error. You just reorder it however you want and it *just works*.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui.c, line 145 at r1](https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZfk4HF1LNbFMXm0cDj:bauho05) ([raw file](https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

It might not always make sense at the bottom of the list. It didn't last time I messed around with it. 

Another benefit of using a construction like the one in draw_helpers.c is that you don't have to manually type in and change all offsets if you're adding something to the middle of the list. Lower risk of human error. You just reorder it however you want and it *just works*.
</blockquote></details>

How about forking each panel into it's own function?

Eg a separate function for each page/settings panel?

Then it would be much easier to update and edit them in situ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui.c, line 145 at r1](https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZfkUVwFTjcoC0jdT9C:bdqmcyk) ([raw file](https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

How about forking each panel into it's own function?

Eg a separate function for each page/settings panel?

Then it would be much easier to update and edit them in situ? 
</blockquote></details>

I've been thinking we should do that too. Also combining all switches, buttons, and text for each panel into their own function so we can get a better overall view of how each panel is built without skipping between 4-5 different files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577)*

**Comment by GrayHatter** [comment]
Let's wait until after the two pending pulls are merged.

Mine and e0f's both touch the surrounding code.

On Dec 23, 2016 4:59 AM, "Robin Lindén" <notifications@github.com> wrote:

Review status: all files reviewed at latest revision, 1 unresolved
discussion, some commit checks failed.
------------------------------

*src/ui.c, line 145 at r1
<https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZfkUVwFTjcoC0jdT9C:bdqmcyk>
(raw file
<https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145>):*
*Previously, GrayHatter (Gregory Mullen) wrote…*

How about forking each panel into it's own function?

Eg a separate function for each page/settings panel?

Then it would be much easier to update and edit them in situ?

I've been thinking we should do that too. Also combining all switches,
buttons, and text for each panel into their own function so we can get a
better overall view of how each panel is built without skipping between 4-5
different files.
------------------------------

*Comments from Reviewable <https://reviewable.io:443/reviews/utox/utox/577>*

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/uTox/uTox/pull/577#issuecomment-268986445>, or mute the
thread

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577#-:-KZy_UEHHcuUOtM8nhFG:bnfp4nl)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui.c, line 145 at r1](https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZya63Z0IBs3Uj1xq5G:b-896fix) ([raw file](https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

*src/ui.c, line 145 at r1 <https://reviewable.io:443/reviews/utox/utox/577#-KZfb6zItPYmle3PcHqa:-KZfkUVwFTjcoC0jdT9C:bdqmcyk> (raw file <https://github.com/utox/utox/blob/92ff3e1c7297c3c0b64de3efbc4f9086dbed9110/src/ui.c#L145>):* *Previously, GrayHatter (Gregory Mullen) wrote…*

How about forking each panel into it's own function?

Eg a separate function for each page/settings panel?

Then it would be much easier to update and edit them in situ?

I've been thinking we should do that too. Also combining all switches, buttons, and text for each panel into their own function so we can get a better overall view of how each panel is built without skipping between 4-5 different files. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577#-:-KZyeoOqojPWTsQkVCew:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577#-:-KZyh7Vp67czQ6_01Fc4:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/577)*

**Pull request merged**
