### PR TITLE
Remove auto-updater

### PR DESCRIPTION
**Pull request by avoidr**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1434)

### CODE REVIEW

**Comment by avoidr** [comment]
Rebased.

**Comment by avoidr** [comment]
Rebased.

**Comment by avoidr** [comment]
Squashed.

**Comment by GrayHatter** [comment]
I'm not sure I would have approved this change...

Why was deleting everything better than trying to fix it, or comment it out?

**Comment by avoidr** [comment]
Windows is unmaintained and there are no updates to uTox, anyway. Nobody would have fixed it for a long time (if ever) and we don't even own that domain anymore. And I don't want to kid anybody. It's just one more broken promise that disappoints and makes a bad impression. And I don't want to see uTox in such a bad state, either.

For the little activity that uTox is seeing, @robinlinden may build binaries for releases. Speaking of releases, I want to do them more often and more regularly, too.

**Pull request merged**
