### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/527)

### CODE REVIEW

**Comment by GrayHatter** [comment]
*[src/util.c, line 611 at r1](https://reviewable.io:443/reviews/utox/utox/527#-KYazcAyjZc9lyfZ90Ps:-KYazcAzFE3rUk1ePGXK:b-ami53q) ([raw file](https://github.com/utox/utox/blob/01665674f9d3375309023e6aa80a6a3f7f01144d/src/util.c#L611)):*
> ```C
>     size_t size = 0;
> 
>     FILE *fp = native_get_file((char *)filepath, &size, UTOX_FILE_OPTS_READ);
> ```

@robinlinden what are we doing with this? `char` or `u8`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527)*

**Comment by GrayHatter** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/friend.c, line 303 at r1](https://reviewable.io:443/reviews/utox/utox/527#-KYayLONXUWuRI49MDmh:-KYayLONXUWuRI49MDmi:brofxc0) ([raw file](https://github.com/utox/utox/blob/01665674f9d3375309023e6aa80a6a3f7f01144d/src/friend.c#L303)):*
> ```C
>     messages_clear_all(&f->msg);
> 
>     utox_remove_friend_chatlog(f->id_str);
> ```

BTW, eventually we should consider moving this into friend.c But that's OOS for this

---

*[src/messages.c, line 385 at r1](https://reviewable.io:443/reviews/utox/utox/527#-KYayToP0xhY7i8U6TZG:-KYayToQcmA6rD3Hwy3v:b-ayd2y7) ([raw file](https://github.com/utox/utox/blob/01665674f9d3375309023e6aa80a6a3f7f01144d/src/messages.c#L385)):*
> ```C
> bool messages_read_from_log(uint32_t friend_number) {
>     size_t    actual_count = 0;
>     uint8_t **data         = utox_load_chatlog(friend[friend_number].id_str, &actual_count, UTOX_MAX_BACKLOG_MESSAGES, 0);
> ```

revert this, its' fixed in file_transfers.c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527)*

**Comment by endoffile78** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/friend.c, line 303 at r1](https://reviewable.io:443/reviews/utox/utox/527#-KYayLONXUWuRI49MDmh:-KYb13qAQCGa7qbMO1tm:btd51a6) ([raw file](https://github.com/utox/utox/blob/01665674f9d3375309023e6aa80a6a3f7f01144d/src/friend.c#L303)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW, eventually we should consider moving this into friend.c But that's OOS for this
</blockquote></details>

I agree.

---

*[src/messages.c, line 385 at r1](https://reviewable.io:443/reviews/utox/utox/527#-KYayToP0xhY7i8U6TZG:-KYb15c4VzqAVNvDUuO5:b-896fix) ([raw file](https://github.com/utox/utox/blob/01665674f9d3375309023e6aa80a6a3f7f01144d/src/messages.c#L385)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

revert this, its' fixed in file_transfers.c
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527#-:-KYbq25509Cq3RMGFchG:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/util.c, line 611 at r1](https://reviewable.io:443/reviews/utox/utox/527#-KYazcAyjZc9lyfZ90Ps:-KYc1JDF_0Bz3u8E8R8T:b-6trv6f) ([raw file](https://github.com/utox/utox/blob/01665674f9d3375309023e6aa80a6a3f7f01144d/src/util.c#L611)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

@robinlinden what are we doing with this? `char` or `u8`?
</blockquote></details>

@robinlinden says we're using u8 for names exclusively. drop this typecast, and change the native_get_file() functions as needed.

They should accept a `u8`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527)*

**Comment by endoffile78** [comment]
Review status: 7 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/util.c, line 611 at r1](https://reviewable.io:443/reviews/utox/utox/527#-KYazcAyjZc9lyfZ90Ps:-KYd2XSugl8Z3bkAUtLD:b-896fix) ([raw file](https://github.com/utox/utox/blob/01665674f9d3375309023e6aa80a6a3f7f01144d/src/util.c#L611)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

@robinlinden says we're using u8 for names exclusively. drop this typecast, and change the native_get_file() functions as needed.

They should accept a `u8`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 5 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527#-:-KYej0V5kHdIoE004mNi:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 6 of 12 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.c, line 191 at r4](https://reviewable.io:443/reviews/utox/utox/527#-KYls-IjlRhrin4TTAl6:-KYls-IjlRhrin4TTAl7:b9swzug) ([raw file](https://github.com/utox/utox/blob/d788a1eb4f04f950edf712e90f4a0d6e59b13256/src/main.c#L191)):*
> ```C
> 
>     if (append) {
>         return native_get_file(name, NULL, UTOX_FILE_OPTS_READ   | UTOX_FILE_OPTS_WRITE |
> ```

this will catch an assert() now drop the write opt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527)*

**Comment by robinlinden** [comment]
Reviewed 1 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main.c, line 191 at r4](https://reviewable.io:443/reviews/utox/utox/527#-KYls-IjlRhrin4TTAl6:-KYnWMo3aVHUtf4muK3o:b-1volxs) ([raw file](https://github.com/utox/utox/blob/d788a1eb4f04f950edf712e90f4a0d6e59b13256/src/main.c#L191)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this will catch an assert() now drop the write opt
</blockquote></details>

Rebasing on develop would fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/527#-:-KYqV5l7ubb7aUv1clIm:bnfp4nl)*

**Pull request merged**
