### PR TITLE
Add video fps control to av settings

### LINKED ISSUE #793: Video framerate
It would be nice to have a possibility to control video frame rate. I.e. for desktop sharing frame rate of 5 to 10 fps would be enough, but better quality is required.

### PR DESCRIPTION
**Pull request by dkmoz**
Fixes #793

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/965)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965#-:-Knr8p3sMzyZrXlnB-5L:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 3 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/settings.c, line 69 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4Aj_h3FZvbCnmo45J:-Ko4Aj_h3FZvbCnmo45K:bj942qo) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L69)):*
> ```C
>     .magic_flist_enabled    = false,
> 
>     .video_fps              = 40, /* 25 fps */
> ```

`= 25` This is frames, not milliseconds. 

---

*[src/settings.c, line 211 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4ArORULUlQLMjsVfO:-Ko4ArORULUlQLMjsVfP:b-iluu40) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L211)):*
> ```C
> 
>     edit_video_fps.length =
>         snprintf((char*)edit_video_fps.data, edit_video_fps.maxlength + 1, "%u", save->video_fps);
> ```

`char *` (space)

---

*[src/settings.c, line 212 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4AyUOAU_H5aLa6M63:-Ko4AyUOAU_H5aLa6M64:b-gcm6w9) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L212)):*
> ```C
>     edit_video_fps.length =
>         snprintf((char*)edit_video_fps.data, edit_video_fps.maxlength + 1, "%u", save->video_fps);
>     if (edit_video_fps.length >= edit_video_fps.maxlength + 1) {
> ```

`> edit_video_fps.maxlength`

---

*[src/settings.h, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4B5aUqiu4OiI9u2O1:-Ko4B5aUqiu4OiI9u2O2:b-ufe11b) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.h#L125)):*
> ```objc
>     uint16_t language;
> 
>     uint32_t video_fps;
> ```

Do we really need to allow for a framerate up to ~4 billion? An `uint8_t` or 16 would be enough in my opinion.

---

*[src/layout/settings.c, line 1101 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4BcO0A0Tgho43_PZV:-Ko4BcO0A0Tgho43_PZW:b-ptn84b) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/layout/settings.c#L1101)):*
> ```C
> {
>     edit_video_fps.data[edit_video_fps.length] = 0;
>     long tmp = strtol((char*)edit_video_fps.data, NULL, 0);
> ```

`char *`

---

*[src/layout/settings.c, line 1105 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4C1ZrjPdUvgQTWO_1:-Ko4C1ZrjPdUvgQTWO_2:b-ptn84b) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/layout/settings.c#L1105)):*
> ```C
>         settings.video_fps = 25;
>         edit_video_fps.length =
>             snprintf((char*)edit_video_fps.data, edit_video_fps.maxlength + 1, "25");
> ```

`char *`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/settings.c, line 69 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4Aj_h3FZvbCnmo45J:-Ko6ax5ckROwd4E8emvD:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L69)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`= 25` This is frames, not milliseconds. 
</blockquote></details>

Done.

---

*[src/settings.c, line 211 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4ArORULUlQLMjsVfO:-Ko6azNg38jud_gSQTmp:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L211)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`char *` (space)
</blockquote></details>

Done.

---

*[src/settings.c, line 212 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4AyUOAU_H5aLa6M63:-Ko6bab0Zl_QP6yP6y6t:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L212)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`> edit_video_fps.maxlength`
</blockquote></details>

Done.

---

*[src/settings.h, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4B5aUqiu4OiI9u2O1:-Ko6cGLPqDHbUxBJsOu4:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.h#L125)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Do we really need to allow for a framerate up to ~4 billion? An `uint8_t` or 16 would be enough in my opinion.
</blockquote></details>

Done.

---

*[src/layout/settings.c, line 1101 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4BcO0A0Tgho43_PZV:-Ko6cHDpeRdt5bCbl6bT:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/layout/settings.c#L1101)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`char *`
</blockquote></details>

Done.

---

*[src/layout/settings.c, line 1105 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4C1ZrjPdUvgQTWO_1:-Ko6cHgs2Z-z69aBWtMc:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/layout/settings.c#L1105)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`char *`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by endoffile78** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/settings.h, line 126 at r3](https://reviewable.io:443/reviews/utox/utox/965#-Ko8eEev0oJSlrlB2aAT:-Ko8eEew5IpspkpvnfCh:b79mfv7) ([raw file](https://github.com/utox/utox/blob/f9f3b9a29eda481de79a0b36fe5dad0a0d8aa3c8/src/settings.h#L126)):*
> ```objc
> 
>     uint8_t  video_fps;
>     uint16_t unused[25];
> ```

This needs to be bumped back up. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by dkmoz** [comment]
Reviewed 4 of 8 files at r1, 1 of 4 files at r2, 3 of 3 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/settings.h, line 126 at r3](https://reviewable.io:443/reviews/utox/utox/965#-Ko8eEev0oJSlrlB2aAT:-Ko8uNwT1hEhZeGG3X-K:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9f3b9a29eda481de79a0b36fe5dad0a0d8aa3c8/src/settings.h#L126)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

This needs to be bumped back up. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965#-:-Ko93973A2QRmpOh2hCl:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/settings.c, line 212 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4AyUOAU_H5aLa6M63:-Ko9CHfjtwuThXfV6B-6:b-54cmme) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L212)):*
<details><summary><i>Previously, dkmoz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This will run unnecessarily now. You need to change `>=` to `>` too. :P It was just a style nit. Sorry for not making that clear.

---

*[src/settings.h, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4B5aUqiu4OiI9u2O1:-Ko9ClC-PGBHwKSvLfzs:b-trqxnu) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.h#L125)):*
<details><summary><i>Previously, dkmoz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You also need to add an `uint8_t unused;` or you'll change the size of the savefile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by robinlinden** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/settings.c, line 212 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4AyUOAU_H5aLa6M63:-KoLbN9n8SD7wo3wiJ3y:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.c#L212)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This will run unnecessarily now. You need to change `>=` to `>` too. :P It was just a style nit. Sorry for not making that clear.
</blockquote></details>

Done.

---

*[src/settings.h, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4B5aUqiu4OiI9u2O1:-KoLbX6uBvK9JAK2ZRty:b-1tjka3) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.h#L125)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You also need to add an `uint8_t unused;` or you'll change the size of the savefile.
</blockquote></details>

Add another variable in there (eg unused_half) or change the type of unused to uint8_t?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by dkmoz** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/settings.h, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4B5aUqiu4OiI9u2O1:-KoLcvfcyuZ0aR_7orNK:b-v2p5uf) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.h#L125)):*
<details><summary><i>Previously, dkmoz wrote…</i></summary><blockquote>

Add another variable in there (eg unused_half) or change the type of unused to uint8_t?
</blockquote></details>

I think the latter would be cleaner

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by robinlinden** [comment]
I'm fine with you changing the type to `uint8_t`. I think we've done the
half unused thing somewhere else and called them zeros.

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/settings.h, line 125 at r2](https://reviewable.io:443/reviews/utox/utox/965#-Ko4B5aUqiu4OiI9u2O1:-Kp3wtVAmlFz5kUFX3Jb:b-896fix) ([raw file](https://github.com/utox/utox/blob/6cb89571613a44819faf592fd527b6d17dd82e3d/src/settings.h#L125)):*
<details><summary><i>Previously, dkmoz wrote…</i></summary><blockquote>

I think the latter would be cleaner
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Comment by robinlinden** [comment]
This looks ~ready to be merged. @endoffile78 can you take another look?
@dkmoz can you rebase this so the CI passes?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/layout/settings.c, line 1099 at r6](https://reviewable.io:443/reviews/utox/utox/965#-KpZef93bauZGzCi0jQG:-KpZef93bauZGzCi0jQH:b7c7rke) ([raw file](https://github.com/utox/utox/blob/947b295f1de1d03c5b320f8d6764abc7610ceebc/src/layout/settings.c#L1099)):*
> ```C
> 
> static void edit_video_fps_onlosefocus(EDIT *UNUSED(edit))
> {
> ```

This needs to be moved to the line above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965#-:-KpZf0IX_qaDeBeIxCfb:b-3epp3b)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965#-:-Kp_vOy8KWIbUKrljZZT:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/965)*

**Pull request merged**
