### PR TITLE
Move Language setting from "Profile" to "User Interface" tab

### PR DESCRIPTION
**Pull request by avoidr**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1243)

### CODE REVIEW

**Comment by redmanmale** [comment]
Reviewed 2 of 2 files at r1.
Review status: 2 files need 1 more reviewer, 1 open discussion remaining, missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---

*[src/ui.c, line 136 at r1](https://reviewable.io/reviews/utox/utox/1243#-LF7NDP06cS0hc6NECZn:-LF7NDP26E3SC-2r39FH:b7uc66t) ([raw file](https://github.com/utox/utox/blob/234f027a9f2a93596ecfd543c98131b8673b8d2d/src/ui.c#L136)):*
> ```C
>     panel_settings_ui.y            = 32;
> 
>     CREATE_DROPDOWN(language, 10, 30, 24, -10);
> ```

There is a new way to declare UI elements.

You could just add a panel with x,y,height,width (see https://github.com/uTox/uTox/blob/develop/src/layout/settings.c#L960) to the language dropdown declaration (https://github.com/uTox/uTox/blob/develop/src/layout/settings.c#L1258).
And then just drop this line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1243)*

**Comment by avoidr** [comment]
Can't I just use this line (`CREATE_DROPDOWN(language, 10, 30, 24, -10);`) in the dropdown_language declaration. Or shouldn't those macros be used for now/that?

**Comment by avoidr** [comment]
And why is `CREATE_DROPDOWN` the only macro with width and height switched around?

**Comment by avoidr** [comment]
Like this, right?

Should I squash those commits?

**Comment by avoidr** [comment]
>It's up to you but not necessary.

Actually, I think it's fine like that. So I'm done here.

>There is a new way to declare UI elements.

Does that mean that the other elements should be converted to the "panel-in-declaration" method, too?

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1243#-:-LFG5mwI5fG8IZgKhpKN:bnfp4nl)*

**Comment by GrayHatter** [comment]
I don't like that this was merged. 

I FULLY agree that it belongs is the UI tab. But if you can't read the language, good luck figuring out where to click.

Instead of reverting this, anyone wanna create a command line flag?

**Comment by GrayHatter** [comment]
Or, perhaps a first run welcome page that allows users to select a language when the settings file doesn't exist? Similar to the current change log page?

**Comment by redmanmale** [comment]
I don't mind any of your proposals but I think it might me overkill.
Default language is english and without it user couldn't even download uTox at all.
And if user changes uTox language on purpose than he knows where to find it.

**Pull request merged**
