### PR TITLE
[Windows] Fix garbage at the end of notification

### LINKED ISSUE #1108: Garbage at the end of the text in the notification balloon
This doesn't always happen, but quite often. Maybe could be related with non ASCII characters in message, I'm not sure.

tox-bug

**Env**
Win 7, 8.1 x64, uTox v.0.16.1

### PR DESCRIPTION
**Pull request by redmanmale**
Fixed #1108.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1135)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1135#-:-L-3-gcvQywIyRM4-GnS:bnfp4nl)*

**Comment by redmanmale** [comment]
Sorry, I forgot about another part of this issue. It's done now.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1135#-:-L-32oLMOQYrivtuXQ85:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/layout/settings.c, line 1333 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-YmSIG9VYTQAeZqTB-:-L-YmSIG9VYTQAeZqTB0:b-h619le) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/layout/settings.c#L1333)):*
> ```C
>     uint16_t length = edit->length;
> 
>     memset(self.name, 0, length);
> ```

Why did you make this change? This will write n bytes which then will be overwritten by memcpy writing n bytes. If you meant to null-terminate, you need 1 more byte in the memset.

---

*[src/layout/settings.c, line 1354 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-YmaokQ02AsGUYHxPx:-L-YmaokQ02AsGUYHxPy:b-h619le) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/layout/settings.c#L1354)):*
> ```C
>     if (length) {
>         length = (length <= TOX_MAX_STATUS_MESSAGE_LENGTH) ? length : TOX_MAX_STATUS_MESSAGE_LENGTH;
>         memset(self.statusmsg, 0, length);
> ```

Why did you make this change? This will write n bytes which then will be overwritten by memcpy writing n bytes. If you meant to null-terminate, you need 1 more byte in the memset.

---

*[src/windows/main.c, line 555 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-Yl_UwKzJfu327a4Eu:-L-Yl_UwKzJfu327a4Ev:boxxfqs) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/windows/main.c#L555)):*
> ```C
>                       self.statusmsg_length, self.statusmsg);
>     uint16_t msg_len = 0;
>     while (msg_len < length)
> ```

Curly brace goes on this line.

---

*[src/windows/notify.c, line 58 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-Yl9xoOAV7oUt1ffKe:-L-Yl9xoOAV7oUt1ffKf:bcvs5tb) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/windows/notify.c#L58)):*
> ```C
> 
>     uint16_t msg_len = 0;
>     while (msg_len < msg_length)
> ```

The curly brace needs to go on this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1135)*

**Comment by redmanmale** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/windows/main.c, line 555 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-Yl_UwKzJfu327a4Eu:-L-c__8Npy5A7KqC8wBa:b-896fix) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/windows/main.c#L555)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Curly brace goes on this line.
</blockquote></details>

Done.

---

*[src/windows/notify.c, line 58 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-Yl9xoOAV7oUt1ffKe:-L-c_aybL9iE-KYw86jf:b-896fix) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/windows/notify.c#L58)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

The curly brace needs to go on this line.
</blockquote></details>

Done.

---

*[src/layout/settings.c, line 1333 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-YmSIG9VYTQAeZqTB-:-L-c_cFJq1LsqlgQhMK3:b-v42qd7) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/layout/settings.c#L1333)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why did you make this change? This will write n bytes which then will be overwritten by memcpy writing n bytes. If you meant to null-terminate, you need 1 more byte in the memset.
</blockquote></details>

Yeah, you're right. It's just pointless.

---

*[src/layout/settings.c, line 1354 at r2](https://reviewable.io:443/reviews/utox/utox/1135#-L-YmaokQ02AsGUYHxPx:-L-c_j1_QZcOQ0yP_aAj:b-816h6l) ([raw file](https://github.com/utox/utox/blob/bb8fb81a8a767f7d11bd251b09d1a601507e266a/src/layout/settings.c#L1354)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why did you make this change? This will write n bytes which then will be overwritten by memcpy writing n bytes. If you meant to null-terminate, you need 1 more byte in the memset.
</blockquote></details>

Same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1135)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1135#-:-L-caafbT5RQi1TEr-gw:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1135#-:-L-ccErTaA_GUQXC-IuU:bnfp4nl)*

**Comment by GrayHatter** [comment]
It's pretty important we get this code right... @robinlinden @endoffile78 how deep did you read into this new function?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1135#-:-L0cFNRW5dV60wvcE89o:b4vuyv9)*

**Pull request merged**
