### PR TITLE
MAX_PATH is bad

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1106)

### CODE REVIEW

**Comment by GrayHatter** [comment]
closes #1105

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1106#-:-KxJtv7EZiQg_2nf1rbB:bnfp4nl)*

**Comment by robinlinden** [comment]
Why is MAX_PATH bad? Why is replacing MAX_PATH with an even bigger number (on some systems) better?

**Comment by GrayHatter** [comment]
MAX_PATH is 260*, but it's not at all tied to the actual value of the max path for the OS.

UTOX_FILE_NAME_LENGTH likely isn't much better. But it wont give a false sense of correctness. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1106#-:-KxKqZG5_gpiQc3eEiy3:byweo49)*

**Comment by redmanmale** [comment]
Why can't we use real MAX_PATH value for each platform and set in #if-defs?

For Windows XP it's 260, Windows 7-8 it's 32767 and from one of the builds of Windows 10 there's no limit at all.

**Comment by GrayHatter** [comment]
@redmanmale I like that idea better, but it's out of scope for the time I have.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1106#-:-KxPDcgE4ksezqOz42Y5:b-jrjpq)*

**Comment by redmanmale** [comment]
But on Windows XP max paths is limited by current MAX_PATH (260) and using bigger number (UTOX_FILE_NAME_LENGTH which is 1024) could cause errors.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1106#-:-KxSLhLGmvhib4kgTIMj:beacykh)*

**Comment by GrayHatter** [comment]
@redmanmale good catch, I'll give it some thought.

**Comment by avoidr** [comment]
Can the branch be deleted?

**Pull request closed without merging**
