### PR TITLE
Fix notifications.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/899)

### CODE REVIEW

**Comment by endoffile78** [comment]
Doesn't compile on OSX.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/899#-:-KjArY8UGvop-zPYEcDY:b4krc7f)*

**Comment by GrayHatter** [comment]
@robinlinden https://travis-ci.org/uTox/uTox/jobs/228133681#L2351 have_focus isn't exposed to osx

**Comment by robinlinden** [comment]
Fixed. I forgot to add it back after I `git checkout --`'d some changes I decided I didn't like. :<

---

Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/899#-:-KjEmtlLQKsR-cHMNl_H:b67zhfl)*

**Comment by GrayHatter** [comment]
:lgtm:

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/899#-:-KjGj7sdaMoMRvAdOGck:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 14 of 15 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 74 at r2](https://reviewable.io:443/reviews/utox/utox/899#-KjF1sKHZHoju2AS18UL:-KjF1sKIrifD7QmgvV34:beyzsdd) ([raw file](https://github.com/utox/utox/blob/34df8e45b1d20c8cd21855163389494daa091434/src/xlib/main.c#L74)):*
> ```C
> }
> 
> static FILE *   ptt_keyboard_handle;
> ```

attach pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/899)*

**Pull request merged**
