### PR TITLE
Create native/window.h

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/831)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/831#-:-KhtcEox6CenI69M4L_6:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/cocoa/window.c, line 31 at r1](https://reviewable.io:443/reviews/utox/utox/831#-KhtfZc64SJAxsabkJI7:-KhtfZc64SJAxsabkJI8:bjete1y) ([raw file](https://github.com/utox/utox/blob/e85bdfcbe6c24199e78e7f5b6335d70f01c855d7/src/cocoa/window.c#L31)):*
> ```C
> }
> 
> UTOX_WINDOW *native_window_create_notify(int x, int y, int w, int h, PANEL* panel) {
> ```

pointer asterisk 

---

*[src/native/window.h, line 39 at r1](https://reviewable.io:443/reviews/utox/utox/831#-Khtfnbzxf3sFsT7LhV-:-Khtfnbzxf3sFsT7LhV0:baxh6hp) ([raw file](https://github.com/utox/utox/blob/e85bdfcbe6c24199e78e7f5b6335d70f01c855d7/src/native/window.h#L39)):*
> ```objc
> // These deal with platform-specific structures
> 
> #if defined __WIN32__ || defined _WIN32 || defined __CYGWIN__
> ```

LGTM but open an issue if this is merged, there shouldn't be any reason all the native functions can't share a type.

---

*[src/xlib/window.c, line 161 at r1](https://reviewable.io:443/reviews/utox/utox/831#-KhtfGDddHk1zCZdt3OX:-KhtfGDenD0hQcpCuF1r:bvb4bd5) ([raw file](https://github.com/utox/utox/blob/e85bdfcbe6c24199e78e7f5b6335d70f01c855d7/src/xlib/window.c#L161)):*
> ```C
> }
> 
> UTOX_WINDOW *native_window_create_notify(int x, int y, int w, int h, PANEL* panel) {
> ```

pointer asterisk is name attached

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/831)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/cocoa/window.c, line 31 at r1](https://reviewable.io:443/reviews/utox/utox/831#-KhtfZc64SJAxsabkJI7:-KiKQ1fmxdthlaIEE_ZM:b-896fix) ([raw file](https://github.com/utox/utox/blob/e85bdfcbe6c24199e78e7f5b6335d70f01c855d7/src/cocoa/window.c#L31)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

pointer asterisk 
</blockquote></details>

Done.

---

*[src/native/window.h, line 39 at r1](https://reviewable.io:443/reviews/utox/utox/831#-Khtfnbzxf3sFsT7LhV-:-KiKQJBzszxRO0XLIX0b:b1md6ij) ([raw file](https://github.com/utox/utox/blob/e85bdfcbe6c24199e78e7f5b6335d70f01c855d7/src/native/window.h#L39)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

LGTM but open an issue if this is merged, there shouldn't be any reason all the native functions can't share a type.
</blockquote></details>

Ack. Will open an issue and fix it in the next step of the native refactor where I'll actually be modifying the .c files.

---

*[src/xlib/window.c, line 161 at r1](https://reviewable.io:443/reviews/utox/utox/831#-KhtfGDddHk1zCZdt3OX:-KiKQHn9l6JhZUKeHnhl:b-896fix) ([raw file](https://github.com/utox/utox/blob/e85bdfcbe6c24199e78e7f5b6335d70f01c855d7/src/xlib/window.c#L161)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

pointer asterisk is name attached
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/831)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/831#-:-KiLokFMlSaDggs2BRoV:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/native/window.h, line 39 at r1](https://reviewable.io:443/reviews/utox/utox/831#-Khtfnbzxf3sFsT7LhV-:-KifUAKf3K6WVVv_QDM3:ba9fswt) ([raw file](https://github.com/utox/utox/blob/e85bdfcbe6c24199e78e7f5b6335d70f01c855d7/src/native/window.h#L39)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Ack. Will open an issue and fix it in the next step of the native refactor where I'll actually be modifying the .c files.
</blockquote></details>

FYI, consider adding a macro for `#if UTOX_PLATFORM_{NIX,OSX,WIN,BSD,AND}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/831#-:-KifUOv1WhmN96_ruB4e:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/831)*

**Pull request merged**
