### PR TITLE
Fix for bad redraw size on windows

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/813)

### CODE REVIEW

**Comment by GrayHatter** [comment]
note that `master` is the target branch

**Comment by GrayHatter** [comment]
fixes #810

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/813)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/813#-:-KhOTbvyXkG50bbOPJWP:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/813#-:-KhOYFi6f7qpCmS67VCv:bnfp4nl)*

**Pull request merged**
