### PR TITLE
Fix a few memory leaks in messages.c

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/706)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/messages.c, line 1643 at r1](https://reviewable.io:443/reviews/utox/utox/706#-KbvTvtoG3fMDUWEpD5h:-KbvTvtpV1mQ8-mI7J4K:b6b61dx) ([raw file](https://github.com/utox/utox/blob/0d47732db01b5f33574135441b6ce626643d4d9f/src/messages.c#L1643)):*
> ```C
> void message_free(MSG_HEADER *msg) {
>     // The group messages are free()d in groups.c (group_free(GROUPCHAT *g))
>     switch (msg->msg_type) {
> ```

why wasn't this throwing a warning once we switched in to a typdef enum?

---

*[src/messages.h, line 75 at r1](https://reviewable.io:443/reviews/utox/utox/706#-KbvUB1jrYkujacyYaGu:-KbvUB1jrYkujacyYaGv:b-97qx26) ([raw file](https://github.com/utox/utox/blob/0d47732db01b5f33574135441b6ce626643d4d9f/src/messages.h#L75)):*
> ```objc
> /* Generic Message type */
> typedef struct msg_header {
>     uint8_t msg_type;
> ```

fix this bug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/706)*

**Comment by endoffile78** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/706)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/messages.c, line 1643 at r1](https://reviewable.io:443/reviews/utox/utox/706#-KbvTvtoG3fMDUWEpD5h:-Kbvxc2uiyQUCKT7iSsx:bb7uirp) ([raw file](https://github.com/utox/utox/blob/0d47732db01b5f33574135441b6ce626643d4d9f/src/messages.c#L1643)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why wasn't this throwing a warning once we switched in to a typdef enum?
</blockquote></details>

It was never switched to being a typedef enum.

---

*[src/messages.h, line 75 at r1](https://reviewable.io:443/reviews/utox/utox/706#-KbvUB1jrYkujacyYaGu:-KbvxfZCbfkQR2oYkPul:b-bwl2k7) ([raw file](https://github.com/utox/utox/blob/0d47732db01b5f33574135441b6ce626643d4d9f/src/messages.h#L75)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fix this bug
</blockquote></details>

It is now a typedef enum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/706)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/706#-:-KbwMKMz1_kmlnorP3C0:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/706#-:-KbxCCNPRlACx-0VfMPi:bnfp4nl)*

**Pull request merged**
