### PR TITLE
Drop file_raw

### LINKED ISSUE #798: Delete file_raw()

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #798 (macOS part).

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1118)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1118#-:-Kz5ImEmfYPpdpLtTDiq:bnfp4nl)*

**Comment by redmanmale** [comment]
@publicarray 
Could you please take a look?

**Comment by publicarray** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/interaction.m, line 1037 at r1](https://reviewable.io:443/reviews/utox/utox/1118#-Kz_gh1tl9u3ueFBaQX4:-Kz_gh1tl9u3ueFBaQX5:b-9v0iwu) ([raw file](https://github.com/utox/utox/blob/19ed40475d56d826abbb155cb5f00175dc96155f/src/cocoa/interaction.m#L1037)):*
> ```objc
> 
>     if (ret == NSFileHandlingPanelOKButton) {
>         int width, height, bpp, size;
> ```

Just a small nit. What is bpp? bits per pixel? 

The only info I could find is in stb_image.h
```
n = # 8-bit components per pixel ...
//    // ... replace '0' with '1'..'4' to force that many components per pixel
//    // ... but 'n' will always be the number that it would have been if you said 0
```

Maybe add a small comment but I leave it to you if you think it is necessary. It is also in the windows implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1118#-:-Kz_kBlE7O39PqtWSd7S:bnfp4nl)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/interaction.m, line 1037 at r1](https://reviewable.io:443/reviews/utox/utox/1118#-Kz_gh1tl9u3ueFBaQX4:-Kz_mo6W6DMAZT1pWBlR:bluqwyj) ([raw file](https://github.com/utox/utox/blob/19ed40475d56d826abbb155cb5f00175dc96155f/src/cocoa/interaction.m#L1037)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Just a small nit. What is bpp? bits per pixel? 

The only info I could find is in stb_image.h
```
n = # 8-bit components per pixel ...
//    // ... replace '0' with '1'..'4' to force that many components per pixel
//    // ... but 'n' will always be the number that it would have been if you said 0
```

Maybe add a small comment but I leave it to you if you think it is necessary. It is also in the windows implementation.

</blockquote></details>

I didn't touch naming but yeah it's bits per pixel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1118)*

**Comment by publicarray** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/interaction.m, line 1037 at r1](https://reviewable.io:443/reviews/utox/utox/1118#-Kz_gh1tl9u3ueFBaQX4:-Kz_nrM50e-kNam3zgSe:b-gia6s0) ([raw file](https://github.com/utox/utox/blob/19ed40475d56d826abbb155cb5f00175dc96155f/src/cocoa/interaction.m#L1037)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

I didn't touch naming but yeah it's bits per pixel.
</blockquote></details>

LGTM Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1118)*

**Pull request merged**
