### PR TITLE
fix #841

### LINKED ISSUE #841: OS X: crash on start
Current develop crashes on start:

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [0]

Application Specific Information:
*** __CFTypeCollectionRetain() called with NULL; likely a collection has been corrupted ***

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fffc6e72252 __CFTypeCollectionRetain + 114
1   com.apple.CoreFoundation      	0x00007fffc6e71fd1 __CFBasicHashAddValue + 1681
2   com.apple.CoreFoundation      	0x00007fffc6e701a7 CFBasicHashAddValue + 311
3   com.apple.CoreFoundation      	0x00007fffc6ea9fce CFDictionaryCreate + 286
4                                 	0x000000010c81b1b3 drawtextwidth + 371
5                                 	0x000000010c83b61c draw_user_badge + 508
6                                 	0x000000010c7e6bfb panel_draw_sub + 219
7                                 	0x000000010c7e6c21 panel_draw_sub + 257
8                                 	0x000000010c81a691 -[uToxView drawRect:] + 241
9   com.apple.AppKit              	0x00007fffc4b44369 -[NSView _drawRect:clip:] + 2276
10  com.apple.AppKit              	0x00007fffc4b942ff -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:] + 1753
11  com.apple.AppKit              	0x00007fffc4b9476a -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:] + 2884
12  com.apple.AppKit              	0x00007fffc4b41ea2 -[NSView _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 837
13  com.apple.AppKit              	0x00007fffc4b4167f -[NSThemeFrame _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 334
14  com.apple.AppKit              	0x00007fffc4b3faa8 -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 2452
15  com.apple.AppKit              	0x00007fffc4b3b39a -[NSView displayIfNeeded] + 1748
16  com.apple.AppKit              	0x00007fffc4b3acab -[NSWindow displayIfNeeded] + 230
17  com.apple.AppKit              	0x00007fffc529ad24 ___NSWindowGetDisplayCycleObserver_block_invoke.6228 + 277
18  com.apple.AppKit              	0x00007fffc4b3a789 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke + 454
19  com.apple.QuartzCore          	0x00007fffcca18dc6 CA::Transaction::run_commit_handlers(CATransactionPhase) + 46
20  com.apple.QuartzCore          	0x00007fffccb228f0 CA::Context::commit_transaction(CA::Transaction*) + 160
21  com.apple.QuartzCore          	0x00007fffcca178a1 CA::Transaction::commit() + 475
22  com.apple.AppKit              	0x00007fffc4e1db99 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke.31 + 323
23  com.apple.CoreFoundation      	0x00007fffc6f0edd7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
24  com.apple.CoreFoundation      	0x00007fffc6f0ed47 __CFRunLoopDoObservers + 391
25  com.apple.CoreFoundation      	0x00007fffc6eef789 __CFRunLoopRun + 873
26  com.apple.CoreFoundation      	0x00007fffc6eef1c4 CFRunLoopRunSpecific + 420
27  com.apple.HIToolbox           	0x00007fffc6450ebc RunCurrentEventLoopInMode + 240
28  com.apple.HIToolbox           	0x00007fffc6450bf9 ReceiveNextEventCommon + 184
29  com.apple.HIToolbox           	0x00007fffc6450b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
30  com.apple.AppKit              	0x00007fffc49ebe24 _DPSNextEvent + 1120
31  com.apple.AppKit              	0x00007fffc516785e -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
32  com.apple.AppKit              	0x00007fffc49e07ab -[NSApplication run] + 926
33                                	0x000000010c82506b main + 3131
34  libdyld.dylib                 	0x00007fffdc652235 start + 1

### PR DESCRIPTION
**Pull request by publicarray**
After many sleepless nights with my best friend, the Xcode debugger and plenty of 🍕 & 🍷  . I have found a solution. jks

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/866)

### CODE REVIEW

**Comment by publicarray** [comment]
The San Francisco font is still needed though.

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/866#-:-KiSwu9aQJ7IuSFaFGUG:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/866#-:-KiT4JQyjYY4H5_Ump3S:bnfp4nl)*

**Comment by publicarray** [comment]
Thanks that was quick.

**Pull request merged**
