### PR TITLE
Opus 1.1.4 -> 1.2.1

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/984)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[extra/common/build_opus.sh, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/984#-KqxjJ8OQkKEaVpKYb_U:-KqxjJ8PAMnebOcSYtJX:bumglh2) ([raw file](https://github.com/utox/utox/blob/46873ed550397efd8596feb3903187765ab6267f/extra/common/build_opus.sh#L7)):*
> ```Shell
>   curl http://downloads.xiph.org/releases/opus/opus-1.2.1.tar.gz -o opus.tar.gz
>   tar xzf opus.tar.gz
>   cd opus-1.2.1
> ```

should be a $VAR at the top of the file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/984#-:-KqxjNZ1CarFG3lkJfZb:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/984#-:-KqxmjBwPEYpeIafIJMk:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/984#-:-Kqxw84Bt_hUxTdOAd_q:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[extra/common/build_opus.sh, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/984#-KqxjJ8OQkKEaVpKYb_U:-Kqy3Oog2KquNF0JaV2G:b-896fix) ([raw file](https://github.com/utox/utox/blob/46873ed550397efd8596feb3903187765ab6267f/extra/common/build_opus.sh#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

should be a $VAR at the top of the file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/984)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/984#-:-Kqy7-J3DEb_RYy-_fMS:bnfp4nl)*

**Pull request merged**
