### PR TITLE
Use git submodule for stb

### PR DESCRIPTION
**Pull request by redmanmale**
It looks straightforward, so if it's not necessary or it has some pitfalls just close this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1041)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-KtY0hSRa4Y53g6-r5S6:bnfp4nl)*

**Comment by GrayHatter** [comment]
should be a separate dir (not `src/` )

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-KtYoV_zamgSZaWFTyd8:b-gvzzft)*

**Comment by redmanmale** [comment]
@GrayHatter 
Done.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-Kty-B-XYpzjkNgHNeBT:bnfp4nl)*

**Comment by cebe** [comment]
all `git clone` calls in `/docs/BUILD.md` need the `--recursive` flag added. Other than that, is looks good.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-Ktzd95NpGkWQQy0SaXp:bh1q7n3)*

**Comment by robinlinden** [comment]
The Jenkins builds will also have to be updated.

**Comment by redmanmale** [comment]
@cebe 
Done.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-KuFjGhYz52HegeFP5sf:bnfp4nl)*

**Comment by cebe** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/BUILD.md, line 166 at r3](https://reviewable.io:443/reviews/utox/utox/1041#-KuGiaRllZr3Rmu6-sQi:-KuGiaRmfjpkkiR_Zh3N:b-i8uv5f) ([raw file](https://github.com/utox/utox/blob/cb8eb0d0e4fad88875c46b9887f0d6e9daea0aed/docs/BUILD.md#L166)):*
> ```Markdown
> ### Cygwin setup
> 
> - Download Cygwin ([x86](https://cygwin.com/setup-x86_64.exe)/[x64](https://cygwin.com/setup-x86.exe))
> ```

link titles do not match the exe name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041)*

**Comment by redmanmale** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/BUILD.md, line 166 at r3](https://reviewable.io:443/reviews/utox/utox/1041#-KuGiaRllZr3Rmu6-sQi:-KuI_SIP0JppawwIhxH8:b-896fix) ([raw file](https://github.com/utox/utox/blob/cb8eb0d0e4fad88875c46b9887f0d6e9daea0aed/docs/BUILD.md#L166)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

link titles do not match the exe name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-KuLXV-vPKS0uo1mVy1c:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-KuMhFv-hIoXleFQypMe:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1041#-:-KuOIfey_YIAqwanhVwS:bnfp4nl)*

**Pull request merged**
