### PR TITLE
Don't allow loading a 0 fps setting from save.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1068)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/settings.c, line 215 at r1](https://reviewable.io:443/reviews/utox/utox/1068#-KurUf4l3LYMX-HriEdc:-KurUf4l3LYMX-HriEdd:b-71qrej) ([raw file](https://github.com/utox/utox/blob/7f376bb7668bfe5609012999e5e471e0ff947212/src/settings.c#L215)):*
> ```C
>     settings.send_version           = save->send_version;
> 
>     settings.video_fps = save->video_fps == 0 ? 25 : save->video_fps;
> ```

`     settings.video_fps = save->video_fps ? save->video_fps : 25;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1068)*

**Comment by robinlinden** [comment]
I did that at first but changed it to this after looking at the other
places this construct was used.

**Comment by GrayHatter** [comment]
the other places are wrong then

**Comment by redmanmale** [comment]
`video_fps` is integer, is it not considered an implicit use of number as boolean bad? Explicit comparison is better in such cases, isn't?

**Comment by GrayHatter** [comment]
Maybe in some languages, but in iso c; bool really isn't a thing. The smallest form of memory is 8 bits. thus even a bool == uint8_t. Where 0 == false, and everything else is true. 

Simply the `?` is just `if not 0, use what's before the :, else use what's after the :`

**Comment by redmanmale** [comment]
Roger that, thanks.

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1068)*

**Comment by robinlinden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/settings.c, line 215 at r1](https://reviewable.io:443/reviews/utox/utox/1068#-KurUf4l3LYMX-HriEdc:-KxdrxE3tmPOm93OSfmn:b-896fix) ([raw file](https://github.com/utox/utox/blob/7f376bb7668bfe5609012999e5e471e0ff947212/src/settings.c#L215)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`     settings.video_fps = save->video_fps ? save->video_fps : 25;`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1068)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1068#-:-KxdtACdlN486j4qayUD:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1068#-:-Kxik5RyvUv4u8tdJMK-:bnfp4nl)*

**Pull request merged**
