### PR TITLE
Mirror changes done on GitLab to GitHub.

### PR DESCRIPTION
**Pull request by robinlinden**
This is mainly so that the build.tox.chat static analysers will have a recent-ish version of the code.

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/785)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm_strong: 

---

Reviewed 85 of 85 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/785#-:-Kf1brEmND-vfv7JhD1t:b-uwkowd)*

**Comment by GrayHatter** [comment]
travis will fail...

**Comment by cebe** [comment]
make sure to not create a merge commit from this one so gitlab and github have the same commit hashes.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 85 of 85 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/785#-:-Kf2ksAbHhe2QQ6Axnht:bnfp4nl)*

**Pull request merged**
