### PR TITLE
Enable updater test only when updater is enabled

### PR DESCRIPTION
**Pull request by nurupo**
Also includes a commit trying to enable dbus on Travis. I can split it in a separate PR if needed.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/849)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 19 at r1](https://reviewable.io:443/reviews/utox/utox/849#-KiHocyUKh2zSZHccHTG:-KiHocyUKh2zSZHccHTH:b-etdtkl) ([raw file](https://github.com/utox/utox/blob/c5a3e441b7c5fb051f5ca081855761288676eeca/.travis.yml#L19)):*
> ```YAML
>       - check
>       - pkg-config
>       - libdbus-1-dev
> ```

IIRC this is already installed?

---

*[extra/travis/linux-script.sh, line 6 at r1](https://reviewable.io:443/reviews/utox/utox/849#-KiHohzsEvz5CAqR5ESG:-KiHohzsEvz5CAqR5ESH:bz34nst) ([raw file](https://github.com/utox/utox/blob/c5a3e441b7c5fb051f5ca081855761288676eeca/extra/travis/linux-script.sh#L6)):*
> ```Shell
> . ./extra/travis/env.sh
> pkg-config --cflags dbus-1
> cmake . -DCMAKE_INCLUDE_PATH="$CACHE_DIR/usr/lib" -DENABLE_TESTS=ON -DENABLE_WERROR=ON -DENABLE_DBUS=ON -DENABLE_AUTOUPDATE=ON
> ```

BTW, if you have to touch this file again, can you split each define onto it's own line 
```
    -DCMAKE_INCLUDE_PATH="$CACHE_DIR/usr/lib" \
    -DENABLE_TESTS=ON \
    -DENABLE_WERROR=ON \
    -DENABLE_DBUS=ON \
    -DENABLE_AUTOUPDATE=ON
```

---

*[tests/CMakeLists.txt, line 39 at r1](https://reviewable.io:443/reviews/utox/utox/849#-KiHoYIp3ycENW7qDyh_:-KiHoYIp3ycENW7qDyha:b-viq7nt) ([raw file](https://github.com/utox/utox/blob/c5a3e441b7c5fb051f5ca081855761288676eeca/tests/CMakeLists.txt#L39)):*
> ```CMake
> make_test(chatlog)
> 
> if(${ENABLE_AUTOUPDATE})
> ```

I don't think you need the ${} for cmake do you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/849)*

**Comment by GrayHatter** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 19 at r1](https://reviewable.io:443/reviews/utox/utox/849#-KiHocyUKh2zSZHccHTG:-KiHqLYcf7Kxg6H42Ydu:b-9mcppd) ([raw file](https://github.com/utox/utox/blob/c5a3e441b7c5fb051f5ca081855761288676eeca/.travis.yml#L19)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

IIRC this is already installed?
</blockquote></details>

LGTM 

nope, I'm wrong, it's needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/849)*

**Comment by nurupo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[extra/travis/linux-script.sh, line 6 at r1](https://reviewable.io:443/reviews/utox/utox/849#-KiHohzsEvz5CAqR5ESG:-KiI-0OTw8C-umItadI1:bb6un1j) ([raw file](https://github.com/utox/utox/blob/c5a3e441b7c5fb051f5ca081855761288676eeca/extra/travis/linux-script.sh#L6)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW, if you have to touch this file again, can you split each define onto it's own line 
```
    -DCMAKE_INCLUDE_PATH="$CACHE_DIR/usr/lib" \
    -DENABLE_TESTS=ON \
    -DENABLE_WERROR=ON \
    -DENABLE_DBUS=ON \
    -DENABLE_AUTOUPDATE=ON
```
</blockquote></details>

Done

---

*[tests/CMakeLists.txt, line 39 at r1](https://reviewable.io:443/reviews/utox/utox/849#-KiHoYIp3ycENW7qDyh_:-KiI-1QDHhp80Gg_uU48:bl2nvjh) ([raw file](https://github.com/utox/utox/blob/c5a3e441b7c5fb051f5ca081855761288676eeca/tests/CMakeLists.txt#L39)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I don't think you need the ${} for cmake do you?
</blockquote></details>

I guess it works both ways. Removed`${}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/849)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 4 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[extra/common/env.sh, line 19 at r2](https://reviewable.io:443/reviews/utox/utox/849#-KiI_O15wG6NDfXpECWX:-KiI_O16_rC3AOYMY4jZ:b-e5j823) ([raw file](https://github.com/utox/utox/blob/ba407a07504a19008c6c4ce5e9a205107aaa07d4/extra/common/env.sh#L19)):*
> ```Shell
> export LD_LIBRARY_PATH="${CACHE_DIR}/usr/lib:/usr/lib"
> 
> export PKG_CONFIG_PATH="${CACHE_DIR}/usr/lib/pkgconfig"
> ```

does this break the OSX docker build?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/849)*

**Comment by nurupo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[extra/common/env.sh, line 19 at r2](https://reviewable.io:443/reviews/utox/utox/849#-KiI_O15wG6NDfXpECWX:-KiIa1PvYypglOg2tJbv:b-t610gl) ([raw file](https://github.com/utox/utox/blob/ba407a07504a19008c6c4ce5e9a205107aaa07d4/extra/common/env.sh#L19)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

does this break the OSX docker build?
</blockquote></details>

No idea what the "OSX docker build" is. All Travis builds seem to pass, if that's what you are about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/849)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[extra/common/env.sh, line 19 at r2](https://reviewable.io:443/reviews/utox/utox/849#-KiI_O15wG6NDfXpECWX:-KiIaqKgAyBDrFr8HbDy:b-k41akq) ([raw file](https://github.com/utox/utox/blob/ba407a07504a19008c6c4ce5e9a205107aaa07d4/extra/common/env.sh#L19)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

No idea what the "OSX docker build" is. All Travis builds seem to pass, if that's what you are about.
</blockquote></details>

LGTM No, the OSX docker build runs on our gitlab CI, it does pass however.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/849#-:-KiIazdtGF_7tFQGVtZj:b593vm9)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/849#-:-KiKN7LM7romshUIQgb7:bnfp4nl)*

**Pull request merged**
