### PR TITLE
Group av

### LINKED ISSUE #34: Version 0.4.2 broke Group Call
With version 0.3.2 group chats worked, even cross-client with qTox. In version 0.4.2, you can chat via text, but voice chat can't be started. The symbol stays greyed out. qTox is also not compatible, you can't call people on qTox with uTox 0.4.2 and they can't call you. Text chat seems to work.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28063473-version-0-4-2-broke-group-call?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by endoffile78**
Fixes #34 

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/928)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 2 of 10 files at r1, 7 of 9 files at r2, 3 of 3 files at r3.
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/utox_av.c, line 140 at r3](https://reviewable.io:443/reviews/utox/utox/928#-KlFESi_7yYRkSzArGjS:-KlFESi_7yYRkSzArGjT:bljklig) ([raw file](https://github.com/utox/utox/blob/00bf0629cc399994e163f9bd79781dc056115945/src/av/utox_av.c#L140)):*
> ```C
>                         LOG_INFO("uToxAv", "Ending group call in groupchat %u", msg->param1);
>                         postmessage_audio(UTOXAUDIO_GROUPCHAT_STOP, msg->param1, msg->param2, NULL);
>                         postmessage_audio(UTOXAUDIO_STOP_RINGTONE, msg->param1, msg->param2, NULL);
> ```

this might be wrong here :<

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928#-:-KlFEfUwO7CMBAhtfTSk:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm: 

---

Reviewed 2 of 10 files at r1, 6 of 9 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928#-:-KlFGjwvsxAHW7PUN-sb:bg7igkv)*

**Comment by GrayHatter** [comment]
+@robinlinden 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928#-:-KlFHF_xdQ3muqtBtosU:bm4pyxg)*

**Comment by robinlinden** [comment]
Reviewed 1 of 10 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/tox.c, line 1063 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFtANAuojwSZKgbVjG:-KlFtANBd2cto9FttZZt:b-1tibq4) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/tox.c#L1063)):*
> ```C
>             uint64_t pkey_to_number = 0;
>             int      key_i          = 0;
>             for (; key_i < TOX_PUBLIC_KEY_SIZE; ++key_i) {
> ```

C99 for loop plz. `key_i` is never used outside of it.

---

*[src/tox.c, line 1070 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFto-jaWJgAqL_vfLl:-KlFto-jaWJgAqL_vfLm:b-12r5vn) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/tox.c#L1070)):*
> ```C
> 
>             group_peer_add(get_group(g_num), 0, 1, name_color);
>             group_peer_name_change(get_group(g_num), 0, (const uint8_t*)self.name, self.name_length);
> ```

`uint8_t *`. Missing a space, and const is implicitly added.

---

*[src/av/audio.c, line 565 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFv2A9Mxsp_uN0Mv7J:-KlFv2A9Mxsp_uN0Mv7K:b-ta8hug) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/audio.c#L565)):*
> ```C
> 
> void postmessage_audio(uint8_t msg, uint32_t param1, uint32_t param2, void *data) {
>     while (audio_thread_msg && utox_audio_thread_init) {
> ```

abcdef

---

*[src/av/audio.c, line 629 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFvTokGRV1F4RFv5HC:-KlFvTokGRV1F4RFv5HD:br5gryr) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/audio.c#L629)):*
> ```C
>             switch (m->msg) {
>                 case UTOXAUDIO_CHANGE_MIC: {
>                     while (audio_in_ignore());
> ```

Consider adding an empty body for these to make it obvious what you mean to do. (I swear this is what you asked me to do.)

---

*[src/av/audio.c, line 922 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFxVwEnRDKyxNTai3T:-KlFxVwEnRDKyxNTai3U:br5gryr) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/audio.c#L922)):*
> ```C
>     alDeleteBuffers(1, &RingBuffer);
> 
>     while (audio_in_device_close());
> ```

Consider adding an empty body for these to make it obvious what you mean to do. (I swear this is what you asked me to do.)

---

*[src/av/utox_av.c, line 140 at r3](https://reviewable.io:443/reviews/utox/utox/928#-KlFESi_7yYRkSzArGjS:-KlFy-YOJ5JCWEoSIbi6:bf4s56v) ([raw file](https://github.com/utox/utox/blob/00bf0629cc399994e163f9bd79781dc056115945/src/av/utox_av.c#L140)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this might be wrong here :<
</blockquote></details>

Yeah, probably.  The ringtone doesn't really have anything to do with us ending an audio call.

---

*[src/av/utox_av.h, line 53 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFyJOT_M38UheRMDkz:-KlFyJOT_M38UheRMDl-:bytn9gz) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/utox_av.h#L53)):*
> ```objc
> };
> 
> typedef struct groupchat GROUPCHAT;
> ```

This line can be deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928)*

**Comment by robinlinden** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/av/audio.c, line 565 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFv2A9Mxsp_uN0Mv7J:-KlG-6KW2g0m0XfDs28q:b-khag4f) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/audio.c#L565)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

abcdef
</blockquote></details>

..I'm sure I started on a comment here for a very good reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/tox.c, line 1063 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFtANAuojwSZKgbVjG:-KlG0WMJltPDSrudj3pX:bb7f2mf) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/tox.c#L1063)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

C99 for loop plz. `key_i` is never used outside of it.
</blockquote></details>

done

---

*[src/tox.c, line 1070 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFto-jaWJgAqL_vfLl:-KlG0XK5aX-iVAR5vlTJ:bb7f2mf) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/tox.c#L1070)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`uint8_t *`. Missing a space, and const is implicitly added.
</blockquote></details>

done

---

*[src/av/audio.c, line 565 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFv2A9Mxsp_uN0Mv7J:-KlG0ZTpGnZB5E4iWzYE:b2r1pyk) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/audio.c#L565)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

..I'm sure I started on a comment here for a very good reason.
</blockquote></details>

lol maybe I fixed it...

---

*[src/av/audio.c, line 629 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFvTokGRV1F4RFv5HC:-KlG0xdFhTD7pkTTSqeW:bb7f2mf) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/audio.c#L629)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Consider adding an empty body for these to make it obvious what you mean to do. (I swear this is what you asked me to do.)
</blockquote></details>

done

---

*[src/av/audio.c, line 922 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFxVwEnRDKyxNTai3T:-KlG0z4ssZUBhCKel4kK:bb7f2mf) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/audio.c#L922)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Consider adding an empty body for these to make it obvious what you mean to do. (I swear this is what you asked me to do.)
</blockquote></details>

done

---

*[src/av/utox_av.c, line 140 at r3](https://reviewable.io:443/reviews/utox/utox/928#-KlFESi_7yYRkSzArGjS:-KlG14QBSW55rtlEbVPa:blj9e8y) ([raw file](https://github.com/utox/utox/blob/00bf0629cc399994e163f9bd79781dc056115945/src/av/utox_av.c#L140)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Yeah, probably.  The ringtone doesn't really have anything to do with us ending an audio call.
</blockquote></details>

removed then

---

*[src/av/utox_av.h, line 53 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFyJOT_M38UheRMDkz:-KlG1BvOxBM9jRpyFYir:b-2bqjmm) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/utox_av.h#L53)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This line can be deleted.
</blockquote></details>

no it can't

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928)*

**Comment by robinlinden** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/av/utox_av.h, line 53 at r6](https://reviewable.io:443/reviews/utox/utox/928#-KlFyJOT_M38UheRMDkz:-KlG1iLvb5qsgjh9XqF0:b-pf4rhp) ([raw file](https://github.com/utox/utox/blob/0dbb99f4b289570aaaada07d96f130f333989a9e/src/av/utox_av.h#L53)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no it can't
</blockquote></details>

Whoops. Missed those lines. You're right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r6, 2 of 4 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928#-:-KlGrCkXkXnqwQ5oR6Yu:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

+@cebe or @robinlinden  need to review this as both @endoffile78 and I have modified the code.


-@GrayHatter 

---

Reviewed 2 of 4 files at r6, 2 of 4 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928#-:-KmycAuwoMrYzGVajfII:byz6v74)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928#-:-Kn0tfPqfrc_dAomujU3:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/928)*

**Pull request merged**
