### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/514)

### CODE REVIEW

**Comment by GrayHatter** [comment]
add `build*/` please

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 6 at r1](https://reviewable.io:443/reviews/utox/utox/514#-KXSobals6Wlmk8bkjwN:-KXSobals6Wlmk8bkjwO:bxs1n43) ([raw file](https://github.com/utox/utox/blob/b134dcdd2bcebcc4759863e823ef0f5b2f739cb3/.gitignore#L6)):*
> ```
> src/*/*.d
> src/*/*.dll
> src/*.o
> ```

replace all `*.o` with `**/*.o`
and .a

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/514#-:-KXSoow4pbs8jtrpORT3:b-afqcm7)*

**Comment by endoffile78** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 6 at r1](https://reviewable.io:443/reviews/utox/utox/514#-KXSobals6Wlmk8bkjwN:-KXSqGMz4peANSoEtCfF:b-896fix) ([raw file](https://github.com/utox/utox/blob/b134dcdd2bcebcc4759863e823ef0f5b2f739cb3/.gitignore#L6)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> replace all `*.o` with `**/*.o`
> and .a
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/514#-:-KXSqNRNO0_9wx6Dj_u9:b-896fix)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 35 at r2](https://reviewable.io:443/reviews/utox/utox/514#-KXSrBIuIW2ivrKvVLpf:-KXSrBIvQplU--oWJNl7:b-2nue3d) ([raw file](https://github.com/utox/utox/blob/b93571cccea9ae45dae14cb60055a4a426ff5ba2/.gitignore#L35)):*
> ```
> CMakeCache.txt
> Makefile
> install_manifest.txt
> ```

add a blank line please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/514#-:-KXSqhHkHvrYfGChc_gY:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 35 at r2](https://reviewable.io:443/reviews/utox/utox/514#-KXSrBIuIW2ivrKvVLpf:-KXSrjvuaaVcVJraCUHo:bb6ywmx) ([raw file](https://github.com/utox/utox/blob/b93571cccea9ae45dae14cb60055a4a426ff5ba2/.gitignore#L35)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> add a blank line please
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/514)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 35 at r2](https://reviewable.io:443/reviews/utox/utox/514#-KXSrBIuIW2ivrKvVLpf:-KXSrudVkRceetr5No-c:b-896fix) ([raw file](https://github.com/utox/utox/blob/b93571cccea9ae45dae14cb60055a4a426ff5ba2/.gitignore#L35)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> LGTM
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/514)*

**Pull request merged**
