### PR TITLE
Fixing warnings

### PR DESCRIPTION
**Pull request by robinlinden**
Still lots of warnings in a lot of files as some are actual problems and some we can't do much about.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/475)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/xlib/main.c, line 235 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQAJH6jX3fOOVmaFe:-KWLQAJH6jX3fOOVmaFf:b-hkwo9d) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L235)):*
> ```C
> uint8_t *native_load_data(const uint8_t *name, size_t name_length, size_t *out_size) {
>     char  path[UTOX_FILE_NAME_LENGTH] = { 0 };
>     uint8_t *data;
> ```

why u8 here?

---

*[src/xlib/main.c, line 262 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQH7MGZEx32SqN1zM:-KWLQH7NnG9hXs4z9g-w:b-dv3dra) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L262)):*
> ```C
>     size_t size = ftell(file);
> 
>     data = (uint8_t *)calloc(size + 1, 1); // needed for the ending null byte
> ```

is this cast needed?

---

*[src/xlib/main.c, line 887 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQkKRylXUMKhZI_0d:-KWLQkKRylXUMKhZI_0e:buh8j1d) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L887)):*
> ```C
>     if (result == -1) {
>         return 0;
>     } else {
> ```

no else after return

---

*[src/xlib/main.c, line 904 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQnyM7vtGP10a2npd:-KWLQnyM7vtGP10a2npe:buh8j1d) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L904)):*
> ```C
>         return 0;
>     } else {
>         return 1;
> ```

no else after return

---

*[src/xlib/main.c, line 929 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLR0okUndsaxQEaCuO:-KWLR0okUndsaxQEaCuP:bg4164u) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L929)):*
> ```C
>     char *str = tohtml(msg, msg_length);
> 
>     /* Todo handle this warning! */
> ```

this should be cleared now right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/475)*

**Comment by robinlinden** [comment]
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/xlib/main.c, line 235 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQAJH6jX3fOOVmaFe:-KWUO9S3a39lRUB2Odjv:b-ykjpac) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L235)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> why u8 here?
</details>
After discussion on IRC, this is going to stay `uint8_t*` as it could be pointing to several different types of data.

---

*[src/xlib/main.c, line 262 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQH7MGZEx32SqN1zM:-KWUMMKGADRFqTHCQ75_:b-22uhrk) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L262)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> is this cast needed?
</details>
Apparently not. `void*` is implicitly cast to anything. Fixed.

---

*[src/xlib/main.c, line 887 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQkKRylXUMKhZI_0d:-KWUMVJhBtD_ue42eE2a:b-896fix) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L887)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> no else after return
</details>
Done.

---

*[src/xlib/main.c, line 904 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQnyM7vtGP10a2npd:-KWUMW7IoeqPW_GsLcd5:b-896fix) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L904)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> no else after return
</details>
Done.

---

*[src/xlib/main.c, line 929 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLR0okUndsaxQEaCuO:-KWUMWd8f8WvE_s4SAh5:bhl7bml) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L929)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> this should be cleared now right?
</details>
You're right. It is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/475)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 4 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/xlib/main.c, line 887 at r1](https://reviewable.io:443/reviews/utox/utox/475#-KWLQkKRylXUMKhZI_0d:-KWVtr52MeHN8s6Cb0OP:b-tz500j) ([raw file](https://github.com/utox/utox/blob/b3a9d36e5f2e606d7949cca5834b108b1903b9d0/src/xlib/main.c#L887)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Done.
</details>
LGTM

From what I remember, this might be a candidate  for returning bool true on success; non-blocking this can be changed later

---

*[src/xlib/main.c, line 7 at r2](https://reviewable.io:443/reviews/utox/utox/475#-KWVsKmToh3CSHy7MfmF:-KWVsKmToh3CSHy7MfmG:bj46d1c) ([raw file](https://github.com/utox/utox/blob/6fb525d09746e318164c1ae66b16c7832cd662e4/src/xlib/main.c#L7)):*
> ```C
> #include "../flist.h"
> #include "../friend.h"
> #include "../main_native.h"
> ```

Putting the file_opts enum in main_native was stupid idea... (I know it was my idea), it needs to be moved to /main.h

Native sources shouldn't include main_native.h, they should just include [platform]/main.h

---

*[src/xlib/main.c, line 183 at r2](https://reviewable.io:443/reviews/utox/utox/475#-KWVt8weFxq2KJAYi3SS:-KWVt8weFxq2KJAYi3ST:buj87n3) ([raw file](https://github.com/utox/utox/blob/6fb525d09746e318164c1ae66b16c7832cd662e4/src/xlib/main.c#L183)):*
> ```C
> // Returns true if path exists, false otherwise.
> bool native_create_dir(const char *filepath) {
>     if (UTOX_FILE_OPTS_WRITE | UTOX_FILE_OPTS_MKDIR) {
> ```

this function doesn't need to check this, only callers need to make this check.

---

*[src/xlib/main.c, line 187 at r2](https://reviewable.io:443/reviews/utox/utox/475#-KWVtK3otjeXC6dWD9pz:-KWVtK3p111SMKVTxAbF:b78dhri) ([raw file](https://github.com/utox/utox/blob/6fb525d09746e318164c1ae66b16c7832cd662e4/src/xlib/main.c#L187)):*
> ```C
>         if (status == 0) {
>             return true;
>         } else if (errno == EEXIST) {
> ```

try to avoid else after return, in this case `|| errno == EEXIST` is better

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/475)*

**Comment by robinlinden** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/xlib/main.c, line 7 at r2](https://reviewable.io:443/reviews/utox/utox/475#-KWVsKmToh3CSHy7MfmF:-KW_CdAgVaYxIaOdf7sw:b-896fix) ([raw file](https://github.com/utox/utox/blob/6fb525d09746e318164c1ae66b16c7832cd662e4/src/xlib/main.c#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Putting the file_opts enum in main_native was stupid idea... (I know it was my idea), it needs to be moved to /main.h
> 
> Native sources shouldn't include main_native.h, they should just include [platform]/main.h
</details>
Done.

---

*[src/xlib/main.c, line 183 at r2](https://reviewable.io:443/reviews/utox/utox/475#-KWVt8weFxq2KJAYi3SS:-KW_Ch-t8oup6QdwIciI:b-896fix) ([raw file](https://github.com/utox/utox/blob/6fb525d09746e318164c1ae66b16c7832cd662e4/src/xlib/main.c#L183)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> this function doesn't need to check this, only callers need to make this check.
</details>
Done.

---

*[src/xlib/main.c, line 187 at r2](https://reviewable.io:443/reviews/utox/utox/475#-KWVtK3otjeXC6dWD9pz:-KW_ChnDk1ZZjsy6wD9J:b-896fix) ([raw file](https://github.com/utox/utox/blob/6fb525d09746e318164c1ae66b16c7832cd662e4/src/xlib/main.c#L187)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> try to avoid else after return, in this case `|| errno == EEXIST` is better
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/475)*

**Comment by GrayHatter** [comment]
:lgtm_strong: 

---

Reviewed 3 of 4 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.h, line 296 at r3](https://reviewable.io:443/reviews/utox/utox/475#-KW_ZydfX9bEwu_77c3H:-KW_Zydg_iA1uvwA1PFs:b-3xubz8) ([raw file](https://github.com/utox/utox/blob/7ef07208c7b5d273592e616259729660c9c9aafd/src/main.h#L296)):*
> ```objc
> bool    mdown;
> 
> /** Takes a filepath and creates it with permissions 0700 if it doesn't already exist.
> ```

0700 in posix environments 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/475#-:-KW_aAqVmwuwEuQN2LPc:b-uwkowd)*

**Comment by robinlinden** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.h, line 296 at r3](https://reviewable.io:443/reviews/utox/utox/475#-KW_ZydfX9bEwu_77c3H:-KW_c6OOxgpL81FZ49KV:b-896fix) ([raw file](https://github.com/utox/utox/blob/7ef07208c7b5d273592e616259729660c9c9aafd/src/main.h#L296)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> 0700 in posix environments 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/475)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/475)*

**Pull request merged**
