### PR TITLE
Clean up CMakeLists.txt.

### LINKED ISSUE #978: CMake needs some TLC
see ~#971~

#974

### PR DESCRIPTION
**Pull request by robinlinden**
Fixes #978

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/983)

### CODE REVIEW

**Comment by dkmoz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/983#-:-KqrF_pLvYfZi3pF4wmU:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/983#-:-Kqs4U7dn_d8-bognR_-:bnfp4nl)*

**Comment by endoffile78** [comment]
The windows travis failed.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/983#-:-Kqs4tdHBKstJ9KOKr2r:bj22myn)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/983#-:-KqsqLVO8Yt6eSJ_y2hl:bnfp4nl)*

**Pull request merged**
