### PR TITLE
Dynamic groups

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/802)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/groups.c, line 289 at r1](https://reviewable.io:443/reviews/utox/utox/802#-KhCBXYffrQsnunn_BQN:-KhCBXYffrQsnunn_BQO:b-3omtmi) ([raw file](https://github.com/utox/utox/blob/a31ad86cb1739e6ba44cb49482f60ba3c5fc3c50/src/groups.c#L289)):*
> ```C
>     }
> 
>     if (group) {
> ```

free(NULL) does nothing, so you can drop this check. If you expect this function to be called more than once you can also set group to NULL after freeing it.

---

*[src/groups.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/802#-KhCBDTwzmiUeOC39Fie:-KhCBDTxPFjUQkKgOZZ_:bj4qnfb) ([raw file](https://github.com/utox/utox/blob/a31ad86cb1739e6ba44cb49482f60ba3c5fc3c50/src/groups.c#L298)):*
> ```C
>                                //there is a pr open for saving them
> 
>     group = calloc(self.groups_list_size, sizeof(GROUPCHAT));
> ```

What happens when you allocate 0 memory is up to the implementation. This might return a nullpointer depending on where it was compiled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by endoffile78** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/groups.c, line 289 at r1](https://reviewable.io:443/reviews/utox/utox/802#-KhCBXYffrQsnunn_BQN:-KhJDDw4SIK1XFr6wPiN:b-896fix) ([raw file](https://github.com/utox/utox/blob/a31ad86cb1739e6ba44cb49482f60ba3c5fc3c50/src/groups.c#L289)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

free(NULL) does nothing, so you can drop this check. If you expect this function to be called more than once you can also set group to NULL after freeing it.
</blockquote></details>

Done.

---

*[src/groups.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/802#-KhCBDTwzmiUeOC39Fie:-KhJDFtwsmIH5wLCEYX6:bikxr3s) ([raw file](https://github.com/utox/utox/blob/a31ad86cb1739e6ba44cb49482f60ba3c5fc3c50/src/groups.c#L298)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

What happens when you allocate 0 memory is up to the implementation. This might return a nullpointer depending on where it was compiled.
</blockquote></details>

Done. I changed it to 1, it may not be the best way but I think its better than the old groupchats array because it uses less memory. If you know of a better way let me know and I do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[src/groups.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/802#-KhCBDTwzmiUeOC39Fie:-KhJRiHsoOvGUuKA2Dir:btl8f3o) ([raw file](https://github.com/utox/utox/blob/a31ad86cb1739e6ba44cb49482f60ba3c5fc3c50/src/groups.c#L298)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Done. I changed it to 1, it may not be the best way but I think its better than the old groupchats array because it uses less memory. If you know of a better way let me know and I do it.
</blockquote></details>

set the size to 0, and if (size == 0)  {return} 

I'm confused about what this function is trying to do?

Also, you can realloc(NULL, ) it'll == malloc() in that case.

---

*[src/groups.c, line 26 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJQOMQtMFbxv1-toex:-KhJQOMRBSrHky3Hddve:b43lmor) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L26)):*
> ```C
> 
> GROUPCHAT *get_group(uint32_t group_number) {
>     if (group_number >= self.groups_list_size) {
> ```

might be uninitialized at start. add `memset(0);` to `self.c@init_self()`

---

*[src/groups.c, line 34 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJPUfPWpsYgZWe0sLp:-KhJPUfQwctrfaiSRsJ8:b-sl4i67) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L34)):*
> ```C
> }
> 
> GROUPCHAT *group_make(uint32_t group_number) {
> ```

can this be static?

---

*[src/groups.c, line 85 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJQkbVD6_OnknGiVrp:-KhJQkbWRvC4EB-5s3aT:bazglmp) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L85)):*
> ```C
>     flist_select_last();
> 
>     self.groups_list_count++;
> ```

this belongs in make_group()

---

*[src/groups.c, line 259 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJR4uI6m4goze6IHY3:-KhJR4uI6m4goze6IHY4:bbw3zzi) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L259)):*
> ```C
> 
> void group_free(GROUPCHAT *g) {
>     LOG_WARN("Groupchats", "Freeing group %u", g->number);
> ```

LOG_INFO

---

*[src/groups.c, line 277 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJR8YcZJh9H3awZkNo:-KhJR8YdXxijQz6N7io9:b-7ropln) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L277)):*
> ```C
>     memset(g, 0, sizeof(GROUPCHAT));
> 
>     self.groups_list_count--;
> ```

ditto

---

*[src/groups.c, line 280 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJRCpROK83R84wVSqf:-KhJRCpROK83R84wVSqg:b-5fdxi) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L280)):*
> ```C
> }
> 
> void free_groups(void) {
> ```

free_group() and raze_groups(), free and raze have different uses/meanings

---

*[src/groups.h, line 87 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJSL2Zp9A_dFcVy0AU:-KhJSL2Zp9A_dFcVy0AV:b3ifg58) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.h#L87)):*
> ```objc
> /*
>  * Create a new slot for the group if group_number is greater than self.groups_list_size and return a pointer to it
>  * If gorup_number is less than self.groups_list_size return a pointer to that slot
> ```

`group`

---

*[src/groups.h, line 94 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJSC5jS3ALQ6B9h_XM:-KhJSC5jS3ALQ6B9h_XN:b-wgml7i) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.h#L94)):*
> ```objc
> void free_groups(void);
> 
> /* Initalize the groupchats array */
> ```

if it's only called once even, who do we expect to call it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by endoffile78** [comment]
Review status: 1 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/groups.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/802#-KhCBDTwzmiUeOC39Fie:-KhKt718g9Q9i2YuWdr_:bqshw8g) ([raw file](https://github.com/utox/utox/blob/a31ad86cb1739e6ba44cb49482f60ba3c5fc3c50/src/groups.c#L298)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

set the size to 0, and if (size == 0)  {return} 

I'm confused about what this function is trying to do?

Also, you can realloc(NULL, ) it'll == malloc() in that case.
</blockquote></details>

Done. I didnt know reallocating NULL would act like malloc. This function is going to initialize the users groups when groups can be saved.

---

*[src/groups.c, line 26 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJQOMQtMFbxv1-toex:-KhKtQwUeg3Ks2fLMQq0:bpz2gkc) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L26)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

might be uninitialized at start. add `memset(0);` to `self.c@init_self()`
</blockquote></details>

`self.groups_list_size` is set in `init_groups` which is called right after tox is created so it shouldn't be uninitialized.

---

*[src/groups.c, line 34 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJPUfPWpsYgZWe0sLp:-KhKtXr1o5cZm4-iIagI:b3u5mq8) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L34)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

can this be static?
</blockquote></details>

Not right now. It needs to be called in tox.c@1047. If init_group is changed to create the group itself rather than being passed the group as an argument it can be static. I'm planning on doing that unless you don't want me to/don't think its necessary.

---

*[src/groups.c, line 85 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJQkbVD6_OnknGiVrp:-KhKv0VTGGaZADAcOqL3:b2ygvhl) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L85)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this belongs in make_group()
</blockquote></details>

I put it here because after calling gorup_make there is room for another group but it doesn't exist. After group_init is called the group actually exists and can be used. If you still don't agree with it being here tell me and I'll change it.

---

*[src/groups.c, line 259 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJR4uI6m4goze6IHY3:-KhKt13piJMt2WfvQmPZ:b-896fix) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L259)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

LOG_INFO
</blockquote></details>

Done.

---

*[src/groups.c, line 277 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJR8YcZJh9H3awZkNo:-KhKuOWIRhcLCO8Y2O2R:b3kre) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L277)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

?

---

*[src/groups.c, line 280 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJRCpROK83R84wVSqf:-KhKt2-UIG9YBXpgDyGr:b-896fix) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L280)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

free_group() and raze_groups(), free and raze have different uses/meanings
</blockquote></details>

Done.

---

*[src/groups.h, line 87 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJSL2Zp9A_dFcVy0AU:-KhKt3lXMz7170xElHLi:b-896fix) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.h#L87)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`group`
</blockquote></details>

Done.

---

*[src/groups.h, line 94 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJSC5jS3ALQ6B9h_XM:-KhKt4y-6Uf1t53127UO:b-896fix) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.h#L94)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

if it's only called once even, who do we expect to call it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 3 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/groups.c, line 26 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJQOMQtMFbxv1-toex:-KhLG5XRA4OHIT-N9TRG:bb6ywmx) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L26)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

`self.groups_list_size` is set in `init_groups` which is called right after tox is created so it shouldn't be uninitialized.
</blockquote></details>

LGTM

---

*[src/groups.c, line 34 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJPUfPWpsYgZWe0sLp:-KhLFoPKuAqGNqaZWrCE:b86yvmf) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L34)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Not right now. It needs to be called in tox.c@1047. If init_group is changed to create the group itself rather than being passed the group as an argument it can be static. I'm planning on doing that unless you don't want me to/don't think its necessary.
</blockquote></details>

let's make this static, and add group_create() that the callbacks can call with all the data. so there's only one file that will have access to this function.

---

*[src/groups.c, line 85 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJQkbVD6_OnknGiVrp:-KhLEgeeHEvHS9DD7s6j:b-r7q49b) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L85)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

I put it here because after calling gorup_make there is room for another group but it doesn't exist. After group_init is called the group actually exists and can be used. If you still don't agree with it being here tell me and I'll change it.
</blockquote></details>

yeah, it needs to be in side group_make(), this code could change and this line is very likely to go missing. Also, divide the responsibility of the functions to ONLY where they need to be. if you're making a group, group_make() should be the one to provision, and do the housekeeping for that group.

---

*[src/groups.c, line 277 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJR8YcZJh9H3awZkNo:-KhLF9ZJ7GNxK9r_Pnbc:b-u6yz5x) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L277)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

?
</blockquote></details>

LGTM

my bad, I read this as count++ and I would have wanted this in side group_make(). But this is correct here

OOS: but at some point we need to make a design decision about what threads are allowed to call what functions, or add more thread mutex calls through out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by endoffile78** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/groups.c, line 34 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJPUfPWpsYgZWe0sLp:-KhOyDTRM8ldSzYeRhVf:b-896fix) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L34)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

let's make this static, and add group_create() that the callbacks can call with all the data. so there's only one file that will have access to this function.
</blockquote></details>

Done.

---

*[src/groups.c, line 85 at r2](https://reviewable.io:443/reviews/utox/utox/802#-KhJQkbVD6_OnknGiVrp:-KhOyETx2fRZ80d09ziU:b-896fix) ([raw file](https://github.com/utox/utox/blob/9b64c6e17005e558d2441791ad1a224d2c3e3248/src/groups.c#L85)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yeah, it needs to be in side group_make(), this code could change and this line is very likely to go missing. Also, divide the responsibility of the functions to ONLY where they need to be. if you're making a group, group_make() should be the one to provision, and do the housekeeping for that group.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by robinlinden** [comment]
Reviewed 1 of 3 files at r2, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/groups.c, line 322 at r4](https://reviewable.io:443/reviews/utox/utox/802#-KiKSg5iFYRTtxnvkisI:-KiKSg5jsqFI7KSpUaBj:bd53zh3) ([raw file](https://github.com/utox/utox/blob/65570a94320caf582634b439cb0330f9ce6519c1/src/groups.c#L322)):*
> ```C
>     }
> 
>     for(size_t i = 0; i < self.groups_list_size; i++){
> ```

Nit: Needs a space before `(` and after `)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802#-:-KiLoFbB7qUrci6c1saj:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/flist.c, line 420 at r5](https://reviewable.io:443/reviews/utox/utox/802#-KifWBs9l9DkLpM9nSmt:-KifWBs9l9DkLpM9nSmu:b-6os0cx) ([raw file](https://github.com/utox/utox/blob/9936324cabc4b7999e37c8e7e809c5322f44c62d/src/flist.c#L420)):*
> ```C
> 
>             panel_chat.disabled  = true;
>             panel_group.disabled = true;
> ```

these two still need to happen, even when g == NULL

---

*[src/flist.c, line 513 at r5](https://reviewable.io:443/reviews/utox/utox/802#-KifWKfz2i3PicBFQ5mH:-KifWKfz2i3PicBFQ5mI:b-tgkdbf) ([raw file](https://github.com/utox/utox/blob/9936324cabc4b7999e37c8e7e809c5322f44c62d/src/flist.c#L513)):*
> ```C
>             if (!g) {
>                 LOG_ERR("F-List", "Could not get group %u", i->id_number);
>                 return;
> ```

this will leave uTox in a "broken" state. If a user clicks on a group that no-longer exists, what should happen? (My best guess is that uTox will overrun, or segv. So anything you suggest will be better than that)

---

*[src/groups.c, line 322 at r4](https://reviewable.io:443/reviews/utox/utox/802#-KiKSg5iFYRTtxnvkisI:-KifXA1I2vRDs-nMx_E5:bb6hx7d) ([raw file](https://github.com/utox/utox/blob/65570a94320caf582634b439cb0330f9ce6519c1/src/groups.c#L322)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Nit: Needs a space before `(` and after `)`.
</blockquote></details>

1TBS

---

*[src/groups.c, line 43 at r5](https://reviewable.io:443/reviews/utox/utox/802#-KifWkipO5g5vX2lcW6T:-KifWkipO5g5vX2lcW6U:bjlc1u3) ([raw file](https://github.com/utox/utox/blob/9936324cabc4b7999e37c8e7e809c5322f44c62d/src/groups.c#L43)):*
> ```C
>         GROUPCHAT *tmp = realloc(group, sizeof(GROUPCHAT) * (group_number + 1));
>         if (!tmp) {
>             LOG_ERR("Groupchats", "Could not reallocate groupchat array to %u.", group_number + 1);
> ```

groups are buggy enough as it is. Let's make this a fatal error.

I'm open to other suggestions as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by endoffile78** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/flist.c, line 420 at r5](https://reviewable.io:443/reviews/utox/utox/802#-KifWBs9l9DkLpM9nSmt:-KilhcLVeE763vZLOnAQ:b-896fix) ([raw file](https://github.com/utox/utox/blob/9936324cabc4b7999e37c8e7e809c5322f44c62d/src/flist.c#L420)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

these two still need to happen, even when g == NULL
</blockquote></details>

Done.

---

*[src/flist.c, line 513 at r5](https://reviewable.io:443/reviews/utox/utox/802#-KifWKfz2i3PicBFQ5mH:-KiljFvY-Q9OdDVtlLSi:bnphlq3) ([raw file](https://github.com/utox/utox/blob/9936324cabc4b7999e37c8e7e809c5322f44c62d/src/flist.c#L513)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this will leave uTox in a "broken" state. If a user clicks on a group that no-longer exists, what should happen? (My best guess is that uTox will overrun, or segv. So anything you suggest will be better than that)
</blockquote></details>

Done. I made it a fatal error.

---

*[src/groups.c, line 322 at r4](https://reviewable.io:443/reviews/utox/utox/802#-KiKSg5iFYRTtxnvkisI:-Kili6x7teCCzIBtFnw3:b-896fix) ([raw file](https://github.com/utox/utox/blob/65570a94320caf582634b439cb0330f9ce6519c1/src/groups.c#L322)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

1TBS
</blockquote></details>

Done.

---

*[src/groups.c, line 43 at r5](https://reviewable.io:443/reviews/utox/utox/802#-KifWkipO5g5vX2lcW6T:-KilhzHMJeBsZxYAwQOy:b-896fix) ([raw file](https://github.com/utox/utox/blob/9936324cabc4b7999e37c8e7e809c5322f44c62d/src/groups.c#L43)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

groups are buggy enough as it is. Let's make this a fatal error.

I'm open to other suggestions as well
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802)*

**Comment by GrayHatter** [comment]
:lgtm:

+@robinlinden 

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802#-:-Kin7mzs70qaNZeEZ37M:b-w3je3k)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/802#-:-KinAGFFgrLDiFNEqE6f:bnfp4nl)*

**Pull request merged**
