### PR TITLE
Add documentation to functions in main.h

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/521)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Consider sorting the `utox_data_*` functions. e.g. everything that loads together and everything that's saves together.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main.h, line 333 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHFXxMrjqNEjYqNHL:-KYRHFXyI7IxD-5u-cRh:b-fgqsyj) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L333)):*
> ```objc
> 
> /**
>  * Saves the settings for utox
> ```

uTox

here and below

---

*[src/main.h, line 342 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHKABUa_VqiSWF158:-KYRHKABUa_VqiSWF159:bcruqu3) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L342)):*
> ```objc
>  * Loads utox settings
>  *
>  * Returns the utox settings on success
> ```

`returns a memory pointer of *size.` Does the caller need to free it?

---

*[src/main.h, line 356 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHaaCinqH8w0dbBSZ:-KYRHaaCinqH8w0dbBS_:bsw251w) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L356)):*
> ```objc
> 
> /**
>  * Saves chat log for friend with id hex
> ```

Consider moving these functions to a new header. 

lets talk with @robinlinden in IRC first, because IIRC a messages.c refactor is on his todo list, and this would be better in that pull.

---

*[src/main.h, line 390 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHq6HGhwCSCvoTC1g:-KYRHq6HGhwCSCvoTC1h:bx6btxt) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L390)):*
> ```objc
> 
> /**
>  * Deletes a file
> ```

any file? or only the the utox system save dir?

---

*[src/main.h, line 404 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHzyl3rOm9dptV5dV:-KYRHzymLhNs3vEB3KWC:bttav60) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L404)):*
> ```objc
> 
> /**
>  * Setup for exporting the chat log to plain text
> ```

verify it always starts a new thread, then say so.

---

*[src/main.h, line 425 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRI6L9P4gPHb59O5OF:-KYRI6L9P4gPHb59O5OG:b-z3j3uv) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L425)):*
> ```objc
>  * Initialize utox
>  */
> void utox_init(void);
> ```

newline needed, comment needed with a TODO suggestion for the following files
again, make sure it's just a suggestion. We might wish to sort the following functions better. E.g. in native, because the drawing functions are VERY dependent on the local system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/521#-:-KYRILddskK1biz0ER3e:bcprlti)*

**Comment by endoffile78** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main.h, line 333 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHFXxMrjqNEjYqNHL:-KYRQKqxHae40-89qhov:b-896fix) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L333)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

uTox

here and below
</blockquote></details>

Done.

---

*[src/main.h, line 342 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHKABUa_VqiSWF158:-KYRQLfAa6H8GAY0QqEm:b-896fix) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L342)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`returns a memory pointer of *size.` Does the caller need to free it?
</blockquote></details>

Done.

---

*[src/main.h, line 390 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHq6HGhwCSCvoTC1g:-KYRQP7Xv_r2-efLYoII:b-896fix) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L390)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

any file? or only the the utox system save dir?
</blockquote></details>

Done.

---

*[src/main.h, line 404 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHzyl3rOm9dptV5dV:-KYRQPiOR5SfBlT37b_i:b-rrwj8r) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L404)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

verify it always starts a new thread, then say so.
</blockquote></details>

It doesn't look like it starts a new thread.

---

*[src/main.h, line 425 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRI6L9P4gPHb59O5OF:-KYRQUXmUZA2H4iXowjV:b-896fix) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L425)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

newline needed, comment needed with a TODO suggestion for the following files
again, make sure it's just a suggestion. We might wish to sort the following functions better. E.g. in native, because the drawing functions are VERY dependent on the local system.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/521)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main.h, line 390 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHq6HGhwCSCvoTC1g:-KYRSnXzVwI6KFu3IZXb:betr8lw) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L390)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Active tox data directory. Some times it'll be the current sometimes home but the call can't decide or find out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/521#-:-KYRTCd5_xjdrw8D73hP:bnfp4nl)*

**Comment by endoffile78** [comment]
Done

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main.h, line 390 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHq6HGhwCSCvoTC1g:-KYRVbhBnPym3hkSR6Yn:b-896fix) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L390)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Active tox data directory. Some times it'll be the current sometimes home but the call can't decide or find out.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/521#-:-KYRVaYiOwbynwH2212o:bb6un1j)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/521#-:-KYRXlUcEQNP85xyylJ3:bnfp4nl)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.h, line 356 at r1](https://reviewable.io:443/reviews/utox/utox/521#-KYRHaaCinqH8w0dbBSZ:-KYRZQG4yLcsiXoTFKOD:b-896fix) ([raw file](https://github.com/utox/utox/blob/c86aeac6f266414c11874201029e60d794171812/src/main.h#L356)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Consider moving these functions to a new header. 

lets talk with @robinlinden in IRC first, because IIRC a messages.c refactor is on his todo list, and this would be better in that pull.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/521)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/521#-:-KYRxcW81GdKBUG_R1xq:bnfp4nl)*

**Pull request merged**
