### PR TITLE
Made compilation on Mac possible

### PR DESCRIPTION
**Pull request by LawlingBear**
Added missing includes (will make them less messy), commented out stuff that didn't work, changed some Mac-specific stuff
Will finish CMakeLists.txt for compiling without the static Makefile

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/493)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 4 of 10 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2iuiZZGC_0P0-g5FF:-KX2iui_jVRHICFXFsKe:bybin59) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/Makefile#L1)):*
> ```Makefile
> ## OPTIONS ##
> ```

this file can't / shouldn't exist in `/` is there a subdirectory it fits in better?

---

*[icons/utox.icns, line 0 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2j3NPT-6BW8pw8SDU:-KX2j3NPT-6BW8pw8SDV:b6ikp8i) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/icons/utox.icns#L0)):*
don't commit binary files (there are some exceptions) can we add a build script that'll generate this instead?

---

*[src/friend.c, line 205 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jEq0oWBPYXqRdHXD:-KX2jEq0oWBPYXqRdHXE:bn4189z) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/friend.c#L205)):*
> ```C
> }
> 
> void aimage(FRIEND *f, NATIVE_IMAGE *native_image, uint16_t width, uint16_t height, UTOX_IMAGE png_image,
> ```

why was this renamed?

---

*[src/cocoa/grabdesktop.m, line 30 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jQbhGRlz7-MTT1Ek:-KX2jQbhGRlz7-MTT1El:bmygd3c) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/grabdesktop.m#L30)):*
> ```objc
>     NSWindow *ret =
>         [[NSWindow alloc] initWithContentRect:CGRectMake(0, 0, target.frame.size.width, target.frame.size.height)
>                                     styleMask:NSWindowStyleMaskBorderless
> ```

why was this change needed?

---

*[src/cocoa/interaction.m, line 730 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jlLBYty7eH7ZOoKw:-KX2jlLBYty7eH7ZOoKx:b618rcx) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/interaction.m#L730)):*
> ```objc
>         // FIXME: asfasg
>         ret = edit_copy(ptr, len);
>     //} else if (selected_item->item == ITEM_FRIEND) {
> ```

you can use `flist_get_selected()` here

---

*[src/cocoa/interaction.m, line 957 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jyI_0fuHRVipxK8Z:-KX2jyI_0fuHRVipxK8_:b-9j6iez) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/interaction.m#L957)):*
> ```objc
>             [s appendFormat:@"%@\n", url.path];
>         }
>         //postmessage_toxcore(TOX_FILE_SEND_NEW, (FRIEND *)selected_item->data - friend, 0xFFFF, strdup(s.UTF8String));
> ```

`flist_get_selected()`

---

*[src/cocoa/main.m, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2k5FKVmV4LVGa-r4A:-KX2k5FKVmV4LVGa-r4B:bthacpg) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/main.m#L10)):*
> ```objc
> #include <libgen.h>
> #include <pthread.h>
> #include <time.h>
> ```

both time. and sys/time.h?

---

*[src/cocoa/main.m, line 181 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kGxhWzoDs2iwrUJt:-KX2kGxhWzoDs2iwrUJu:b-fgrv6x) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/main.m#L181)):*
> ```objc
>     NSURL *url = NULL;
>     if (!strncasecmp((const char *)str, "http://", 7) || !strncasecmp((const char *)str, "https://", 8)) {
>                    url = [NSURL URLWithString:urls];
> ```

why the extra indent?

---

*[src/cocoa/objc_main.h, line 48 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kg3f5pA5qHdQYEfq:-KX2kg3g0wK0nNEtFkk2:bb7r2f0) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/objc_main.h#L48)):*
> ```objc
> #define AT_LEAST_YOSEMITE_DO MAC_OS_AT_LEAST_DO(10, 10, 0)
> #define AT_LEAST_ELCAPITAN_DO MAC_OS_AT_LEAST_DO(10, 11, 0)
> #define AT_LEAST_SIERRA_DO MAC_OS_AT_LEAST_DO(10, 12, 0)
> ```

why?

---

*[src/cocoa/video.m, line 390 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kP7otEjGNUaCuU0H:-KX2kP7otEjGNUaCuU0I:bvlfz2h) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/video.m#L390)):*
> ```objc
>         [[uToxIroncladWindow alloc] initWithContentRect:START_RECT
>                                               styleMask:NSHUDWindowMask | NSUtilityWindowMask | NSClosableWindowMask
>                                                   | NSTitledWindowMask | NSWindowStyleMaskResizable
> ```

why did this need to be changed?

---

*[src/cocoa/video.m, line 511 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kYFoguCdNLOtB-El:-KX2kYFoguCdNLOtB-Em:b-jnmksd) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/video.m#L511)):*
> ```objc
>         setFrame:(CGRect) { CGRectGetMaxX(utoxwin.frame), CGRectGetMaxY(utoxwin.frame) - rsheight, rswidth, rsheight }
>          display:YES];
>                  ((uToxIroncladView *)video_win.contentView).videoSize = (CGSize){ width, height };
> ```

is this white space change correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/493)*

**Comment by LawlingBear** [comment]
Review status: 4 of 10 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2iuiZZGC_0P0-g5FF:-KX2mZr6MXXq_z1H2k6U:btxeq9g) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/Makefile#L1)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> this file can't / shouldn't exist in `/` is there a subdirectory it fits in better?
</details>
It could just exist in the cocoa folder for the time being, til I fix the APPLE-part of CMakeLists.txt

---

*[icons/utox.icns, line  at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2j3NPT-6BW8pw8SDU:-KX2oBMCUTVCCTxUVTB_:b-wbheq0) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/icons/utox.icns#L)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> don't commit binary files (there are some exceptions) can we add a build script that'll generate this instead?
</details>
Yes, that probably won't be difficult

---

*[src/friend.c, line 205 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jEq0oWBPYXqRdHXD:-KX2oRCVuuCzkrq69n7x:b-jhtues) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/friend.c#L205)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> why was this renamed?
</details>
That's a mistake
wow

---

*[src/cocoa/grabdesktop.m, line 30 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jQbhGRlz7-MTT1Ek:-KX2m2j1YXroKBiO4G29:b-3c1xdd) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/grabdesktop.m#L30)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> why was this change needed?
</details>
NSBorderlessWindowMask and several other attributes are deprecated from OS X 12 and on

---

*[src/cocoa/main.m, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2k5FKVmV4LVGa-r4A:-KX2nNS4yL6UNYZc_rz2:b-6otgvo) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/main.m#L10)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> both time. and sys/time.h?
</details>
I'll fix the includes :(

---

*[src/cocoa/main.m, line 181 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kGxhWzoDs2iwrUJt:-KX2nReOuWs-RlxfFmz2:b-dz30ln) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/main.m#L181)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> why the extra indent?
</details>
Probably through retab, I'll fix it

---

*[src/cocoa/objc_main.h, line 48 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kg3f5pA5qHdQYEfq:-KX2nWm8dSJjg0cmplvn:b-vvx3pd) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/objc_main.h#L48)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> why?
</details>
I saw, and I added that line, in case it'll be needed (for whatever reason)

---

*[src/cocoa/video.m, line 390 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kP7otEjGNUaCuU0H:-KX2nohzVMkk3IoJXHLE:baymmb0) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/video.m#L390)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> why did this need to be changed?
</details>
Deprecated stuff

---

*[src/cocoa/video.m, line 511 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kYFoguCdNLOtB-El:-KX2o0XuuYuZuz27Ec87:b-o9agy0) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/video.m#L511)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> is this white space change correct?
</details>
Doesn't look like it :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/493)*

**Comment by LawlingBear** [comment]
Review status: 2 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/cocoa/interaction.m, line 730 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jlLBYty7eH7ZOoKw:-KX2wwJDNJy2wuwpsC_l:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/interaction.m#L730)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> you can use `flist_get_selected()` here
</details>
Done.

---

*[src/cocoa/interaction.m, line 957 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jyI_0fuHRVipxK8Z:-KX2wveX-UWX-XCWvqPO:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/interaction.m#L957)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> `flist_get_selected()`
</details>
Done.

---

*[src/cocoa/main.m, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2k5FKVmV4LVGa-r4A:-KX2wpvdsigTExt3fyky:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/main.m#L10)):*
<details><summary><i>Previously, LawlingBear (Karl) wrote…</i></summary>
> I'll fix the includes :(
</details>
Done.

---

*[src/cocoa/main.m, line 181 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kGxhWzoDs2iwrUJt:-KX2woOiEeHBxSRhWhaK:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/main.m#L181)):*
<details><summary><i>Previously, LawlingBear (Karl) wrote…</i></summary>
> Probably through retab, I'll fix it
</details>
Done.

---

*[src/cocoa/objc_main.h, line 48 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kg3f5pA5qHdQYEfq:-KX2wr7546H6iNd_lO-m:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/objc_main.h#L48)):*
<details><summary><i>Previously, LawlingBear (Karl) wrote…</i></summary>
> I saw, and I added that line, in case it'll be needed (for whatever reason)
</details>
Done.

---

*[src/cocoa/video.m, line 390 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kP7otEjGNUaCuU0H:-KX2ws-ueHW8L9l8Ss1o:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/video.m#L390)):*
<details><summary><i>Previously, LawlingBear (Karl) wrote…</i></summary>
> Deprecated stuff
</details>
Done.

---

*[src/cocoa/video.m, line 511 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2kYFoguCdNLOtB-El:-KX2wslb-rMfp8ijPxYc:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/cocoa/video.m#L511)):*
<details><summary><i>Previously, LawlingBear (Karl) wrote…</i></summary>
> Doesn't look like it :(
</details>
Done.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2iuiZZGC_0P0-g5FF:-KX2wu6HC6yPYP9yD-1U:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/Makefile#L1)):*
<details><summary><i>Previously, LawlingBear (Karl) wrote…</i></summary>
> It could just exist in the cocoa folder for the time being, til I fix the APPLE-part of CMakeLists.txt
</details>
Done.

---

*[src/friend.c, line 205 at r1](https://reviewable.io:443/reviews/utox/utox/493#-KX2jEq0oWBPYXqRdHXD:-KX2wusrD1HXLGU3skmK:b-896fix) ([raw file](https://github.com/utox/utox/blob/f7924e4e5c793d7c086c150ea27f1727d0efe845/src/friend.c#L205)):*
<details><summary><i>Previously, LawlingBear (Karl) wrote…</i></summary>
> That's a mistake
> wow
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/493)*

**Comment by GrayHatter** [comment]
Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/493)*

**Comment by GrayHatter** [comment]
@LawlingBear thanks mate... something went screwy in the rebase. But @endoffile78 has a branch that has your commit plus another as well. So instead of merging this one, I'm going to merge that one. 

Can you double check #500 and make sure it's not missing any code you want included?

**Pull request closed without merging**
