### PR TITLE
Improve logging macros

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/656)

### CODE REVIEW

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656#-:-KbC2Dpv6vfz7Dzy8OKq:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656#-:-KbC2qIM7ofOoqiwQfGu:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 52 of 52 files at r1, 1 of 43 files at r2.
Review status: 14 of 56 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/file_transfers.c, line 1114 at r1](https://reviewable.io:443/reviews/utox/utox/656#-KbatBuEQOH7Eu57gvil:-KbatBuEQOH7Eu57gvim:b-j5wu26) ([raw file](https://github.com/utox/utox/blob/3a8c3d8fd18e18ea6f42159ce8a521bb931f3164/src/file_transfers.c#L1114)):*
> ```C
>     }
> 
>     // Removed until we can find a better way of working this in;
> ```

FYI, just adding a comment here to preserve this revision so that the following reviews are much easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656)*

**Comment by GrayHatter** [comment]
+@robinlinden +@cebe closes #572 

---

Review status: 1 of 57 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656#-:-Kbb2kIhLz_nTRVWKzCg:b-lx4jk)*

**Comment by endoffile78** [comment]
drawing.m needs to be updated

---

Reviewed 2 of 52 files at r1, 5 of 43 files at r2, 51 of 51 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656#-:-KbfKnEQvoZ0Gdapw48u:bsh3wc8)*

**Comment by robinlinden** [comment]
Reviewed 1 of 52 files at r1, 24 of 51 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/avatar.c, line 50 at r3](https://reviewable.io:443/reviews/utox/utox/656#-Kbh1gmQ83NLkZ6caGqO:-Kbh1gmQ83NLkZ6caGqP:b-952dbv) ([raw file](https://github.com/utox/utox/blob/6a371743b9e354308f98df27f6b58772ae9b925b/src/avatar.c#L50)):*
> ```C
>     }
> 
>     uint8_t *data = calloc(size, 1);
> ```

Not really in scope, but `size` and `1` need to be switched.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/avatar.c, line 50 at r3](https://reviewable.io:443/reviews/utox/utox/656#-Kbh1gmQ83NLkZ6caGqO:-KbhDCqn19R-duHtzJWq:b-896fix) ([raw file](https://github.com/utox/utox/blob/6a371743b9e354308f98df27f6b58772ae9b925b/src/avatar.c#L50)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Not really in scope, but `size` and `1` need to be switched.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656#-:-KbhVGCc0KNYGxfX29H_:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 5 of 43 files at r2, 27 of 51 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656#-:-Kbk9pDiGKaFCLDcmLxk:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/file_transfers.c, line 1114 at r1](https://reviewable.io:443/reviews/utox/utox/656#-KbatBuEQOH7Eu57gvil:-KblKw3C8hpYP5VIxvOV:b-896fix) ([raw file](https://github.com/utox/utox/blob/3a8c3d8fd18e18ea6f42159ce8a521bb931f3164/src/file_transfers.c#L1114)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

FYI, just adding a comment here to preserve this revision so that the following reviews are much easier.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/file_transfers.c, line 1114 at r1](https://reviewable.io:443/reviews/utox/utox/656#-KbatBuEQOH7Eu57gvil:-KblL3JEywMGEsEtfD2u:bb6ywmx) ([raw file](https://github.com/utox/utox/blob/3a8c3d8fd18e18ea6f42159ce8a521bb931f3164/src/file_transfers.c#L1114)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/656)*

**Pull request merged**
