### PR TITLE
Add friend by public key

### LINKED ISSUE #967: Simple PubKeys can't be added
We should be able to add users by pubkey, with a warning that a friend request can't be sent.

### PR DESCRIPTION
**Pull request by dkmoz**
Fixes #967

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/968)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/friend.c, line 480 at r1](https://reviewable.io:443/reviews/utox/utox/968#-Ko8f01-xvQUQlxtYA7E:-Ko8f01005_gxFeNt9ZF:b-182htd) ([raw file](https://github.com/utox/utox/blob/3310ca22aa3bc24ca754573ebf85373c67434a0d/src/friend.c#L480)):*
> ```C
>     } else if (length_cleaned == 64) { /* public key length */
>         string_to_id(id, (char*)name_cleaned);
>         uint8_t *data = calloc(sizeof(uint8_t), TOX_PUBLIC_KEY_SIZE);
> ```

Make sure memory was allocated

---

*[src/tox.c, line 743 at r1](https://reviewable.io:443/reviews/utox/utox/968#-Ko8fQZKUa7DMI5zu0qa:-Ko8fQZLs3jQ6hV_vUww:bp0z318) ([raw file](https://github.com/utox/utox/blob/3310ca22aa3bc24ca754573ebf85373c67434a0d/src/tox.c#L743)):*
> ```C
>                 char hex_id[TOX_ADDRESS_SIZE * 2];
>                 id_to_string(hex_id, data);
>                 LOG_TRACE("Toxcore", "Unable to accept friend %s, error num = %i" , hex_id, fid);
> ```

free data here. It's freed after sending it with `postmessage_utox` but not if the there is an error.

---

*[src/utox.c, line 468 at r1](https://reviewable.io:443/reviews/utox/utox/968#-Ko8fe5zfyj0_7X52mjj:-Ko8fe5zfyj0_7X52mjk:b-mn9i13) ([raw file](https://github.com/utox/utox/blob/3310ca22aa3bc24ca754573ebf85373c67434a0d/src/utox.c#L468)):*
> ```C
>                 FRIEND *f = get_friend(param2);
>                 if (!f) {
>                     LOG_ERR("uTox", "Could not get friend with number: %u", param2);
> ```

free data

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/friend.c, line 480 at r1](https://reviewable.io:443/reviews/utox/utox/968#-Ko8f01-xvQUQlxtYA7E:-Ko8y3dfYpZypEIFDHOv:b-896fix) ([raw file](https://github.com/utox/utox/blob/3310ca22aa3bc24ca754573ebf85373c67434a0d/src/friend.c#L480)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Make sure memory was allocated
</blockquote></details>

Done.

---

*[src/tox.c, line 743 at r1](https://reviewable.io:443/reviews/utox/utox/968#-Ko8fQZKUa7DMI5zu0qa:-Ko8yImUEwYgfCopEMRD:b-896fix) ([raw file](https://github.com/utox/utox/blob/3310ca22aa3bc24ca754573ebf85373c67434a0d/src/tox.c#L743)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

free data here. It's freed after sending it with `postmessage_utox` but not if the there is an error.
</blockquote></details>

Done.

---

*[src/utox.c, line 468 at r1](https://reviewable.io:443/reviews/utox/utox/968#-Ko8fe5zfyj0_7X52mjj:-Ko8yK3YaBholatMXmwh:b-896fix) ([raw file](https://github.com/utox/utox/blob/3310ca22aa3bc24ca754573ebf85373c67434a0d/src/utox.c#L468)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

free data
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968#-:-Ko91qvu606B0YBPVVsS:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968#-:-Kp_zKdVZ-xDU4takPEn:bnfp4nl)*

**Comment by robinlinden** [comment]
Assigning this to 0.17.0 since it adds more strings and we already have translations done for 0.16.0.

**Comment by redmanmale** [comment]
Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/friend.c, line 478 at r3](https://reviewable.io:443/reviews/utox/utox/968#-KsFYTOKlLWJag7IgH8c:-KsFYTOLDcxfHM7fgpHd:bwd80b0) ([raw file](https://github.com/utox/utox/blob/005f6e8f40376bf73019757ba4a93b3453f7235f/src/friend.c#L478)):*
> ```C
>     if (length_cleaned == TOX_ADDRESS_SIZE * 2 && string_to_id(id, (char *)name_cleaned)) {
>         friend_addid(id, msg, msg_length);
>     } else if (length_cleaned == 64) { /* public key length */
> ```

TOX_PUBLIC_KEY_SIZE * 2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968)*

**Comment by dkmoz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/friend.c, line 478 at r3](https://reviewable.io:443/reviews/utox/utox/968#-KsFYTOKlLWJag7IgH8c:-KsHcD-KQ4NZpecakQjH:b-896fix) ([raw file](https://github.com/utox/utox/blob/005f6e8f40376bf73019757ba4a93b3453f7235f/src/friend.c#L478)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

TOX_PUBLIC_KEY_SIZE * 2
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968#-:-KsHnum1keVqcYUv1guZ:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/968#-:-KsK1zW0SQwT4GvUSkZM:bnfp4nl)*

**Pull request merged**
