### PR TITLE
Add error checks to messages.c

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1171)

### CODE REVIEW

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1171#-:-L3S4c30PCYgciKMyixL:bnfp4nl)*

**Comment by GrayHatter** [comment]
*[src/messages.c, line 245 at r1](https://reviewable.io:443/reviews/utox/utox/1171#-L3dgwasgYmu2aOEA_Uy:-L3dgwasgYmu2aOEA_Uz:b-l3ve7l) ([raw file](https://github.com/utox/utox/blob/1e59f0da128e9982fb8cf7879af0702bbd3119e6/src/messages.c#L245)):*
> ```C
>     MSG_HEADER *msg = calloc(1, sizeof(MSG_HEADER));
>     if (!msg) {
>         LOG_DEBUG("Messages", "Could not allocate memory for a message.");
> ```

This isn't a debug, it's more likely a fatal error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1171)*

**Comment by endoffile78** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/messages.c, line 245 at r1](https://reviewable.io:443/reviews/utox/utox/1171#-L3dgwasgYmu2aOEA_Uy:-L4fzqgRt5Q8gdGVGY26:b-896fix) ([raw file](https://github.com/utox/utox/blob/1e59f0da128e9982fb8cf7879af0702bbd3119e6/src/messages.c#L245)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

This isn't a debug, it's more likely a fatal error
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1171)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[src/messages.c, line 246 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gIn8oIulhvw_yZzPj:-L4gIn8oIulhvw_yZzPk:bwwkda3) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L246)):*
> ```C
>     if (!msg) {
>         LOG_FATAL_ERR(EXIT_MALLOC, "Messages", "Could not allocate memory for a message.");
>         return UINT32_MAX;
> ```

BTW return after exit... lol wut

---

*[src/messages.c, line 293 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gItOi7k3y37m0MxTb:-L4gItOi7k3y37m0MxTc:b-7qq8rl) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L293)):*
> ```C
>     MSG_HEADER *msg = calloc(1, sizeof(MSG_HEADER));
>     if (!msg) {
>         LOG_DEBUG("Messages", "Could not get message header.");
> ```

fatal

---

*[src/messages.c, line 303 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gIw5PqCEc-Ilw-OwK:-L4gIw5QM2m6oPUrXtVd:b-7qq8rl) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L303)):*
> ```C
>     msg->via.action.msg = calloc(1, length);
>     if (!msg->via.action.msg) {
>         LOG_DEBUG("Messages", "Could not allocate memory for message.");
> ```

fatal

---

*[src/messages.c, line 369 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gIy1xFj71GyCl1Ez1:-L4gIy1xFj71GyCl1Ez2:b-7qq8rl) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L369)):*
> ```C
>     MSG_HEADER *msg = calloc(1, sizeof(MSG_HEADER));
>     if (!msg) {
>         LOG_DEBUG("Messages", "Could not allocate memory for message header");
> ```

fatal

---

*[src/messages.c, line 393 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gJ-4rYlhP3Qi5dfci:-L4gJ-4sq_4gGh4uhOvl:b-7qq8rl) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L393)):*
> ```C
>     MSG_HEADER *msg = calloc(1, sizeof(MSG_HEADER));
>     if (!msg) {
>         LOG_DEBUG("Messages", "Could not allocate memory for message header");
> ```

fatal

---

*[src/messages.c, line 419 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gJ0JAzTy6CG1mgr_C:-L4gJ0JAzTy6CG1mgr_D:b-7qq8rl) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L419)):*
> ```C
>         msg->via.ft.path = calloc(1, UTOX_FILE_NAME_LENGTH);
>         if (!msg->via.ft.path) {
>             LOG_DEBUG("Messages", "Could not allocate memory for file path.");
> ```

fatal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1171)*

**Comment by endoffile78** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/messages.c, line 246 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gIn8oIulhvw_yZzPj:-L5F5kAbQn4-r-yCL93k:b-896fix) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L246)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW return after exit... lol wut
</blockquote></details>

Done.

---

*[src/messages.c, line 293 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gItOi7k3y37m0MxTb:-L5F5kj9DrJ8LdWD2h3D:b-896fix) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L293)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fatal
</blockquote></details>

Done.

---

*[src/messages.c, line 303 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gIw5PqCEc-Ilw-OwK:-L5F5lIQBI-hLgyGrg4w:b-896fix) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L303)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fatal
</blockquote></details>

Done.

---

*[src/messages.c, line 369 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gIy1xFj71GyCl1Ez1:-L5F5m5UVqOcnYgxGfw_:b-896fix) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L369)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fatal
</blockquote></details>

Done.

---

*[src/messages.c, line 393 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gJ-4rYlhP3Qi5dfci:-L5F5n3CzZEa8c-orIWL:b-896fix) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L393)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fatal
</blockquote></details>

Done.

---

*[src/messages.c, line 419 at r2](https://reviewable.io:443/reviews/utox/utox/1171#-L4gJ0JAzTy6CG1mgr_C:-L5F5n_F5G_8Atx84nIz:b-896fix) ([raw file](https://github.com/utox/utox/blob/80ca6be58a47473a829e7d13cab43676af37e0c3/src/messages.c#L419)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fatal
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1171)*

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1171)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1171#-:-L5IlIaLfmQojsFfl0no:bnfp4nl)*

**Pull request merged**
