### PR TITLE
Fix a potential overflow write

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1011)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1011)*

**Comment by endoffile78** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/window.c, line 170 at r1](https://reviewable.io:443/reviews/utox/utox/1011#-KsWwk6p-hSNXBiY6uH_:-KsWwk6qjGWSC3gA_TiE:bd9mt10) ([raw file](https://github.com/utox/utox/blob/44ec31cae78ceaa243ddee742cac7df45554ec0a/src/xlib/window.c#L170)):*
> ```C
>         next = &popup_window;
>     } else {
>         next = calloc(sizeof(UTOX_WINDOW), 1);
> ```

Shouldn't the arguments be switched.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1011)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/window.c, line 170 at r1](https://reviewable.io:443/reviews/utox/utox/1011#-KsWwk6p-hSNXBiY6uH_:-KsilixmoWl0VJ-Wfgqv:b-bgqvnr) ([raw file](https://github.com/utox/utox/blob/44ec31cae78ceaa243ddee742cac7df45554ec0a/src/xlib/window.c#L170)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Shouldn't the arguments be switched.
</blockquote></details>

yes, they need to be, standby

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1011)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/window.c, line 170 at r1](https://reviewable.io:443/reviews/utox/utox/1011#-KsWwk6p-hSNXBiY6uH_:-KuLbo7fzyu6K-Xa9_R8:b-896fix) ([raw file](https://github.com/utox/utox/blob/44ec31cae78ceaa243ddee742cac7df45554ec0a/src/xlib/window.c#L170)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yes, they need to be, standby
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1011)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1011#-:-KuMgUzTew5MQHeZu-RQ:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1011#-:-L0kT4OgtAyBIACzLThN:bnfp4nl)*

**Pull request merged**
