### PR TITLE
Version tick

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/633)

### CODE REVIEW

**Comment by fcore117** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/633)*

**Comment by robinlinden** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/AndroidManifest.xml, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/633#-Kb2YughkJS1uLk4y7Gn:-Kb2YughkJS1uLk4y7Go:b-e2ygb) ([raw file](https://github.com/utox/utox/blob/2253207b0bf635e6a4f1b377e8b428546d3cf072/src/android/AndroidManifest.xml#L4)):*
> ```XML
>         package="tox.client.utox"
>         android:versionName="0.12.0"
>         android:versionCode="3"> 
> ```

This number must be incremented by 1 every release or Android won't know this version is newer. The `versionName` is just a pretty string containing our official version number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/633)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/AndroidManifest.xml, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/633#-Kb2YughkJS1uLk4y7Gn:-Kb2w9o2Fm8yArvNa0T3:b8r5fse) ([raw file](https://github.com/utox/utox/blob/2253207b0bf635e6a4f1b377e8b428546d3cf072/src/android/AndroidManifest.xml#L4)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This number must be incremented by 1 every release or Android won't know this version is newer. The `versionName` is just a pretty string containing our official version number.
</blockquote></details>

no, don't do this...

Android says the version code must increase with every update, so let me do it when I'm ready to push a new version.

If we want to make the uTox android client officially supported, then we can discuss how we want to do version/revision, until then, lets leave this alone. I don't want to get stuck with out of order versions because I forgot to update this, or want to push a roll back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/633#-:-Kb2wiIdD6M_twbGUgBD:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/633#-:-Kb4KJeyvHRaWdSQuP4h:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm: 

---

Reviewed 3 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/633#-:-Kb4KNv9QI2QbI5RhK0w:bg7igkv)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/AndroidManifest.xml, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/633#-Kb2YughkJS1uLk4y7Gn:-Kb4KkyIkliCR4-sU2cP:bb7ka2b) ([raw file](https://github.com/utox/utox/blob/2253207b0bf635e6a4f1b377e8b428546d3cf072/src/android/AndroidManifest.xml#L4)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no, don't do this...

Android says the version code must increase with every update, so let me do it when I'm ready to push a new version.

If we want to make the uTox android client officially supported, then we can discuss how we want to do version/revision, until then, lets leave this alone. I don't want to get stuck with out of order versions because I forgot to update this, or want to push a roll back.
</blockquote></details>

ltgm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/633)*

**Pull request merged**
