### PR TITLE
Update ja.h Update Japanese translation

### PR DESCRIPTION
**Pull request by xfm00mm**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1192)

### CODE REVIEW

**Comment by robinlinden** [comment]
Thank you! :lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1192#-:-L7zoA9pKIt90evaiHBv:be5hxjj)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[langs/ja.h, line 235 at r1](https://reviewable.io:443/reviews/utox/utox/1192#-L80NpCE0R6O-HKuQHvm:-L80NpCE0R6O-HKuQHvn:b-3fnx69) ([raw file](https://github.com/utox/utox/blob/21741d301e96dea028fcf730cad2b027148cb2be/langs/ja.h#L235)):*
> ```objc
> //msgstr("Desktop")
> 
> TODO: Localize or remove.
> ```

Remove this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1192)*

**Comment by GrayHatter** [comment]
@endoffile78 can you pull down this patch, and fixit please?

**Comment by endoffile78** [comment]
Superceded by #1466

**Pull request closed without merging**
