### PR TITLE
Fix autoaccept setting not triggering metadata save.

### LINKED ISSUE #879: Remember auto-accept option
after closing uTox then option is off again.

### LINKED ISSUE #905: Friend settings are not saved unless you change the alias too
Trying to deactivate autoaccepting file transfers does nothing, unless you set the alias simultaneously with deactivating it (like, by focusing on the alias field and hitting enter). 

This way you can properly set the friend settings, but even with autoaccept showing as deactivated, tox still crashes because of one file transfer... but we'll write an issue about that when my friend tries debugging it on his end too.

### PR DESCRIPTION
**Pull request by robinlinden**
Fixes #879 
Fixes #905 

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/891)

### CODE REVIEW

**Comment by fcore117** [comment]
Tested by compiling and ran tests, looks like option now is remembered.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891#-:-KiuSbELG3-aUmEIQXtn:b-9ijrdi)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/friend.c, line 213 at r1](https://reviewable.io:443/reviews/utox/utox/891#-KivMVo5OIqO2VA0znhr:-KivMVo5OIqO2VA0znhs:bt980zr) ([raw file](https://github.com/utox/utox/blob/107d21d34e7ef4be42c7bcdfce1dcdf131f8205e/src/friend.c#L213)):*
> ```C
>     }
> 
>     if (size < sizeof(*metadata)) {
> ```

why did you drop this check?

---

*[src/layout/friend.c, line 583 at r1](https://reviewable.io:443/reviews/utox/utox/891#-KivMZIp0pxsBIYyxBjA:-KivMZIp0pxsBIYyxBjB:bsqme51) ([raw file](https://github.com/utox/utox/blob/2ffc0af3343e0eab96178152e45143cb7a7c3bef/src/layout/friend.c#L583)):*
> ```C
>     if (f) {
>         f->ft_autoaccept = !f->ft_autoaccept;
>         utox_write_metadata(f);
> ```

we should also call this on clean exit, for each friend

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891#-:-KivMQ0Q2uyYmqxkwZtx:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/friend.c, line 213 at r1](https://reviewable.io:443/reviews/utox/utox/891#-KivMVo5OIqO2VA0znhr:-KivOMU9lEAjCfl6uDlJ:b-evt1vr) ([raw file](https://github.com/utox/utox/blob/107d21d34e7ef4be42c7bcdfce1dcdf131f8205e/src/friend.c#L213)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why did you drop this check?
</blockquote></details>

If we don't get the complete metadata, `read_meta` is set to false and we never get this far. It wasn't a case that could happen. 

---

*[src/layout/friend.c, line 583 at r1](https://reviewable.io:443/reviews/utox/utox/891#-KivMZIp0pxsBIYyxBjA:-KivOpR14mx8g2ZyGibj:b-4pzbu6) ([raw file](https://github.com/utox/utox/blob/2ffc0af3343e0eab96178152e45143cb7a7c3bef/src/layout/friend.c#L583)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

we should also call this on clean exit, for each friend
</blockquote></details>

Seems like a waste when we're already calling it after changing the metadata for the friend we modify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/friend.c, line 213 at r1](https://reviewable.io:443/reviews/utox/utox/891#-KivMVo5OIqO2VA0znhr:-KivbYnMj8-lIzgW_Wwq:b84bxac) ([raw file](https://github.com/utox/utox/blob/107d21d34e7ef4be42c7bcdfce1dcdf131f8205e/src/friend.c#L213)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

If we don't get the complete metadata, `read_meta` is set to false and we never get this far. It wasn't a case that could happen. 
</blockquote></details>

..It wasn't a case that could happen until I fixed that we were allocating ~2x the memory required to hold the metadata. Will add this back in. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/friend.c, line 213 at r1](https://reviewable.io:443/reviews/utox/utox/891#-KivMVo5OIqO2VA0znhr:-KivdR7AuZtzbnzWEZPD:b-g4v1oy) ([raw file](https://github.com/utox/utox/blob/107d21d34e7ef4be42c7bcdfce1dcdf131f8205e/src/friend.c#L213)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

..It wasn't a case that could happen until I fixed that we were allocating ~2x the memory required to hold the metadata. Will add this back in. 
</blockquote></details>

Added back a check checking if we read at least `sizeof(FRIEND_META_DATA)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891)*

**Comment by GrayHatter** [comment]
:lgtm:

+@endoffile78 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/layout/friend.c, line 583 at r1](https://reviewable.io:443/reviews/utox/utox/891#-KivMZIp0pxsBIYyxBjA:-Kiwb_8kTr1mkmlUFhdz:by5ougr) ([raw file](https://github.com/utox/utox/blob/2ffc0af3343e0eab96178152e45143cb7a7c3bef/src/layout/friend.c#L583)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Seems like a waste when we're already calling it after changing the metadata for the friend we modify.
</blockquote></details>

OK, but that's what we 'were' doing before :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891#-:-Kiwbg1fQnmYI9JpBaIf:bxkzh9z)*

**Comment by endoffile78** [comment]
Fails to build on linux

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891#-:-KjAq1zqLzLAuNL8Ngs0:bauhogq)*

**Comment by GrayHatter** [comment]
https://travis-ci.org/uTox/uTox/jobs/227230710#L702

> /home/travis/build/uTox/uTox/src/friend.c:155:37: error: missing field 'ft_autoaccept' initializer [-Werror,-Wmissing-field-initializers]

Do we want to suppress this warning? @robinlinden @endoffile78 @cebe

**Comment by robinlinden** [comment]
That behaviour is well defined in the C standard and there is a bug open
against clang to silence that warning for the case when you use `{0}`. It
should be silenced for Clang at least. If we want to detect legitimate
instances of missing initialisers we should add a gcc build since they had
the same bug but fixed it.

**Comment by GrayHatter** [comment]
@robinlinden let's supress the warning and add a `# TODO 2017 JULY remove this warning suppression`

maybe clang will have fixed it by then 😁

**Comment by GrayHatter** [comment]
@cebe if you wanna push that fix, @endoffile78 and I can review that change without @robinlinden

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/891#-:-KjkvBbDPw1nkY06bOWw:bnfp4nl)*

**Pull request merged**
