### PR TITLE
Reduce and make includes explicit.

### PR DESCRIPTION
**Pull request by robinlinden**
It looks like I added a lot of them, but there are actually fewer of them now.. They used to be included through other files and I've reduced that so we can eventually add tests.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/626)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/flist.h, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadGO8IfyJaPogT1D09:-KadGO8IfyJaPogT1D0A:b-b60d4a) ([raw file](https://github.com/utox/utox/blob/9f920154640197da60d479a6ffa9a426407977ec/src/flist.h#L4)):*
> ```objc
> #define FLIST_H
> 
> #include "friend.h"
> ```

this is my favorite part of this whole pull!

---

*[src/groups.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadGdgTPzoI2-_Ou2s4:-KadGdgTPzoI2-_Ou2s5:bc69tgp) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/groups.h#L7)):*
> ```objc
> 
> #include "av/audio.h"
> // #include "ui/edit.h"
> ```

delete this maybe?

---

*[src/ui.h, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadH7aoMc9NoThdn9O-:-KadH7apc1VMdESDx8OI:bqhz1x) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/ui.h#L5)):*
> ```objc
> 
> #include "main.h"
> #include "main_native.h"
> ```

BTW out of scope for this pull, but we should just name this `native.h`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626#-:-KadHaygWAmhawhE2C8X:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/flist.h, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadGO8IfyJaPogT1D09:-KadMvShNTZQ240Ag_H6:b-wjixuj) ([raw file](https://github.com/utox/utox/blob/9f920154640197da60d479a6ffa9a426407977ec/src/flist.h#L4)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this is my favorite part of this whole pull!
</blockquote></details>

Lots of forward declares and I ended up actually having to include system libraries!

---

*[src/groups.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadGdgTPzoI2-_Ou2s4:-KadN2ddw9iYwcXoFXlr:b-xqwnep) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/groups.h#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

delete this maybe?
</blockquote></details>

Done. I was in the middle of something when I made this PR.

---

*[src/ui.h, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadH7aoMc9NoThdn9O-:-KadN76h9OhU2QDuoPgY:b-5dtop) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/ui.h#L5)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW out of scope for this pull, but we should just name this `native.h`
</blockquote></details>

That's a good idea. I think we should also rename all the native_x functions to not start with native_. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626#-:-KadUBdjmM3tyBp8Sy6X:bnfp4nl)*

**Comment by endoffile78** [comment]
This doesn't build on linux, legacy windows, and OSX.

**Comment by cebe** [comment]
Reviewed 35 of 36 files at r1, 21 of 32 files at r2.
Review status: 46 of 57 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/avatar.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadH_7YRdM8QobJabzW:-KadH_7YRdM8QobJabzX:bddvp45) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/avatar.h#L7)):*
> ```objc
> 
> typedef struct native_image NATIVE_IMAGE;
> typedef struct avatar AVATAR;
> ```

how does forward declare of structs work? I tried that once and it did not compile for me...

---

*[src/flist.h, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadGO8IfyJaPogT1D09:-KadI6ladybMrp9eJce0:b5o5fz6) ([raw file](https://github.com/utox/utox/blob/9f920154640197da60d479a6ffa9a426407977ec/src/flist.h#L4)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this is my favorite part of this whole pull!
</blockquote></details>

also: friend.h and groups.h are not the smalles includes :-D

---

*[src/ui.h, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadH7aoMc9NoThdn9O-:-KadJ0WYNR6DFdGOtXr3:byr870v) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/ui.h#L5)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW out of scope for this pull, but we should just name this `native.h`
</blockquote></details>

better not too early, we have already logging_native.h. lets fix the includes first and then think of how we do the native override stuff.

---

*[src/ui/draw_helpers.c, line 267 at r1](https://reviewable.io:443/reviews/utox/utox/626#-Kadm4882pyRJYbTNhih:-Kadm489c3XZPPZeKyJX:bw50kg2) ([raw file](https://github.com/utox/utox/blob/9f920154640197da60d479a6ffa9a426407977ec/src/ui/draw_helpers.c#L267)):*
> ```C
>             case ADDF_UNKNOWN: // for unknown error.
>             case ADDF_NONE:    // this case must never be rendered, but if it does, assume it's an error
>             default:
> ```

str will be undefined if this is not present and not argument matches, why did you remove it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by cebe** [comment]
Reviewed 11 of 32 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/avatar.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadH_7YRdM8QobJabzW:-KadnrCaWJfxVmHUOEMs:bukc75y) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/avatar.h#L7)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

how does forward declare of structs work? I tried that once and it did not compile for me...
</blockquote></details>

It only works when you use pointers. That's why I have to leave a few includes in the headers for now.

In this file we're using `NATIVE_IMAGE *img`, but we never access it, so we don't need to know what it contains; and it's a pointer to it, so we don't need to know the size of it either.  This means you can use a forward declare. 

For a forward-declare to be possible, the struct has to be named. 

**Works:**
```
// Definition
struct avatar { int a; };

// Forward-declare (in different file or whatever)
struct avatar;
```

**Also works:**
```
// Definition
typedef struct avatar { int a; } AVATAR;

// Forward-declare (in different file or whatever)
typedef struct avatar AVATAR;
```

**Doesn't work:**
```
// Definition
typedef struct { int a; } AVATAR;

// No forward-declare possible since the struct is anonymous. :(
```

This is why I'm randomly* adding names to a few structs I want to forward declare.

---

*[src/ui.h, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadH7aoMc9NoThdn9O-:-KadqU-KeBNq7c1yyjnQ:brcpai8) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/ui.h#L5)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

better not too early, we have already logging_native.h. lets fix the includes first and then think of how we do the native override stuff.
</blockquote></details>

Yeah, it's all out of scope for this PR. I'm not changing any names or anything. Just moving things around or deleting things.

---

*[src/ui/draw_helpers.c, line 267 at r1](https://reviewable.io:443/reviews/utox/utox/626#-Kadm4882pyRJYbTNhih:-KadrUA4wbcyZxLn-zF-:b-290ot7) ([raw file](https://github.com/utox/utox/blob/9f920154640197da60d479a6ffa9a426407977ec/src/ui/draw_helpers.c#L267)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

str will be undefined if this is not present and not argument matches, why did you remove it?
</blockquote></details>

See: https://reviewable.io/reviews/utox/utox/610#-KaLq-3GJCnM5KvKYrml

Since this is now a `typedef enum` (see the change in `dns.h`), this will emit a warning/error if a case is missing. (See the documentation on the -Wswitch compiler flag.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/avatar.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/626#-KadH_7YRdM8QobJabzW:-Kae0jKYa8dE3mw2KgrI:b-5edy46) ([raw file](https://github.com/utox/utox/blob/fdc3e6ff4c6c4e7d571b2d0869c76a4f8110f318/src/avatar.h#L7)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

It only works when you use pointers. That's why I have to leave a few includes in the headers for now.

In this file we're using `NATIVE_IMAGE *img`, but we never access it, so we don't need to know what it contains; and it's a pointer to it, so we don't need to know the size of it either.  This means you can use a forward declare. 

For a forward-declare to be possible, the struct has to be named. 

**Works:**
```
// Definition
struct avatar { int a; };

// Forward-declare (in different file or whatever)
struct avatar;
```

**Also works:**
```
// Definition
typedef struct avatar { int a; } AVATAR;

// Forward-declare (in different file or whatever)
typedef struct avatar AVATAR;
```

**Doesn't work:**
```
// Definition
typedef struct { int a; } AVATAR;

// No forward-declare possible since the struct is anonymous. :(
```

This is why I'm randomly* adding names to a few structs I want to forward declare.
</blockquote></details>

cool, thanks for explaining!

---

*[src/ui/draw_helpers.c, line 267 at r1](https://reviewable.io:443/reviews/utox/utox/626#-Kadm4882pyRJYbTNhih:-Kae0v_W_864fVkBIYZo:b-8fx2u7) ([raw file](https://github.com/utox/utox/blob/9f920154640197da60d479a6ffa9a426407977ec/src/ui/draw_helpers.c#L267)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

See: https://reviewable.io/reviews/utox/utox/610#-KaLq-3GJCnM5KvKYrml

Since this is now a `typedef enum` (see the change in `dns.h`), this will emit a warning/error if a case is missing. (See the documentation on the -Wswitch compiler flag.)
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by cebe** [comment]
Reviewed 1 of 36 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by cebe** [comment]
Reviewed 19 of 19 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by GrayHatter** [comment]
Reviewed 17 of 32 files at r2, 4 of 7 files at r3, 7 of 19 files at r4, 51 of 51 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/logging_native.h, line 4 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KaknIz5MHvCDMMQqI78:-KaknIz66ADOtrF4kO1p:bk5v6n) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/logging_native.h#L4)):*
> ```objc
> #define LOGGING_NATIVE_H
> 
> #include <stdio.h>
> ```

why is stdio here?

---

*[src/ui.h, line 27 at r6](https://reviewable.io:443/reviews/utox/utox/626#-Kaknxb4dCtxf_tp6QKW:-Kaknxb4dCtxf_tp6QKX:bg50ije) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/ui.h#L27)):*
> ```objc
> #if defined __WIN32__
> // Windows supplies its own RGB function.
> #include <windows.h>
> ```

this isn't cool, we can fix this later, because I'm generally happy with this pull as is.

But we should never be including native headers outside of native code (no one look at the updater)

---

*[src/ui/buttons.c, line 4 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KalIf4i7Jcoaiq65fPM:-KalIf4i7Jcoaiq65fPN:br896h2) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/ui/buttons.c#L4)):*
> ```C
> 
> #include "contextmenu.h"
> #include "scrollable.h"
> ```

why do we need scrollable here?

---

*[src/xlib/keysym2ucs.h, line 41 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KalJS4ZX9oZW7UVMb4S:-KalJS4ZX9oZW7UVMb4T:b-n5ay7t) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/xlib/keysym2ucs.h#L41)):*
> ```objc
> #include <inttypes.h>
> 
> #include <X11/keysymdef.h>
> ```

are you sure this is needed here? also, IIRC there's a list copied into xlib somewhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 49 of 51 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/logging_native.h, line 4 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KaknIz5MHvCDMMQqI78:-KamRh6EEv9DJ_T9wbDF:bdimmgp) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/logging_native.h#L4)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why is stdio here?
</blockquote></details>

it is used in xlib/logging.h windows/logging.h which are included below. should maybe be moved into those files.

---

*[src/ui/buttons.c, line 4 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KalIf4i7Jcoaiq65fPM:-KamTSky3LzG6gCTRsI-:bqep95r) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/ui/buttons.c#L4)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why do we need scrollable here?
</blockquote></details>

line 627 accesses `scrollbar_settings.content_height`

---

*[src/xlib/keysym2ucs.h, line 41 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KalJS4ZX9oZW7UVMb4S:-KamX7V0fWwOi07q5R6f:b822gnk) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/xlib/keysym2ucs.h#L41)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

are you sure this is needed here? also, IIRC there's a list copied into xlib somewhere else.
</blockquote></details>

it defines the `KeySym` tyoe, used below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626#-:-KamXRwuccnv4lUwT5TM:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/logging_native.h, line 4 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KaknIz5MHvCDMMQqI78:-KamZ9Tgz8cNvrq0VGLG:b-h3byap) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/logging_native.h#L4)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

it is used in xlib/logging.h windows/logging.h which are included below. should maybe be moved into those files.
</blockquote></details>

What CeBe said. I was under the impression that __android_log_print and whatever we use on OS X also needed stdio. I've moved it into xlib and windows logging.h

---

*[src/ui.h, line 27 at r6](https://reviewable.io:443/reviews/utox/utox/626#-Kaknxb4dCtxf_tp6QKW:-Kam_lVDe4iL8eGyAYyZ:b-bm40t8) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/ui.h#L27)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this isn't cool, we can fix this later, because I'm generally happy with this pull as is.

But we should never be including native headers outside of native code (no one look at the updater)
</blockquote></details>

This is a temporary thing. We need to add native headers that are used exclusively in the UI and I didn't want to commit to adding those properly in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 51 files at r5, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/buttons.c, line 4 at r6](https://reviewable.io:443/reviews/utox/utox/626#-KalIf4i7Jcoaiq65fPM:-KanSofKk3BTQzPVSSE9:bd33uhx) ([raw file](https://github.com/utox/utox/blob/acc2af69351478666703fddcae363c1bdc11f9c5/src/ui/buttons.c#L4)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

line 627 accesses `scrollbar_settings.content_height`
</blockquote></details>

LGTM

we probably should try to write a separate function for those lines. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 51 files at r5, 2 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626#-:-Kanm0AxNGDN9-16hfA8:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 17 of 32 files at r2, 4 of 7 files at r3, 7 of 19 files at r4, 50 of 51 files at r5, 1 of 1 files at r6, 2 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/626#-:-KanumqDQVTwOjJTb_6D:bnfp4nl)*

**Pull request merged**
