### PR TITLE
Better cmake && extern to avoid a segfault on windows

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/508)

### CODE REVIEW

**Comment by endoffile78** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 65 at r1](https://reviewable.io:443/reviews/utox/utox/508#-KXKBI3ytS4wu37SpS3u:-KXKBI4-shQceWvVZxDC:bvdefxr) ([raw file](https://github.com/utox/utox/blob/f3e168782078ed20da6255efb0cf6ef96ecda591/CMakeLists.txt#L65)):*
> ```CMake
>         src/windows/video.c
>         src/windows/filesys.c
>         icons/icon.rc )
> ```

Does the icon need to be added here and added later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/508)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 65 at r1](https://reviewable.io:443/reviews/utox/utox/508#-KXKBI3ytS4wu37SpS3u:-KXKIkc0bBC_qOydn4Gr:bz3oboo) ([raw file](https://github.com/utox/utox/blob/f3e168782078ed20da6255efb0cf6ef96ecda591/CMakeLists.txt#L65)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary>
> Does the icon need to be added here and added later.
</details>
no, just later... good catch, thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/508)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/508#-:-KXKN5Tt0RQSP0TqFNKu:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/508)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 65 at r1](https://reviewable.io:443/reviews/utox/utox/508#-KXKBI3ytS4wu37SpS3u:-KXSLyTin7FkUiKhG46Q:b-896fix) ([raw file](https://github.com/utox/utox/blob/f3e168782078ed20da6255efb0cf6ef96ecda591/CMakeLists.txt#L65)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> no, just later... good catch, thank you!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/508)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/508#-:-KXSO671FOg7SkTwtbn3:bnfp4nl)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/508)*

**Pull request merged**
