### PR TITLE
Fix a typo in CMakeLists.txt

### PR DESCRIPTION
**Pull request by fling-**
The word "staticlly" should be "statically".

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/672)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/672#-:-KbMH6MGeZ88BVaRAMHM:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/672#-:-KbMT7q96UZ5yeFNO94C:bnfp4nl)*

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/672)*

**Pull request merged**
