### PR TITLE
Allow uTox to check for updates

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/627)

### CODE REVIEW

**Comment by cebe** [comment]
Reviewed 2 of 9 files at r1, 13 of 15 files at r2.
Review status: 15 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main.c, line 28 at r2](https://reviewable.io:443/reviews/utox/utox/627#-KarNqpNTG0jwLZDMMSk:-KarNqpOVRw5qN7EYVJ2:busr5a2) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/main.c#L28)):*
> ```C
>     .auto_update        = false,
>     .update_to_develop  = false,
>     .send_version       = false,
> ```

these new settings should also be saved in the utox_save file, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by endoffile78** [comment]
Reviewed 3 of 9 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/updater.c, line 85 at r2](https://reviewable.io:443/reviews/utox/utox/627#-KaseKXRnJwDunkzeD-r:-KaseKXSg0JCMEPCYvz2:b-k22um3) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/updater.c#L85)):*
> ```C
> 
>         uint32_t len = 0, real_len = 0, header_len = 0;
>         uint8_t *buffer = calloc(1, 0x10000);
> ```

Buffer is never freed.

---

*[src/updater.c, line 180 at r2](https://reviewable.io:443/reviews/utox/utox/627#-Kasebypt5He6ZlUNSTE:-Kasebypt5He6ZlUNSTF:b-vawi3z) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/updater.c#L180)):*
> ```C
>     uint8_t *raw = download("downloads.utox.io", "utox_version_stable", &len);
>     if (!raw) {
>         debug_error("Updater:\tDownload failed.\n");
> ```

Shouldn't there be a return here.

---

*[src/updater.c, line 200 at r2](https://reviewable.io:443/reviews/utox/utox/627#-KasepwqNTiq4drUnDl1:-KasepwqNTiq4drUnDl2:b2407bs) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/updater.c#L200)):*
> ```C
>     memcpy(&v, data + 4, sizeof(v));
>     uint32_t version = ntohl(v);
> ```

free data before returning

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by GrayHatter** [comment]
Review status: 16 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.c, line 28 at r2](https://reviewable.io:443/reviews/utox/utox/627#-KarNqpNTG0jwLZDMMSk:-KasibU0SnCKLRbxDoMY:b-896fix) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/main.c#L28)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

these new settings should also be saved in the utox_save file, right?
</blockquote></details>

Done.

---

*[src/updater.c, line 85 at r2](https://reviewable.io:443/reviews/utox/utox/627#-KaseKXRnJwDunkzeD-r:-KasicFmRXtlSgq1fas5:b-896fix) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/updater.c#L85)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Buffer is never freed.
</blockquote></details>

Done.

---

*[src/updater.c, line 180 at r2](https://reviewable.io:443/reviews/utox/utox/627#-Kasebypt5He6ZlUNSTE:-Kasid6YL6GxmOCykHwL:b-896fix) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/updater.c#L180)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Shouldn't there be a return here.
</blockquote></details>

Done.

---

*[src/updater.c, line 200 at r2](https://reviewable.io:443/reviews/utox/utox/627#-KasepwqNTiq4drUnDl1:-KasidWvZDvFQGxr2rsB:b-896fix) ([raw file](https://github.com/utox/utox/blob/1ba697748b4c67553b23105cd1b0fefd3c4f1257/src/updater.c#L200)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

free data before returning
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by cebe** [comment]
Reviewed 1 of 9 files at r1, 2 of 3 files at r3.
Review status: 18 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.h, line 131 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kasneywk9PtiOURM27q:-Kasneywk9PtiOURM27r:bxh0gmd) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/main.h#L131)):*
> ```objc
>     uint8_t zero_3              : 8;
> 
>     uint16_t unused[28];
> ```

if you add 4*8 bit above, this array of 16bit integers should be reduced by 2, not 1. Or did I misunderstand how this works?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by GrayHatter** [comment]
Review status: 18 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.h, line 131 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kasneywk9PtiOURM27q:-Kat-1t1j3bratZvc_5g:b-dp5xds) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/main.h#L131)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

if you add 4*8 bit above, this array of 16bit integers should be reduced by 2, not 1. Or did I misunderstand how this works?
</blockquote></details>

I'm using bit fields here, I only added 2 `u8` the first `zero :1` existed already. I added 2 `u8` the first 2 bits going to auto_update, and send_version respectively. the remaining 6 bits, to zero_2, then a 2nd `u8` to make sure that the alignment doesn't change.   And now that we have static asserts with C11,  we should assert the size here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by cebe** [comment]
Review status: 18 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.h, line 131 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kasneywk9PtiOURM27q:-Kat0H5P1lRgtCinvFj0:bwpwkt5) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/main.h#L131)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I'm using bit fields here, I only added 2 `u8` the first `zero :1` existed already. I added 2 `u8` the first 2 bits going to auto_update, and send_version respectively. the remaining 6 bits, to zero_2, then a 2nd `u8` to make sure that the alignment doesn't change.   And now that we have static asserts with C11,  we should assert the size here too.
</blockquote></details>

I see, was not aware of this syntax. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by endoffile78** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/util.c, line 747 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat5LhgJ-xxzjsS3KuQ:-Kat5Lhh3KKkUda3eYro:brgnvce) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/util.c#L747)):*
> ```C
>     save->status_notifications = settings.status_notifications;
> 
>     save->auto_update           = settings.auto_update;
> ```

These settings aren't loaded when uTox starts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by robinlinden** [comment]
Reviewed 5 of 9 files at r1, 13 of 15 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 202 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat2AozudiqNxf1b6IY:-Kat2AozudiqNxf1b6IZ:bq9q6uf) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/main.c#L202)):*
> ```C
> void parse_args(int argc, char *argv[],
>                 bool *skip_updater,
>                 bool *signal_updater,
> ```

What is signal_updater? It doesn't seem to be used for anything (right now, anyway)

---

*[src/updater.c, line 8 at r3](https://reviewable.io:443/reviews/utox/utox/627#-KatYw-tX3MZb_5nYpM5:-KatYw-u_itscOLI6NMl:b-z3dlb8) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L8)):*
> ```C
> 
> #include <stddef.h>
> #include <inttypes.h>
> ```

Should be `stdint.h`. You're not using any of the macros or functions from `inttypes.h`.

---

*[src/updater.c, line 50 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat_77dQk6sVCWOoXMz:-Kat_77eozDFOO1DTzN2:bw8pk4j) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L50)):*
> ```C
>     }
> 
>     int32_t sock = 0;
> ```

This is never used outside of the loop.

---

*[src/updater.c, line 56 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat_2t-BfToR9uIULF8:-Kat_2t-BfToR9uIULF9:b-tvvg6f) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L56)):*
> ```C
>         }
> 
>         sock = socket(info->ai_family, SOCK_STREAM, IPPROTO_TCP);
> ```

`int32_t sock = ..`

---

*[src/updater.c, line 85 at r3](https://reviewable.io:443/reviews/utox/utox/627#-KatcWb6nXK5gRU9Loxc:-KatcWb6nXK5gRU9Loxd:bpjwtq2) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L85)):*
> ```C
> 
>         uint32_t len = 0, real_len = 0, header_len = 0;
>         uint8_t *buffer = calloc(1, 0x10000);
> ```

Check if this allocation worked.

---

*[src/updater.c, line 133 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Katbc0SuAYk7D9iQQnS:-Katbc0SuAYk7D9iQQnT:b-e9pbza) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L133)):*
> ```C
>             if (real_len + len > header_len) {
>                 debug_error("Updater:\tCorrupt download, can't continue with update.\n");
>                 free(buffer);
> ```

And `free(data);`

---

*[src/updater.c, line 144 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Katbsqz1g48ODnAd9K1:-KatarfnHaLvnzzk5rSq:b-39sjlh) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L144)):*
> ```C
>                 *out_len = real_len;
>             }
>             return data;
> ```

`buffer` isn't freed before this return.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 202 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat2AozudiqNxf1b6IY:-Kau_VL354c1RCPH0PJe:b-gnai15) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/main.c#L202)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

What is signal_updater? It doesn't seem to be used for anything (right now, anyway)
</blockquote></details>

I don't have the time to implement the full updater inside uTox yet, but when I do, it'll be needed to tell the updater, that the installed version can't start successfully, and it should revert to the backup version.

---

*[src/updater.c, line 8 at r3](https://reviewable.io:443/reviews/utox/utox/627#-KatYw-tX3MZb_5nYpM5:-Kau_uJJv2q_CeuI02A8:b-896fix) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L8)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Should be `stdint.h`. You're not using any of the macros or functions from `inttypes.h`.
</blockquote></details>

Done.

---

*[src/updater.c, line 50 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat_77dQk6sVCWOoXMz:-Kau_z60WSvCBAwodImh:b-896fix) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L50)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This is never used outside of the loop.
</blockquote></details>

Done.

---

*[src/updater.c, line 56 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat_2t-BfToR9uIULF8:-Kaua2f4EWzSOTkdSPkU:b-896fix) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L56)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`int32_t sock = ..`
</blockquote></details>

Done.

---

*[src/updater.c, line 85 at r3](https://reviewable.io:443/reviews/utox/utox/627#-KatcWb6nXK5gRU9Loxc:-KauaERsnGcGPg07MueU:b-896fix) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L85)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Check if this allocation worked.
</blockquote></details>

Done.

---

*[src/updater.c, line 133 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Katbc0SuAYk7D9iQQnS:-KauaKFS9tMUcW_FzrSY:b-896fix) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L133)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

And `free(data);`
</blockquote></details>

Done.

---

*[src/updater.c, line 144 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Katbsqz1g48ODnAd9K1:-KauaTIXMYrEHF3Yp_8I:b-896fix) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/updater.c#L144)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`buffer` isn't freed before this return.
</blockquote></details>

Done.

---

*[src/util.c, line 747 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat5LhgJ-xxzjsS3KuQ:-KauaU73snxGKo8sLJdN:b-896fix) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/util.c#L747)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

These settings aren't loaded when uTox starts.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 202 at r3](https://reviewable.io:443/reviews/utox/utox/627#-Kat2AozudiqNxf1b6IY:-KavD91xuNm9xe3YIN8x:bu1c5k3) ([raw file](https://github.com/utox/utox/blob/c515b90c4051405de7e7422b62829afb6725166c/src/main.c#L202)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I don't have the time to implement the full updater inside uTox yet, but when I do, it'll be needed to tell the updater, that the installed version can't start successfully, and it should revert to the backup version.
</blockquote></details>

Maybe rename it to "revert_update" or something less generic than "signal_updater".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627#-:-KavErWE5yVhDIPJ-5zf:b-jbsf8z)*

**Comment by GrayHatter** [comment]
@uTox/devs signoff needed

**Comment by cebe** [comment]
Reviewed 1 of 3 files at r4, 42 of 43 files at r5.
Review status: 57 of 58 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by cebe** [comment]
On advanced tab, the password  warning is broken:

bildschirmfoto von 2017-01-20 17 25 28

**Comment by cebe** [comment]
Reviewed 1 of 1 files at r6.
Review status: 57 of 58 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r4, 42 of 43 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627#-:-KaymOkurNFceIcaqqqG:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627#-:-KaysJxhyEwXOeGk6iG0:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627#-:-Kaz6VrfxBuW-I5-M6PG:bnfp4nl)*

**Comment by fcore117** [comment]
Reviewed 3 of 9 files at r1, 11 of 15 files at r2, 1 of 3 files at r4, 39 of 43 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 3 of 5 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627#-:-Kb0TmWswD3pAIEIvYZW:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 39 of 43 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 3 of 5 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/627#-:-Kb45KMgs4-oA_Eqii4R:bnfp4nl)*

**Pull request merged**
