### PR TITLE
Release v0.15.0

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/852)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/852)*

**Comment by v2e** [comment]
Is there a way for an actual translation to get into the current release? It would be a bit strange to always translate the greetings and changelog for the _previous_ version.

**Comment by robinlinden** [comment]
Heh. Yeah, that is true. We could add you to the uTox org and I'll tick the box that allow you to push a commit to this branch with the Ukrainian translation. Would that be okay? Alternatively, you could provide a patch or something.

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/852#-:-KiMSBeHM5jdyyIZ40iA:bnfp4nl)*

**Comment by redmanmale** [comment]
Russian translation for latest changelog.
https://gist.github.com/redmanmale/43bd7bffc1c628f1897ef7f71e7e7e9b

**Comment by v2e** [comment]
@robinlinden What is the best way to do it? I am not sure what the title of this pull request actually means. Does it mean nothing will be added to v.0.15.0 after it is merged?

**Comment by robinlinden** [comment]
@v2e You could join IRC for easier communication. :P Other than that, we're happy with whatever way you think is convenient.
Yeah, nothing will be added to 0.15.0 after this is merged. We're going to start having a longer lead time on the release PRs so people have time to translate the changelog and stuff if they want to starting next release.

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/852#-:-KiMiqgmBfdcT1QzUb5m:bnfp4nl)*

**Comment by v2e** [comment]
Here is a patch for v.0.15.0: https://gist.github.com/v2e/f4207749f166e7e7ad9c40183166b626

**Comment by robinlinden** [comment]
Thank you so much, @v2e! If you want, we'll add you to the uTox org and the translation team so we can tag you in releases. (If you want to continue contributing, of course.) :P

**Comment by v2e** [comment]
@robinlinden I am not sure what exactly the 'tagging' means, but yes, I would like to contribute to uTox in the future.

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/852#-:-KiMp284moknjr0CSSTD:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/852#-:-KiMpy-U5RAXz3md2_AD:bnfp4nl)*

**Comment by redmanmale** [comment]
Reviewed 3 of 5 files at r1, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/852)*

**Pull request merged**
