### PR TITLE
Fix GTK loading

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1009)

### CODE REVIEW

**Comment by redmanmale** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/xlib/gtk.c, line 27 at r1](https://reviewable.io:443/reviews/utox/utox/1009#-KsKnzt3UbgnfmwjnNQD:-KsKnzt3UbgnfmwjnNQE:b-vv34zn) ([raw file](https://github.com/utox/utox/blob/1ea3e8103b5e21b8b9a52dbf8bb6cc9c7a858736/src/xlib/gtk.c#L27)):*
> ```C
> #include <string.h>
> 
> #define LIBGTK_FILENAME "libgtk-3.so.0"
> ```

Revert back to `libgtk-3.so`, it's primary case.

---

*[src/xlib/gtk.c, line 429 at r1](https://reviewable.io:443/reviews/utox/utox/1009#-KsKo5elGnCsFNDrsqrw:-KsKo5emxyBCXYdkEK1d:bpdebmy) ([raw file](https://github.com/utox/utox/blob/1ea3e8103b5e21b8b9a52dbf8bb6cc9c7a858736/src/xlib/gtk.c#L429)):*
> ```C
>     if (!lib) { //try again with libgtk-3.so.0 if the first one failed
>         LOG_INFO("GTK", "Failed loading: %s. Falling back to libgtk-3.so.0", LIBGTK_FILENAME);
>         lib = dlopen("libgtk-3.so.0", RTLD_LAZY);
> ```

Maybe new const i.e. `LIBGTK_FILENAME_FALLBACK`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1009)*

**Comment by endoffile78** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/xlib/gtk.c, line 27 at r1](https://reviewable.io:443/reviews/utox/utox/1009#-KsKnzt3UbgnfmwjnNQD:-KsLGOe-uOVAgiORoJST:b-896fix) ([raw file](https://github.com/utox/utox/blob/1ea3e8103b5e21b8b9a52dbf8bb6cc9c7a858736/src/xlib/gtk.c#L27)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Revert back to `libgtk-3.so`, it's primary case.
</blockquote></details>

Done.

---

*[src/xlib/gtk.c, line 429 at r1](https://reviewable.io:443/reviews/utox/utox/1009#-KsKo5elGnCsFNDrsqrw:-KsLGPE2OSg8hJRDKB_P:b-896fix) ([raw file](https://github.com/utox/utox/blob/1ea3e8103b5e21b8b9a52dbf8bb6cc9c7a858736/src/xlib/gtk.c#L429)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Maybe new const i.e. `LIBGTK_FILENAME_FALLBACK`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1009)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1009#-:-KsNFDrLNOx6hGu0awQO:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1009#-:-KsOwmGG8OqM4EUC4sJ8:bnfp4nl)*

**Pull request merged**
