### PR TITLE
Version tick

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/541)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm: 

good catch on the cmake

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/541#-:-KZ0QZU_nTtwue0weqYw:b-9g0fza)*

**Comment by robinlinden** [comment]
Needs to be changed in https://github.com/uTox/uTox/blob/develop/src/android/AndroidManifest.xml#L3 too.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/541#-:-KZCOxeZ10GuUpxEZAjG:b5bioub)*

**Comment by GrayHatter** [comment]
Looks like it's time to write a version update script.

**Comment by endoffile78** [comment]
@robinlinden Done.

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/541#-:-KZDUA_cRMfqhIJ3WL0k:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/541#-:-KZLchYEA4_py9uSq9kT:bnfp4nl)*

**Pull request merged**
