### PR TITLE
Document the static builds are outdated.

### PR DESCRIPTION
**Pull request by fling-**
Resolves https://github.com/uTox/uTox/issues/1220

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1222)

### CODE REVIEW

**Comment by GrayHatter** [comment]
I'm torn on this, it's a trivial merge, but I don't see a real benefit, I'd rather drop the lines if we're not going to maintain build.tox.chat, or fix build.tox.chat if we are

@robinlinden

**Comment by fling-** [comment]
The older binary is still good if you can't build one.

**Comment by robinlinden** [comment]
iirc, they're currently broken because of the git submodules not being included in the source Jenkins provides. I'd like to just fix them rather than dropping them.

**Comment by GrayHatter** [comment]
good luck @robinlinden

**Comment by robinlinden** [comment]
I'm not going to fix this. :(

**Comment by GrayHatter** [comment]
Branch conflict, with different solution than this PR

**Pull request closed without merging**
