### PR TITLE
Fix null dereference in edit.c

### PR DESCRIPTION
**Pull request by robinlinden**
To reproduce the crash this fixes:
```
tssx: click between settings tab(no button on off, just between tabs), then right click in friend search tab and press 2 mouse buttons on cut selection
```

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/920)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/920#-:-KkXz75tlyYH2n4yRpiS:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/edit.c, line 417 at r1](https://reviewable.io:443/reviews/utox/utox/920#-KkZldtnR5khMwsNdxk-:-KkZldtoN2r5_U2kciZZ:b29ejk3) ([raw file](https://github.com/utox/utox/blob/1f7cf846578ed9ed211e71df3acbd19c7af4729c/src/ui/edit.c#L417)):*
> ```C
> void edit_char(uint32_t ch, bool control, uint8_t flags) {
>     if (!active_edit) {
>         return;
> ```

needs a LOG_ERR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/920#-:-KkZlh47wg7Satq91eF7:b-uwkowd)*

**Comment by robinlinden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/edit.c, line 417 at r1](https://reviewable.io:443/reviews/utox/utox/920#-KkZldtnR5khMwsNdxk-:-Kkr6wkE3o5k2OSEhysw:b-geuad8) ([raw file](https://github.com/utox/utox/blob/1f7cf846578ed9ed211e71df3acbd19c7af4729c/src/ui/edit.c#L417)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

needs a LOG_ERR
</blockquote></details>

There you go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/920)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/920#-:-KkrBY07DSZZA0gKjXfk:bnfp4nl)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/920)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/920#-:-KkrCxXtT6HMLaUEnn59:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/920#-:-Kl2CBVsRDmS24PNuLyf:bg7igkv)*

**Pull request merged**
