### PR TITLE
Update tools

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/547)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/update-chanelog.sh, line 3 at r1](https://reviewable.io:443/reviews/utox/utox/547#-KZ9X1UFLeE6m_IDmWXH:-KZ9X1UHjdjlIvxW-TI-:bc86iuj) ([raw file](https://github.com/utox/utox/blob/0841e36c7753f156ca1814b34f4247cb9602851d/tools/update-chanelog.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> if [[ -z $1 ]]; then
> ```

can we save the token in the .git config?

`git config user.github_token`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/547)*

**Comment by endoffile78** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/update-chanelog.sh, line 3 at r1](https://reviewable.io:443/reviews/utox/utox/547#-KZ9X1UFLeE6m_IDmWXH:-KZ9aLPiBH63vjIYgjlO:b-896fix) ([raw file](https://github.com/utox/utox/blob/0841e36c7753f156ca1814b34f4247cb9602851d/tools/update-chanelog.sh#L3)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

can we save the token in the .git config?

`git config user.github_token`

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/547)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/547)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/547#-:-KZAS1soMqt4Piur5f49:bnfp4nl)*

**Comment by robinlinden** [comment]
You might want to rename the file to `update-changelog.sh` (missing g)

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/547#-:-KZCMS7iREVM_g5Bn7TR:bmu24yr)*

**Comment by endoffile78** [comment]
@robinlinden Done.

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/547#-:-KZDZeebwdF-wtR1EDG9:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/547#-:-KZLddTzQTjn7w9w7JTL:bnfp4nl)*

**Pull request merged**
