### PR TITLE
fix #1156

### LINKED ISSUE #1156: uTox (0.16.1) doesn't automatically create .config/tox
Hello,
No able to use uTox with my Mac.
I have installed it on Windows, Linux and Mac, seems to work (didn't fully test it yet) but not with my Mac.
It doesn't keep any of my settings including my uTox username, Tox ID etc.
Any ideas ?
Thx

### PR DESCRIPTION
**Pull request by publicarray**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1182)

### CODE REVIEW

**Comment by redmanmale** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/posix/filesys.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rbMf9bzTYiJLSQxqD:-L5rbMf9bzTYiJLSQxqE:byhs2nv) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L15)):*
> ```C
> #include <sys/stat.h>
> 
> bool native_create_dir_tree(const uint8_t *path) {
> ```

Maybe use `char*` to avoid unnecessary casts?

---

*[src/posix/filesys.c, line 17 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rbnU-GyBFqVEg2doA:-L5rbnU-GyBFqVEg2doB:b-pfnll9) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L17)):*
> ```C
> bool native_create_dir_tree(const uint8_t *path) {
>     size_t size = strlen((const char *)path);
>     if (size <= 2) {
> ```

Some comment about why `2`.

---

*[src/posix/filesys.c, line 21 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rbtJcBAwzs_P5vbN7:-L5rbtJcBAwzs_P5vbN8:bx2ypq7) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L21)):*
> ```C
>     }
> 
>     uint8_t *buff = calloc(1, size);
> ```

Make sure memory was allocated.

---

*[src/posix/filesys.c, line 24 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rc08kOhFQNVOEQoJM:-L5rc08kOhFQNVOEQoJN:bmj556f) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L24)):*
> ```C
>     for (size_t i = 1; i < size; ++i) { // i = 1 to skip root '/'
>         if (path[i] == '/') {
>             memcpy(buff, path, i+1);
> ```

Spacing: `i + 1`

---

*[src/posix/filesys.c, line 25 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rc75VfjiqP6EYLhK8:-L5rc75VfjiqP6EYLhK9:bijvfz1) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L25)):*
> ```C
>         if (path[i] == '/') {
>             memcpy(buff, path, i+1);
>             if (native_create_dir(buff) == false) {
> ```

Could be simplified: just drop `== false`.

---

*[src/posix/filesys.c, line 56 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rcVrBJg8qNs6ozX7r:-L5rcVrBJg8qNs6ozX7s:b235t25) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L56)):*
> ```C
>     }
> 
>     if (native_create_dir_tree((unsigned char *)path) == false) {
> ```

Could be simplified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1182)*

**Comment by publicarray** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/posix/filesys.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rbMf9bzTYiJLSQxqD:-L5u_G4oTQYLDdSTmeEv:b-896fix) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L15)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Maybe use `char*` to avoid unnecessary casts?
</blockquote></details>

Done.

---

*[src/posix/filesys.c, line 17 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rbnU-GyBFqVEg2doA:-L5u_GyQKC6G1OoMqnxO:b-896fix) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L17)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Some comment about why `2`.
</blockquote></details>

Done.

---

*[src/posix/filesys.c, line 21 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rbtJcBAwzs_P5vbN7:-L5u_HaQwhZFFAq4Uapp:b-896fix) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L21)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Make sure memory was allocated.
</blockquote></details>

Done.

---

*[src/posix/filesys.c, line 24 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rc08kOhFQNVOEQoJM:-L5u_I-x4qn1XYx1HA1v:b-896fix) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L24)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Spacing: `i + 1`
</blockquote></details>

Done.

---

*[src/posix/filesys.c, line 25 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rc75VfjiqP6EYLhK8:-L5u_IM3RwL--NrHP3dN:b-896fix) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L25)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Could be simplified: just drop `== false`.
</blockquote></details>

Done.

---

*[src/posix/filesys.c, line 56 at r1](https://reviewable.io:443/reviews/utox/utox/1182#-L5rcVrBJg8qNs6ozX7r:-L5u_Ip8EyhF6JXMcPAl:b-896fix) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L56)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Could be simplified.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1182)*

**Comment by endoffile78** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/posix/filesys.c, line 30 at r2](https://beta.reviewable.io/reviews/utox/utox/1182#-L5vCAP86oz4YS0oXt6f:-L5vCAP86oz4YS0oXt6g:b-wotiep) ([raw file](https://github.com/utox/utox/blob/9940ea67745b6306a4711436f4ac3857870761f2/src/posix/filesys.c#L30)):*
> ```C
>         if (path[i] == '/') {
>             memcpy(buff, path, i + 1);
>             if (!native_create_dir(buff)) {
> ```

Cast buff to `uint8_t *`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1182)*

**Comment by publicarray** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/posix/filesys.c, line 30 at r2](https://beta.reviewable.io/reviews/utox/utox/1182#-L5vCAP86oz4YS0oXt6f:-L5wXiwe2r9hj-KO-AIA:b-896fix) ([raw file](https://github.com/utox/utox/blob/9940ea67745b6306a4711436f4ac3857870761f2/src/posix/filesys.c#L30)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Cast buff to `uint8_t *`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1182)*

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/posix/filesys.c, line 17 at r1](https://beta.reviewable.io/reviews/utox/utox/1182#-L5rbnU-GyBFqVEg2doA:-L5wbmVm-Kwpe7p1_uzl:b70vyw) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L17)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still not quite clear why this limit.
Why path can't be something like `/a`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1182)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1182)*

**Comment by publicarray** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/posix/filesys.c, line 17 at r1](https://beta.reviewable.io/reviews/utox/utox/1182#-L5rbnU-GyBFqVEg2doA:-L6QQz2v1ztJeub8GAUQ:b-ja93cg) ([raw file](https://github.com/utox/utox/blob/ba5073dc39a13345b1e60fe741d5655593bedecc/src/posix/filesys.c#L17)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

It's still not quite clear why this limit.
Why path can't be something like `/a`?
</blockquote></details>

I've removed the `=` in the last commit. before it was `size <= 2` and you are correct in that we should allow one character folders `/a` and before it would not allow that. Thanks for pointing that out :smile:

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1182)*

**Comment by redmanmale** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1182#-:-L6QZASA82IlGdddDRQK:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1182#-:-L6Th1WMbo__6YcnNQfe:bnfp4nl)*

**Pull request merged**
