### PR TITLE
Fixes UI glitches

### PR DESCRIPTION
**Pull request by redmanmale**
- Fix for #667.
- Fixed alignment of profile password input.
- Partially fix for #868.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/870)

### CODE REVIEW

**Comment by GrayHatter** [comment]
There's a few more switches that were missed in the last one as well. 

I don't remember which ones, but make sure you take a look at audio filtering, auto-update, and sidebar auto hide.

**Comment by GrayHatter** [comment]
I also added you to the dev's list. You now have write access to uTox/uTox

Don't push anything to `master` or `develop` without a pgp signature. Otherwise, go nuts, and be nice.

**Comment by redmanmale** [comment]
I'll take a look and fix them if I could find any.
Thank you!

**Comment by redmanmale** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui.c, line 338 at r2](https://reviewable.io:443/reviews/utox/utox/870#-Kiaqq4PFkbLeVI3nqrK:-Kiaqq4Q6ZJujAl2hsME:b39vtgg) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/ui.c#L338)):*
> ```C
> 
>     /* Confirm deletion */
>     CREATE_BUTTON(confirm_deletion, 10, MAIN_TOP + 40, _BM_SBUTTON_WIDTH, _BM_SBUTTON_HEIGHT);
> ```

There's some black magic with this button.
I don't know why, but only for english at DPI more than ~150% this button breaks (cut last couple of pixels).

I checked any other language - the problem is gone.
I tried change text on this button - the problem is gone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by redmanmale** [comment]
I figured out that this button is broken only at odd DPI values (90%, 110%, 130%), so it's some rounding error obviously.

**Comment by GrayHatter** [comment]
@utox/i18n new strings were added

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870#-:-KifR_v_bfpSOkD0YRUL:b-cs5rf)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 3 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/ui.c, line 338 at r2](https://reviewable.io:443/reviews/utox/utox/870#-Kiaqq4PFkbLeVI3nqrK:-KifT8PE3Jls6q0AvNiw:b-8f7mpj) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/ui.c#L338)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

There's some black magic with this button.
I don't know why, but only for english at DPI more than ~150% this button breaks (cut last couple of pixels).

I checked any other language - the problem is gone.
I tried change text on this button - the problem is gone.
</blockquote></details>

OK, It's not blocking, but let me know if you need me to take a look at it too.

---

*[src/layout/friend.c, line 123 at r2](https://reviewable.io:443/reviews/utox/utox/870#-KifTal1ywM6VoBPafwW:-KifTal22M5LXJKnnpAL:b-5ngyrs) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/layout/friend.c#L123)):*
> ```C
>     setcolor(COLOR_MAIN_TEXT_SUBTEXT);
>     setfont(FONT_TEXT);
>     drawstr(x + SCALE(10), SCALE(MAIN_TOP + 10), TOXID);
> ```

FYI https://github.com/uTox/uTox/issues/871

---

*[src/layout/settings.c, line 473 at r2](https://reviewable.io:443/reviews/utox/utox/870#-KifSHm7op-g56D5EUmu:-KifSHm7op-g56D5EUmv:b-b4cwi8) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/layout/settings.c#L473)):*
> ```C
> 
> static void update_show_nospam_button_text(void) {
>     if(panel_nospam_settings.disabled) {
> ```

as pedantic as this is, I'm going to require 1TBS https://en.wikipedia.org/wiki/Indent_style#Variant:_1TBS_.28OTBS.29

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870#-:-KifTgmlJqQGRJk_9KGS:bg7igkv)*

**Comment by GrayHatter** [comment]
@robinlinden or @endoffile78 

your turn

**Comment by robinlinden** [comment]
Reviewed 3 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/layout/friend.c, line 123 at r2](https://reviewable.io:443/reviews/utox/utox/870#-KifTal1ywM6VoBPafwW:-Kifl_WAgAtt-gIejjnf:b-dia6sg) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/layout/friend.c#L123)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

FYI https://github.com/uTox/uTox/issues/871
</blockquote></details>

I'm a little confused; should I use function arguments (x, y) don't?
So everywhere in functions it should be `drawstr(x + SCALE(10), y + SCALE(70), TOXID);`
or `drawstr(SCALE(10), SCALE(70), TOXID);`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/ui.c, line 338 at r2](https://reviewable.io:443/reviews/utox/utox/870#-Kiaqq4PFkbLeVI3nqrK:-KifmGnTAJbFYfP6qSo_:b-la6hhm) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/ui.c#L338)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

OK, It's not blocking, but let me know if you need me to take a look at it too.
</blockquote></details>

I've given up at this one, so if you could spare some time, it would be really helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/ui.c, line 338 at r2](https://reviewable.io:443/reviews/utox/utox/870#-Kiaqq4PFkbLeVI3nqrK:-KifnMcnuwqQzjw-GSSI:b-wc0fdb) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/ui.c#L338)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

I've given up at this one, so if you could spare some time, it would be really helpful.
</blockquote></details>

cool, I'll look at it next time I'm in this code. For now this LGTM 

---

*[src/layout/friend.c, line 123 at r2](https://reviewable.io:443/reviews/utox/utox/870#-KifTal1ywM6VoBPafwW:-Kifmrghk4zQSnCOWttw:bfqtiua) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/layout/friend.c#L123)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

I'm a little confused; should I use function arguments (x, y) don't?
So everywhere in functions it should be `drawstr(x + SCALE(10), y + SCALE(70), TOXID);`
or `drawstr(SCALE(10), SCALE(70), TOXID);`
</blockquote></details>

you don't have to do anything here. It was broken before, and you made it a bit better. I only commented with that issue so everyone is aware that we're trying to get away from ROOT offsets. 

In this case you should do nothing because it's out of scope for this pull request. (OOS) I just want everyone to know if they touch or move this code, they shouldn't try to keep `MAIN_TOP` because eventually it will go away :grin: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by redmanmale** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/layout/settings.c, line 473 at r2](https://reviewable.io:443/reviews/utox/utox/870#-KifSHm7op-g56D5EUmu:-KifngFBHoK6WBgyVOYO:b-896fix) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/layout/settings.c#L473)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

as pedantic as this is, I'm going to require 1TBS https://en.wikipedia.org/wiki/Indent_style#Variant:_1TBS_.28OTBS.29
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by GrayHatter** [comment]
Travis fails on the chrono test, we can ignore that failure because @endoffile78 is fixing that issue in #864

**Comment by GrayHatter** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/layout/settings.c, line 473 at r2](https://reviewable.io:443/reviews/utox/utox/870#-KifSHm7op-g56D5EUmu:-KifoBQPlxtRyPFfnVzZ:b-3av3n4) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/layout/settings.c#L473)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you also need a space between the if and the (, here and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by redmanmale** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/layout/settings.c, line 473 at r2](https://reviewable.io:443/reviews/utox/utox/870#-KifSHm7op-g56D5EUmu:-KifpQLPNvYLKDVLspYT:b-896fix) ([raw file](https://github.com/utox/utox/blob/feaf7469cc71229f6f0013a34586ad4e11c2a6f1/src/layout/settings.c#L473)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

you also need a space between the if and the (, here and below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870#-:-Kifway4Lpjr8I82sSdn:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 4 of 5 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870#-:-KihlSivS95svZdqRj6v:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/870#-:-KinF9CsMU__1x5OdPBz:bnfp4nl)*

**Comment by redmanmale** [comment]
If I would merge this via GitHub would this merge-commit be signed? Or I have to merge this via git and push?

I've just never faced with this before.

**Comment by robinlinden** [comment]
You have to merge on the cmdline. :P If you're not sure about it, just
leave it and I'll merge it after work or walk you through how to do it.

**Pull request merged**
