### PR TITLE
Refactor commands

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/524)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/command_funcs.c, line 20 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWX6kpIEIFDZ7RlmzX:-KYWX6kqDGkNhSa7Vgsw:b-qy48a9) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/command_funcs.c#L20)):*
> ```C
> bool slash_device(void *object, char *arg, int UNUSED(arg_length)) {
>     FRIEND *f =  object;
>     uint8_t id[TOX_FRIEND_ADDRESS_SIZE * 2];
> ```

Is it intentional that this is the only variable of the size `TOX_FRIEND_ADDRESS_SIZE * 2` and all the others are `TOX_FRIEND_ADDRESS_SIZE`?

---

*[src/command_funcs.c, line 59 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWU93oPL1xKMe4cTwR:-KYWU93pUNVDX8iSdAYo:bx02q0o) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/command_funcs.c#L59)):*
> ```C
> bool slash_topic(void *object, char *arg, int arg_length) {
>     GROUPCHAT *g = object;
>     void *d = malloc(arg_length);
> ```

May want to check this allocation succeeded.

---

*[src/commands.h, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWT73oD5plUznKl0UI:-KYWT73pFFvFRywATec5:b-brpwur) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/commands.h#L4)):*
> ```objc
> #define COMMANDS_H
> 
> #include "friend.h"
> ```

Can be moved to commands.c

---

*[src/ui/edits.c, line 84 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWStnpI3Gh15vd0IUo:-KYWStnpI3Gh15vd0IUp:b-7qqe9u) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/ui/edits.c#L84)):*
> ```C
>     // debug("cmd %u\n", command_length);
> 
>     bool action = 0;
> ```

false

---

*[src/ui/edits.c, line 90 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWSsnRfwePf9SHcd4r:-KYWSsnSQavWLAkpNyqm:bb7pcsz) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/ui/edits.c#L90)):*
> ```C
>         if ((command_length == 2) && (!memcmp(command, "me", 2))) {
>             if (argument) {
>                 action = 1;
> ```

true

---

*[src/ui/edits.c, line 113 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWV6S7rkeaSq7p_yjq:-KYWV6S7rkeaSq7p_yjr:bx02q0o) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/ui/edits.c#L113)):*
> ```C
>     } else if (flist_get_selected()->item == ITEM_GROUP) {
>         GROUPCHAT *g = flist_get_selected()->data;
>         void *d = malloc(length);
> ```

May want to check this allocation succeeded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524)*

**Comment by endoffile78** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/command_funcs.c, line 20 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWX6kpIEIFDZ7RlmzX:-KYWe4p8LZQhZ03Rhv5S:b-hq30md) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/command_funcs.c#L20)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Is it intentional that this is the only variable of the size `TOX_FRIEND_ADDRESS_SIZE * 2` and all the others are `TOX_FRIEND_ADDRESS_SIZE`?
</blockquote></details>

I'm not sure why its that why, we'll have to ask @GrayHatter.

---

*[src/command_funcs.c, line 59 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWU93oPL1xKMe4cTwR:-KYWe0vYpDhZJ8LqhYcH:b-896fix) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/command_funcs.c#L59)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

May want to check this allocation succeeded.
</blockquote></details>

Done.

---

*[src/commands.h, line 4 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWT73oD5plUznKl0UI:-KYWe2AfllONoJVaDowO:b-896fix) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/commands.h#L4)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Can be moved to commands.c
</blockquote></details>

Done.

---

*[src/ui/edits.c, line 84 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWStnpI3Gh15vd0IUo:-KYWe31Bfwtgfv9O9Y_p:b-896fix) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/ui/edits.c#L84)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

false
</blockquote></details>

Done.

---

*[src/ui/edits.c, line 90 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWSsnRfwePf9SHcd4r:-KYWe3OB9W-QwTgumtd1:b-896fix) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/ui/edits.c#L90)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

true
</blockquote></details>

Done.

---

*[src/ui/edits.c, line 113 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWV6S7rkeaSq7p_yjq:-KYWe4D22kT9wVu7SmHJ:b-896fix) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/ui/edits.c#L113)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

May want to check this allocation succeeded.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 6 files at r1, 2 of 3 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/command_funcs.c, line 20 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWX6kpIEIFDZ7RlmzX:-KY_0Hzinwl2wE7W7x_z:bm97o7i) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/command_funcs.c#L20)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

I'm not sure why its that why, we'll have to ask @GrayHatter.
</blockquote></details>

'cause reasons?

This converts a hex string to the bin array that toxcore wants. This is correct

---

*[src/command_funcs.c, line 1 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_49doX6eEIqY2D3LH:-KY_49doX6eEIqY2D3LI:bo9yst2) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/command_funcs.c#L1)):*
> ```C
> #include "command_funcs.h"
> ```

Through out this file, I'd rather handle the successful malloc as the if, and return true. Then make the error case the default. Your call @endoffile78 

---

*[src/commands.c, line 1 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_1CDFRNYG9tGPw1q3:-KY_1CDFRNYG9tGPw1q4:b-2l92xj) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/commands.c#L1)):*
> ```C
> // commands.c
> ```

Net change -40 LOC... no change in function... http://i.imgur.com/AxNFauH.gif

---

*[src/ui/edits.c, line 77 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_3FxiIkuP5pcePdYs:-KY_3FxiIkuP5pcePdYt:b-jedgzj) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/ui/edits.c#L77)):*
> ```C
> 
>     // TODO: Magic number
>     if (command_length == 65535) {
> ```

sub  -1 for 65535 or UINT16_MAX

---

*[src/ui/edits.c, line 117 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_26bH3TQ-S30dlEaK:-KY_26bH3TQ-S30dlEaL:bj61ycu) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/ui/edits.c#L117)):*
> ```C
>             memcpy(d, text, length);
>             postmessage_toxcore((action ? TOX_GROUP_SEND_ACTION : TOX_GROUP_SEND_MESSAGE), (g - group), length, d);
>         }
> ```

FYI Silent failure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524)*

**Comment by endoffile78** [comment]
Review status: 4 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/command_funcs.c, line 20 at r1](https://reviewable.io:443/reviews/utox/utox/524#-KYWX6kpIEIFDZ7RlmzX:-KY_amfiAMI-Isor29hk:b2nhll9) ([raw file](https://github.com/utox/utox/blob/1f482704c027a0b51bb4c3a12143b8b01ec9c4b2/src/command_funcs.c#L20)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

'cause reasons?

This converts a hex string to the bin array that toxcore wants. This is correct
</blockquote></details>

Ok.

---

*[src/command_funcs.c, line 1 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_49doX6eEIqY2D3LH:-KY_aqxCNqvZrSCC8its:b-896fix) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/command_funcs.c#L1)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Through out this file, I'd rather handle the successful malloc as the if, and return true. Then make the error case the default. Your call @endoffile78 
</blockquote></details>

Done.

---

*[src/commands.c, line 1 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_1CDFRNYG9tGPw1q3:-KY_arixWmALu09sMkDp:b2ni78k) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/commands.c#L1)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Net change -40 LOC... no change in function... http://i.imgur.com/AxNFauH.gif
</blockquote></details>

lol

---

*[src/ui/edits.c, line 77 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_3FxiIkuP5pcePdYs:-KY_auRRv_vKpO9iVuWP:b-896fix) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/ui/edits.c#L77)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

sub  -1 for 65535 or UINT16_MAX
</blockquote></details>

Done.

---

*[src/ui/edits.c, line 117 at r2](https://reviewable.io:443/reviews/utox/utox/524#-KY_26bH3TQ-S30dlEaK:-KY_bOUDjmE6mEpgXhES:b-896fix) ([raw file](https://github.com/utox/utox/blob/f940babb630072d22ff5f132449adf6fd516e0bb/src/ui/edits.c#L117)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

FYI Silent failure
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524#-:-KYdTpXQzldFSEMlCxEa:bnfp4nl)*

**Comment by GrayHatter** [comment]
+@grayhatter 

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/command_funcs.c, line 30 at r3](https://reviewable.io:443/reviews/utox/utox/524#-KYf-M3wftdNTE6VqtkZ:-KYf-M3wftdNTE6Vqtk_:b-u6ehf6) ([raw file](https://github.com/utox/utox/blob/1b6751fb083ab9ab3aab7624733e34bf68c96687/src/command_funcs.c#L30)):*
> ```C
>         return true;
>     }
>     debug("slash_device:\t Could not allocate memory.\n");
> ```

_error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524#-:-KYf-d3dJw7fxE5Z2PO7:b-joyoeb)*

**Comment by GrayHatter** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524#-:-KYfa_lgl3QLWIesAKvK:b-uwkowd)*

**Comment by endoffile78** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/command_funcs.c, line 30 at r3](https://reviewable.io:443/reviews/utox/utox/524#-KYf-M3wftdNTE6VqtkZ:-KYgOYiMDZp_WPhcKlMf:b-896fix) ([raw file](https://github.com/utox/utox/blob/1b6751fb083ab9ab3aab7624733e34bf68c96687/src/command_funcs.c#L30)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

_error
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/524#-:-KYlNCA_jyWlvCSGfmxI:bnfp4nl)*

**Pull request merged**
