### PR TITLE
Add DEPENDENCIES.md

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1230)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1230#-:-LDcMPSB357ctobyjTH7:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1230#-:-LDcN4FH1EWvsaE6Sdgy:bnfp4nl)*

**Comment by endoffile78** [comment]
@publicarray Can you make sure all the OSX dependencies are listed.

**Comment by publicarray** [comment]
:lgtm: on MacOS. Just one question, aren't we missing libsodium?

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1230#-:-LDfityC0Z_Zf4GwzJYm:b-swdl4n)*

**Comment by publicarray** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1230#-:-LE3bIgVB577R1djXF5H:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1230#-:-LF7ODNs47DSM7nkMIz6:bnfp4nl)*

**Pull request merged**
