### PR TITLE
Add --allow-root option

### LINKED ISSUE #587: uTox should not run as root unless specified.
perhaps `--allow-root`

### PR DESCRIPTION
**Pull request by endoffile78**
Closes #587

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1102)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 830 at r1](https://reviewable.io:443/reviews/utox/utox/1102#-KxJW_I7B9XT4PgxRnvb:-KxJW_I7B9XT4PgxRnvc:bo5y2wo) ([raw file](https://github.com/utox/utox/blob/c9e755b43d1da4f6b19f483079cd008eeacca93d/src/windows/main.c#L830)):*
> ```C
>     int8_t should_launch_at_startup, set_show_window;
>     bool   skip_updater, allow_root;
>     parse_args(argc, argv, &skip_updater, &should_launch_at_startup, &set_show_window, &allow_root);
> ```

allow_root is meaninless on windows, pass NULL instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1102)*

**Comment by endoffile78** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 830 at r1](https://reviewable.io:443/reviews/utox/utox/1102#-KxJW_I7B9XT4PgxRnvb:-KxJqdr9C8Y96dz4vyVo:b-896fix) ([raw file](https://github.com/utox/utox/blob/c9e755b43d1da4f6b19f483079cd008eeacca93d/src/windows/main.c#L830)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

allow_root is meaninless on windows, pass NULL instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1102)*

**Comment by robinlinden** [comment]
The code all looks good, but I don't think this is a thing uTox needs or should have. I don't mind enough to block it, but I think it's complexity for no benefit.

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.c, line 132 at r2](https://reviewable.io:443/reviews/utox/utox/1102#-KxUfyoojBjUdbhYkVVs:-KxUfyoojBjUdbhYkVVt:b-nuxtrj) ([raw file](https://github.com/utox/utox/blob/d6cdba479413a6bd7c731512860b84950fd82479/src/main.c#L132)):*
> ```C
>         { "verbose", no_argument, NULL, 'v' },          { "help", no_argument, NULL, 'h' },
>         { "debug", required_argument, NULL, 1 },        { "allow-root", no_argument, NULL, 2 },
> 		{ 0, 0, 0, 0 }
> ```

These tabs should be spaces.

---

*[src/main.h, line 71 at r2](https://reviewable.io:443/reviews/utox/utox/1102#-KxUg2Q-BjUWSCCPoJR1:-KxUg2Q-BjUWSCCPoJR2:bdo3k2x) ([raw file](https://github.com/utox/utox/blob/d6cdba479413a6bd7c731512860b84950fd82479/src/main.h#L71)):*
> ```objc
>                 int8_t *should_launch_at_startup,
>                 int8_t *set_show_window,
> 	            bool *allow_root);
> ```

This tab should be spaces.

---

*[src/cocoa/main.m, line 533 at r2](https://reviewable.io:443/reviews/utox/utox/1102#-KxUg6s-v-SXJVhjRX64:-KxUg6s-v-SXJVhjRX65:bnqm2jw) ([raw file](https://github.com/utox/utox/blob/d6cdba479413a6bd7c731512860b84950fd82479/src/cocoa/main.m#L533)):*
> ```objc
> 
>     if (getuid() == 0 && !allow_root) {
>         LOG_FATAL_ERR(EXIT_FAILURE, "XLIB MAIN", "You can't run uTox as root unless --allow-root is set.");
> ```

"XLIB MAIN"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1102#-:-KxUgEyLvuB3IURmyhGB:b-1hokm3)*

**Comment by endoffile78** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.c, line 132 at r2](https://reviewable.io:443/reviews/utox/utox/1102#-KxUfyoojBjUdbhYkVVs:-KxZwplO4qwRU02ai-Qe:b-896fix) ([raw file](https://github.com/utox/utox/blob/d6cdba479413a6bd7c731512860b84950fd82479/src/main.c#L132)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

These tabs should be spaces.
</blockquote></details>

Done.

---

*[src/main.h, line 71 at r2](https://reviewable.io:443/reviews/utox/utox/1102#-KxUg2Q-BjUWSCCPoJR1:-KxZwqRHG9M2yPiMPFHh:b-896fix) ([raw file](https://github.com/utox/utox/blob/d6cdba479413a6bd7c731512860b84950fd82479/src/main.h#L71)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This tab should be spaces.
</blockquote></details>

Done.

---

*[src/cocoa/main.m, line 533 at r2](https://reviewable.io:443/reviews/utox/utox/1102#-KxUg6s-v-SXJVhjRX64:-KxZwr8mQTYNjIZj5er_:b-896fix) ([raw file](https://github.com/utox/utox/blob/d6cdba479413a6bd7c731512860b84950fd82479/src/cocoa/main.m#L533)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

"XLIB MAIN"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1102)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1102#-:-Kx_5L_t4659KNBbqyEV:bnfp4nl)*

**Pull request merged**
