### PR TITLE
UI refactor to make things cool and stuff

### LINKED ISSUE #810: Interface glitches after changing DPI
**Steps to reproduce**
* Open uTox
* Change DPI

**Notes**
No matter increase or decrease DPI, it reproduces anyway. It looks like this:
pic

After window resize or move (when it's redrawn) everything is OK.

**Env**
Win 7 x86, x64, uTox v.0.14.0

### PR DESCRIPTION
**Pull request by GrayHatter**
fixes #810 

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/842)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 24 of 24 files at r1, 1 of 10 files at r2.
Review status: 16 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/842#-:-Ki2C53ez5n9WQ9FgOcR:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/842#-:-Ki2CLoPTBVys_yQ1hQk:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 15 of 24 files at r1, 10 of 10 files at r2, 1 of 3 files at r3.
Review status: 24 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/842)*

**Comment by redmanmale** [comment]
On Ubuntu 16.04 there's a glitch of status icon:
pic

**Comment by robinlinden** [comment]
New (and only) warning when compiling this on Windows.
```
/cygdrive/d/Projects/Tox/uTox/src/windows/main.7.c: In function ‘launch_at_startup’:
/cygdrive/d/Projects/Tox/uTox/src/windows/main.7.c:142:56: warning: passing argument 3 of ‘RegSetKeyValueW’ from incompatible pointer type [-Wincompatible-pointer-types]
             uint16_t ret = RegSetKeyValueW(hKey, NULL, L"uTox", REG_SZ, path, path_length * 2);
                                                        ^
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/windows.h:76:0,
                 from /cygdrive/d/Projects/Tox/uTox/src/windows/main.h:30,
                 from /cygdrive/d/Projects/Tox/uTox/src/windows/main.7.c:7:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/winreg.h:371:23: note: expected ‘LPCSTR {aka const char *}’ but argument is of type ‘short unsigned int *’
 WINADVAPI LONG WINAPI RegSetKeyValueW(
                       ^
```

**Comment by GrayHatter** [comment]
@redmanmale do the size of the UI glitches with the buttons change with the DPI?

**Comment by redmanmale** [comment]
@GrayHatter 
Size of glitches is corresponding with controls.
Higher DPI => bigger controls => bigger absolute size of glitches, but relative size is the same.

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/842#-:-KiGyHX6EoF6B362uCgb:bnfp4nl)*

**Pull request merged**
