### PR TITLE
Add sign-release.sh and checksum.sh

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/607)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/sign-release.sh, line 8 at r1](https://reviewable.io:443/reviews/utox/utox/607#-KaGnRURCntWWLF-02vW:-KaGnRURCntWWLF-02vX:b-w9expc) ([raw file](https://github.com/utox/utox/blob/d0dd5ab32d055a12c7825c910a023392271c59a1/tools/sign-release.sh#L8)):*
> ```Shell
> curl -O "https://github.com/uTox/uTox/archive/$TAG.zip" -O "https://github.com/uTox/uTox/archive/$TAG.tar.gz"
> 
> gpg --armor --detach-sign "$TAG.zip"
> ```

this should also untar and unzip, in to the working directory (you can assume it's `cwd`) and then exit on `git diff --exit-code`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607)*

**Comment by endoffile78** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/sign-release.sh, line 8 at r1](https://reviewable.io:443/reviews/utox/utox/607#-KaGnRURCntWWLF-02vW:-KaJytt_-SDNhi6FmSBq:b-896fix) ([raw file](https://github.com/utox/utox/blob/d0dd5ab32d055a12c7825c910a023392271c59a1/tools/sign-release.sh#L8)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this should also untar and unzip, in to the working directory (you can assume it's `cwd`) and then exit on `git diff --exit-code`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607)*

**Comment by GrayHatter** [comment]
+@grayhatter 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaLlHehNesyt-AlqaYw:b-joyoeb)*

**Comment by GrayHatter** [comment]
see more-scripts on uTox/ I added a commit but couldn't push to your repo.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaM0H71TMz9O8ALncPS:b-i1dy3m)*

**Comment by endoffile78** [comment]
@GrayHatter merged.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaOltEq0zWdMrkR_cfy:b45xifa)*

**Comment by GrayHatter** [comment]
:lgtm: but we need another +1 because I wrote half of this code

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaOnU-XYOA7TzkJeAQc:b-8fsakw)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/sign-release.sh, line 4 at r3](https://reviewable.io:443/reviews/utox/utox/607#-KaOqn4DffagWEX7YAhe:-KaOqn4EJKzE05M0Rs-6:b57bq54) ([raw file](https://github.com/utox/utox/blob/ca0fdcf2e64cb87bbe6f6b500aab925193594b26/tools/sign-release.sh#L4)):*
> ```Shell
> # set -e
> TAG=$(git describe --abbrev=0 --tags)
> USER=$(git config --get user.name)
> ```

user.name will be something like `Carsten Brandt` or `Gregory Mullen (grayhatter)`. this does not really fit well for the file name.
This should be possible to give as an argument for the script or use `whoami` command, which would fit in my case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607)*

**Comment by GrayHatter** [comment]
*[tools/sign-release.sh, line 4 at r3](https://reviewable.io:443/reviews/utox/utox/607#-KaOqn4DffagWEX7YAhe:-KaOvCGv5frGxi0UQRVr:b-5pgii8) ([raw file](https://github.com/utox/utox/blob/ca0fdcf2e64cb87bbe6f6b500aab925193594b26/tools/sign-release.sh#L4)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

user.name will be something like `Carsten Brandt` or `Gregory Mullen (grayhatter)`. this does not really fit well for the file name.
This should be possible to give as an argument for the script or use `whoami` command, which would fit in my case.
</blockquote></details>

this is missing my addition... I fixed this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607)*

**Comment by cebe** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaOxDaZ_Cw_WpaLImbT:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaRPPXCHDWOfWQj01Nb:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaRQxhT-BlQ08BqZFtB:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/607#-:-KaRSx0U3J6jVMJ2JxDP:bnfp4nl)*

**Pull request merged**
