### PR TITLE
Fix a lot of the issues found on coverity.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/797)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/filesys.c, line 21 at r1](https://reviewable.io:443/reviews/utox/utox/797#-Kh9ScZVc_gOkxKlG_o_:-Kh9ScZWLJQEkxk_efu1:b5okskc) ([raw file](https://github.com/utox/utox/blob/bef532112973e2a9c71190e276003ef8907b01c6/src/filesys.c#L21)):*
> ```C
> }
> 
> void *file_raw(char *path, uint32_t *size) {
> ```

fyi https://github.com/uTox/uTox/issues/798

---

*[src/friend.c, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/797#-Kh9TkPmYx5_v4CCkEIQ:-Kh9TkPmYx5_v4CCkEIR:bo74wi5) ([raw file](https://github.com/utox/utox/blob/3f925662bd4bf737872ea1885fed26d2837aa470/src/friend.c#L357)):*
> ```C
>         memcpy(f->alias, alias, length);
>         f->alias_length           = length;
>         f->alias[f->alias_length] = 0;
> ```

why was this dropped?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/797#-:-Kh9UcsPQK8WJjQd2QGB:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/797#-:-Kh9XZ2yeJFbE5HzkBeX:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/filesys.c, line 21 at r1](https://reviewable.io:443/reviews/utox/utox/797#-Kh9ScZVc_gOkxKlG_o_:-Kh9XV15ayJH5UCsF41t:bgnek3r) ([raw file](https://github.com/utox/utox/blob/bef532112973e2a9c71190e276003ef8907b01c6/src/filesys.c#L21)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fyi https://github.com/uTox/uTox/issues/798
</blockquote></details>

Will open a second PR doing that unless someone beats me to it. 

---

*[src/friend.c, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/797#-Kh9TkPmYx5_v4CCkEIQ:-Kh9XDN94Lql2ttUSvXE:btrudr0) ([raw file](https://github.com/utox/utox/blob/3f925662bd4bf737872ea1885fed26d2837aa470/src/friend.c#L357)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why was this dropped?
</blockquote></details>

`calloc` zeros it for us. I can add it back if you want to make it extra clear that it's a null-terminated string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/797)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/friend.c, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/797#-Kh9TkPmYx5_v4CCkEIQ:-Kh9dfDhwsnQDRNCD6yj:bdwyj1d) ([raw file](https://github.com/utox/utox/blob/3f925662bd4bf737872ea1885fed26d2837aa470/src/friend.c#L357)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`calloc` zeros it for us. I can add it back if you want to make it extra clear that it's a null-terminated string.
</blockquote></details>

nope, we're good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/797)*

**Pull request merged**
