### PR TITLE
Release 0.16.0.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/937)

### CODE REVIEW

**Comment by robinlinden** [comment]
What needs to be done before this can be merged is as follows:
1. Fix OS X with asan (or disable it on OS X again for now.)
1. Any actions that restart the Toxcore thread are broken. This absolutely needs to be fixed before we can do a release.

**Comment by v2e** [comment]
As the title states, this pull request is related to the new version of uTox. Could you please notify the translators if there are some new strings to be translated before the actual release?

**Comment by robinlinden** [comment]
@v2e You're right. I completely forgot about that. Thank you!

@uTox/i18n PTAL at the 3 new strings added to https://github.com/uTox/uTox/blob/develop/langs/en.h
(HIDE_UI_PASSWORD, HIDE_UI_PASSWORD_TOOLTIP, and HIDE_NOSPAM.)

**Comment by sfan5** [comment]
Just wanna leave a note here that
<pre>
msgid(DELETE_MESSAGE)
msgstr("Are you sure you want to delete ")
</pre>
is absolute shit for translating. Where are my format strings?

**Comment by robinlinden** [comment]
@sfan5 Agreed. I thought about too when fixing up the Swedish translations earlier today. :(

**Comment by v2e** [comment]
@robinlinden Just two small points:

- The Ukrainian [language code](http://www.loc.gov/standards/iso639-2/php/code_list.php) should be "uk", not "ua" (in the filename). It is often confused with the county code "uk" for United Kingdom.
- What about the version name and changelog text for v.0.16?

**Comment by robinlinden** [comment]
@v2e Thanks! See #977 

The version name and changelog are pending until we're ready to make a release. I have a draft done in the [release list](https://github.com/uTox/uTox/releases) if you want to have a look. (They need to be updated again since we've merged features since the release started being prepped.)

**Comment by v2e** [comment]
@robinlinden I can see only "uTox v0.15.0 slowpoke" on the [release list](https://github.com/uTox/uTox/releases). As far as I understand, this is for the previous release. Maybe, the draft is not visible for all users? In any case, it would be great if I were able to update the translation before the 0.16 release.

**Comment by robinlinden** [comment]
@v2e Oh, right. I thought you were a member of the uTox org. I'll try to put together a complete changelog ASAP (likely tomorrow) so you can translate that too if you want.

**Comment by redmanmale** [comment]
@robinlinden 
I'll be glad to translate changelog into Russian.

**Comment by robinlinden** [comment]
We'll do a feature-freeze sooner next release so everything is ready when we open the version bump PR.

**Comment by GrayHatter** [comment]
@sfan5 @robinlinden there's no reason we can't use %s inside translations.

We'd just have to make a 2nd string macro/function to do the formatting before passing it to the gui.

**Comment by robinlinden** [comment]
@GrayHatter We already do that. See the example I posted a few comments ago.

**Comment by robinlinden** [comment]
@uTox/i18n Added changelog and meme to the release PR.

@uTox/devs I'd appreciate it if you could have a quick look and let me know if I missed anything.

**Comment by endoffile78** [comment]
The version in the man file should be updated.

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/937#-:-Kq1H5wjhZKmTpbPbMoZ:bfuc6c3)*

**Comment by robinlinden** [comment]
@endoffile78 Good catch!

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/937#-:-KrDUG0_f3k2NSvnwSFO:bnfp4nl)*

**Comment by GrayHatter** [comment]
@robinlinden add the man.file to the cmake, so the cmake will auto generate the man.file

**Comment by robinlinden** [comment]
@GrayHatter I was planning to in a separate PR.

**Comment by redmanmale** [comment]
https://github.com/robinlinden/uTox/pull/3
Translate new changelog and add new strings.

**Comment by GrayHatter** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/937)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 2 of 3 files at r9, 1 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/937#-:-Ks0JFitEzKTjwRYlsL2:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/937#-:-Ks0JJLnhRPaq3d0FZHx:bnfp4nl)*

**Pull request merged**
