### PR TITLE
Warning fix

### PR DESCRIPTION
**Pull request by redmanmale**
Fix for #699.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/918)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/918#-:-KkTeC3YGVJvY2F6hEEb:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm: ... probably

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/918#-:-KkX_eiajrUbmTYVC_Jf:b-ur06e4)*

**Comment by redmanmale** [comment]
> probably

Is something wrong? Or I can merge this one?

**Comment by robinlinden** [comment]
:lgtm: You can merge it.

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/918#-:-KkXe4gvZJ9vkQIayAtp:b-h741xh)*

**Pull request merged**
