### PR TITLE
Password too short warning

### LINKED ISSUE #825: Add warning about password length minimum
Passwords must be at least four characters long but currently there is no way for the user to know without reading the source code.

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #825.

Show a message box with localized text when trying to set a password less then 4 characters. Clear password field after that.
Implemented for all platforms (except Android).

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1138)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1138#-:-L-AtWPjdPNpFMEzaUki:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1138#-:-L-ccIJuzzh_38HWQQO1:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/xlib/gtk.c, line 218 at r1](https://reviewable.io:443/reviews/utox/utox/1138#-L-rS87iBVNZu9aMMpka:-L-rS87iBVNZu9aMMpkb:b-tm1teu) ([raw file](https://github.com/utox/utox/blob/2dcf377373a5acf85806bdb309655e21a7f5b8db/src/xlib/gtk.c#L218)):*
> ```C
> }
> 
> void show_messagebox(const char *UNUSED(caption), uint16_t UNUSED(caption_length),
> ```

what happens when a user doesn't' have GTK installed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1138)*

**Comment by redmanmale** [comment]
I haven't add any new code for GTK handling.
And uTox will no work without GTK, right?

**Comment by GrayHatter** [comment]
uTox used to, and needs to work without GTK.

It will be missing features, but the reason we're loading GTK at run time is so uTox can work on systems with out GTK.

**Pull request merged**
