### PR TITLE
Fix save inline image dialog

### LINKED ISSUE #1000: Click to open doesn't work with inline images
**Steps to reproduce**
*    receive an inline image
*    save it
*    click on it to open

**Expected behavior**
Saved image should open.

**Actual behavior**
Folder with uTox.exe is opened.

**Env**
Win 7 x64, uTox v.0.16.0.

It looks a lot like this one #794.

### PR DESCRIPTION
**Pull request by redmanmale**
Allow Unicode path and update selected filename in UI.
Fix #1000.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1008)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/windows/main.c, line 191 at r1](https://reviewable.io:443/reviews/utox/utox/1008#-KtD4Yng-7sXCo6UnrWU:-KtD4Yng-7sXCo6UnrWV:b-9g142g) ([raw file](https://github.com/utox/utox/blob/38d3e017b4b91add8db49d205ebf1d4b985d1c32/src/windows/main.c#L191)):*
> ```C
>             fclose(file);
> 
>             msg->via.ft.path = calloc(1, UTOX_FILE_NAME_LENGTH);
> ```

Is `via.ft.path` empty for inlines? If not, this leaks whatever was in there before this assignent.

---

*[src/windows/main.c, line 192 at r1](https://reviewable.io:443/reviews/utox/utox/1008#-KtD5bR8_TCsF7XksKNT:-KtD5bR8_TCsF7XksKNU:bwfkw94) ([raw file](https://github.com/utox/utox/blob/38d3e017b4b91add8db49d205ebf1d4b985d1c32/src/windows/main.c#L192)):*
> ```C
> 
>             msg->via.ft.path = calloc(1, UTOX_FILE_NAME_LENGTH);
>             if(!msg->via.ft.path) {
> ```

Space between if and condition.

---

*[src/windows/main.c, line 198 at r1](https://reviewable.io:443/reviews/utox/utox/1008#-KtD4KlkJbQrrPOJQcZj:-KtD4KlkJbQrrPOJQcZk:b-hff9bb) ([raw file](https://github.com/utox/utox/blob/38d3e017b4b91add8db49d205ebf1d4b985d1c32/src/windows/main.c#L198)):*
> ```C
>             }
> 
>             snprintf((char *) msg->via.ft.path, UTOX_FILE_NAME_LENGTH, "%s", path);
> ```

You can copy the path over (if it's null-terminated) using `strdup`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1008)*

**Comment by redmanmale** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/windows/main.c, line 191 at r1](https://reviewable.io:443/reviews/utox/utox/1008#-KtD4Yng-7sXCo6UnrWU:-KtDP1Q8hxW-P3MKQsCy:b-dl7i2g) ([raw file](https://github.com/utox/utox/blob/38d3e017b4b91add8db49d205ebf1d4b985d1c32/src/windows/main.c#L191)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Is `via.ft.path` empty for inlines? If not, this leaks whatever was in there before this assignent.
</blockquote></details>

If I got it right it's null in case of inline.
https://github.com/uTox/uTox/blob/develop/src/messages.c#L379

But I could check for null before this assignment.

---

*[src/windows/main.c, line 192 at r1](https://reviewable.io:443/reviews/utox/utox/1008#-KtD5bR8_TCsF7XksKNT:-KtDKS_6GPuIXLMSETRB:b-896fix) ([raw file](https://github.com/utox/utox/blob/38d3e017b4b91add8db49d205ebf1d4b985d1c32/src/windows/main.c#L192)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Space between if and condition.
</blockquote></details>

Done.

---

*[src/windows/main.c, line 198 at r1](https://reviewable.io:443/reviews/utox/utox/1008#-KtD4KlkJbQrrPOJQcZj:-KtDLg_EL62AmfYj1UXg:b-896fix) ([raw file](https://github.com/utox/utox/blob/38d3e017b4b91add8db49d205ebf1d4b985d1c32/src/windows/main.c#L198)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You can copy the path over (if it's null-terminated) using `strdup`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1008)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/windows/main.c, line 191 at r1](https://reviewable.io:443/reviews/utox/utox/1008#-KtD4Yng-7sXCo6UnrWU:-KtDTM-RvLScFeEW8uv1:br8u2tu) ([raw file](https://github.com/utox/utox/blob/38d3e017b4b91add8db49d205ebf1d4b985d1c32/src/windows/main.c#L191)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

If I got it right it's null in case of inline.
https://github.com/uTox/uTox/blob/develop/src/messages.c#L379

But I could check for null before this assignment.
</blockquote></details>

No need to check. You're right.

---

*[src/windows/main.c, line 199 at r2](https://reviewable.io:443/reviews/utox/utox/1008#-KtDSaUNKgWwxNmHUILx:-KtDSaUNKgWwxNmHUILy:b8iu9d2) ([raw file](https://github.com/utox/utox/blob/7d025064ae5530a3903909a37f3a12a698ad4086/src/windows/main.c#L199)):*
> ```C
> 
>             msg->via.ft.path = (uint8_t *)strdup(path);
>             msg->via.ft.name = basename((char *) msg->via.ft.path);
> ```

I just realised that this can clobber via.ft.path, so if it's used anywhere else you need to make a copy to give to basename.

See e.g. musl libc's implementation for an example that actually does clobber the string you pass to `basename`: http://git.musl-libc.org/cgit/musl/tree/src/misc/basename.c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1008)*

**Comment by redmanmale** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 199 at r2](https://reviewable.io:443/reviews/utox/utox/1008#-KtDSaUNKgWwxNmHUILx:-KtDWZVc0Wk7YAFzvACh:b-896fix) ([raw file](https://github.com/utox/utox/blob/7d025064ae5530a3903909a37f3a12a698ad4086/src/windows/main.c#L199)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I just realised that this can clobber via.ft.path, so if it's used anywhere else you need to make a copy to give to basename.

See e.g. musl libc's implementation for an example that actually does clobber the string you pass to `basename`: http://git.musl-libc.org/cgit/musl/tree/src/misc/basename.c
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1008)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1008)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1008#-:-KtHl0cea3wefBdJP1KS:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1008#-:-KtIeaIXGZ7HSq9G6r7R:bnfp4nl)*

**Pull request merged**
