### PR TITLE
Fix language-selection dropdown having multiple English languages and none of others.

### LINKED ISSUE #563: Language selector shows multiple options for english
bildschirmfoto von 2016-12-21 10 53 30

### PR DESCRIPTION
**Pull request by robinlinden**
Fixes #563 

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/564)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/564#-:-KZVrYNBianbufCQXndF:bnfp4nl)*

**Comment by cebe** [comment]
yep, that fixes it!

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/564#-:-KZWuMO49AX_sbxZlydE:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/564)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/564#-:-KZi-Ln4Bg8Zi9-yAaJJ:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/564#-:-KZi-VtGUJKz8Q1lEObp:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/564#-:-KZi0MkmEQGucZQYJa70:bnfp4nl)*

**Pull request merged**
