### PR TITLE
Groupchat creating page

### PR DESCRIPTION
**Pull request by redmanmale**
I think that separate page is much butter to use than current right-click-and-context-menu thing.

It looks like this:
pic

There are old strings that will be updated in groupchat accept invite PR.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1087)

### CODE REVIEW

**Comment by GrayHatter** [comment]
This is clearly better. We should merge this!

Should we simply detect if there's an existing empty groupchat, if so show the add audio toggle at the top of the group chat screen. And then once they try to add a user to it, only then mark it as used, and send the command to toxcore to create the group. Then followed by inviting that user?

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/ui.c, line 338 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfGycImbGVWu-Sypni:-KwfGycImbGVWu-Sypnj:be6j1rh) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/ui.c#L338)):*
> ```C
>     CREATE_BUTTON(deny_deletion,    110, MAIN_TOP + 40, _BM_SBUTTON_WIDTH, _BM_SBUTTON_HEIGHT);
> 
>     group_create_draw();
> ```

per other comments, delete this line.

---

*[src/layout/group.c, line 28 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfH2eFOc7Q20_ZTTd-:-KwfH2eFOc7Q20_ZTTd0:b-rtagwg) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L28)):*
> ```C
> #include <tox/tox.h>
> 
> static void draw_group_create(int x, int y, int UNUSED(width), int UNUSED(height));
> ```

delete

---

*[src/layout/group.c, line 104 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfH3fN2oyfvLwypaLy:-KwfH3fN2oyfvLwypaLz:b-rtagwg) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L104)):*
> ```C
> }
> 
> void group_create_draw() {
> ```

delete

---

*[src/layout/group.c, line 584 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfHrmm1oW_i8D8zMrI:-KwfHrmm1oW_i8D8zMrJ:b-q1jvjq) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L584)):*
> ```C
> };
> 
> BUTTON button_create_group = {
> ```

add the size settings to the `.panel` struct here

https://github.com/uTox/uTox/blob/develop/src/layout/settings.c#L911 is the new "correct" way of adding UI systems

---

*[src/layout/group.c, line 592 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfHtGb6HpYb_xQIRvH:-KwfHtGb6HpYb_xQIRvI:bdvthiw) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L592)):*
> ```C
> };
> 
> UISWITCH switch_group_type = {
> ```

add the UI size stuff here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KwfIQlVLUYptWSaqtFP:b-vorz12)*

**Comment by endoffile78** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087)*

**Comment by redmanmale** [comment]
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/layout/group.c, line 28 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfH2eFOc7Q20_ZTTd-:-Kwg-vwT4HlcbzJCifxt:b-896fix) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L28)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

---

*[src/layout/group.c, line 104 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfH3fN2oyfvLwypaLy:-Kwg-wiS7SWZnwSbS-GK:b-896fix) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L104)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

---

*[src/layout/group.c, line 584 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfHrmm1oW_i8D8zMrI:-Kwg-xb6Y_gs_bYGDPMt:b-896fix) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L584)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

add the size settings to the `.panel` struct here

https://github.com/uTox/uTox/blob/develop/src/layout/settings.c#L911 is the new "correct" way of adding UI systems
</blockquote></details>

Done.

---

*[src/layout/group.c, line 592 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfHtGb6HpYb_xQIRvH:-Kwg-yNP6b6LPEy0J-tR:b-896fix) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L592)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

add the UI size stuff here too.
</blockquote></details>

Done.

---

*[src/ui.c, line 338 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwfGycImbGVWu-Sypni:-Kwg-zXSpugsK5Ycj6Ng:b-896fix) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/ui.c#L338)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

per other comments, delete this line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KwwKaGxCNB4ARAeXiZ7:bnfp4nl)*

**Comment by GrayHatter** [comment]
the toggle switch either needs a text element to tell the user it'll change voice, or, alternatively, just use 2 buttons.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KxJUV43b_knmiGAF-mo:b-417krr)*

**Comment by GrayHatter** [comment]
please also merge develop

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KxJUgynVUci4QkOuYYw:b4wbxwt)*

**Comment by GrayHatter** [comment]
+@grayhatter 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KxJUlPJhQQFXeEhBmD2:b-joyoeb)*

**Comment by redmanmale** [comment]
When switch is changing text on the button is changing too. Don't this enough?

> please also merge develop

Rebase onto develop? But there's no conflicts.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KxKN0Hu-czRV6ZQhiWA:b-yudrvo)*

**Comment by GrayHatter** [comment]
Sure, if you know what the toggle is going to do. 

Normal users wont click on that toggle without knowing what it will do. Meaning they'd never see the name of the button change. I like the current way better, but only when you already know what the toggle is going to do, which most users wont.

I wanted develop merged first because of the dependency conflict between the two. I'll never ask you to rebase, a simple `git merge develop` should be much easier, and is what I'd prefer. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KxP5rPxkEnGClpghJfD:bpmm4hz)*

**Comment by redmanmale** [comment]
Any ideas how it should look like? Can it be just tooltip something like "Toggle to change groupchat type"?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KxUhz7OjOfPnHXfs5Yv:bakqpzn)*

**Comment by GrayHatter** [comment]
```
[ switch ] Enable Audio
[ button ] // should still change the button text when the switch is changed
```

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 6 of 9 files at r1, 1 of 3 files at r2, 7 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layout/group.c, line 2 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwWD9mAmIRjTDg98xEf:-KwWD9mAmIRjTDg98xEg:by0x4ei) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L2)):*
> ```C
> #include "create.h"
> #include "group.h"
> ```

The primary header should be at the top, so this should be:
```
group.h

create.h

../commands.h
../debug.h
[..]
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KyDXhVCMKebgowDMoIB:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KyDd8CX7UUw-0BTQNI9:bnfp4nl)*

**Comment by redmanmale** [comment]
> the toggle switch either needs a text element

Done.

>please also merge develop

Done.

---

Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/layout/group.c, line 2 at r1](https://reviewable.io:443/reviews/utox/utox/1087#-KwWD9mAmIRjTDg98xEf:-KyFsZ3Xyka0JImNPEz9:b-896fix) ([raw file](https://github.com/utox/utox/blob/de7b38cf686461e2b1514f7590d3f940691fba3f/src/layout/group.c#L2)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

The primary header should be at the top, so this should be:
```
group.h

create.h

../commands.h
../debug.h
[..]
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KxgSzVgLyX90ZgUcI8k:b194n18)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KyHOVwdugCx1T-3XTIZ:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1087#-:-KyM2W1HcJd4GxYNVSVD:bnfp4nl)*

**Comment by redmanmale** [comment]
It's been a while... Can we merge this?

**Pull request merged**
