### PR TITLE
Fix problems detected by coverity

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/857)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/857#-:-KiR3U8bgeP_z5FOAv-k:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog.c, line 155 at r1](https://reviewable.io:443/reviews/utox/utox/857#-KiRT_RWkCvs-I-Bh3dw:-KiRT_RWkCvs-I-Bh3dx:bofmypq) ([raw file](https://github.com/utox/utox/blob/2d2b8df61b90327b79952fee74a6f0ee741662f1/src/chatlog.c#L155)):*
> ```C
>             if (!msg) {
>                 LOG_ERR("Chatlog", "Unable to malloc... sorry!");
>                 free(start);
> ```

did you do an indepth review on chatlog.c to make sure we're not trying to free a pointer after changing it's location with `*p++`?

If not, just drop the chatlog.c changes because I'm concerned it really needs a full line by line review (and then obviously a refactor to split some of it into separate functions), and that this will fix the warning, but not the root issue... which I don't want to go ignored.

With this rare memleak left in place, we'll still have a reminder it needs real work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/857)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog.c, line 155 at r1](https://reviewable.io:443/reviews/utox/utox/857#-KiRT_RWkCvs-I-Bh3dw:-KitXyFTjYKek-Q3c4pv:bdbw2j8) ([raw file](https://github.com/utox/utox/blob/2d2b8df61b90327b79952fee74a6f0ee741662f1/src/chatlog.c#L155)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

did you do an indepth review on chatlog.c to make sure we're not trying to free a pointer after changing it's location with `*p++`?

If not, just drop the chatlog.c changes because I'm concerned it really needs a full line by line review (and then obviously a refactor to split some of it into separate functions), and that this will fix the warning, but not the root issue... which I don't want to go ignored.

With this rare memleak left in place, we'll still have a reminder it needs real work.
</blockquote></details>

`start` is what we got back from calloc ~40 lines earlier in this function. I wouldn't say an indepth review or anything is required. This is all local to this function. The pointer we're moving is `data`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/857)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/857#-:-KjkyRgFDBIDldPPshDd:bnfp4nl)*

**Pull request merged**
