### PR TITLE
UI code cleanup

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/483)

### CODE REVIEW

**Comment by robinlinden** [comment]
Fixes #471

**Comment by GrayHatter** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ui.c, line 271 at r1](https://reviewable.io:443/reviews/utox/utox/483#-KWtKDA0djtMWZYV2X-O:-KWtKDA1kK51BeuOEqov:bt42ibq) ([raw file](https://github.com/utox/utox/blob/2a5424640180eabb04b40ab6121ff6dfba3f4e28/src/ui.c#L271)):*
> ```C
>     CREATE_BUTTON(lock_uTox, SCALE(10), SCALE(260), BM_SBUTTON_WIDTH, BM_SBUTTON_HEIGHT);
> 
>     PANEL e_name = {
> ```

use or create a `CREATE_EDIT()` macro for these

---

*[src/ui.c, line 396 at r1](https://reviewable.io:443/reviews/utox/utox/483#-KWtKX6AtRJ6u7JcjPJu:-KWtKX6AtRJ6u7JcjPJv:bab4ggr) ([raw file](https://github.com/utox/utox/blob/2a5424640180eabb04b40ab6121ff6dfba3f4e28/src/ui.c#L396)):*
> ```C
>     // Profile tab
> 
>     PANEL d_language = {
> ```

ditto on the `CREATE_DROPDOWN` macro

also be careful x, y HEIGHT, WIDTH... because fuck normal order AMIRITE?

---

*[src/ui/draw_helpers.c, line 433 at r1](https://reviewable.io:443/reviews/utox/utox/483#-KWtL2TGcLTkIPQg18ld:-KWtL2TH_-c3oQA_o7TM:b725sw7) ([raw file](https://github.com/utox/utox/blob/2a5424640180eabb04b40ab6121ff6dfba3f4e28/src/ui/draw_helpers.c#L433)):*
> ```C
>     // The element is draw_pos_y_inc units apart and they start draw_pos_y down.
>     uint16_t draw_pos_y = 10;
>     uint16_t draw_pos_y_inc = 30;
> ```

OPTIONAL 

do we want to make this UPPERCASE because it's generally unchanging? 

IMO it would make parsing faster for humans

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/483)*

**Comment by robinlinden** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/ui.c, line 271 at r1](https://reviewable.io:443/reviews/utox/utox/483#-KWtKDA0djtMWZYV2X-O:-KWu7mS78cFS2NTKlHlT:b-896fix) ([raw file](https://github.com/utox/utox/blob/2a5424640180eabb04b40ab6121ff6dfba3f4e28/src/ui.c#L271)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> use or create a `CREATE_EDIT()` macro for these
</details>
Done.

---

*[src/ui.c, line 396 at r1](https://reviewable.io:443/reviews/utox/utox/483#-KWtKX6AtRJ6u7JcjPJu:-KWu7jSIpPQISDX9U8Cv:b-896fix) ([raw file](https://github.com/utox/utox/blob/2a5424640180eabb04b40ab6121ff6dfba3f4e28/src/ui.c#L396)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> ditto on the `CREATE_DROPDOWN` macro
> 
> also be careful x, y HEIGHT, WIDTH... because fuck normal order AMIRITE?
</details>
Done.

---

*[src/ui/draw_helpers.c, line 433 at r1](https://reviewable.io:443/reviews/utox/utox/483#-KWtL2TGcLTkIPQg18ld:-KWtM3l078xghC_yU6jD:b8v4jx8) ([raw file](https://github.com/utox/utox/blob/2a5424640180eabb04b40ab6121ff6dfba3f4e28/src/ui/draw_helpers.c#L433)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> OPTIONAL 
> 
> do we want to make this UPPERCASE because it's generally unchanging? 
> 
> IMO it would make parsing faster for humans
</details>
I agree with showing that it's a const/unchanging variable in some way, but if we mark this as such, a human might think it never changes from 30 when it does. :P Want to go with ALL_CAPS for const variables?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/483)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/draw_helpers.c, line 433 at r1](https://reviewable.io:443/reviews/utox/utox/483#-KWtL2TGcLTkIPQg18ld:-KWuBmpo3Ve0JHr8J6OQ:be09xkl) ([raw file](https://github.com/utox/utox/blob/2a5424640180eabb04b40ab6121ff6dfba3f4e28/src/ui/draw_helpers.c#L433)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> I agree with showing that it's a const/unchanging variable in some way, but if we mark this as such, a human might think it never changes from 30 when it does. :P Want to go with ALL_CAPS for const variables?
</details>
discussed on IRC LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/483)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/483)*

**Comment by GrayHatter** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/483)*

**Comment by GrayHatter** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/483#-:-KWuKPkiN1GMx01-Ifdq:b-uwkowd)*

**Pull request merged**
