### PR TITLE
Remove references to removed member variables.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1095)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1095#-:-KwSd6XZi-Wq7tzRqF13:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1095#-:-KwUGZNZTarlKWT-9bM3:bnfp4nl)*

**Comment by redmanmale** [comment]
I'm sorry I missed that in my PR.

**Comment by robinlinden** [comment]
Don't worry about it, that happens. It's why we generally should never
merge things when we don't have a working CI system.

**Pull request merged**
