### PR TITLE
Always exit on LOG_FATAL_ERR, and convert exiting LOG_ERRs

### LINKED ISSUE #748: LOG_FATAL_ERR should never be a no-op
As it is now, LOG_FATAL_ERR is a worse LOG_ERR since it has to be used like
```C
LOG_FATAL_ERR(exit_code, "Example", "Error body.");
exit(exit_code);
```
meaning you have to edit the exit_code in multiple locations and DRY and all that.

### PR DESCRIPTION
**Pull request by cebe**
- made LOG_FATAL_ERR always print the error and always exit.
- cleanup exit codes and use LOG_FATAL_ERR in case LOG_ERR was used with exit()
- some other minor log message cleanups

fixes #748

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/751)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/751#-:-Kd7ci9liiNQPGRBWAXj:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

conflicts with @endoffile78's pull to log to a file, we want to accept @endoffile78's version of LOG_FATAR, where theres' no ? exit() : exit()

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/751#-:-Kd7dNi_FvVG0rffnN9g:bp8kx9m)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 15 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/debug.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/751#-Kd8UV0rmSXcec-Ec-4O:-Kd8UV0rmSXcec-Ec-4P:b-e8lplj) ([raw file](https://github.com/utox/utox/blob/22a93005f0274cb1edc02a3cc3d70b40fad2d8c3/src/debug.h#L7)):*
> ```objc
> 
> #ifndef EXIT_SUCCESS // should be defined in stdlib.h
> #define	EXIT_SUCCESS	0	/* Successful exit status.  */
> ```

Uses tabs instead of spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/751#-:-Kd8VL6q3Lcqdvd0TOb9:b-jbsf8z)*

**Comment by robinlinden** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/751)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/debug.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/751#-Kd8UV0rmSXcec-Ec-4O:-Kd8ePYe2WhCQ25pj1j3:b-yhzlq4) ([raw file](https://github.com/utox/utox/blob/22a93005f0274cb1edc02a3cc3d70b40fad2d8c3/src/debug.h#L7)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Uses tabs instead of spaces.
</blockquote></details>

I like tabs :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/751)*

**Comment by GrayHatter** [comment]
rebase or merge needed

**Comment by cebe** [comment]
blocked by https://github.com/uTox/uTox/pull/737, should be rebased after that one is merged.

**Comment by GrayHatter** [comment]
@cebe it's going now

**Comment by cebe** [comment]
rebased and adjusted to latest code changes.

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/debug.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/751#-Kd8UV0rmSXcec-Ec-4O:-KdD5CG87D7scxAAwSws:b-7dhzsj) ([raw file](https://github.com/utox/utox/blob/22a93005f0274cb1edc02a3cc3d70b40fad2d8c3/src/debug.h#L7)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

I like tabs :)
</blockquote></details>

Yeah, I don't care one way or the other. I only mentioned it because I don't see tabs in uTox's codebase. :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/751#-:-KdD5hrveeAFY5jk9iQD:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/debug.h, line 7 at r1](https://reviewable.io:443/reviews/utox/utox/751#-Kd8UV0rmSXcec-Ec-4O:-Kd7ctpUBdeU4HuwaeXF:b-jkj39f) ([raw file](https://github.com/utox/utox/blob/22a93005f0274cb1edc02a3cc3d70b40fad2d8c3/src/debug.h#L7)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Yeah, I don't care one way or the other. I only mentioned it because I don't see tabs in uTox's codebase. :P
</blockquote></details>

tabs are evil :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/751#-:-KdD6By-zggNHJGksVYc:bnfp4nl)*

**Pull request merged**
