### PR TITLE
Friend request improvements

### PR DESCRIPTION
**Pull request by endoffile78**
The message no longer drawn in the headline and a sound is played when a friend request is recieved.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/608)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm: 

Friend requests are few and far in between, I'd suggest the notification be made 2-3x longer

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608#-:-KaGmtbsOIBAZ__dcCpm:b41e0nv)*

**Comment by endoffile78** [comment]
@GrayHatter Done, I also changed the notifciation a little i think it now sounds a little bit more different than the other ones.

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608#-:-KaK0MR1z1AkRVRwGEh1:bcnd06m)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608#-:-KaKZgSHXesKXptOSodO:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/audio.c, line 483 at r2](https://reviewable.io:443/reviews/utox/utox/608#-KaLkdcONlZE7kSP6v_N:-KaLkdcPJxpIixbawOhJ:b-z0qmj3) ([raw file](https://github.com/utox/utox/blob/e83526e1a032d97480c981c985dadba89676340d/src/av/audio.c#L483)):*
> ```C
> static void generate_tone_friend_new_msg() { generate_melody(friend_new_msg, 1, 8, &ToneBuffer); }
> 
> static void generate_tone_friend_request() { generate_melody(friend_request, 1, 4, &ToneBuffer); }
> ```

you're still only using the first 4 notes, for friend requests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608)*

**Comment by endoffile78** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/audio.c, line 483 at r2](https://reviewable.io:443/reviews/utox/utox/608#-KaLkdcONlZE7kSP6v_N:-KaOlLnbnYZ0ZpamkEk6:b-896fix) ([raw file](https://github.com/utox/utox/blob/e83526e1a032d97480c981c985dadba89676340d/src/av/audio.c#L483)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

you're still only using the first 4 notes, for friend requests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608#-:-KaOnhTbxZSpeJIcewk4:bg7igkv)*

**Comment by cebe** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/608)*

**Pull request merged**
