### PR TITLE
Fix chat logging

### PR DESCRIPTION
**Pull request by robinlinden**
Merge after #526

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/531)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 4 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.c, line 201 at r1](https://reviewable.io:443/reviews/utox/utox/531#-KYeh-kzCz1n2FGq5uJM:-KYeh-kzCz1n2FGq5uJN:b3yrmz2) ([raw file](https://github.com/utox/utox/blob/d9ce761d9693bc85b34909a6bcabe32e56e5692d/src/main.c#L201)):*
> ```C
>     }
> 
>     fseeko(fp, 0, SEEK_END);
> ```

seek to the beginning first. I want this code to work, and I know that I've had issues with this on windows. But I don't remember where.

Add a comment explaining why. We seek to the start first.

---

*[src/main.c, line 305 at r1](https://reviewable.io:443/reviews/utox/utox/531#-KYehXSyt3-QtV0WCj11:-KYehXSyt3-QtV0WCj12:b-yh5n0p) ([raw file](https://github.com/utox/utox/blob/d9ce761d9693bc85b34909a6bcabe32e56e5692d/src/main.c#L305)):*
> ```C
>                     *size = 0;
>                 }
>                 
> ```

Set you editor to trim trailing whitespace on save.

---

*[src/messages.c, line 379 at r1](https://reviewable.io:443/reviews/utox/utox/531#-KYehy5pjxwWqeV6v4NK:-KYehy5pjxwWqeV6v4NL:b-6t8t5i) ([raw file](https://github.com/utox/utox/blob/d9ce761d9693bc85b34909a6bcabe32e56e5692d/src/messages.c#L379)):*
> ```C
>         }
>         default: { 
>             debug("uTox Logging:\tUnsupported file type %i\n", msg->msg_type); 
> ```

debug_notice and it's should read `message type`, not file type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531)*

**Comment by robinlinden** [comment]
Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 201 at r1](https://reviewable.io:443/reviews/utox/utox/531#-KYeh-kzCz1n2FGq5uJM:-KYfPWQafB0X4FkVV0yr:b-896fix) ([raw file](https://github.com/utox/utox/blob/d9ce761d9693bc85b34909a6bcabe32e56e5692d/src/main.c#L201)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

seek to the beginning first. I want this code to work, and I know that I've had issues with this on windows. But I don't remember where.

Add a comment explaining why. We seek to the start first.
</blockquote></details>

Done.

---

*[src/main.c, line 305 at r1](https://reviewable.io:443/reviews/utox/utox/531#-KYehXSyt3-QtV0WCj11:-KYfQNqEd-oCfaCiAtSe:b-896fix) ([raw file](https://github.com/utox/utox/blob/d9ce761d9693bc85b34909a6bcabe32e56e5692d/src/main.c#L305)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Set you editor to trim trailing whitespace on save.
</blockquote></details>

Done.

---

*[src/messages.c, line 379 at r1](https://reviewable.io:443/reviews/utox/utox/531#-KYehy5pjxwWqeV6v4NK:-KYfQPbVKPc4fnaxbcwX:b-896fix) ([raw file](https://github.com/utox/utox/blob/d9ce761d9693bc85b34909a6bcabe32e56e5692d/src/messages.c#L379)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

debug_notice and it's should read `message type`, not file type
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 8 files at r1, 2 of 2 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/main.c, line 218 at r2](https://reviewable.io:443/reviews/utox/utox/531#-KYfbjvzLC7NJOl1zA-3:-KYfbjvzLC7NJOl1zA-4:b-7hympb) ([raw file](https://github.com/utox/utox/blob/83b66e761954d42e8b4de75ea945f5facf9d22c4/src/android/main.c#L218)):*
> ```C
>     }
> 
>     mode[3] = '\0';
> ```

`mode[3] =0;`

---

*[src/android/main.c, line 229 at r2](https://reviewable.io:443/reviews/utox/utox/531#-KYfbs3HrN6FKeS1QtuN:-KYfbs3HrN6FKeS1QtuO:b-wmuk5c) ([raw file](https://github.com/utox/utox/blob/83b66e761954d42e8b4de75ea945f5facf9d22c4/src/android/main.c#L229)):*
> ```C
> 
>     if (opts > UTOX_FILE_OPTS_DELETE) {
>         debug_error("NATIVE:\tDon't call native_get_file with UTOX_FILE_OPTS_DELETE in combination with other options.\n");
> ```

do we want this to be an assert? users shouldn't see this, only developers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/main.c, line 218 at r2](https://reviewable.io:443/reviews/utox/utox/531#-KYfbjvzLC7NJOl1zA-3:-KYffuczUagEKHdWz1lB:b6x65be) ([raw file](https://github.com/utox/utox/blob/83b66e761954d42e8b4de75ea945f5facf9d22c4/src/android/main.c#L218)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`mode[3] =0;`
</blockquote></details>

Fixing this in the POSIX native PR. 

---

*[src/android/main.c, line 229 at r2](https://reviewable.io:443/reviews/utox/utox/531#-KYfbs3HrN6FKeS1QtuN:-KYffqTm8HEV0NqpXLWs:b-2fwpth) ([raw file](https://github.com/utox/utox/blob/83b66e761954d42e8b4de75ea945f5facf9d22c4/src/android/main.c#L229)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

do we want this to be an assert? users shouldn't see this, only developers
</blockquote></details>

We do, but this isn't in scope for this PR. Will make the change in the POSIX native PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531)*

**Comment by robinlinden** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/main.c, line 218 at r2](https://reviewable.io:443/reviews/utox/utox/531#-KYfbjvzLC7NJOl1zA-3:-KYfjGavrvFFtNRBlqIN:bqk2b6h) ([raw file](https://github.com/utox/utox/blob/83b66e761954d42e8b4de75ea945f5facf9d22c4/src/android/main.c#L218)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Fixing this in the POSIX native PR. 
</blockquote></details>

Fixed it in the other PR and rebased on top of that.

---

*[src/android/main.c, line 229 at r2](https://reviewable.io:443/reviews/utox/utox/531#-KYfbs3HrN6FKeS1QtuN:-KYfjK0ZK1ytV9bC8Yln:bqk2b6h) ([raw file](https://github.com/utox/utox/blob/83b66e761954d42e8b4de75ea945f5facf9d22c4/src/android/main.c#L229)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

We do, but this isn't in scope for this PR. Will make the change in the POSIX native PR.
</blockquote></details>

Fixed it in the other PR and rebased on top of that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/windows/filesys.c, line 53 at r3](https://reviewable.io:443/reviews/utox/utox/531#-KYlNnTqSltcRG_Wfi7m:-KYlNnTrrpD9D33zOXNj:bvr4thu) ([raw file](https://github.com/utox/utox/blob/02fe124f10483525623616a816a6e2b7aa4c8769/src/windows/filesys.c#L53)):*
> ```C
>     }
> 
>     if (opts > UTOX_FILE_OPTS_DELETE) {
> ```

BTW

TFW, no assert here :cry: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531#-:-KYlNyHNO-htiqFEqWFt:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 2 of 2 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531#-:-KYlOqW2Yf5G19xpq6AH:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/531#-:-KYmQgKwjEScC_iya4Nl:bnfp4nl)*

**Pull request merged**
