### PR TITLE
Cleanup utoxav

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/671)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/audio.c, line 559 at r1](https://reviewable.io:443/reviews/utox/utox/671#-KbRfHyifE5syrEB31xs:-KbRfHyifE5syrEB31xt:bfwnf7z) ([raw file](https://github.com/utox/utox/blob/01d2fc045d7d1eb49fe3b6a694e58835e15db8e1/src/av/audio.c#L559)):*
> ```C
> 
>     #define PREVIEW_BUFFER_SIZE (UTOX_DEFAULT_SAMPLE_RATE_A / 2)
>     int16_t *preview_buffer = calloc(PREVIEW_BUFFER_SIZE, 2);
> ```

Make sure memory was allocated for preview_buffer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/671)*

**Comment by robinlinden** [comment]
Review status: 7 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/audio.c, line 559 at r1](https://reviewable.io:443/reviews/utox/utox/671#-KbRfHyifE5syrEB31xs:-KbS3MSQ0Wncn6mjYcs3:b-896fix) ([raw file](https://github.com/utox/utox/blob/01d2fc045d7d1eb49fe3b6a694e58835e15db8e1/src/av/audio.c#L559)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Make sure memory was allocated for preview_buffer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/671)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/671#-:-KbSCabZH9A_8yGDg2sV:bnfp4nl)*

**Comment by GrayHatter** [comment]
theres' a pull on your repo, merge or ignore, either way :lgtm: 

---

Reviewed 7 of 10 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/tox.c, line 18 at r4](https://reviewable.io:443/reviews/utox/utox/671#-KbTqFMbqsz-3X1B9e8j:-KbTqFMbqsz-3X1B9e8k:b-1rqxd4) ([raw file](https://github.com/utox/utox/blob/22586fa2f2e87f0a3e3a45932623ace291d65eb3/src/tox.c#L18)):*
> ```C
> #include "utox.h"
> 
> #include "av/audio.h"
> ```

Why are we including these at all?

We should only need to use postmessage_utoxav

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/671#-:-KbTrNL80XTbsjo1v5v1:bdkhp4y)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/671#-:-KbWtm_gG4YupEl8FpEt:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/tox.c, line 18 at r4](https://reviewable.io:443/reviews/utox/utox/671#-KbTqFMbqsz-3X1B9e8j:-KbWwRtiaPJEtQIQQsMP:b-q8t2h9) ([raw file](https://github.com/utox/utox/blob/22586fa2f2e87f0a3e3a45932623ace291d65eb3/src/tox.c#L18)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Why are we including these at all?

We should only need to use postmessage_utoxav
</blockquote></details>

`UTOX_DEFAULT_BITRATE_A` is defined in audio.h and used for `toxav_call`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/671)*

**Pull request merged**
