### PR TITLE
Support for OpenBSD, NetBSD and FreeBSD.

### LINKED ISSUE #809: make with -DENABLE_FILTERAUDIO=0 fails
Commit: 53cb07945897
```
 $ cmake -DENABLE_FILTERAUDIO=0 && make
...
[ 97%] Building C object CMakeFiles/utox.dir/src/utox.c.o
[ 98%] Building C object CMakeFiles/utox.dir/src/window.c.o
[100%] Linking C executable utox
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lfilteraudio
```
The linker flag seems to be hardcoded at CMakeLists.txt line 261.

### PR DESCRIPTION
**Pull request by robinlinden**
A join effort between me and @endoffile78

Fixes #809 

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/801)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[cmake/toolchain-freebsd.cmake, line 7 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi-bWyv-E_DRfXDBJ2:-Khi-bWzSLp4s06DebRQ:b-j0whfo) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/cmake/toolchain-freebsd.cmake#L7)):*
> ```CMake
> set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L/usr/local/lib" CACHE STRING "" FORCE)
> 
> set(ENABLE_TESTS OFF CACHE STRING "" FORCE)
> ```

parent scope?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by GrayHatter** [comment]
Reviewed 4 of 6 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[CMakeLists.txt, line 38 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2nJiPyWf1igBewgE:-Khi2nJiPyWf1igBewgF:b-4pu33o) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/CMakeLists.txt#L38)):*
> ```CMake
> endif()
> 
> if(WIN32)
> ```

check for windows

check for osx

check for unix
-> check for type of unix

---

*[cmake/toolchain-openbsd.cmake, line 4 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi-fu7BSj_5Hf-ikz4:-Khi-fu7BSj_5Hf-ikz5:b-cx5pao) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/cmake/toolchain-openbsd.cmake#L4)):*
> ```CMake
> UNSET(CMAKE_C_FLAGS CACHE)
> 
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I/usr/local/include -L/usr/local/lib -I/usr/X11R6/include -L/usr/X11R6/lib -std=c99" CACHE STRING "" FORCE)
> ```

this is likely to be system specific, are you sure this is right?

If you're not sure, add a comment

---

*[src/dns.c, line 27 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi-rnX3zY_QWhdn_Ot:-Khi-rnYy4Gzea71szJY:b-mfnp65) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/dns.c#L27)):*
> ```C
> #include <netinet/in.h>
> #include <sys/types.h>
> #else
> ```

this else needs a comment

---

*[src/main.h, line 56 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi0cVfTd1BCrXECgDq:-Khi0cVfTd1BCrXECgDr:b-5ngyvx) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/main.h#L56)):*
> ```objc
>  ***  TODO fix them?
> #if !defined (__OBJC__) && !defined (__NetBSD__)
> #define volatile(x) (*((volatile typeof(x)*)&x))
> ```

FYI https://github.com/uTox/uTox/issues/827

---

*[src/updater.c, line 23 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi1-qhF7iG81DAI1pn:-Khi1-qi5MMe_UcQWAjq:b-8hhefn) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/updater.c#L23)):*
> ```C
> #ifdef __WIN32__
> #include <winsock2.h>
> #include <ws2tcpip.h>
> ```

are you sure, IIRC this order matters?

---

*[src/av/CMakeLists.txt, line 11 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi17No7Fln-yP9HFNc:-Khi17Np-89QDGeq3rA6:b-ysazbq) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/av/CMakeLists.txt#L11)):*
> ```CMake
> if(WIN32)
>     target_link_libraries(utoxAV OpenAL32)
> elseif(NOT APPLE)
> ```

this isn't okay. You can't if, if not, if, else

at least not without a bunch of comments

---

*[src/xlib/CMakeLists.txt, line 78 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2WdV7i2F-wlCP0lN:-Khi2WdV7i2F-wlCP0lO:b-x8rskm) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/CMakeLists.txt#L78)):*
> ```CMake
>         )
> 
> if(CMAKE_SYSTEM_NAME MATCHES ".*Linux")
> ```

switch the order with the one below, it's generally better to go from specific to general.

---

*[src/xlib/CMakeLists.txt, line 85 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2cCqvMUsV7WrXXhg:-Khi2cCqvMUsV7WrXXhh:b-9dk6xd) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/CMakeLists.txt#L85)):*
> ```CMake
> endif()
> 
> if(CMAKE_SYSTEM_NAME MATCHES ".*Linux" OR CMAKE_SYSTEM_NAME MATCHES "kNetBSD.*|NetBSD.*")
> ```

handle the error case of openbsd instead of trying to limit what already works?

---

*[src/xlib/main.c, line 93 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi1P3t8fzPJWtDPu_g:-Khi1P3t8fzPJWtDPu_h:bnr6fqi) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/main.c#L93)):*
> ```C
>     }
>     // Only Linux has KEY_LEFTCTRL and KEY_MAX.
> #ifdef __linux__
> ```

I don't like #ifdef inside functions.

extern this block of code, then add

```
    #ifdef __linux__
        return linux_check_ptt();
    #else
        return bsd_check_ptt();
    #endif
```
and wrap the definition of each function in the same ifdef

---

*[src/xlib/v4l.c, line 12 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2IC9oY14h6aq165H:-Khi2ICAOrlUyx-HE6p3:b-q10zir) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/v4l.c#L12)):*
> ```C
> 
> #include <sys/mman.h>
> #ifdef __linux__
> ```

are you sure you're ALWAYS gonna get __linux__ here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[src/xlib/v4l.c, line 12 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2IC9oY14h6aq165H:-Khi3ojp54hxEVm2biP8:b-5kjxou) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/v4l.c#L12)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

are you sure you're ALWAYS gonna get __linux__ here?
</blockquote></details>

There's an else for which is needed for OpenBSD. For FreeBSD you can install v4l.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[cmake/toolchain-freebsd.cmake, line 7 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi-bWyv-E_DRfXDBJ2:-Khi4EZtrXh8pYdzAPm4:bt24myb) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/cmake/toolchain-freebsd.cmake#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

parent scope?
</blockquote></details>

Not needed. I did it this way in the Windows toolchains and they work as intended.

---

*[src/xlib/CMakeLists.txt, line 78 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2WdV7i2F-wlCP0lN:-Khi4YycOz2oWBMPHJbh:b-vdiw0q) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/CMakeLists.txt#L78)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

switch the order with the one below, it's generally better to go from specific to general.
</blockquote></details>

We should probably use the SYSTEM variables we set in the main CMakeLists.txt here. (If they're available?)

---

*[src/xlib/v4l.c, line 12 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2IC9oY14h6aq165H:-Khi3iSj0LeLbzgk2mTE:bfuybj0) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/v4l.c#L12)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

There's an else for which is needed for OpenBSD. For FreeBSD you can install v4l.
</blockquote></details>

I'm pretty sure **linux**/videodev2.h is a Linux thing. (`__linux__` should be set by all compilers on all Linux distros)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[src/xlib/v4l.c, line 12 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2IC9oY14h6aq165H:-Khi84g_iKzqtSlz1P0g:b-6mrbd7) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/v4l.c#L12)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I'm pretty sure **linux**/videodev2.h is a Linux thing. (`__linux__` should be set by all compilers on all Linux distros)
</blockquote></details>

It is on FreeBSD after installing libv4l v4l-utils and v4l_compat I have a linux folder in my includes I forgot to add the check for FreeBSD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[src/xlib/CMakeLists.txt, line 78 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2WdV7i2F-wlCP0lN:-KhiDWVqmU23J4rgGo9u:b-67njww) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/CMakeLists.txt#L78)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

We should probably use the SYSTEM variables we set in the main CMakeLists.txt here. (If they're available?)
</blockquote></details>

yeah, do that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by endoffile78** [comment]
Review status: 2 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[CMakeLists.txt, line 38 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2nJiPyWf1igBewgE:-KhiD-hUnrx3jYCVUcTg:bb6un1j) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/CMakeLists.txt#L38)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

check for windows

check for osx

check for unix
-> check for type of unix
</blockquote></details>

Done

---

*[cmake/toolchain-openbsd.cmake, line 4 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi-fu7BSj_5Hf-ikz4:-KhiE6DbLUO-MCaX3E56:bb6un1j) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/cmake/toolchain-openbsd.cmake#L4)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this is likely to be system specific, are you sure this is right?

If you're not sure, add a comment
</blockquote></details>

Done

---

*[src/dns.c, line 27 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi-rnX3zY_QWhdn_Ot:-KhiE4g6U3MV1TSr1EdB:bb6un1j) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/dns.c#L27)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this else needs a comment
</blockquote></details>

Done

---

*[src/av/CMakeLists.txt, line 11 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi17No7Fln-yP9HFNc:-KhiE_ibCIH1RbrAMnnN:bb6un1j) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/av/CMakeLists.txt#L11)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this isn't okay. You can't if, if not, if, else

at least not without a bunch of comments
</blockquote></details>

Done

---

*[src/xlib/main.c, line 93 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi1P3t8fzPJWtDPu_g:-KhiEcHjPaOH15cYhl1a:bb6un1j) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/main.c#L93)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I don't like #ifdef inside functions.

extern this block of code, then add

```
    #ifdef __linux__
        return linux_check_ptt();
    #else
        return bsd_check_ptt();
    #endif
```
and wrap the definition of each function in the same ifdef

</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by endoffile78** [comment]
Review status: 2 of 10 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[src/xlib/v4l.c, line 12 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2IC9oY14h6aq165H:-KhiHaRjL26zOIoyyvfS:b-1n2rwt) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/v4l.c#L12)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

It is on FreeBSD after installing libv4l v4l-utils and v4l_compat I have a linux folder in my includes I forgot to add the check for FreeBSD
</blockquote></details>

Added the FreeBSD check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by endoffile78** [comment]
Review status: 2 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/xlib/CMakeLists.txt, line 78 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2WdV7i2F-wlCP0lN:-KhiHxoenxIaiOmhg_VI:brzsqoi) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/CMakeLists.txt#L78)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yeah, do that
</blockquote></details>

Changed it to use the variables and switched order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by cebe** [comment]
Reviewed 2 of 6 files at r3, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[cmake/toolchain-freebsd.cmake, line 10 at r5](https://reviewable.io:443/reviews/utox/utox/801#-KhiWLvBjUNES2FswhsH:-KhiWLvBjUNES2FswhsI:btamowx) ([raw file](https://github.com/utox/utox/blob/cb5b301259fa11e7c8a5328de3f2620ae02f4153/cmake/toolchain-freebsd.cmake#L10)):*
> ```CMake
> set(ENABLE_TESTS OFF CACHE STRING "" FORCE)
> set(ENABLE_DBUS OFF CACHE STRING "" FORCE)
> set(ENABLE_FILTERAUDIO OFF CACHE STRING "" FORCE)
> ```

Why are you using `CACHE STRING "" FORCE`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[cmake/toolchain-freebsd.cmake, line 10 at r5](https://reviewable.io:443/reviews/utox/utox/801#-KhiWLvBjUNES2FswhsH:-KhiYAxuTK_05l18FiVk:bwjpc9t) ([raw file](https://github.com/utox/utox/blob/cb5b301259fa11e7c8a5328de3f2620ae02f4153/cmake/toolchain-freebsd.cmake#L10)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

Why are you using `CACHE STRING "" FORCE`?
</blockquote></details>

To override the variables in the main CMakeLists.txt file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by GrayHatter** [comment]
Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/av/CMakeLists.txt, line 11 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi17No7Fln-yP9HFNc:-KhjRPkyV-Pq0EI0YtVE:bjumchv) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/av/CMakeLists.txt#L11)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Done
</blockquote></details>

LGTM, don't change it... but I'm still uncomfortable with if true, if false, else

---

*[src/xlib/CMakeLists.txt, line 85 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi2cCqvMUsV7WrXXhg:-KhjRkOzef0-ZC1yOlDj:bb6ywmx) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/xlib/CMakeLists.txt#L85)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

handle the error case of openbsd instead of trying to limit what already works?
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/updater.c, line 23 at r4](https://reviewable.io:443/reviews/utox/utox/801#-Khi1-qhF7iG81DAI1pn:-KhmIFizj7K-hCPgJw-P:brbckyt) ([raw file](https://github.com/utox/utox/blob/1305af0277209dbdf4b56b87f9a2e6e1771d9b7a/src/updater.c#L23)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

are you sure, IIRC this order matters?
</blockquote></details>

Yeah, this compiles without warnings on Windows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801#-:-KhodFqulcENjEiMWx2V:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[cmake/toolchain-freebsd.cmake, line 10 at r5](https://reviewable.io:443/reviews/utox/utox/801#-KhiWLvBjUNES2FswhsH:-Ki1mrZ0XztNSC4guzWQ:bgdzhlr) ([raw file](https://github.com/utox/utox/blob/cb5b301259fa11e7c8a5328de3f2620ae02f4153/cmake/toolchain-freebsd.cmake#L10)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

To override the variables in the main CMakeLists.txt file.
</blockquote></details>

that also means you can not specify them on the command line, but its probably fine for these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801#-:-Ki1n7L3fZ_C_mpNrlzd:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/801#-:-Ki6YkjNRvW56701zCsE:bnfp4nl)*

**Pull request merged**
