### PR TITLE
Add macros.h

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/649)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Do all of those files really still need main.h included?

**Comment by GrayHatter** [comment]
Is main.h still needed in all the files where you removed the `// FIXME` comments?

Can you sort the headers as well? (clang-format can do that in bulk if you run it and tell it to ONLY sort headers, is probably the fastest way)

---

Reviewed 3 of 38 files at r1.
Review status: 3 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/file_transfers.c, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/649#-Kb9Rpp-kUJyMiOinDJ5:-Kb9Rpp-kUJyMiOinDJ6:b2o5t86) ([raw file](https://github.com/utox/utox/blob/15c10d90ff5df0dd2d18e7c9402c7db73a8c8d9d/src/file_transfers.c#L10)):*
> ```C
> #include "util.h"
> #include "utox.h"
> #include "main.h"
> ```

Is main.h still needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/649#-:-Kb9Rvbo1mMAp2sPcj-B:bhjd0o9)*

**Comment by robinlinden** [comment]
@GrayHatter In this PR, most files still rely on being able to access the settings struct in the main file. This in combination with #647 should get almost all of them.

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/file_transfers.c, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/649#-Kb9Rpp-kUJyMiOinDJ5:-KbBAA3vxTmG-bwEOBVK:b-73mklj) ([raw file](https://github.com/utox/utox/blob/15c10d90ff5df0dd2d18e7c9402c7db73a8c8d9d/src/file_transfers.c#L10)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Is main.h still needed?
</blockquote></details>

It's still needed until e0f's settings PR is merged.
`settings.accept_inline_images` is used in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/649#-:-KbBALJ9y0xW0-hmrcp_:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 35 of 38 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/649#-:-KbBmzQSv9Ei-3ckbNc1:bnfp4nl)*

**Pull request merged**
