### PR TITLE
Fix groupchat problems.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/922)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/tox_callbacks.c, line 154 at r1](https://reviewable.io:443/reviews/utox/utox/922#-KkrCQB_lfhAvhbFnY2i:-KkrCQBa1Sn2hSLnJdwm:b-amexg7) ([raw file](https://github.com/utox/utox/blob/55dd1f9ad6cdf60a68d7a0388cbcd6c56e40aaa0/src/tox_callbacks.c#L154)):*
> ```C
> static void callback_group_invite(Tox *tox, uint32_t fid, TOX_CONFERENCE_TYPE type, const uint8_t *data, size_t length,
>                                   void *UNUSED(userdata)) {
>     if (type != TOX_CONFERENCE_TYPE_TEXT) {
> ```

Add a `LOG_ERR` saying audio/video groupchats aren't supported currently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/922)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/tox_callbacks.c, line 154 at r1](https://reviewable.io:443/reviews/utox/utox/922#-KkrCQB_lfhAvhbFnY2i:-KkrTJrRPfq853SO9bGK:b-896fix) ([raw file](https://github.com/utox/utox/blob/55dd1f9ad6cdf60a68d7a0388cbcd6c56e40aaa0/src/tox_callbacks.c#L154)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Add a `LOG_ERR` saying audio/video groupchats aren't supported currently.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/922)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/922#-:-KkrTznmDO93EvOF0NQE:bnfp4nl)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/groups.c, line 236 at r2](https://reviewable.io:443/reviews/utox/utox/922#-Kl0GJ-qbFV-KfSTfAwC:-Kl0GJ-r-KdMLhslluPJ:b582j8d) ([raw file](https://github.com/utox/utox/blob/a0aab995788241c2efb3e79004d40deae626fe91/src/groups.c#L236)):*
> ```C
>         if (!new_peer) {
>             free(peer);
>             LOG_FATAL_ERR(EXIT_MALLOC, "Groupchat", "couldn't realloc for group peer name!");
> ```

Don't we should exit here?

---

*[src/groups.c, line 254 at r2](https://reviewable.io:443/reviews/utox/utox/922#-Kl0Gc_4-LLNZSU6offr:-Kl0Gc_567xMRxFnO5ih:b582j8d) ([raw file](https://github.com/utox/utox/blob/a0aab995788241c2efb3e79004d40deae626fe91/src/groups.c#L254)):*
> ```C
>     if (!new_peer) {
>         free(peer);
>         LOG_FATAL_ERR(EXIT_MALLOC, "Groupchat", "Unable to realloc for group peer who just joined.");
> ```

Don't we should exit here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/922)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/groups.c, line 236 at r2](https://reviewable.io:443/reviews/utox/utox/922#-Kl0GJ-qbFV-KfSTfAwC:-Kl0Gv2if6UFdqwJGShN:bxel7ws) ([raw file](https://github.com/utox/utox/blob/a0aab995788241c2efb3e79004d40deae626fe91/src/groups.c#L236)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Don't we should exit here?
</blockquote></details>

`LOG_FATAL_ERR` does something like `LOG_ERR(message); exit(error_code);` so we do exit here. ...If that's what you're asking.

---

*[src/groups.c, line 254 at r2](https://reviewable.io:443/reviews/utox/utox/922#-Kl0Gc_4-LLNZSU6offr:-Kl0HC-BI9AFxOrJ-Xrn:bmoqmjk) ([raw file](https://github.com/utox/utox/blob/a0aab995788241c2efb3e79004d40deae626fe91/src/groups.c#L254)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Don't we should exit here?
</blockquote></details>

See the other comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/922)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/groups.c, line 236 at r2](https://reviewable.io:443/reviews/utox/utox/922#-Kl0GJ-qbFV-KfSTfAwC:-Kl0Hhv_JOPihMcfHTYQ:b3u1l1h) ([raw file](https://github.com/utox/utox/blob/a0aab995788241c2efb3e79004d40deae626fe91/src/groups.c#L236)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`LOG_FATAL_ERR` does something like `LOG_ERR(message); exit(error_code);` so we do exit here. ...If that's what you're asking.
</blockquote></details>

OK, that's my bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/922#-:-Kl0Hx9312hy3QtSFVXC:bnfp4nl)*

**Pull request merged**
