### PR TITLE
[Windows] Wait until window is inited before coping ToxID from Toxcore

### LINKED ISSUE #592: Tox ID isn't displayed
Tox ID field looks like this before selection:

after selection:

But ID could not be copied either via CTRL-C or button COPY.

Win 7, 8.1 x64, uTox v.0.11.1

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #592.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1307)

### CODE REVIEW

**Comment by GrayHatter** [comment]
What's the goal of this?

I hate the idea of blocking on toxcore thread waiting for the main thread...

**Comment by redmanmale** [comment]
The goal is to avoid this thing from happening.
In that case user is unable to see or copy his ToxID.
error

**Comment by GrayHatter** [comment]
how about preloading that text entry field with "Loading ToxID..." instead?

**Comment by redmanmale** [comment]
I'll try. Just didn't think about it.

**Comment by GrayHatter** [comment]
@redmanmale bump

**Pull request closed without merging**
