### PR TITLE
Fix file sending for macOS

### PR DESCRIPTION
**Pull request by publicarray**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1034)

### CODE REVIEW

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/interaction.m, line 990 at r1](https://reviewable.io:443/reviews/utox/utox/1034#-KtFhg9p9V_eVYasTMFy:-KtFhg9p9V_eVYasTMFz:b-w9uy3v) ([raw file](https://github.com/utox/utox/blob/af88a7b5654766e51d1ca5079831824f96341350/src/cocoa/interaction.m#L990)):*
> ```objc
>         NSArray * urls = picker.URLs;
>         FRIEND *f = flist_get_friend();
>         if (!f) {
> ```

`f` is never freed.

---

*[src/cocoa/interaction.m, line 994 at r1](https://reviewable.io:443/reviews/utox/utox/1034#-KtFhv7JWx1OChnaTXuX:-KtFhv7Kg5seJEdI_N7Q:b-wl3llj) ([raw file](https://github.com/utox/utox/blob/af88a7b5654766e51d1ca5079831824f96341350/src/cocoa/interaction.m#L994)):*
> ```objc
>             return;
>         }
>         
> ```

Redundant spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1034)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/cocoa/interaction.m, line 990 at r1](https://reviewable.io:443/reviews/utox/utox/1034#-KtFhg9p9V_eVYasTMFy:-KtHlZRB1L_udkBuzD6U:bjh7x61) ([raw file](https://github.com/utox/utox/blob/af88a7b5654766e51d1ca5079831824f96341350/src/cocoa/interaction.m#L990)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

`f` is never freed.
</blockquote></details>

Don't free `f`. It's the memory that holds your contact for the lifetime of the program. :P

---

*[src/cocoa/interaction.m, line 996 at r1](https://reviewable.io:443/reviews/utox/utox/1034#-KtHushEIBiFcrykN3KI:-KtHushEIBiFcrykN3KJ:b-8jqn9e) ([raw file](https://github.com/utox/utox/blob/af88a7b5654766e51d1ca5079831824f96341350/src/cocoa/interaction.m#L996)):*
> ```objc
>         
>         for (NSURL *url in urls) {
>             UTOX_MSG_FT *msg = malloc(sizeof(UTOX_MSG_FT));
> ```

You might want to use calloc so you get zeroed memory. All null checks might (probably will) fail unless you manually set all fields to null with malloc'd memory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1034)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/interaction.m, line 990 at r1](https://reviewable.io:443/reviews/utox/utox/1034#-KtFhg9p9V_eVYasTMFy:-KtI-9ySF7ptuOuHY4rW:b-2q0j3o) ([raw file](https://github.com/utox/utox/blob/af88a7b5654766e51d1ca5079831824f96341350/src/cocoa/interaction.m#L990)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Don't free `f`. It's the memory that holds your contact for the lifetime of the program. :P
</blockquote></details>

Sorry about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1034)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1034#-:-KtIbZXwqoef0DzKmtD5:bnfp4nl)*

**Comment by publicarray** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/interaction.m, line 994 at r1](https://reviewable.io:443/reviews/utox/utox/1034#-KtFhv7JWx1OChnaTXuX:-KtIb5Nf4s-BhT91rofc:b8elt90) ([raw file](https://github.com/utox/utox/blob/af88a7b5654766e51d1ca5079831824f96341350/src/cocoa/interaction.m#L994)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Redundant spaces.
</blockquote></details>

Done.  (I also changed the setting in Xcode. Why on earth would this be the default)

---

*[src/cocoa/interaction.m, line 996 at r1](https://reviewable.io:443/reviews/utox/utox/1034#-KtHushEIBiFcrykN3KI:-KtIb64AvDbnJImtyRHl:b-896fix) ([raw file](https://github.com/utox/utox/blob/af88a7b5654766e51d1ca5079831824f96341350/src/cocoa/interaction.m#L996)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You might want to use calloc so you get zeroed memory. All null checks might (probably will) fail unless you manually set all fields to null with malloc'd memory.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1034)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1034#-:-KtIdqi6G4jvBQIK5jsn:bnfp4nl)*

**Pull request merged**
