### PR TITLE
Sliding sidebar

### PR DESCRIPTION
**Pull request by jhert0**
Problems that need to be fixed:
* ~~Multiple threads are started after a double click~~
* ~~The sidebar no longer responds to clicks~~

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/916)

### CODE REVIEW

**Comment by robinlinden** [comment]
The code overall looks good with a few nits. Test doesn't link on OS X because force_redraw isn't a thing on that platform right now.

---

Reviewed 6 of 11 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/chrono.c, line 25 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX2Wasi4WgBM7iYiRb:-KkX2Wasi4WgBM7iYiRc:b5vg8b9) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/chrono.c#L25)):*
> ```C
>         *info->ptr += info->step;
>         yieldcpu(info->interval_ms);
>         force_redraw();
> ```

Should chrono really be doing UI stuff? Isn't this the job of the callback function if it's needed?

---

*[src/devices.h, line 12 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX1U1Tc7npa06YOBAX:-KkX1U1UVGxCQn_DMSXe:b3cd5yp) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/devices.h#L12)):*
> ```objc
> 
> #ifndef ENABLE_MULTIDEVICE
> // typedef uint8_t TOX_DEVICE_STATUS;
> ```

You can delete this.

---

*[src/ui.c, line 49 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX1iJdnStEg9leuwZa:-KkX1iJdnStEg9leuwZb:b-6nzv6v) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/ui.c#L49)):*
> ```C
> 
> static bool background_mdbl(PANEL *UNUSED(p), bool triclick) {
>     LOG_ERR("UI root", "bg dblclick %u", triclick);
> ```

Remove this.

---

*[src/ui.c, line 53 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX1dW1FXFrTUQmRgZM:-KkX1dW1FXFrTUQmRgZN:b-nj33dr) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/ui.c#L53)):*
> ```C
>     int step = 0;
> 
>     if (!sidebar_chrono) { //sidebar_chrono has not been initialzed
> ```

Comment isn't needed because of the `LOG_`.

---

*[src/layout/sidebar.h, line 4 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX2IpFR4XS2oj9RanF:-KkX2IpFR4XS2oj9RanG:b-yynds6) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/layout/sidebar.h#L4)):*
> ```objc
> #define LAYOUT_SIDEBAR_H
> 
> #include <stdbool.h>
> ```

This file doesn't use `bool`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916#-:-KkX304J9eOXaiFR6EZw:b-vhtfz9)*

**Comment by robinlinden** [comment]
Oh, and (optionally) the commit history could do with some cleanup if you feel like it.

**Comment by endoffile78** [comment]
Review status: 6 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/chrono.c, line 25 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX2Wasi4WgBM7iYiRb:-Kkc-OCdglve4O5_PP95:b4yunw6) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/chrono.c#L25)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Should chrono really be doing UI stuff? Isn't this the job of the callback function if it's needed?
</blockquote></details>

I changed it to use `chrono_callback` which is `yieldcpu` with a callback. 

---

*[src/ui.c, line 53 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX1dW1FXFrTUQmRgZM:-Kkc-_3doCXk7Cncq88M:b-896fix) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/ui.c#L53)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Comment isn't needed because of the `LOG_`.
</blockquote></details>

Done.

---

*[src/devices.h, line 12 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX1U1Tc7npa06YOBAX:-Kkc-bN7MKl6DoCCnESC:b-896fix) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/devices.h#L12)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You can delete this.
</blockquote></details>

Done.

---

*[src/layout/sidebar.h, line 4 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX2IpFR4XS2oj9RanF:-Kkc-cLbT1Jg9cnQLlvO:b-896fix) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/layout/sidebar.h#L4)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This file doesn't use `bool`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by robinlinden** [comment]
Reviewed 11 of 11 files at r3, 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui.c, line 638 at r4](https://reviewable.io:443/reviews/utox/utox/916#-KkqkUx6L8p8xjuSYp2O:-KkqkUx6L8p8xjuSYp2P:bc3c2hq) ([raw file](https://github.com/utox/utox/blob/76a1f0b6efc34bfdba35b930d03f5dbd1894a0f4/src/ui.c#L638)):*
> ```C
>         case PANEL_NONE: {
>             draw = background_mdbl(p, triclick);
>             return draw;
> ```

Why was this change made? Do `PANEL_NONE` never have subpanels?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by endoffile78** [comment]
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui.c, line 49 at r2](https://reviewable.io:443/reviews/utox/utox/916#-KkX1iJdnStEg9leuwZa:-KkqnGHrzJpX-qPSa4hY:b-896fix) ([raw file](https://github.com/utox/utox/blob/eb7014beb8a1c167e2140f2fd18b083711cec8fa/src/ui.c#L49)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

Done.

---

*[src/ui.c, line 638 at r4](https://reviewable.io:443/reviews/utox/utox/916#-KkqkUx6L8p8xjuSYp2O:-KkqnMKJsksvtUc7CZJH:b-5usgzv) ([raw file](https://github.com/utox/utox/blob/76a1f0b6efc34bfdba35b930d03f5dbd1894a0f4/src/ui.c#L638)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why was this change made? Do `PANEL_NONE` never have subpanels?
</blockquote></details>

I did this because it wasn't working everytime i tried to get the sidebar to slide but i just reverted it and tried and it seemed to be working everytime. I'll revert this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by robinlinden** [comment]
Reviewed 1 of 11 files at r3, 10 of 10 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 248 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vSI5f6zfjY0QDamsZ:-L2vSI5f6zfjY0QDams_:b-ofevxn) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/CMakeLists.txt#L248)):*
> ```CMake
> if (ENABLE_ASAN)
>     if (UTOX_STATIC)
>         message("ASAN is incompatible with static compilation, on some systems.")
> ```

This change doesn't belong in this PR.

---

*[src/flist.c, line 178 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vSgqkn9HB_I881PkM:-L2vSgqkn9HB_I881PkN:bow3lrp) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/src/flist.c#L178)):*
> ```C
>                     flist_draw_status_icon(status, w - SCALE(15), y + box_height / 2, f->unread_msg);
>                 }
> ```

Kill this line.

---

*[src/layout/settings.c, line 701 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vTSCS3h2nKWoeMk93:-L2vTSCS3h2nKWoeMk94:b20jtpc) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/src/layout/settings.c#L701)):*
> ```C
> }
> 
> #include "../chrono.h"
> ```

It doesn't look like any changes in this PR would affect which headers this file needs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by endoffile78** [comment]
Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 248 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vSI5f6zfjY0QDamsZ:-L2vXyEzYZHt1Y74xPlu:b-896fix) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/CMakeLists.txt#L248)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This change doesn't belong in this PR.
</blockquote></details>

Done.

---

*[src/flist.c, line 178 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vSgqkn9HB_I881PkM:-L2vXzdCmtTxaDNvwP3B:b-896fix) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/src/flist.c#L178)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Kill this line.
</blockquote></details>

Done.

---

*[src/layout/settings.c, line 701 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vTSCS3h2nKWoeMk93:-L2vY-RXuFcTiChu_2wQ:b-896fix) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/src/layout/settings.c#L701)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

It doesn't look like any changes in this PR would affect which headers this file needs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by robinlinden** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layout/settings.c, line 701 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vTSCS3h2nKWoeMk93:-L2v_t0pwsG3zagSBQp4:boj2fcc) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/src/layout/settings.c#L701)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is the other header added required? Because there are no changes to this file aside from adding the two headers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layout/settings.c, line 701 at r6](https://reviewable.io:443/reviews/utox/utox/916#-L2vTSCS3h2nKWoeMk93:-L2vbfEeYwGVuIOAp025:b-susmhs) ([raw file](https://github.com/utox/utox/blob/76f6d62989cd5037e0075857ac07678eea588695/src/layout/settings.c#L701)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Is the other header added required? Because there are no changes to this file aside from adding the two headers.
</blockquote></details>

It doesn't look like it's needed I don't know why it was added.  I removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by redmanmale** [comment]
Reviewed 5 of 11 files at r3, 7 of 10 files at r6, 2 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/flist.c, line 171 at r8](https://reviewable.io:443/reviews/utox/utox/916#-L2vfUYSUFPhDy2h2Pff:-L2vfUYTszflt1EaL5AS:bslgfnb) ([raw file](https://github.com/utox/utox/blob/95e784f3bd11a8c47c1c947794b25a3b9138b2b1/src/flist.c#L171)):*
> ```C
>             }
> 
>             if (w > 100) {
> ```

Maybe introduce some constants for this one and one below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by robinlinden** [comment]
I tested this on Windows for a bit: 
Graphics explode if I toggle the sidebar: https://imgur.com/a/1EGXE
Segv occasionally when double clicking: https://gist.github.com/robinlinden/93573639d4be254798376b242a53e45b

**Comment by GrayHatter** [comment]
Reviewed 1 of 11 files at r1, 1 of 11 files at r3, 1 of 5 files at r4.
Review status: 14 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/ui.c, line 32 at r4](https://reviewable.io:443/reviews/utox/utox/916#-KknqdCjv2r5jm8VBSWY:-KknqdCk8Pr9X5QIK5xJ:b-1wgwsl) ([raw file](https://github.com/utox/utox/blob/76a1f0b6efc34bfdba35b930d03f5dbd1894a0f4/src/ui.c#L32)):*
> ```C
> #include "ui/tooltip.h"
> 
> static CHRONO_INFO *sidebar_chrono = NULL;
> ```

This scope should be reduced to inside `background_mdbl()`.

---

*[src/windows/drawing.c, line 17 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34tZ0HXmmU8Y3UqV7z:-L34tZ0HXmmU8Y3UqV8-:bnpd0fv) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L17)):*
> ```C
> #define MAX_BITMAPS BM_ENDMARKER + 1;
> 
> void *bitmap[MAX_BITMAPS];
> ```

= {0};

---

*[src/windows/drawing.c, line 27 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34tdpbo2gPRA8SvLx0:-L34tdpbo2gPRA8SvLx1:b-b3uf17) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L27)):*
> ```C
> 
> void drawalpha(int bm, int x, int y, int width, int height, uint32_t color) {
>     if (bm > MAX_BITMAPS) {
> ```

why isn't this >= BM_ENDMARKER.

IIRC endmarker isn't a SVG we're creating; thus, we would never need to draw endmarker?

See also why we're using END_MARKER +1 we shouldn't need to add 1 to the dummy enum that signals the end number of the enumerated list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by GrayHatter** [comment]
Review status: 14 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[src/windows/drawing.c, line 53 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34uKH3HtfO0F0aE44k:-L34uKH3HtfO0F0aE44l:bibigsp) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L53)):*
> ```C
> 
>     // create temporary bitmap we'll combine the alpha and colors on
>     uint32_t *out_pixel;
> ```

windows is fucky, set the value == NULL

---

*[src/windows/drawing.c, line 54 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34uHM22dBcmJ57OBW6:-L34uHM22dBcmJ57OBW7:bob3go9) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L54)):*
> ```C
>     // create temporary bitmap we'll combine the alpha and colors on
>     uint32_t *out_pixel;
>     HBITMAP   temp = CreateDIBSection(curr->mem_DC, &bmi, DIB_RGB_COLORS, (void **)&out_pixel, NULL, 0);
> ```

does this need to be void?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Comment by endoffile78** [comment]
Review status: 13 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/ui.c, line 32 at r4](https://reviewable.io:443/reviews/utox/utox/916#-KknqdCjv2r5jm8VBSWY:-L35G_9GNz0c9eNaiGMT:bj1w4if) ([raw file](https://github.com/utox/utox/blob/76a1f0b6efc34bfdba35b930d03f5dbd1894a0f4/src/ui.c#L32)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

This scope should be reduced to inside `background_mdbl()`.
</blockquote></details>

I made it global so memory does'nt have to be allocated everytime the user double clicks.

---

*[src/windows/drawing.c, line 17 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34tZ0HXmmU8Y3UqV7z:-L35FtgdhjHfXvPVApH9:b-896fix) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L17)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

= {0};
</blockquote></details>

Done.

---

*[src/windows/drawing.c, line 27 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34tdpbo2gPRA8SvLx0:-L35FuubF0gcyjnHpvBi:b43n6xn) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L27)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why isn't this >= BM_ENDMARKER.

IIRC endmarker isn't a SVG we're creating; thus, we would never need to draw endmarker?

See also why we're using END_MARKER +1 we shouldn't need to add 1 to the dummy enum that signals the end number of the enumerated list.
</blockquote></details>

Fixed. I don't know why the + 1 is there, `BM_ENDMARKER` is just the number of bitmaps. It doesn't look necessary but maybe its something weird with windows? I can remove it if you want.

---

*[src/windows/drawing.c, line 53 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34uKH3HtfO0F0aE44k:-L35FuUVlyX5yLCEs3Ow:b-896fix) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L53)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

windows is fucky, set the value == NULL
</blockquote></details>

Done.

---

*[src/windows/drawing.c, line 54 at r9](https://reviewable.io:443/reviews/utox/utox/916#-L34uHM22dBcmJ57OBW6:-L35GKiwER-caVa0hrAm:b-ykocfo) ([raw file](https://github.com/utox/utox/blob/c767cbbdd5252ed2f4a0d0a27820f4a695633f5c/src/windows/drawing.c#L54)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

does this need to be void?
</blockquote></details>

The function is expecting `void **'`. I'm guessing the cast is there more for suppressing a warning than because it has to be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/916)*

**Pull request closed without merging**
