### PR TITLE
Force toxcore >= v0.1

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/542)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.h, line 48 at r1](https://reviewable.io:443/reviews/utox/utox/542#-KZ2CnKOFvQK8cRy0eid:-KZ2CnKOFvQK8cRy0eie:bi59fkh) ([raw file](https://github.com/utox/utox/blob/afca8e014e2200a4a91ea599fef2250161f96d83/src/main.h#L48)):*
> ```objc
> // YAY!!
> #else
>   #error "Unable to compile uTox with this Toxcore version. TOO OLD!"
> ```

This error will trigger when we reach v0.2.0 which is too new. How about "This version of uTox requires Toxcore v0.1.x" or something along those lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/542)*

**Comment by GrayHatter** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.h, line 48 at r1](https://reviewable.io:443/reviews/utox/utox/542#-KZ2CnKOFvQK8cRy0eid:-KZBwEBoG6b5JnXdi-PR:b-896fix) ([raw file](https://github.com/utox/utox/blob/afca8e014e2200a4a91ea599fef2250161f96d83/src/main.h#L48)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This error will trigger when we reach v0.2.0 which is too new. How about "This version of uTox requires Toxcore v0.1.x" or something along those lines?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/542)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/542#-:-KZCOcNxXaEh2LlCjK0N:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/542#-:-KZDOVl-5vGzsQqhgAEu:bnfp4nl)*

**Pull request merged**
