### PR TITLE
Simple flow fixes for chatlog reading

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/760)

### CODE REVIEW

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/760#-:-KdPmbDzBsP0Kz79arQT:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/760#-:-KdR1HdmAorg7N_IXKqk:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/760#-:-KdSxI-4w2z49svqrXAt:bnfp4nl)*

**Comment by GrayHatter** [comment]
rebased and merged out of order

**Pull request closed without merging**
