### PR TITLE
Minor refactor to split off the uTox code from the Toxcore code

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/534)

### CODE REVIEW

**Comment by robinlinden** [comment]
Looks good except that you forgot to change tox_message to utox_message in the cocoa files.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/534#-:-KYnMlCVBphSCQcwNhKi:b-vjbbqp)*

**Comment by GrayHatter** [comment]
Done

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/534#-:-KYoxcl9VkyOgq5KCakH:bb6un1j)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/534#-:-KYoyTF7ymfcYGLvG24K:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/534#-:-KYp20g2YMrp7KJ4Z7bb:bnfp4nl)*

**Pull request merged**
