### PR TITLE
Don't build release builds with ASAN

### LINKED ISSUE #1026: Don't build release builds with ASAN
It comes with a ~2x slowdown or so. It's fine for debug builds, but not release ones.

### PR DESCRIPTION
**Pull request by endoffile78**
closes #1026

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1096)

### CODE REVIEW

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1096#-:-Kwd3AvcVRrm4S1R4aMd:bnfp4nl)*

**Comment by GrayHatter** [comment]
see also 
#897 
#940

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1096#-:-KwgPDr2W37gdmFo-YFx:bnfp4nl)*

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1096)*

**Comment by GrayHatter** [comment]
@endoffile78 confirm you can override this setting with a command line flag, and I'll LGTM this.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1096#-:-Kwn9lUrF9VmHVGfSyKA:blfgcf8)*

**Comment by cebe** [comment]
@GrayHatter 

```
$ cmake -DENABLE_ASAN=OFF ..
...
- Add ASAN:                OFF
...
```

```
$ cmake -DENABLE_ASAN=ON ..
...
- Add ASAN:                ON
...
```

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1096)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1096#-:-KwvGOtIAj5lauvwxQC1:bnfp4nl)*

**Pull request merged**
