### PR TITLE
Fix SIGTRAP on clearing chat backlog.

### PR DESCRIPTION
**Pull request by robinlinden**
Thank you @fcore117 for the detailed bug report that made this trivial to find and fix.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/705)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/705#-:-KblnSWEQqt5Bht2MjU0:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/705#-:-Kbnnnjq9KfKtQzhCGkF:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/705#-:-KbnwEbYARpKK67PBcXh:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/705#-:-KbnyTe76oDjT3v5LRHf:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/705#-:-KbnzBafls8e4vWGO79B:bnfp4nl)*

**Pull request merged**
