### PR TITLE
Fix segv on saving inline images on Windows

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/642)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/file_transfers.h, line 67 at r1](https://reviewable.io:443/reviews/utox/utox/642#-Kb7Ouj_J1ZqaqObQRx0:-Kb7Ouja2ME71-Vg0-X7:b-7yglo4) ([raw file](https://github.com/utox/utox/blob/abe6429cf7e28a31bb417829f7dbf51a6e8eaf35/src/file_transfers.h#L67)):*
> ```objc
>     uint8_t  resume_update;
> 
>     MSG_FILE *ui_data;
> ```

YAY!!

---

*[src/windows/main.c, line 135 at r1](https://reviewable.io:443/reviews/utox/utox/642#-Kb7PEaGEO4f1HJK0kJP:-Kb7PEaHTwsHn7Vo9hjo:b-4xv7dv) ([raw file](https://github.com/utox/utox/blob/abe6429cf7e28a31bb417829f7dbf51a6e8eaf35/src/windows/main.c#L135)):*
> ```C
> 
> void file_save_inline(FILE_TRANSFER *file) {
>     char *path = (char *)calloc(1, UTOX_FILE_NAME_LENGTH);
> ```

did you need to typecast the void*?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/642)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 135 at r1](https://reviewable.io:443/reviews/utox/utox/642#-Kb7PEaGEO4f1HJK0kJP:-Kb7jOwom5k3ewmwVSGx:b-kbeoz) ([raw file](https://github.com/utox/utox/blob/abe6429cf7e28a31bb417829f7dbf51a6e8eaf35/src/windows/main.c#L135)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

did you need to typecast the void*?
</blockquote></details>

I don't need to. It's a habit from C++ programming. If we add a build to compile everything in C++ too (which I'd quite like to do) not casting would warn or error. Want me to remove the cast for now at least?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/642)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 135 at r1](https://reviewable.io:443/reviews/utox/utox/642#-Kb7PEaGEO4f1HJK0kJP:-Kb86FdoWe2JDI3j2NxF:b-3vkmqu) ([raw file](https://github.com/utox/utox/blob/abe6429cf7e28a31bb417829f7dbf51a6e8eaf35/src/windows/main.c#L135)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I don't need to. It's a habit from C++ programming. If we add a build to compile everything in C++ too (which I'd quite like to do) not casting would warn or error. Want me to remove the cast for now at least?
</blockquote></details>

yes, that's a stupid error, that if we go with C++ we'll suppress

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/642)*

**Comment by robinlinden** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 135 at r1](https://reviewable.io:443/reviews/utox/utox/642#-Kb7PEaGEO4f1HJK0kJP:-Kb8Hd_v-rsal4ZrnG6y:b-896fix) ([raw file](https://github.com/utox/utox/blob/abe6429cf7e28a31bb417829f7dbf51a6e8eaf35/src/windows/main.c#L135)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yes, that's a stupid error, that if we go with C++ we'll suppress
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/642)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/642#-:-Kb8P_nRNUfoQlUw5Yle:bnfp4nl)*

**Pull request merged**
