### PR TITLE
Add notifications and advanced settings tab

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/574)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[langs/en.h, line 709 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbhkyKFho2B6_lWDUH:-KZbhkyKFho2B6_lWDUI:b6o9oer) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/langs/en.h#L709)):*
> ```objc
> msgstr("Status Notifications")
> 
> msgid(ADV_BUTTON)
> ```

Move the two new strings up to the sorted section under a suitable header.

---

*[langs/i18n_decls.h, line 122 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbhzXmcYBIDrxqlRO2:-KZbhzXmcYBIDrxqlRO3:bh0xnz1) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/langs/i18n_decls.h#L122)):*
> ```objc
>     STR_USER_INTERFACE_BUTTON,
>     STR_AUDIO_VIDEO_BUTTON,
>     STR_ADV_BUTTON,
> ```

Maybe rename this to `STR_ADVANCED_BUTTON` since no other settings buttons are abbreviated.

---

*[src/main.c, line 49 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbb8s3RNTphXnCQrHT:-KZbb8s3RNTphXnCQrHU:bkhzluo) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/src/main.c#L49)):*
> ```C
> 
>     .window_height        = 600,
>     .window_width         = 1000,
> ```

Use MAIN_WIDTH and MAIN_HEIGHT here.

---

*[src/ui.c, line 110 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbk9MMOTlgKythUUm_:-KZbk9MNHMcu03hzZa-F:b-2h80n6) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/src/ui.c#L110)):*
> ```C
>     panel_settings_ui.y      = SCALE(32);
>     panel_settings_av.y      = SCALE(32);
>     panel_settings_adv.y     = SCALE(32);
> ```

No panel_settings_notifications?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/574)*

**Comment by endoffile78** [comment]
Review status: 5 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[langs/en.h, line 709 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbhkyKFho2B6_lWDUH:-KZcDKyluFgSKv7xZi6v:b-896fix) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/langs/en.h#L709)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Move the two new strings up to the sorted section under a suitable header.
</blockquote></details>

Done.

---

*[langs/i18n_decls.h, line 122 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbhzXmcYBIDrxqlRO2:-KZcDLgqwqaP01NTZc0-:b-896fix) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/langs/i18n_decls.h#L122)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Maybe rename this to `STR_ADVANCED_BUTTON` since no other settings buttons are abbreviated.
</blockquote></details>

Done.

---

*[src/main.c, line 49 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbb8s3RNTphXnCQrHT:-KZcDMFqN7kRcz4eJJyP:b-896fix) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/src/main.c#L49)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Use MAIN_WIDTH and MAIN_HEIGHT here.
</blockquote></details>

Done.

---

*[src/ui.c, line 110 at r1](https://reviewable.io:443/reviews/utox/utox/574#-KZbk9MMOTlgKythUUm_:-KZcDN1fxlhXZtojHjZk:b-896fix) ([raw file](https://github.com/utox/utox/blob/c260b35d50143d2e727f60c62c9908690c16b1cf/src/ui.c#L110)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

No panel_settings_notifications?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/574)*

**Comment by robinlinden** [comment]
After testing this, I can see that you need to move all items in the Notifications tab up 1 item and also increase the minimum width of the window even more. After that, this should be good to merge. You may want to rebase the [nospam PR](https://github.com/uTox/uTox/pull/513) on top of this one and add it to the advanced menu so we can merge them both and not have the advanced menu be empty.
Move items up

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/574#-:-KZfs1pzw2KLPinJ3vbs:bso0k2r)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/574#-:-KZi50yLX-AcudIof3xc:bnfp4nl)*

**Comment by endoffile78** [comment]
Merged into #550

**Pull request closed without merging**
