### PR TITLE
Improve macOS Builds

### PR DESCRIPTION
**Pull request by publicarray**
Both make and Xcode now create valid Info.plist files but only Xcode builds get the nice app icon, not quite sure why. The inclusion of more search paths for mac builds should make it easier to build the project.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/854)

### CODE REVIEW

**Comment by publicarray** [comment]
Pinging @stal888 any objections?

**Comment by stal888** [comment]
not an objection, but can't we find toxcore headers with pkgconfig?

**Comment by publicarray** [comment]
I think that is a good idea. I just have to figure out how to do it :)

**Comment by stal888** [comment]
I don't know how to operate cmake, so I'll leave the final review to @GrayHatter .

**Comment by publicarray** [comment]
@stal888 I think it would be better to do it in a separate pull request. It would make sense to use pkgconfig for filter_audio as well.

**Comment by GrayHatter** [comment]
I only know cmake enough to break it.

@cebe or @endoffile78 who seem to fix cmake files when I break them.

**Comment by GrayHatter** [comment]
:lgtm: I agree with @stal888, using pkg-config would be better. But I can't test it out, so this is better than it was!

Needs one more LGTM before merge

@publicarray if you're willing to keep contributing and helping out. We can add you to the dev list if you'd like. It'd make it easier to work on uTox, when you can merge your own branches. And we could really use an OSX dev :grin: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 279 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOddd5QY8EvbPsU9Mh:-KiOddd5QY8EvbPsU9Mi:bf9wr72) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L279)):*
> ```CMake
>     # Make apple icon
>     set(APPLE_ICON utox.icns)
>     add_custom_command(OUTPUT utox.icns
> ```

add_custom_command will delete the created files with make clean. Is this what you want? or is this something we might want to commit to the repo. (This is a question. There's no reason we can't do both)

---

*[CMakeLists.txt, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOdHXjI4Pxzbb1npwJ:-KiOdHXjI4Pxzbb1npwK:bkogvs7) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L357)):*
> ```CMake
> set_property(TARGET utox PROPERTY C_STANDARD 11)
> if(APPLE)
>     set_target_properties(utox PROPERTIES MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION})
> ```

Does this still work if we put it all in the `cocoa/CMakeLists.txt` file? 

I'm going to asume it won't but I'd still like to try it?

---

*[CMakeLists.txt, line 362 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOe-7_LUq8QUXH252r:-KiOe-7_LUq8QUXH252s:b-w1nsgl) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L362)):*
> ```CMake
>     set_target_properties(utox PROPERTIES MACOSX_BUNDLE_GUI_IDENTIFIER "org.utox.future")
>     set_target_properties(utox PROPERTIES MACOSX_BUNDLE_BUNDLE_NAME "uTox")
>     set_target_properties(utox PROPERTIES MACOSX_BUNDLE_COPYRIGHT "Copyright © 2015-2017 Tox project. All rights reserved.")
> ```

Copyright 2017 uTox Contributors, Some Rights Reserved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854#-:-KiOeDfnZDuP-6B7hDbQ:bjyh7mw)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOdHXjI4Pxzbb1npwJ:-KiQMCyLyI40gPmGCZE6:bfal2ls) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L357)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Does this still work if we put it all in the `cocoa/CMakeLists.txt` file? 

I'm going to asume it won't but I'd still like to try it?
</blockquote></details>

We could put it in a separate file and `include(cmake/osx.cmake)` or something along those lines. (Or I think that should work.)

---

*[CMakeLists.txt, line 360 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiQMQ_0FGDQi31plDjQ:-KiQMQ_0FGDQi31plDjR:bree1v1) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L360)):*
> ```CMake
>     set_target_properties(utox PROPERTIES MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION})
>     set_target_properties(utox PROPERTIES MACOSX_BUNDLE_LONG_VERSION_STRING ${PROJECT_VERSION})
>     set_target_properties(utox PROPERTIES MACOSX_BUNDLE_GUI_IDENTIFIER "org.utox.future")
> ```

Our domain is utox.io, so this should probably be `io.utox.future`
(Assuming this works the same as it does for Android packages and that stuff.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854)*

**Comment by endoffile78** [comment]
@publicarray To use pkg-config you need to add something like find_packge(Toxcore REQUIRED) and then you will probably have to write a FindToxcore.cmake and put it in the cmake directory. But what you have done is better than what we had so if you dont want to do that thats fine.

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOdHXjI4Pxzbb1npwJ:-KiQwThRCf9aCaFpQN8d:b-tn2dyp) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L357)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

We could put it in a separate file and `include(cmake/osx.cmake)` or something along those lines. (Or I think that should work.)
</blockquote></details>

nah, here is fine if it doesn't work in the cocoa dir

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854)*

**Comment by publicarray** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 279 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOddd5QY8EvbPsU9Mh:-KiQ-_nHNfs0eypJ4tjA:b-smwsno) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L279)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

add_custom_command will delete the created files with make clean. Is this what you want? or is this something we might want to commit to the repo. (This is a question. There's no reason we can't do both)
</blockquote></details>

hm I don't mind either way but adding it to the repo seems unnecessary when the file can be generated (on every mac)

---

*[CMakeLists.txt, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOdHXjI4Pxzbb1npwJ:-KiPxgJa8PPQ_mxX5RiV:b7jqwpv) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L357)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

nah, here is fine if it doesn't work in the cocoa dir
</blockquote></details>

Unfortunately set_targe_properties requires the target to be defined beforehand. +1 on the seperate files for platform specific build stuff though. Your decision of course :)

---

*[CMakeLists.txt, line 362 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOe-7_LUq8QUXH252r:-KiPyUTfgVEQYeqK2AF1:bbtd2is) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L362)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Copyright 2017 uTox Contributors, Some Rights Reserved
</blockquote></details>

I've just copied from cocoa/Info.plist should I change it there too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854)*

**Comment by publicarray** [comment]
@endoffile78 thanks for the info after a little goggling I had an attempt at pkg-config stuff. https://github.com/publicarray/uTox/tree/pkgconfig 

@GrayHatter and @robinlinden Thanks for asking me to be a dev on this awesome project. I'm just afraid of messing something up with git 😇  But I'm happy to help out, also I don't have much experience. but I see what I can do.

**Comment by GrayHatter** [comment]
@publicarray you don't have to worry about messing anything up, everything in uTox gets review by at least 1 extra developer, so there's no risk of messing anything up. (At least no additional risk, if everyone messes up the review, it was gonna happen no matter what)

Meanwhile now uTox builds on OSX again.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 279 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOddd5QY8EvbPsU9Mh:-KiRmWLE0KmQqumzIwm_:b-zem5zw) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L279)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

hm I don't mind either way but adding it to the repo seems unnecessary when the file can be generated (on every mac)
</blockquote></details>

LGTM then

---

*[CMakeLists.txt, line 357 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOdHXjI4Pxzbb1npwJ:-KiRm_CPVodL4CA1bqcD:bu9c1gp) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L357)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Unfortunately set_targe_properties requires the target to be defined beforehand. +1 on the seperate files for platform specific build stuff though. Your decision of course :)
</blockquote></details>

OK, it's a setting on the final binary. It needs to be here. and if it becomes to messy, we can add more comments.

---

*[CMakeLists.txt, line 362 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOe-7_LUq8QUXH252r:-KiRmoFwgD2Rzn69tJBa:b-n0tjw8) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L362)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

I've just copied from cocoa/Info.plist should I change it there too?
</blockquote></details>

yes please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854#-:-KiRm5DkLw7iaJQx6pcM:b-oysvqm)*

**Comment by GrayHatter** [comment]
:lgtm:

+@robinlinden 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854#-:-KiRpfx31wBxiiOr7LIS:b-w3je3k)*

**Comment by GrayHatter** [comment]
-@robinlinden +@endoffile78 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854#-:-KiRprxmd5o5IKbUyPam:b-du0c20)*

**Comment by publicarray** [comment]
@GrayHatter OK than. You convinced me :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 362 at r1](https://reviewable.io:443/reviews/utox/utox/854#-KiOe-7_LUq8QUXH252r:-KiRoJufQP4m5AsYqtY-:b-535ue0) ([raw file](https://github.com/utox/utox/blob/42397ef38b00aa75f6878ddbb51c7176ee37f123/CMakeLists.txt#L362)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yes please
</blockquote></details>

done :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854#-:-KiRoy4lGRZs-rh85SDU:bdjz29w)*

**Comment by publicarray** [comment]
Sorry I didn't realise that I just added unnecessary overhead with my comment on Reviewable.

**Comment by robinlinden** [comment]
:lgtm: but I still think we should try to move platform-specific CMakeMagic to files we include in order to keep the main one clean. Can be done after this PR if anyone feels like it though.

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/854#-:-KiRs5JLDTJsx83_zwwo:bvyk1jf)*

**Comment by stal888** [comment]
closing thoughts: i miss the old bundle identifier, `future.utox`

**Pull request merged**
