### PR TITLE
Create filter_audio.c

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/936)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/filter_audio.c, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/936#-KlFGMAa1KWegK-iu0m0:-KlFGMAbaFJ8XIlLoccT:b-ttuc4e) ([raw file](https://github.com/utox/utox/blob/62e5525bc73ac1cf225354f0f29596773db2385d/src/av/filter_audio.c#L5)):*
> ```C
> #include "audio.h"
> 
> #include "../settings.h"
> ```

Don't do any state in the file at all, just return what the UI cares about.

That way we can test it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/936)*

**Comment by endoffile78** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/filter_audio.c, line 5 at r1](https://reviewable.io:443/reviews/utox/utox/936#-KlFGMAa1KWegK-iu0m0:-KlH_ab8a_Jxsf583T6V:b-896fix) ([raw file](https://github.com/utox/utox/blob/62e5525bc73ac1cf225354f0f29596773db2385d/src/av/filter_audio.c#L5)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Don't do any state in the file at all, just return what the UI cares about.

That way we can test it later.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/936)*

**Comment by GrayHatter** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/av/filter_audio.c, line 5 at r2](https://reviewable.io:443/reviews/utox/utox/936#-KlHhgwdgzIRbPOw2eb7:-KlHhgwdgzIRbPOw2eb8:bvz5wco) ([raw file](https://github.com/utox/utox/blob/637e9a4ac0a5e8b7464643fe9b649cab914f1e1b/src/av/filter_audio.c#L5)):*
> ```C
> #include "audio.h"
> 
> #include "../settings.h"
> ```

drop this include now

---

*[src/av/filter_audio.c, line 22 at r2](https://reviewable.io:443/reviews/utox/utox/936#-KlHhkMayQOPGpQpj80J:-KlHhkMayQOPGpQpj80K:blfvoje) ([raw file](https://github.com/utox/utox/blob/637e9a4ac0a5e8b7464643fe9b649cab914f1e1b/src/av/filter_audio.c#L22)):*
> ```C
>             LOG_INFO("Filter Audio", "filter audio failed" );
>             return false;
>         } else { // no return is needed for this one because it is already true
> ```

no else after return;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/936)*

**Comment by endoffile78** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/av/filter_audio.c, line 5 at r2](https://reviewable.io:443/reviews/utox/utox/936#-KlHhgwdgzIRbPOw2eb7:-KlJzAI36OuxYo3va3Xk:b-j85gc4) ([raw file](https://github.com/utox/utox/blob/637e9a4ac0a5e8b7464643fe9b649cab914f1e1b/src/av/filter_audio.c#L5)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

drop this include now
</blockquote></details>

It's still needed. Its use in the if and else if and its returned.

---

*[src/av/filter_audio.c, line 22 at r2](https://reviewable.io:443/reviews/utox/utox/936#-KlHhkMayQOPGpQpj80J:-KlJzG4ZgZ_i5JoLhJV6:b-896fix) ([raw file](https://github.com/utox/utox/blob/637e9a4ac0a5e8b7464643fe9b649cab914f1e1b/src/av/filter_audio.c#L22)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no else after return;
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/936)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/936#-:-KlK-phsAeANDg-Xhtts:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/936#-:-Kmycm2zQjhuzfoJObqY:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/936)*

**Pull request merged**
