### PR TITLE
Add debug option to CMakeLists.txt

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/503)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 40 at r1](https://reviewable.io:443/reviews/utox/utox/503#-KXI7tN0L37lUSIV6zrO:-KXI7tN1iSsL7Ms0nlf6:bidnfea) ([raw file](https://github.com/utox/utox/blob/887d306f530d440bd0753b8df7b235375ab77ff4/CMakeLists.txt#L40)):*
> ```CMake
> option(DEBUG "Enable debugging symbols" OFF)
> if(DEBUG)
>   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g3")
> ```

Maybe also `set(CMAKE_BUILD_TYPE Debug)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/503)*

**Comment by endoffile78** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 40 at r1](https://reviewable.io:443/reviews/utox/utox/503#-KXI7tN0L37lUSIV6zrO:-KXI9sJQDyvngx5nda7n:b-896fix) ([raw file](https://github.com/utox/utox/blob/887d306f530d440bd0753b8df7b235375ab77ff4/CMakeLists.txt#L40)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Maybe also `set(CMAKE_BUILD_TYPE Debug)`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/503)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/503#-:-KXI9vwttZk8SMf1AHv9:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/503)*

**Comment by GrayHatter** [comment]
doesn't -DCMAKE_BUILD_TYPE=Debug already do this?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/503#-:-KXJ4m1mOmw2kcIvhwq7:bisorrf)*

**Comment by endoffile78** [comment]
@GrayHatter Yeah it does it didnt know about that. I can revert this if you want me to.

**Comment by GrayHatter** [comment]
yeah, let's do that

**Pull request merged**
