### PR TITLE
Add compiler support for dbus

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/690)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/690#-:-KbYLvHf6k_pfIAxEeG5:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/690)*

**Comment by GrayHatter** [comment]
@grayhatter do something like this https://github.com/TokTok/c-toxcore/blob/master/cmake/Dependencies.cmake#L52

**Comment by GrayHatter** [comment]
rebased

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/xlib/CMakeLists.txt, line 11 at r3](https://reviewable.io:443/reviews/utox/utox/690#-KdPkRlZeCJs-7asOLNa:-KdPkRlZeCJs-7asOLNb:b-jv3rn5) ([raw file](https://github.com/utox/utox/blob/ef6a2e1d36bcf5031a9e9bf1b96d792024cca61b/src/xlib/CMakeLists.txt#L11)):*
> ```CMake
>     add_cflag("-DHAVE_DBUS=1")
> else()
>     add_cflag("-DNO_DBUS=1")
> ```

this is not needed, we only check for `#ifdef HAVE_DBUS` in the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/690#-:-KdPkuN0rxGloP0z2na4:bnfp4nl)*

**Pull request closed without merging**
