### PR TITLE
removed superflous newlines in log messages

### PR DESCRIPTION
**Pull request by cebe**
not needed because `"\n"` is appended to each log message anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/749)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/749#-:-Kd7Rgp6y0MWeGLcs36r:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/749#-:-Kd7eymhGCiYk4VWGRA-:bnfp4nl)*

**Comment by cebe** [comment]
rebased.

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/749#-:-KdA9qOkSKnSkEB8VW59:bnfp4nl)*

**Comment by mannol** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/749#-:-KdADUjW19zY8AFPkpye:bnfp4nl)*

**Comment by mannol** [comment]
Reviewed 24 of 26 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/749)*

**Pull request merged**
