### PR TITLE
Reload tray icon after Windows Explorer crash

### LINKED ISSUE #1004: Reload tray icon after Windows Explorer crash
Launch uTox, kill Windows Explorer and uTox still works but tray icon do not appear anymore until you restart uTox.

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #1004.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1010)

### CODE REVIEW

**Comment by GrayHatter** [comment]
I'd rather register the text when we use it. IIRC the default case isn't called that often so leaving that UINT in the "global" scope is 'naughty'

**Comment by redmanmale** [comment]
Default case is firing pretty often when I'm testing this.
And it doesn't work if that UINT is not static, I tried.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010#-:-KwuM8loM8N0dW98ZSPQ:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/events.c, line 113 at r1](https://reviewable.io:443/reviews/utox/utox/1010#-KxKrbDZs8NEDX8AGLy2:-KxKrbDadMtt3PpPQjTy:bi8cxvd) ([raw file](https://github.com/utox/utox/blob/86bbb017c403d8ab42da92e4c289fc53d4a89ec6/src/windows/events.c#L113)):*
> ```C
>     static bool mdown = false;
>     static int mdown_x, mdown_y;
>     static UINT taskbar_created;
> ```

don't use UINT, windows macros and typedefs are crap we want to avoid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010)*

**Comment by redmanmale** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/events.c, line 113 at r1](https://reviewable.io:443/reviews/utox/utox/1010#-KxKrbDZs8NEDX8AGLy2:-KxUZOSDZRath_nJYOnF:b-896fix) ([raw file](https://github.com/utox/utox/blob/86bbb017c403d8ab42da92e4c289fc53d4a89ec6/src/windows/events.c#L113)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

don't use UINT, windows macros and typedefs are crap we want to avoid.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010#-:-KxUnLw9UpDAjI-av14k:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/events.c, line 113 at r3](https://reviewable.io:443/reviews/utox/utox/1010#-Kxj0wJpOGCItiTtKTlz:-Kxj0wJpOGCItiTtKTm-:b-v58bmp) ([raw file](https://github.com/utox/utox/blob/91760253091e0a87e0042d96f4e75dc34a8ef6ab/src/windows/events.c#L113)):*
> ```C
>     static bool mdown = false;
>     static int mdown_x, mdown_y;
>     static uint16_t taskbar_created;
> ```

This should be an `unsigned` or you're not able to hold all return values of RegisterWindowMessage. (UINT is just a typedef of unsigned and can be anything above 16 bits. On most OSes it will be 32, but it will be 64 on some even today.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010)*

**Comment by redmanmale** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/events.c, line 113 at r3](https://reviewable.io:443/reviews/utox/utox/1010#-Kxj0wJpOGCItiTtKTlz:-KxjAQvmfd6tYHf6aBNf:b-896fix) ([raw file](https://github.com/utox/utox/blob/91760253091e0a87e0042d96f4e75dc34a8ef6ab/src/windows/events.c#L113)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This should be an `unsigned` or you're not able to hold all return values of RegisterWindowMessage. (UINT is just a typedef of unsigned and can be anything above 16 bits. On most OSes it will be 32, but it will be 64 on some even today.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010#-:-KxjDdVzVTQA3wTtR9Ft:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1010#-:-KxnW-7N_KB8cO-S4X8L:bnfp4nl)*

**Pull request merged**
