### PR TITLE
Better error checking for xlib/video.c

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1130)

### CODE REVIEW

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 88 at r1](https://reviewable.io:443/reviews/utox/utox/1130#-Kzx8JtCIMA7gJdnivK1:-Kzx8JtCIMA7gJdnivK2:b-dritqn) ([raw file](https://github.com/utox/utox/blob/67709b9530e12c1358c2963d5a5ac659536d8287/src/xlib/video.c#L88)):*
> ```C
>         new_data = malloc(attrs.width * attrs.height * 4);
>         if (!new_data) {
>             LOG_DEBUG("Video", "Could not allocate memory for scaled imeage.");
> ```

Typo: `imeage`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1130#-:-Kzx8d8WPhE1TBUzT33v:bnfp4nl)*

**Comment by endoffile78** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 88 at r1](https://reviewable.io:443/reviews/utox/utox/1130#-Kzx8JtCIMA7gJdnivK1:-KzxRNEDNxjYJ0FmUnNL:b-896fix) ([raw file](https://github.com/utox/utox/blob/67709b9530e12c1358c2963d5a5ac659536d8287/src/xlib/video.c#L88)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Typo: `imeage`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1130)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 88 at r2](https://reviewable.io:443/reviews/utox/utox/1130#-L0GpiWZismRk988Ys14:-L0GpiW_Zlmc-Y2k6YCC:b-fjczs4) ([raw file](https://github.com/utox/utox/blob/58a2a086557c7b05caa80b9ce10f7853fadec5e0/src/xlib/video.c#L88)):*
> ```C
>         new_data = malloc(attrs.width * attrs.height * 4);
>         if (!new_data) {
>             LOG_DEBUG("Video", "Could not allocate memory for scaled image.");
> ```

this is a malloc error, use the fatal_err here

theres' a branch somewhere with a macro that makes this easy, anyone remember where?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1130)*

**Comment by endoffile78** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 88 at r2](https://reviewable.io:443/reviews/utox/utox/1130#-L0GpiWZismRk988Ys14:-L0kDy9IlzRWgKC0ksFz:b-896fix) ([raw file](https://github.com/utox/utox/blob/58a2a086557c7b05caa80b9ce10f7853fadec5e0/src/xlib/video.c#L88)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this is a malloc error, use the fatal_err here

theres' a branch somewhere with a macro that makes this easy, anyone remember where?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1130)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1130#-:-L0kG9LQVgEqC20J07O5:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1130#-:-L0kGuoVmjYjmixUY9ul:bnfp4nl)*

**Pull request merged**
