### PR TITLE
Add timestamps to messages in chatlog

### PR DESCRIPTION
**Pull request by dkmoz**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/953)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/chatlog.c, line 254 at r1](https://reviewable.io:443/reviews/utox/utox/953#-Kn5duKp2yUXX_UZhXjZ:-Kn5duKp2yUXX_UZhXj_:bkxbr5q) ([raw file](https://github.com/utox/utox/blob/28a28baa1791c09228aa4b58a65810366e2043cf/src/chatlog.c#L254)):*
> ```C
>     FILE *file = chatlog_get_file(hex, false);
> 
>     char buffer[128];
> ```

Move this to the scope in which it's used.

---

*[src/chatlog.c, line 255 at r1](https://reviewable.io:443/reviews/utox/utox/953#-Kn5dm2tcQgkesWFQIbZ:-Kn5dm2tcQgkesWFQIb_:b-lrf9u) ([raw file](https://github.com/utox/utox/blob/28a28baa1791c09228aa4b58a65810366e2043cf/src/chatlog.c#L255)):*
> ```C
> 
>     char buffer[128];
>     time_t timetmp = time(NULL);
> ```

This doesn't seem to be used.

---

*[src/chatlog.c, line 256 at r1](https://reviewable.io:443/reviews/utox/utox/953#-Kn5dWLm11DksOIEVMv9:-Kn5dWLnM8JuC7b8rFd4:bevmw3n) ([raw file](https://github.com/utox/utox/blob/28a28baa1791c09228aa4b58a65810366e2043cf/src/chatlog.c#L256)):*
> ```C
>     char buffer[128];
>     time_t timetmp = time(NULL);
>     struct tm tm_curr, tm_prev = {0, 0, 0, 1, 0, 0, 0, 0};
> ```

Initialise this like `{ .tm_day = 1 }`.

---

*[src/chatlog.c, line 260 at r1](https://reviewable.io:443/reviews/utox/utox/953#-Kn5eHH46WLDcFXpt5zK:-Kn5eHH46WLDcFXpt5zL:b5axz3p) ([raw file](https://github.com/utox/utox/blob/28a28baa1791c09228aa4b58a65810366e2043cf/src/chatlog.c#L260)):*
> ```C
>     while (fread(&header, sizeof(header), 1, file) == 1) {
> 
>         localtime_r(&header.time, &tm_curr);
> ```

`localtime_r` isn't defined in the C standard. Would `localtime_s` work instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/953)*

**Comment by robinlinden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/chatlog.c, line 256 at r1](https://reviewable.io:443/reviews/utox/utox/953#-Kn5dWLm11DksOIEVMv9:-Kn5wAJcE9sZx-V4jtmn:b-ltstwr) ([raw file](https://github.com/utox/utox/blob/28a28baa1791c09228aa4b58a65810366e2043cf/src/chatlog.c#L256)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Initialise this like `{ .tm_day = 1 }`.
</blockquote></details>

Struct members not initialised are always set to 0, so you only have to initialise day here. (This is up to you though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/953)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/953#-:-Kn5xu_s150FrjUfOr3t:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/953#-:-Kn60Ffkml0qtvm1p4oQ:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/953#-:-Kn62-vZpNSsgW2qSX5F:bnfp4nl)*

**Comment by dkmoz** [comment]
Not sure what was the deal with gcc and localtime_s but localtime should work

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/chatlog.c, line 263 at r4](https://reviewable.io:443/reviews/utox/utox/953#-KnWIln5x3CMr3auEQDF:-KnWIln5x3CMr3auEQDG:bhuf533) ([raw file](https://github.com/utox/utox/blob/682a6f61252d3d2e10eee0a9802f5734f0a087f0/src/chatlog.c#L263)):*
> ```C
>     while (fread(&header, sizeof(header), 1, file) == 1) {
> 
>         tm_curr = localtime(&header.time);
> ```

I would've preferred it if this were `struct tm *tm_curr =..`, but this is not blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/953#-:-KnWIxX6gd-oLbF62910:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/953#-:-Kn_kWbUI_Kw5MoRssJQ:bnfp4nl)*

**Pull request merged**
