### PR TITLE
Make uTox save the language you set.

### LINKED ISSUE #96: Language settings don't save after changing
How to reproduce:
- open Tox;
- change language to another;
- close Tox;
- open again: language will be the same before changing.

This happens only with language, other settings save correctly.

Win 7 x64, Win 8.1 x64. v.0.4.4.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29267893-language-settings-don-t-save-after-changing?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by robinlinden**
Fixes #96 (I didn't even know that was assigned to me. :x )

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/890)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/890#-:-KizpkIwjwC5tyvPQhFI:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/settings.c, line 90 at r1](https://reviewable.io:443/reviews/utox/utox/890#-Kj1dmTK-uRd2-t4YTjy:-Kj1dmTK-uRd2-t4YTjz:brb8lzl) ([raw file](https://github.com/utox/utox/blob/e64e956d6eded3fd50f25569ae68131088c3e930/src/settings.c#L90)):*
> ```C
> 
> // TODO refactor to match same order in main.h
> UTOX_SAVE *config_load(void) {
> ```

Consider refactoring and doing the sanity checks in this function, then calling a new `static` function to do the actual setting of the state.

---

*[src/settings.c, line 125 at r1](https://reviewable.io:443/reviews/utox/utox/890#-Kj1dZMTiR9qNfPYNW78:-Kj1dZMTiR9qNfPYNW79:b-gwgz2i) ([raw file](https://github.com/utox/utox/blob/e64e956d6eded3fd50f25569ae68131088c3e930/src/settings.c#L125)):*
> ```C
>     /* UX Settings */
> 
>     dropdown_language.selected = dropdown_language.over = settings.language = save->language;
> ```

What if it's NULL? Will this reset the system default?

---

*[src/layout/settings.c, line 1097 at r1](https://reviewable.io:443/reviews/utox/utox/890#-Kj1cm43833KpWr7Xs5G:-Kj1cm43833KpWr7Xs5H:bu3d0tw) ([raw file](https://github.com/utox/utox/blob/e64e956d6eded3fd50f25569ae68131088c3e930/src/layout/settings.c#L1097)):*
> ```C
> 
> static void dropdown_language_onselect(uint16_t i, const DROPDOWN *UNUSED(dm)) {
>     settings.language = (UTOX_LANG)i;
> ```

Is this typecast needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/890)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/settings.c, line 90 at r1](https://reviewable.io:443/reviews/utox/utox/890#-Kj1dmTK-uRd2-t4YTjy:-Kj2SyhIrT7l6SUk8InC:bz533jz) ([raw file](https://github.com/utox/utox/blob/e64e956d6eded3fd50f25569ae68131088c3e930/src/settings.c#L90)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Consider refactoring and doing the sanity checks in this function, then calling a new `static` function to do the actual setting of the state.
</blockquote></details>

Out of scope for this PR.

---

*[src/settings.c, line 125 at r1](https://reviewable.io:443/reviews/utox/utox/890#-Kj1dZMTiR9qNfPYNW78:-Kj2SrMNAElUOjPDEzZJ:b9zk53q) ([raw file](https://github.com/utox/utox/blob/e64e956d6eded3fd50f25569ae68131088c3e930/src/settings.c#L125)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

What if it's NULL? Will this reset the system default?
</blockquote></details>

NULL is English. We never saved the system default, so it doesn't reset anything. We could add a button that sets the dropdown to the system default or alternatively add a language to the dropdown that always uses the system default.

---

*[src/layout/settings.c, line 1097 at r1](https://reviewable.io:443/reviews/utox/utox/890#-Kj1cm43833KpWr7Xs5G:-Kj2T-gYzye29B0Wl3jp:b-3j3hzk) ([raw file](https://github.com/utox/utox/blob/e64e956d6eded3fd50f25569ae68131088c3e930/src/layout/settings.c#L1097)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Is this typecast needed?
</blockquote></details>

Yes. `settings.language` is a `UTOX_LANG` and `i` is an `uint16_t`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/890)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/890#-:-Kj35AiyuuF1wukyepJa:bnfp4nl)*

**Pull request merged**
