### PR TITLE
Replace native_load_data and native_save_data with native_get_file

### PR DESCRIPTION
**Pull request by endoffile78**
What needs to be done:
 * Windows version (GrayHatter said he would do it)
 * ~Replace native_load_data and native_save_data (started doesn't work yet)~

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/466)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 5 of 10 files at r1.
Review status: 5 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 102 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqK62SI7glICPsr1c0:-KVqK62SI7glICPsr1c1:b-tsdlsh) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/main.c#L102)):*
> ```C
> bool utox_data_save_utox(UTOX_SAVE *data, size_t length) {
>     uint8_t name[] = "utox_save";
>     size_t size;
> ```

set = 0; 

---

*[src/main.c, line 118 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqK-BKjV9lnoxGj6Zb:-KVqK-BLpO4RCueISpQP:b-iko20m) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/main.c#L118)):*
> ```C
> 
> UTOX_SAVE *utox_data_load_utox(void) {
>     uint8_t name[] = "utox_save", *data;
> ```

use UTOX_SAVE so we don't have to typecast as often

---

*[src/android/main.c, line 294 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJ3xEyzr97805hNKM:-KVqJ3xFDOcoCkR82bOE:b-tkvvq9) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/android/main.c#L294)):*
> ```C
>     snprintf((char *)path, UTOX_FILE_NAME_LENGTH, ANDROID_INTERNAL_SAVE);
> 
>     if (strlen((const char *)path) + name_length >= UTOX_FILE_NAME_LENGTH) {
> ```

there's no name length here

---

*[src/android/main.c, line 310 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJtWUVVtA0TjGt0cL:-KVqJtWVxDxe51Jx86sm:bvexiq) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/android/main.c#L310)):*
> ```C
> 
>     fseek(fp, 0, SEEK_END);
>     *size = ftell(fp);
> ```

if not null

---

*[src/cocoa/main.m, line 326 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJUfR_8EtGhwdPVGY:-KVqJUfSp29NeOu3_MuU:b-eyp2ei) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/cocoa/main.m#L326)):*
> ```objc
> }
> 
> FILE *native_get_file(uint8_t *name, size_t *size, char *flag) {
> ```

try to use char when you can, we can type cast to u8 when we need utf-8

---

*[src/cocoa/main.m, line 352 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJguBA5BNNbQiTZCP:-KVqJguCmVCqKExoj7D1:b-luydo6) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/cocoa/main.m#L352)):*
> ```objc
> 
>     fseek(fp, 0, SEEK_END);
>     *size = ftell(fp);
> ```

if size != NULL

---

*[src/xlib/main.c, line 334 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJq7WrSuiMRN_zac0:-KVqJq7WrSuiMRN_zac1:bvexiq) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/xlib/main.c#L334)):*
> ```C
> 
>     fseek(fp, 0, SEEK_END);
>     *size = ftell(fp);
> ```

if not null

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by robinlinden** [comment]
Reviewed 1 of 10 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 58 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwDmLIWI9_3uScCynO:-KVwDY_PCXJzHoqO8AP2:bn1zkj3) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/src/main.c#L58)):*
> ```C
>     FILE *fp = native_get_file((char *)name, &length, "wb");
>     if (fp == NULL) {
>         return true;
> ```

Return true on failure?

---

*[src/main.c, line 65 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwE34IoQcq-veAIyX0:-KVwE34IoQcq-veAIyX1:b-2briq3) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/src/main.c#L65)):*
> ```C
>     fclose(fp);
> 
>     return false;
> ```

Return false on success?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 102 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqK62SI7glICPsr1c0:-KVwu4gCJ-XOFGi5dVfB:b-896fix) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/main.c#L102)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> set = 0; 
</details>
Done.

---

*[src/main.c, line 118 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqK-BKjV9lnoxGj6Zb:-KVwu5Jkletsu8SA4IkK:b-896fix) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/main.c#L118)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> use UTOX_SAVE so we don't have to typecast as often
</details>
Done.

---

*[src/main.c, line 58 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwDmLIWI9_3uScCynO:-KVwtyBTsj3eT_wZUnL9:byf5qzj) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/src/main.c#L58)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Return true on failure?
</details>
The result of this fuction is saved to a global variable called save_needed so if this function fails a save is needed and if succeeds then one is not needed currently.

---

*[src/android/main.c, line 294 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJ3xEyzr97805hNKM:-KVwu6GdyR4T0AxFg3Eg:b-896fix) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/android/main.c#L294)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> there's no name length here
</details>
Done.

---

*[src/android/main.c, line 310 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJtWUVVtA0TjGt0cL:-KVwu6gachdwXtGUski3:b-896fix) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/android/main.c#L310)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> if not null
</details>
Done.

---

*[src/cocoa/main.m, line 326 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJUfR_8EtGhwdPVGY:-KVwu7Ap0Ha1-gWp7JC1:b-896fix) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/cocoa/main.m#L326)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> try to use char when you can, we can type cast to u8 when we need utf-8
</details>
Done.

---

*[src/cocoa/main.m, line 352 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJguBA5BNNbQiTZCP:-KVwu7leawThmSY4X4ee:b-896fix) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/cocoa/main.m#L352)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> if size != NULL
</details>
Done.

---

*[src/xlib/main.c, line 334 at r1](https://reviewable.io:443/reviews/utox/utox/466#-KVqJq7WrSuiMRN_zac0:-KVwu8JU5Cb6BruYJZR7:b-896fix) ([raw file](https://github.com/utox/utox/blob/632cf921d49d97912dec7fa33b3c50e0e47dc5c2/src/xlib/main.c#L334)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> if not null
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by GrayHatter** [comment]
Reviewed 5 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 36 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwC4yySfSq5-BidWJM:-KVwC4yySfSq5-BidWJN:bp5wnlj) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/.gitignore#L36)):*
> ```
> CMakeFiles
> cmake_install.cmake
> CMakeCache.txt
> ```

reviewable is strange , is there a newline here?

---

*[src/main.c, line 58 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwDmLIWI9_3uScCynO:-KVx75yebUmNLwBYSBSe:b19go19) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/src/main.c#L58)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary>
> The result of this fuction is saved to a global variable called save_needed so if this function fails a save is needed and if succeeds then one is not needed currently.
</details>
you can use !utox_data_save_tox(); to reverse the use of this function. That said, that's a really bad way to check if a save is needed (I know I wrote that code, its' still really bad)

---

*[src/main.c, line 65 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwE34IoQcq-veAIyX0:-KVx7JA-tK0AnU4Gy-C_:b-d36p7o) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/src/main.c#L65)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Return false on success?
</details>
Yeah if a function is bool the common style is report the success, (so you can `if (function_worked())` when it's an int each number means something different, and 0 being first, is known as everything worked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by GrayHatter** [comment]
Review status: 5 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main.c, line 87 at r3](https://reviewable.io:443/reviews/utox/utox/466#-KWL9IvaYtqGajr0dQtq:-KWL9IvaYtqGajr0dQtr:b-6tkktl) ([raw file](https://github.com/utox/utox/blob/d46919ef76ec27e1643355baf1b7917561b929ad/src/main.c#L87)):*
> ```C
>             debug("Could not allocate memory.\n");
>             fclose(fp);
>             break; //quit were out of memory, calloc will fail again
> ```

return instead

---

*[src/main.c, line 93 at r3](https://reviewable.io:443/reviews/utox/utox/466#-KWL9Lx3G7CKeX5ovBAH:-KWL9Lx3G7CKeX5ovBAI:b-x5bnhc) ([raw file](https://github.com/utox/utox/blob/d46919ef76ec27e1643355baf1b7917561b929ad/src/main.c#L93)):*
> ```C
>             fclose(fp);
>             free(data);
>             continue;
> ```

return as well and add a comment `// return because if this file exits we don't want to fall back to an old version, we need the user to decide`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by GrayHatter** [comment]
Review status: 5 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main.c, line 96 at r3](https://reviewable.io:443/reviews/utox/utox/466#-KWLA61ympoUNJN8YWXX:-KWLA61ympoUNJN8YWXY:b-sp1qig) ([raw file](https://github.com/utox/utox/blob/d46919ef76ec27e1643355baf1b7917561b929ad/src/main.c#L96)):*
> ```C
>         }
>         fclose(fp);
>         return data;
> ```

set *size here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by endoffile78** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main.c, line 87 at r3](https://reviewable.io:443/reviews/utox/utox/466#-KWL9IvaYtqGajr0dQtq:-KWLXDssAC2kYvIqmf0I:b-896fix) ([raw file](https://github.com/utox/utox/blob/d46919ef76ec27e1643355baf1b7917561b929ad/src/main.c#L87)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> return instead
</details>
Done.

---

*[src/main.c, line 93 at r3](https://reviewable.io:443/reviews/utox/utox/466#-KWL9Lx3G7CKeX5ovBAH:-KWLXD_MnV8j5sUq8Bsn:b-896fix) ([raw file](https://github.com/utox/utox/blob/d46919ef76ec27e1643355baf1b7917561b929ad/src/main.c#L93)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> return as well and add a comment `// return because if this file exits we don't want to fall back to an old version, we need the user to decide`
</details>
Done.

---

*[src/main.c, line 96 at r3](https://reviewable.io:443/reviews/utox/utox/466#-KWLA61ympoUNJN8YWXX:-KWLWU5MNZo5Uo55ngK9:b-896fix) ([raw file](https://github.com/utox/utox/blob/d46919ef76ec27e1643355baf1b7917561b929ad/src/main.c#L96)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> set *size here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by endoffile78** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.c, line 58 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwDmLIWI9_3uScCynO:-KWPY6Zd5VnT3aHntqhl:b-896fix) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/src/main.c#L58)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> you can use !utox_data_save_tox(); to reverse the use of this function. That said, that's a really bad way to check if a save is needed (I know I wrote that code, its' still really bad)
</details>
Done.

---

*[src/main.c, line 65 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwE34IoQcq-veAIyX0:-KWPY73ywF3vwN3w5lCj:b-896fix) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/src/main.c#L65)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Yeah if a function is bool the common style is report the success, (so you can `if (function_worked())` when it's an int each number means something different, and 0 being first, is known as everything worked.
</details>
Done.

---

*[.gitignore, line 36 at r2](https://reviewable.io:443/reviews/utox/utox/466#-KVwC4yySfSq5-BidWJM:-KWPY8kb7GnATuPcdNAf:b-896fix) ([raw file](https://github.com/utox/utox/blob/b5cb19922da99d1a8e3ab0a50c179596a7b69dcf/.gitignore#L36)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> reviewable is strange , is there a newline here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 10 files at r1, 6 of 10 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/466)*

**Pull request merged**
