### PR TITLE
v0.11.0 to master

### PR DESCRIPTION
**Pull request by GrayHatter**
@endoffile78 @robinlinden no need to actually review, just want you to be aware.

And maybe hit the LGTM button, master enforces the checks on admins.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/540)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: 0 of 174 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/540#-:-KYr4B3NwL4sOPqKgy2Z:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 177 of 177 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/540)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/540#-:-KYrS03IndSr_P53i_EQ:bg7igkv)*

**Comment by robinlinden** [comment]
Reviewed 177 of 177 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/540)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 177 of 177 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/540#-:-KYs4ntuYjTXruTLtCBb:bnfp4nl)*

**Pull request merged**
