### PR TITLE
Fix webcam issues on XLIB

### LINKED ISSUE #873: Clicking on webcam makes uTox crash 0.15.0
Hi as per title whenever I click on the webcam icon, webcam light blinks and then uTox crashes.
It used to work perfectly in the previous version therefore I don't think.

I am on Lubuntu 16.04.01

If you need more info please let me know (sorry if this bug report is incomplete, this is my first bug report on github)

### PR DESCRIPTION
**Pull request by GrayHatter**
closes #873

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/909)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909#-:-KjuTPJA9_DwaG4KdZ9i:bnfp4nl)*

**Comment by GrayHatter** [comment]
@cebe @robinlinden @redmanmale I just assigned all of you, you can fight for the 2nd :lgtm:

**Comment by GrayHatter** [comment]
#874 as well

**Comment by robinlinden** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 179 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCu3UUqPyo2YVvcv27:-KkCu3UVwdiX05nVJm5n:bpg3eaf) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/CMakeLists.txt#L179)):*
> ```CMake
>     # Enable Link Time Optimization on Clang
>     if(ENABLE_LTO)
>         set(SAVE_CMAKE_REQUIRED_LIBRARIES "${CMAKE_REQUIRED_LIBRARIES}")
> ```

You should add a comment on what you're doing here. This looks really wrong.

---

*[src/xlib/main.h, line 87 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCuEfpONNFfs_YvjhB:-KkCuEfqoUZNa2H-vPx7:bqka3oe) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/main.h#L87)):*
> ```objc
> 
> // Brute Force, the video window we got a close command on (xlib/video.c)
> uint32_t brtfrs_video_windows(Window w);
> ```

"brtfrs" doesn't make any sense. `find_video_window` or something similar? You should also mention what uint32_max and uint16_max as return values mean.

---

*[src/xlib/video.c, line 22 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCucGLZbnO4MusVAIK:-KkCucGLZbnO4MusVAIL:by0m5u8) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L22)):*
> ```C
> #include <sys/shm.h>
> 
> Window video_win[32]; // TODO we should allocate this dynamically but this'll work for now
> ```

These look like they could be static.

---

*[src/xlib/video.c, line 42 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCvXQTNrgBgj4-EfeC:-KkCvXQTNrgBgj4-EfeD:b-yq3oh6) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L42)):*
> ```C
> 
> void video_frame(uint32_t id, uint8_t *img_data, uint16_t width, uint16_t height, bool resize) {
>     Window *win = &video_win[id];
> ```

Sure `video_win[UINT16_MAX]` is a good idea? Maybe you should assign null here and give it a value in an if .. else .. construct instead.

---

*[src/xlib/video.c, line 93 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCwD8hPukVnXlau_hn:-KkCwD8hPukVnXlau_ho:b2nreh6) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L93)):*
> ```C
> 
> void video_begin(uint32_t id, char *name, uint16_t name_length, uint16_t width, uint16_t height) {
>     Window *win = &video_win[id];
> ```

Same as above.

---

*[src/xlib/video.c, line 122 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCw8fywAf_R0Wm3GZL:-KkCw8fzJumsV1B6nPvX:b2nreh6) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L122)):*
> ```C
> 
> void video_end(uint32_t id) {
>     Window *win = &video_win[id];
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909)*

**Comment by endoffile78** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 179 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCu3UUqPyo2YVvcv27:-Kmye1te7Qvh9V8EIlyu:b-896fix) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/CMakeLists.txt#L179)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You should add a comment on what you're doing here. This looks really wrong.
</blockquote></details>

Done.

---

*[src/xlib/main.h, line 87 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCuEfpONNFfs_YvjhB:-KmyeXzZz-I9SrSPCeve:b-896fix) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/main.h#L87)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

"brtfrs" doesn't make any sense. `find_video_window` or something similar? You should also mention what uint32_max and uint16_max as return values mean.
</blockquote></details>

Done.

---

*[src/xlib/video.c, line 22 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCucGLZbnO4MusVAIK:-Kn0Uj-27e7mak9y-8u9:b-896fix) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L22)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

These look like they could be static.
</blockquote></details>

Done.

---

*[src/xlib/video.c, line 42 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCvXQTNrgBgj4-EfeC:-Kn0UozPz7B8iUs0eIR7:bv5o70m) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L42)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Sure `video_win[UINT16_MAX]` is a good idea? Maybe you should assign null here and give it a value in an if .. else .. construct instead.
</blockquote></details>

id is a number, it can't be null, and 0 is the start of the array. -1 or UINT_MAX is the right thing to use here.

---

*[src/xlib/video.c, line 93 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCwD8hPukVnXlau_hn:-Kn0UzDGblzLrQ0lnNmy:bv5o70m) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L93)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

id is a number, it can't be null, and 0 is the start of the array. -1 or UINT_MAX is the right thing to use here.

---

*[src/xlib/video.c, line 122 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCw8fywAf_R0Wm3GZL:-Kn0UzuOgG7j5HwSjbT3:bv5o70m) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L122)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

id is a number, it can't be null, and 0 is the start of the array. -1 or UINT_MAX is the right thing to use here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909#-:-Kn0VmH1c1UxX64yRhaj:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 42 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCvXQTNrgBgj4-EfeC:-Kn0tFLHIHvn-YvSt2Kq:bq6xlex) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L42)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

id is a number, it can't be null, and 0 is the start of the array. -1 or UINT_MAX is the right thing to use here.
</blockquote></details>

Per IRC -1 would be `uint32_max` and break everything. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909)*

**Comment by GrayHatter** [comment]
Review status: 5 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 42 at r1](https://reviewable.io:443/reviews/utox/utox/909#-KkCvXQTNrgBgj4-EfeC:-Kn0wweBhuaJ-Bck1MyA:b-mzl64x) ([raw file](https://github.com/utox/utox/blob/5e20fb04550e7c289c3dd1c3506b630bf141dcef/src/xlib/video.c#L42)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Per IRC -1 would be `uint32_max` and break everything. 
</blockquote></details>

whoopsies, fixed.

thanks @robinlinden 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909#-:-Kn0zSNF72yK-C-Z27VF:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909#-:-Kn0zXEleYtTeeOgXUfB:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909#-:-Kn113eYA4DBXzGuPfe8:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/909#-:-Kn1LGsFx3txK3BDr22T:bnfp4nl)*

**Pull request merged**
