### PR TITLE
Added Native file functions to Windows

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/490)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 146 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3blhW10dUvDIz4J-K:-KX3blhX4U8QGhlsKGQJ:b89f2p) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/main.c#L146)):*
> ```C
>     snprintf(name, sizeof(name), "%.*s.ftinfo", TOX_PUBLIC_KEY_SIZE * 2, hex);
> 
>     FILE *fp = native_get_file(name, NULL, UTOX_FILE_OPTS_READ);
> ```

UTOX_FILE_OPTS_WRITE

---

*[src/windows/main.c, line 200 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gKUn94Nbmf68flpb:-KX3gKUn94Nbmf68flpc:b8wti5x) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L200)):*
> ```C
> 
> ```

Are all these line breaks intentional?

---

*[src/windows/main.c, line 221 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gYlJFJshmxk9UIuC:-KX3gYlJFJshmxk9UIuD:b-8jmj7b) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L221)):*
> ```C
> 
> void init_ptt(void) {
>     settings.push_to_talk = 1;
> ```

1 -> true

---

*[src/windows/main.c, line 227 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gVt8bFDNuUQ2kNZB:-KX3gVt8bFDNuUQ2kNZC:b-74hhco) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L227)):*
> ```C
>     if (!settings.push_to_talk) {
>         // debug("PTT is disabled\n");
>         return 1; /* If push to talk is disabled, return true. */
> ```

These should be true or false.

---

*[src/windows/main.c, line 240 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gbMPMWIsID9cls4S:-KX3gbMPMWIsID9cls4T:bm91i21) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L240)):*
> ```C
> 
> void exit_ptt(void) {
>     settings.push_to_talk = 0;
> ```

0 -> false

---

*[src/xlib/main.c, line 188 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3ggYNY1XKR24vJyIi:-KX3ggYOdjTrOx5z1cgq:b7td9cn) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/xlib/main.c#L188)):*
> ```C
> }
> 
> #if 0
> ```

Leave a comment saying why this is here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/490)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/main.c, line 146 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3blhW10dUvDIz4J-K:-KX3hkXJw1JibE4Rp3wJ:b-896fix) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/main.c#L146)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> UTOX_FILE_OPTS_WRITE
</details>
Done.

---

*[src/windows/main.c, line 200 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gKUn94Nbmf68flpb:-KX3hlZcr6jTdt-0n5Al:bkb1tl4) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L200)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Are all these line breaks intentional?
</details>
Yes, I'm going to sort and reformat, and hopefully add a new file.

---

*[src/windows/main.c, line 221 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gYlJFJshmxk9UIuC:-KX3ht_q2qcsY7xqdmSC:b-896fix) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L221)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> 1 -> true
</details>
Done.

---

*[src/windows/main.c, line 227 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gVt8bFDNuUQ2kNZB:-KX3iGpckl7oFNpHFgmk:b-896fix) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L227)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> These should be true or false.
</details>
Done.

---

*[src/windows/main.c, line 240 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3gbMPMWIsID9cls4S:-KX3igQ241rYJFApB1FB:b-896fix) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/windows/main.c#L240)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> 0 -> false
</details>
Done.

---

*[src/xlib/main.c, line 188 at r2](https://reviewable.io:443/reviews/utox/utox/490#-KX3ggYNY1XKR24vJyIi:-KX3isqAoeRb5Gc6j3Lm:b-896fix) ([raw file](https://github.com/utox/utox/blob/4c13f0467aa72ce6d8e76b714493f5637454f92c/src/xlib/main.c#L188)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Leave a comment saying why this is here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/490)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/490#-:-KX3kHAr6tz_yCaQnkZi:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/490)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: 6 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/490#-:-KXJw0AgfpUCaALKrlB5:bnfp4nl)*

**Comment by endoffile78** [comment]
Reviewed 1 of 8 files at r1, 1 of 3 files at r2, 4 of 6 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/490)*

**Pull request merged**
