### PR TITLE
Entry Level cmake system.

### PR DESCRIPTION
**Pull request by GrayHatter**
breaks dysym GTK3

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/456)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[CMakeLists.txt, line 17 at r1](https://reviewable.io:443/reviews/utox/utox/456#-KVlPhQLkBYN8ENuT2_W-r1-17:-KVlQjwd11R_wJbJtwyT:b-896fix) ([raw file](https://github.com/utox/utox/blob/a40ebf5f3a0513bb8ef97c19aea1ef1437383a49/CMakeLists.txt#L17)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary>
> duplicate of line 4
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/456)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/456#-:-KVlS6HSjDmH1bAymOIp:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 142 at r2](https://reviewable.io:443/reviews/utox/utox/456#-KVlTZw8RLO_ZTl2wkp6:-KVlTZw9sHmgjNIllhrS:b-2utj6o) ([raw file](https://github.com/utox/utox/blob/d513d78a86856b80ed250c68a57f420b8d093dff/CMakeLists.txt#L142)):*
> ```CMake
>     src/messages.h
>     src/sized_string.h
>     src/stb_image.h
> ```

Duplicate line.

---

*[CMakeLists.txt, line 144 at r2](https://reviewable.io:443/reviews/utox/utox/456#-KVlTfZu0zXGOWTLhP5O:-KVlTfZu0zXGOWTLhP5P:b-2utj6o) ([raw file](https://github.com/utox/utox/blob/d513d78a86856b80ed250c68a57f420b8d093dff/CMakeLists.txt#L144)):*
> ```CMake
>     src/stb_image.h
>     src/stb_image.h
>     src/stb_image_write.h
> ```

Duplicate line.

---

*[CMakeLists.txt, line 148 at r2](https://reviewable.io:443/reviews/utox/utox/456#-KVlTgzLRgaKeTVR6-Q0:-KVlTgzLRgaKeTVR6-Q1:b-2utj6o) ([raw file](https://github.com/utox/utox/blob/d513d78a86856b80ed250c68a57f420b8d093dff/CMakeLists.txt#L148)):*
> ```CMake
>     src/theme.c
>     src/theme.h
>     src/theme_tables.h
> ```

Duplicate line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/456)*

**Comment by GrayHatter** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 142 at r2](https://reviewable.io:443/reviews/utox/utox/456#-KVlTZw8RLO_ZTl2wkp6:-KVlUMva2ohrR6yA3rc2:b-896fix) ([raw file](https://github.com/utox/utox/blob/d513d78a86856b80ed250c68a57f420b8d093dff/CMakeLists.txt#L142)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Duplicate line.
</details>
Done.

---

*[CMakeLists.txt, line 144 at r2](https://reviewable.io:443/reviews/utox/utox/456#-KVlTfZu0zXGOWTLhP5O:-KVlUO6PCvsa6exF0aRX:b-896fix) ([raw file](https://github.com/utox/utox/blob/d513d78a86856b80ed250c68a57f420b8d093dff/CMakeLists.txt#L144)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Duplicate line.
</details>
Done.

---

*[CMakeLists.txt, line 148 at r2](https://reviewable.io:443/reviews/utox/utox/456#-KVlTgzLRgaKeTVR6-Q0:-KVlUOakXHf_FIUtWRg4:b-896fix) ([raw file](https://github.com/utox/utox/blob/d513d78a86856b80ed250c68a57f420b8d093dff/CMakeLists.txt#L148)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> Duplicate line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/456)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 9 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/456#-:-KVlYs_B7Fo87F_JP0Gj:bnfp4nl)*

**Comment by GrayHatter** [comment]
this is already merged

**Pull request closed without merging**
