### PR TITLE
Fix cmake so linux can cross compile all versions

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/993)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/993#-:-Ks1ATnJm5Jk3MEa2rsp:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 302 at r2](https://reviewable.io:443/reviews/utox/utox/993#-KsAj178ph-l1SXgEVe5:-KsAj178ph-l1SXgEVe6:b-6tez6w) ([raw file](https://github.com/utox/utox/blob/f0640abb36633d903a8455a35e176ad96d647297/CMakeLists.txt#L302)):*
> ```CMake
>     ############################################################
> 
>     if(WIN32)
> ```

Always true here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/993)*

**Comment by GrayHatter** [comment]
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 302 at r2](https://reviewable.io:443/reviews/utox/utox/993#-KsAj178ph-l1SXgEVe5:-KsOx5vnb_QTNRZjlRTo:b-896fix) ([raw file](https://github.com/utox/utox/blob/f0640abb36633d903a8455a35e176ad96d647297/CMakeLists.txt#L302)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Always true here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/993)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/993#-:-KsP7CrJyl1DAenr9ekk:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/993#-:-KsPED_V-rddhum4Se6i:bnfp4nl)*

**Pull request merged**
