### PR TITLE
Version Tick v0.12.1 to v0.12.2

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/692)

### CODE REVIEW

**Comment by robinlinden** [comment]
Was the inclusion of the dbus commits in this PR intentional?

**Comment by GrayHatter** [comment]
@robinlinden nope

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/692#-:-KbaYR7aLiV_Y30NLK-5:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/692#-:-Kbag5T9nfrELnExPYBU:bnfp4nl)*

**Pull request merged**
