### PR TITLE
Log call info to disk

### LINKED ISSUE #322: message log should contain information on calls
Messages currently do not contain information on `Call started` and `Call ended` anymore.
it should also indicate when switching from video to audio mode and back.

### PR DESCRIPTION
**Pull request by dkmoz**
Call start, end and the duration is logged. Fixes #322 and #238 (partly)

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/963)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963#-:-Knp6fshOtFmWHFWOll7:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/chatlog.c, line 294 at r1](https://reviewable.io:443/reviews/utox/utox/963#-Ko9EInquBlkXVX9v2HX:-Ko9EInquBlkXVX9v2HY:bwrrzh1) ([raw file](https://github.com/utox/utox/blob/ede5c491171a231011e1af1f926c8a69d4e71962/src/chatlog.c#L294)):*
> ```C
>             fwrite(">", 1, 1, dest_file);
>         }
>         
> ```

Stray whitespace.

---

*[src/av/utox_av.c, line 124 at r1](https://reviewable.io:443/reviews/utox/utox/963#-KpZgUNv39Zx4T8CPcOY:-KpZgUNv39Zx4T8CPcOZ:b110bh9) ([raw file](https://github.com/utox/utox/blob/ede5c491171a231011e1af1f926c8a69d4e71962/src/av/utox_av.c#L124)):*
> ```C
>                     if (f->call_started != 0) {
>                         char notice_msg[64];
>                         double duration = difftime(time(NULL), f->call_started);
> ```

Maybe make this `int duration` and cast the return value of difftime since it's always used as an integer anyway. Would let you drop the casts on the coming lines.

---

*[src/av/utox_av.c, line 143 at r1](https://reviewable.io:443/reviews/utox/utox/963#-KpZg5M9nWr37T05cOEw:-Ko9Hi5eV_xhVTLOFiL7:bwrrzh1) ([raw file](https://github.com/utox/utox/blob/ede5c491171a231011e1af1f926c8a69d4e71962/src/av/utox_av.c#L143)):*
> ```C
>                         f->call_started = 0;
>                     }
>                     
> ```

Stray whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by robinlinden** [comment]
The call started and call ended should probably also be translatable language strings.

**Comment by dkmoz** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/chatlog.c, line 294 at r1](https://reviewable.io:443/reviews/utox/utox/963#-Ko9EInquBlkXVX9v2HX:-KpcvETV51H-lh_E4qtm:b-896fix) ([raw file](https://github.com/utox/utox/blob/963cd511c6ec91cb2f3e2dfbc0c99cacafea0bc6/src/chatlog.c#L294)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Stray whitespace.
</blockquote></details>

Done.

---

*[src/av/utox_av.c, line 124 at r1](https://reviewable.io:443/reviews/utox/utox/963#-KpZgUNv39Zx4T8CPcOY:-KpcvKQCqL0erZlkgtfe:b-896fix) ([raw file](https://github.com/utox/utox/blob/963cd511c6ec91cb2f3e2dfbc0c99cacafea0bc6/src/av/utox_av.c#L124)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Maybe make this `int duration` and cast the return value of difftime since it's always used as an integer anyway. Would let you drop the casts on the coming lines.
</blockquote></details>

Done.

---

*[src/av/utox_av.c, line 143 at r1](https://reviewable.io:443/reviews/utox/utox/963#-KpZg5M9nWr37T05cOEw:-KpcvL1v6z42UzVITQ5a:b-896fix) ([raw file](https://github.com/utox/utox/blob/963cd511c6ec91cb2f3e2dfbc0c99cacafea0bc6/src/av/utox_av.c#L143)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Stray whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/av/utox_av.c, line 70 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2S8BkprFcO9tD-13A:-Kr2S8BkprFcO9tD-13B:bk79dw4) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L70)):*
> ```C
>                     FRIEND *f = get_friend(msg->param1);
>                     f->call_started = time(NULL);
>                     message_add_type_notice(&f->msg, "Call started", 12, true); // log to disk
> ```

`"Call started"` should be moved to the language file and made translatable.
(If you don't want to do that in this PR, add back the `//TODO localization with S() SLEN()`)

---

*[src/av/utox_av.c, line 128 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2Rdi_PwkaHDBgp4Dh:-Kr2Rdi_PwkaHDBgp4Di:bh95n1j) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L128)):*
> ```C
>                         int minutes = (duration / 60) % 60;
>                         int seconds = duration % 60;
>                         int length = snprintf(notice_msg, 64, "Call ended:");
> ```

`"Call ended:"` should be moved to the language file and made translatable.

---

*[src/av/utox_av.c, line 131 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2T2zllGm8KJPDv-QU:-Kr2T2zllGm8KJPDv-QV:by5iroj) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L131)):*
> ```C
> 
>                         if (hours) {
>                             length += snprintf(notice_msg + length, 64 - length, " %d hours", hours);
> ```

Probably print the time in ISO8601 extended format (hh:mm:ss) so you don't have to localise this and add support for single hours, minutes, and seconds. :P
I think printing `00:03:15` for a 3m 15s call would be acceptable and universal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by dkmoz** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/av/utox_av.c, line 70 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2S8BkprFcO9tD-13A:-Kr5NUsz_FIDvkfcYNp0:b-896fix) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L70)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`"Call started"` should be moved to the language file and made translatable.
(If you don't want to do that in this PR, add back the `//TODO localization with S() SLEN()`)
</blockquote></details>

Done.

---

*[src/av/utox_av.c, line 128 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2Rdi_PwkaHDBgp4Dh:-Kr5NW0lLedXJbDfll-5:b-896fix) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L128)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`"Call ended:"` should be moved to the language file and made translatable.
</blockquote></details>

Done.

---

*[src/av/utox_av.c, line 131 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2T2zllGm8KJPDv-QU:-Kr4Xxe_1tcAF7gAUeW_:b-896fix) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L131)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Probably print the time in ISO8601 extended format (hh:mm:ss) so you don't have to localise this and add support for single hours, minutes, and seconds. :P
I think printing `00:03:15` for a 3m 15s call would be acceptable and universal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963#-:-Kr6RoISsjQoAGECQaaz:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 3 files at r1, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/av/utox_av.c, line 70 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2S8BkprFcO9tD-13A:-Kr71l9ZiTUabdKM35pz:b-w35ilo) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L70)):*
<details><summary><i>Previously, dkmoz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no, you need SLEN() instead of 12, otherwise different languages can over/underrun

---

*[src/av/utox_av.c, line 126 at r3](https://reviewable.io:443/reviews/utox/utox/963#-Kr72iOcA4D4dApjifPR:-Kr72iOcA4D4dApjifPS:bq0jyya) ([raw file](https://github.com/utox/utox/blob/d2a96bc50cb521f445d9947a386c0b0fa12a684c/src/av/utox_av.c#L126)):*
> ```C
>                         char notice_msg[64];
>                         int duration = difftime(time(NULL), f->call_started);
>                         int length = snprintf(notice_msg, 64, "%s: %02u:%02u:%02u",
> ```

verify that `length < 64`, if it's not error, and exit early

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 2 files at r2, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by dkmoz** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/av/utox_av.c, line 70 at r2](https://reviewable.io:443/reviews/utox/utox/963#-Kr2S8BkprFcO9tD-13A:-KrJsN6loF4T2WlrcOLd:b-896fix) ([raw file](https://github.com/utox/utox/blob/05037e9bab7192ce0fb78b196896339dcac0ee03/src/av/utox_av.c#L70)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no, you need SLEN() instead of 12, otherwise different languages can over/underrun
</blockquote></details>

Done.

---

*[src/av/utox_av.c, line 126 at r3](https://reviewable.io:443/reviews/utox/utox/963#-Kr72iOcA4D4dApjifPR:-KrJsOtRgMFVhd0CVOHx:b-896fix) ([raw file](https://github.com/utox/utox/blob/d2a96bc50cb521f445d9947a386c0b0fa12a684c/src/av/utox_av.c#L126)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

verify that `length < 64`, if it's not error, and exit early
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/av/utox_av.c, line 128 at r4](https://reviewable.io:443/reviews/utox/utox/963#-KrN-CPPJDA9eaLYJqGz:-KrN-CPPJDA9eaLYJqH-:b7z7erf) ([raw file](https://github.com/utox/utox/blob/9e6e3b9e589aef75c420643ba840bcdce118fa24/src/av/utox_av.c#L128)):*
> ```C
>                         int length = snprintf(notice_msg, 64, "%s: %02u:%02u:%02u",
>                                 S(CALL_ENDED), duration / 3600, (duration / 60) % 60, duration % 60);
> 						if (length < 64)
> ```

if's must have {}, even for single lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by dkmoz** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/av/utox_av.c, line 128 at r4](https://reviewable.io:443/reviews/utox/utox/963#-KrN-CPPJDA9eaLYJqGz:-KrOs5ieouCmqiSdv5Dk:b-896fix) ([raw file](https://github.com/utox/utox/blob/9e6e3b9e589aef75c420643ba840bcdce118fa24/src/av/utox_av.c#L128)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

if's must have {}, even for single lines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963#-:-KrPNQuVJQBCzrcXQ6l9:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963#-:-KrRMCYrHIG5M6vpSZtn:bnfp4nl)*

**Comment by GrayHatter** [comment]
+@robinlinden 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963#-:-Ks00QOwsfNSST43VgvT:bm4pyxg)*

**Comment by robinlinden** [comment]
Leaving this for 0.17.0 since it adds more strings and we've already merged the translations for 0.16.0.

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/963#-:-KsjLwGwl8y9Ze7m3n5u:bnfp4nl)*

**Pull request merged**
