### PR TITLE
Fix crash on video preview

### PR DESCRIPTION
**Pull request by endoffile78**
Fixes (#873)

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/876)

### CODE REVIEW

**Comment by robinlinden** [comment]
Awesome job finding and fixing this! :lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 69 at r1](https://reviewable.io:443/reviews/utox/utox/876#-KiofRFvAqvy69JefAJI:-KiofRFvAqvy69JefAJJ:b-epk6ll) ([raw file](https://github.com/utox/utox/blob/60b2c08d035f1f3faddc78851c9327f77aca22d6/src/xlib/video.c#L69)):*
> ```C
> 
>     if (id >= 32) {
>         LOG_ERR("Videp", "id is too large. Got %u exptected it to be less than 32", id);
> ```

Typos: video, expected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/876#-:-KiofejwHgM9ZMCXKlQc:bx05lrt)*

**Comment by endoffile78** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/video.c, line 69 at r1](https://reviewable.io:443/reviews/utox/utox/876#-KiofRFvAqvy69JefAJI:-Kiog_ixbT_h1Ex0yaRX:b-896fix) ([raw file](https://github.com/utox/utox/blob/60b2c08d035f1f3faddc78851c9327f77aca22d6/src/xlib/video.c#L69)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Typos: video, expected
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/876)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/876)*

**Comment by GrayHatter** [comment]
This fix is backwards, UINT16_MAX is the preview window. Else friend number 0 will conflict with the preview window. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/876#-:-KipWmioXuu14nfo_3OY:bsmy5hs)*

**Pull request closed without merging**
