### PR TITLE
Idle status

### PR DESCRIPTION
**Pull request by redmanmale**
aka auto away (#325) aka presence state (#167).

After some configurable time of inactivity (no mousemoves or keystrokes) your status will be automatically changed to `away`. In case of activity it will be changed back to `online`.

* save settings
* UI: switch for on/off, label and input for value
* Windows: timer to check for last user activity
* Linux: select() and check for last user activity via x11 screensaver extensions **libxss-dev** (it's used everywhere)
* macOS: timer to check for last user activity (implemented by @publicarray)

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1071)

### CODE REVIEW

**Comment by redmanmale** [comment]
@publicarray
Could you help me with macOS part?

**Comment by publicarray** [comment]
@redmanmale Yea I'll look into it. Do you want me to add commits to this pr?

**Comment by publicarray** [comment]
There is a race condition when the status has switched to idle (due to inactivity) and the user quickly  (before the code switches the status) presses the status button to become online. The idle code will no longer switch to idle status automatically.

**Comment by redmanmale** [comment]
Thank you very much @publicarray!

**Comment by publicarray** [comment]
You are very welcome :smile: Love to help.

**Comment by publicarray** [comment]
This is just a guess but I don't think `!PLATFORM_ANDROID` is needed. Isn't the file only imported, compiled and linked on MacOS?

**Comment by redmanmale** [comment]
Yes, it's a little overkill, but I want to use the same condition `!DISABLE_IDLE_STATUS && !PLATFORM_ANDROID` everywhere.

**Comment by publicarray** [comment]
IMHO I prefer to keep platform specific stuff tied to that platform and not sprinkle it over to other platforms.

**Comment by GrayHatter** [comment]
I'll re-review once there's not an #ifdef in every file.

+@grayhatter 

---

Reviewed 3 of 11 files at r1.
Review status: 3 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[langs/en.h, line 495 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNXpHk_UiqYEje98j:-KwfNXpHk_UiqYEje98k:b-53gd2p) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/langs/en.h#L495)):*
> ```objc
>  * Status name (Away) should be the same as STATUS_AWAY
>  */
> #if !DISABLE_IDLE_STATUS && !PLATFORM_ANDROID
> ```

don't add an #if here

---

*[langs/i18n_decls.h, line 169 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNDXrxQE_kkc20r_a:-KwfNDXrxQE_kkc20r_b:baox1cy) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/langs/i18n_decls.h#L169)):*
> ```objc
>     STR_SETTINGS_UI_AUTO_HIDE_SIDEBAR,
> 
>     #if !DISABLE_IDLE_STATUS && !PLATFORM_ANDROID
> ```

these should always exist. Even if they're not used no a platform... 

poor android...

---

*[langs/ru.h, line 416 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNaYRrwTsD7guvuwa:-KwfNaYRrwTsD7guvuwb:b-myq78a) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/langs/ru.h#L416)):*
> ```objc
>  * Название статуса (не на месте) должно быть таким же, как STATUS_AWAY
>  */
> #if !DISABLE_IDLE_STATUS && !PLATFORM_ANDROID
> ```

no #if

---

*[src/settings.c, line 73 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNokbvDg5QxajyONF:-KwfNokbvDg5QxajyONG:by61svv) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/src/settings.c#L73)):*
> ```C
>     .magic_flist_enabled    = false,
> 
>     #if !DISABLE_IDLE_STATUS && !PLATFORM_ANDROID
> ```

I'm gonna stop commenting but I don't like #if's unless they're features you have a strong reason to compile in/out. X11 must exist, so Xss is a fine dependency to add.

If you really want to be pedantic, you could detect for the existence of Xss, and then just disable the option via the UI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1071#-:-KwfOIAYNCRux8b4klfm:b467t7b)*

**Comment by redmanmale** [comment]
@GrayHatter 
Can I just drop DISABLE_IDLE_STATUS option and always require X11 package?

**Comment by redmanmale** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[langs/en.h, line 495 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNXpHk_UiqYEje98j:-KwkqxYBu-6PdqmHx0rJ:b-896fix) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/langs/en.h#L495)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

don't add an #if here
</blockquote></details>

Done.

---

*[langs/i18n_decls.h, line 169 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNDXrxQE_kkc20r_a:-KwkqyN2wRCf6Vi-BI8e:b-896fix) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/langs/i18n_decls.h#L169)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

these should always exist. Even if they're not used no a platform... 

poor android...
</blockquote></details>

Done.

---

*[langs/ru.h, line 416 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNaYRrwTsD7guvuwa:-Kwkqz7THCcgwpFOEpU1:b-896fix) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/langs/ru.h#L416)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no #if
</blockquote></details>

Done.

---

*[src/settings.c, line 73 at r3](https://reviewable.io:443/reviews/utox/utox/1071#-KwfNokbvDg5QxajyONF:-Kwkqzw_2GQSq5_VOqAG:b-896fix) ([raw file](https://github.com/utox/utox/blob/41e201c0e285866a2b0552a2464defae35c6491c/src/settings.c#L73)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I'm gonna stop commenting but I don't like #if's unless they're features you have a strong reason to compile in/out. X11 must exist, so Xss is a fine dependency to add.

If you really want to be pedantic, you could detect for the existence of Xss, and then just disable the option via the UI
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1071)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1071#-:-KwuLM7unTiQA38ANEY7:bnfp4nl)*

**Comment by GrayHatter** [comment]
@redmanmale I think you have dropped DISABLE_IDLE_STATUS, which is fine. But this is going to take me some time to review. I'm not convinced XNextEventTimed is the best way to go about this, so I'll have to do a little research.

If you want to merge this sooner, you can wrap the xlib stuff in an #ifdef 0 and comments as to why, then I can just review the Windows stuff which on first glance looks fine.

---

Reviewed 2 of 12 files at r4, 2 of 6 files at r5.
Review status: 8 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1071#-:-KxP9sqwfRFtcHG8it0F:b-b36uq7)*

**Comment by redmanmale** [comment]
I don't like to merge unfinished features so I'll wait for your review.
But I hope we'll have this in next release (0.17.0), otherwise I'd prefer to comment out Xlib part as you said.

---

Review status: 8 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1071#-:-KxUcx0fMK04YRB8ll2D:b5t0zi4)*

**Comment by robinlinden** [comment]
Reviewed 6 of 12 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[CMakeLists.txt, line 301 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBvFbEOp-_rQe9x2SX:-KyBvFbEOp-_rQe9x2SY:b-iikt0i) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/CMakeLists.txt#L301)):*
> ```CMake
> set(LIBRARIES ${LIBRARIES} ${LIBSODIUM_LIBRARIES})
> 
> if(UNIX AND NOT APPLE)
> ```

@endoffile78 Can you test this on whateverBSD?

---

*[langs/en.h, line 499 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBqm-wh1KMDVKMUe_8:-KyBqm-xrxeZXHc3arU5:b-bgjhgc) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/langs/en.h#L499)):*
> ```objc
>  */
> msgid(SETTINGS_IDLE_STATUS)
> msgstr("Show me as Away after")
> ```

You should probably combine this string with the one below and add a %u format specifier for the number to make localisation less of a chore.

---

*[src/settings.c, line 73 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBr0VorCqnjB39id_C:-KyBr0VorCqnjB39id_D:bkvry2p) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/settings.c#L73)):*
> ```C
>     .magic_flist_enabled    = false,
> 
>     // TODO: Add to save
> ```

Can this be done now that the .ini PR is merged?

---

*[src/cocoa/main.m, line 41 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBs-C-z9RwfBXCOwVo:-KyBs-C-z9RwfBXCOwVp:bo1wajv) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/cocoa/main.m#L41)):*
> ```objc
> #define DEFAULT_HEIGHT (320 * DEFAULT_SCALE)
> 
> struct utox_self *tox_self; // reference to self from self.h
> ```

Make this static.

---

*[src/layout/settings.c, line 1419 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBsY6g5ewy5qKAghC7:-KyBsY6g5ewy5qKAghC8:b9jinz4) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/layout/settings.c#L1419)):*
> ```C
> static void edit_idle_interval_onenter(EDIT *UNUSED(edit)) {
>     edit_idle_interval.data[edit_idle_interval.length] = 0;
>     settings.idle_interval = strtol((char *)edit_idle_interval.data, NULL, 0);
> ```

What happens when settings.idle_interval is set to 0? (If strtol fails.) Should we do some sanity/bound checking here?

---

*[src/windows/main.c, line 813 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBsnAnyzbO-y0WTmip:-KyBsnAoj4smXhhzXKf_:b-b103n8) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/windows/main.c#L813)):*
> ```C
> 
> static void CALLBACK idle_handler(HWND UNUSED(hwnd), UINT UNUSED(message), UINT UNUSED(idTimer), DWORD dwTime)
> {
> ```

Move this to the line above. (1TBS)

---

*[src/windows/main.c, line 823 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBtFObLlA_Ix7K_9bT:-KyBtFObLlA_Ix7K_9bU:b-bj1p3q) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/windows/main.c#L823)):*
> ```C
>     GetLastInputInfo(&last_active);
> 
>     if (dwTime - last_active.dwTime > (uint16_t)(settings.idle_interval * 1000 * 60)) {
> ```

This should probably not be cast to an uint16_t since 2 seconds would mean that the number we're casting is 120 000 and a bit bigger than what an uint16 can contain.

---

*[src/xlib/main.c, line 753 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBuwHJ6c9RIcNU5kTX:-KyBuwHKGD0vLO1B-Tb0:bdu1ydv) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/xlib/main.c#L753)):*
> ```C
>             tv->tv_usec = 0;
>             return false;
>         } else {
> ```

You can let this fall through to the end of the function where this code also exists.

---

*[src/xlib/main.c, line 757 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBuyUXikL3yp1lD4Jd:-KyBuyUXikL3yp1lD4Je:b-jdnqk3) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/xlib/main.c#L757)):*
> ```C
>             return true;
>         }
>     } else {
> ```

No else after return.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1071)*

**Comment by GrayHatter** [comment]
bump

**Comment by redmanmale** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[langs/en.h, line 499 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBqm-wh1KMDVKMUe_8:-L4gWFYBaKYENIQTsI_l:b-rncird) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/langs/en.h#L499)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You should probably combine this string with the one below and add a %u format specifier for the number to make localisation less of a chore.
</blockquote></details>

I can't do it just like that because it used in the different UI labels.

---

*[src/settings.c, line 73 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBr0VorCqnjB39id_C:-L4gW3mBZbm3ZaosPme4:b-896fix) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/settings.c#L73)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Can this be done now that the .ini PR is merged?
</blockquote></details>

Done.

---

*[src/cocoa/main.m, line 41 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBs-C-z9RwfBXCOwVo:-L4gW51XrwpY26e7dJaA:b-896fix) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/cocoa/main.m#L41)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Make this static.
</blockquote></details>

Done.

---

*[src/layout/settings.c, line 1419 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBsY6g5ewy5qKAghC7:-L4gW67iQdfGP3v9EWko:b-896fix) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/layout/settings.c#L1419)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

What happens when settings.idle_interval is set to 0? (If strtol fails.) Should we do some sanity/bound checking here?
</blockquote></details>

Done.

---

*[src/windows/main.c, line 813 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBsnAnyzbO-y0WTmip:-L4gW7Nr63l0dDdmKH7e:b-896fix) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/windows/main.c#L813)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Move this to the line above. (1TBS)
</blockquote></details>

Done.

---

*[src/windows/main.c, line 823 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBtFObLlA_Ix7K_9bT:-L4gW8JAO4BWdAYus8TD:b-896fix) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/windows/main.c#L823)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This should probably not be cast to an uint16_t since 2 seconds would mean that the number we're casting is 120 000 and a bit bigger than what an uint16 can contain.
</blockquote></details>

Done.

---

*[src/xlib/main.c, line 753 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBuwHJ6c9RIcNU5kTX:-L4gW9EyOf524d_SoDVM:b-896fix) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/xlib/main.c#L753)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You can let this fall through to the end of the function where this code also exists.
</blockquote></details>

Done.

---

*[src/xlib/main.c, line 757 at r5](https://reviewable.io:443/reviews/utox/utox/1071#-KyBuyUXikL3yp1lD4Jd:-L4gWA-9bww3Gb2F8t07:b-896fix) ([raw file](https://github.com/utox/utox/blob/cc5f233342de2e56fed289cff58ca8cb9b37a143/src/xlib/main.c#L757)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

No else after return.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1071)*

**Comment by redmanmale** [comment]
It's been a while... Can we merge this?

**Comment by GrayHatter** [comment]
Robin is away on vacation, he'll have to take a look when he gets back.

---

Reviewed 2 of 12 files at r6.
Review status: 12 files need 2 more reviewers, 9 open discussions remaining, 1 assignee LGTMs are missing, missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1071#-:-LEzieo3AzWqvccreTZu:bwv6ieg)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 8 files at r7.
Review status: 12 files need 2 more reviewers, 10 open discussions remaining, 1 assignee LGTMs are missing, missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---

*[src/ui.c, line 147 at r7](https://reviewable.io/reviews/utox/utox/1071#-LFcVBlVAMdl13pITWbT:-LFcVBlVAMdl13pITWbU:bcy1qtz) ([raw file](https://github.com/utox/utox/blob/f271ccd7ad8551320d4a474408d03c361975f128/src/ui.c#L147)):*
> ```C
>     CREATE_SWITCH(auto_startup,      10, 150, _BM_SWITCH_WIDTH, _BM_SWITCH_HEIGHT);
>     CREATE_SWITCH(mini_contacts,     10, 180, _BM_SWITCH_WIDTH, _BM_SWITCH_HEIGHT);
>     CREATE_EDIT(idle_interval, _BM_SWITCH_WIDTH + 25 + UN_SCALE(UTOX_STR_WIDTH(SETTINGS_IDLE_STATUS)), 211, 50, 24);
> ```

this isn't supposed to be in here anymore. It belongs in the layout dir

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1071)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 12 files at r6, 2 of 8 files at r7.
Review status: 12 files need 2 more reviewers, 11 open discussions remaining, 1 assignee LGTMs are missing, missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---

*[src/settings.h, line 20 at r7](https://reviewable.io/reviews/utox/utox/1071#-LFcVVO329PWLGOJPGP9:-LFcVVO45_CcvtWN8B7c:b-okij1f) ([raw file](https://github.com/utox/utox/blob/f271ccd7ad8551320d4a474408d03c361975f128/src/settings.h#L20)):*
> ```objc
>  * Period (in seconds) for check is user idle or not.
>  */
> static const uint16_t idle_check_period = 1;
> ```

I defines in headers make me nervous... ESPECIALLY when you make them static as well.

Plus, wouldn't time_t be better here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1071)*

**Comment by redmanmale** [comment]
Review status: 12 files need 2 more reviewers, 11 open discussions remaining, 1 assignee LGTMs are missing, missing Admin LGTM at current revision. (waiting on @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, @undefined, and @undefined)

---

*[src/settings.h, line 20 at r7](https://reviewable.io/reviews/utox/utox/1071#-LFcVVO329PWLGOJPGP9:-LFhCsLJ080g6-NORwQX:b-8v4l8d) ([raw file](https://github.com/utox/utox/blob/f271ccd7ad8551320d4a474408d03c361975f128/src/settings.h#L20)):*
> I defines in headers make me nervous... ESPECIALLY when you make them static as well.

What do you mean? Is there a better place for it? Or something else?

> wouldn't time_t be better here

On macOS it's `double` for seconds, on Win it's `uint` for milliseconds.
Only on Linux it's `time_t`.

---

*[src/ui.c, line 147 at r7](https://reviewable.io/reviews/utox/utox/1071#-LFcVBlVAMdl13pITWbT:-LFhEsQVA804AqsfKZx0:b-2n8651) ([raw file](https://github.com/utox/utox/blob/f271ccd7ad8551320d4a474408d03c361975f128/src/ui.c#L147)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this isn't supposed to be in here anymore. It belongs in the layout dir
</blockquote></details>

IIRC I tried but failed.
It couldn't be done because of the macros `UN_SCALE` and `UTOX_STR_WIDTH`, panel struct definition allows only constans.

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1071)*

**Pull request closed without merging**
