### PR TITLE
Update travis script for win*

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/753)

### CODE REVIEW

**Comment by cebe** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/753)*

**Comment by mannol** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/753#-:-KdA52cLj9vn0v8kJzun:bnfp4nl)*

**Comment by mannol** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/753)*

**Comment by GrayHatter** [comment]
:lgtm: I'm a cheater

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/753#-:-KdA5C4Xmq65MSrLSiHV:b-glibb3)*

**Pull request merged**
