### PR TITLE
Make user status enum

### PR DESCRIPTION
**Pull request by redmanmale**
instead of uint.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1086)

### CODE REVIEW

**Comment by redmanmale** [comment]
It seems that my efforts have not been successful. macOS build is still failing.
I'll remove last commit before merge.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086#-:-KwRsOV0jumIvFj3bo4E:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 8 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/self.h, line 12 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfJFoY-gvmC5IShseb:-KwfJFoZHEtU_ZiDlGvU:b5l1c1n) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/self.h#L12)):*
> ```objc
>     USER_STATUS_AWAY_IDLE,
>     USER_STATUS_DO_NOT_DISTURB,
>     USER_STATUS_OFFLINE
> ```

offline should be first (zero)

---

*[src/self.h, line 13 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfJzErcJXyOtpRYWR-:-KwfJzErcJXyOtpRYWR0:b1rgmfr) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/self.h#L13)):*
> ```objc
>     USER_STATUS_DO_NOT_DISTURB,
>     USER_STATUS_OFFLINE
> } USER_STATUS;
> ```

add an INVALID canary to the end as well, see later comment

---

*[src/layout/sidebar.c, line 83 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfJegflwAqReAzAmrn:-KwfJeggnhbklkKaAhH-:b-529oi6) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/layout/sidebar.c#L83)):*
> ```C
>                   BM_STATUSAREA_WIDTH, BM_STATUSAREA_HEIGHT,
>                   button_usr_state.mouseover ? COLOR_BKGRND_LIST_HOVER : COLOR_BKGRND_LIST);
>         uint8_t status = tox_connected ? self.status : USER_STATUS_OFFLINE;
> ```

BTW pedantic: don't create a u8 here. just drop the ?: into the array selector 

(you don't really need to change this)

---

*[src/layout/userbadge.c, line 75 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfK3onOqAzExJZcRlO:-KwfK3onOqAzExJZcRlP:bh5y5l4) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/layout/userbadge.c#L75)):*
> ```C
> static void button_status_on_mup(void) {
>     self.status++;
>     if (self.status == USER_STATUS_OFFLINE) {
> ```

if >= _INVALID; then set AVAILABLE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by redmanmale** [comment]
Review status: 5 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/self.h, line 12 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfJFoY-gvmC5IShseb:-KwfwQanUaCg_4gHlTG6:b-896fix) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/self.h#L12)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

offline should be first (zero)
</blockquote></details>

Done.

---

*[src/self.h, line 13 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfJzErcJXyOtpRYWR-:-KwfwRPVsc5XU8AEfE2q:b-896fix) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/self.h#L13)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

add an INVALID canary to the end as well, see later comment
</blockquote></details>

Done.

---

*[src/layout/sidebar.c, line 83 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfJegflwAqReAzAmrn:-KwfwTqlxKV0IwhgxeeC:b-896fix) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/layout/sidebar.c#L83)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

BTW pedantic: don't create a u8 here. just drop the ?: into the array selector 

(you don't really need to change this)
</blockquote></details>

Done.

---

*[src/layout/userbadge.c, line 75 at r1](https://reviewable.io:443/reviews/utox/utox/1086#-KwfK3onOqAzExJZcRlO:-KwfwUo1h8Eip69XAT9n:b-896fix) ([raw file](https://github.com/utox/utox/blob/3b44d421375d074345e5b9af8b51732933bef7ef/src/layout/userbadge.c#L75)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

if >= _INVALID; then set AVAILABLE
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by redmanmale** [comment]
Review status: 5 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/self.c, line 43 at r2](https://reviewable.io:443/reviews/utox/utox/1086#-Kwfx3Z3ljFir1hp9mqC:-Kwfx3Z3ljFir1hp9mqD:b-54pix2) ([raw file](https://github.com/utox/utox/blob/bff5e61dfa14e5b07bbf09926439ee48f47e36b3/src/self.c#L43)):*
> ```C
> USER_STATUS to_utox_user_status(TOX_USER_STATUS tox_user_status) {
>     return (USER_STATUS)(tox_user_status + 1);
> }
> ```

If you don't mind I create a conversion functions to avoid spreading that logic over all places where it used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086#-:-Kx0aymSKLpHoxo_CQ6Y:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 9 files at r1, 7 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/self.c, line 43 at r2](https://reviewable.io:443/reviews/utox/utox/1086#-Kwfx3Z3ljFir1hp9mqC:-Kx9id5lioKq-vB9paBl:b-vcjoc) ([raw file](https://github.com/utox/utox/blob/bff5e61dfa14e5b07bbf09926439ee48f47e36b3/src/self.c#L43)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

If you don't mind I create a conversion functions to avoid spreading that logic over all places where it used.
</blockquote></details>

do you think `user_status_to_tox` and `user_status_to_utox` would be better names?

---

*[src/theme.c, line 563 at r3](https://reviewable.io:443/reviews/utox/utox/1086#-Kx9iuOcguj-62gSLKRB:-Kx9iuOcguj-62gSLKRC:but4n4u) ([raw file](https://github.com/utox/utox/blob/2b60d95110dfe14a360592cbee85edb1cabce28a/src/theme.c#L563)):*
> ```C
>     }
> 
>     status_color[0] = COLOR_STATUS_BUSY;
> ```

do we not have an offline color defined?

should we?

---

*[src/theme.h, line 102 at r3](https://reviewable.io:443/reviews/utox/utox/1086#-Kx9izcZ_5-FA07PR8Se:-Kx9izcZ_5-FA07PR8Sf:b-wbywid) ([raw file](https://github.com/utox/utox/blob/2b60d95110dfe14a360592cbee85edb1cabce28a/src/theme.h#L102)):*
> ```objc
> void theme_load(const THEME loadtheme);
> 
> uint32_t status_color[5];
> ```

you can use the enum invalid value here, then it'll never go out of date

---

*[src/layout/sidebar.c, line 84 at r3](https://reviewable.io:443/reviews/utox/utox/1086#-Kx9jl43CY_Se6P2WkI8:-Kx9jl43CY_Se6P2WkI9:b-2bzwdi) ([raw file](https://github.com/utox/utox/blob/2b60d95110dfe14a360592cbee85edb1cabce28a/src/layout/sidebar.c#L84)):*
> ```C
>                   button_usr_state.mouseover ? COLOR_BKGRND_LIST_HOVER : COLOR_BKGRND_LIST);
> 
>         drawalpha(tox_connected ? self.status : BM_OFFLINE,
> ```

`tox_connected ? (BM_ONLINE + self.status - 1) :  BM_OFFLINE`

But that's gross... the best options are: revert this change and add the U8 back, or even better, reorder the enum in svg.h to match the user status enum. 

If you reorder the svg.h enum, make sure you do that in it's very own commit. (Touching svg.h is dangerous, so keeping it in it's own commit will allow git bisect to work later on)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/layout/sidebar.c, line 84 at r3](https://reviewable.io:443/reviews/utox/utox/1086#-Kx9jl43CY_Se6P2WkI8:-Kx9qyjgX5lHEcPqSGjS:b9zkt85) ([raw file](https://github.com/utox/utox/blob/2b60d95110dfe14a360592cbee85edb1cabce28a/src/layout/sidebar.c#L84)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`tox_connected ? (BM_ONLINE + self.status - 1) :  BM_OFFLINE`

But that's gross... the best options are: revert this change and add the U8 back, or even better, reorder the enum in svg.h to match the user status enum. 

If you reorder the svg.h enum, make sure you do that in it's very own commit. (Touching svg.h is dangerous, so keeping it in it's own commit will allow git bisect to work later on)
</blockquote></details>

Hm, there's not such code here anymore.
But I agreed that reordering colours would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by redmanmale** [comment]
Review status: 8 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/self.c, line 43 at r2](https://reviewable.io:443/reviews/utox/utox/1086#-Kwfx3Z3ljFir1hp9mqC:-KxEASMwg1mJW228pOL_:b-896fix) ([raw file](https://github.com/utox/utox/blob/bff5e61dfa14e5b07bbf09926439ee48f47e36b3/src/self.c#L43)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

do you think `user_status_to_tox` and `user_status_to_utox` would be better names?
</blockquote></details>

Done.

---

*[src/theme.c, line 563 at r3](https://reviewable.io:443/reviews/utox/utox/1086#-Kx9iuOcguj-62gSLKRB:-KxEATHcDrHKFmtAfoyQ:b-wf72tr) ([raw file](https://github.com/utox/utox/blob/2b60d95110dfe14a360592cbee85edb1cabce28a/src/theme.c#L563)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

do we not have an offline color defined?

should we?
</blockquote></details>

Nope for both.

---

*[src/theme.h, line 102 at r3](https://reviewable.io:443/reviews/utox/utox/1086#-Kx9izcZ_5-FA07PR8Se:-KxEBCugc-N5zSwffMtg:b-896fix) ([raw file](https://github.com/utox/utox/blob/2b60d95110dfe14a360592cbee85edb1cabce28a/src/theme.h#L102)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

you can use the enum invalid value here, then it'll never go out of date
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by endoffile78** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/theme.h, line 102 at r4](https://reviewable.io:443/reviews/utox/utox/1086#-KxEYCf3LoOtNcFKrmR1:-KxEYCf3LoOtNcFKrmR2:b-icm35z) ([raw file](https://github.com/utox/utox/blob/04d468d85d722f240af8089f4c59e920d3d1426d/src/theme.h#L102)):*
> ```objc
> void theme_load(const THEME loadtheme);
> 
> uint32_t status_color[USER_STATUS_INVALID];
> ```

You need to include `self.h` so `USER_STATUS_INVALID` can be used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by redmanmale** [comment]
Review status: 13 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/theme.h, line 102 at r4](https://reviewable.io:443/reviews/utox/utox/1086#-KxEYCf3LoOtNcFKrmR1:-KxEtBvAMlEECXWbbLrb:b-896fix) ([raw file](https://github.com/utox/utox/blob/04d468d85d722f240af8089f4c59e920d3d1426d/src/theme.h#L102)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

You need to include `self.h` so `USER_STATUS_INVALID` can be used.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 8 files at r2, 5 of 6 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/flist.c, line 114 at r5](https://reviewable.io:443/reviews/utox/utox/1086#-KxEwRpedacVV7OIS15n:-KxEwRpedacVV7OIS15o:b-j1pr1k) ([raw file](https://github.com/utox/utox/blob/19344a65d416a68269e61c9299b4dd253bd79742/src/flist.c#L114)):*
> ```C
>     x -= BM_STATUS_WIDTH / 2;
> 
>     drawalpha(status == USER_STATUS_OFFLINE ? BM_OFFLINE : status,
> ```

this could easily go out of scope, we need to do something different here.

same as sidebar.c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by robinlinden** [comment]
Reviewed 5 of 9 files at r1, 3 of 8 files at r2, 5 of 6 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1086)*

**Comment by GrayHatter** [comment]
@redmanmale still waiting on a fix for my comment.

**Comment by redmanmale** [comment]
I'm aware of this, but don't have any ideas yet how to fix it properly.

**Pull request closed without merging**
