### PR TITLE
Graceful shutdown

### LINKED ISSUE #901: Settings are not saved
First of all, on Linux I do not see how to properly close an app (no context menu on the tray icon to do so). Killing an app results in settings not being saved.
The most I can do is to save all settings besides "Close to tray", since closing to tray means that I can't close an app "normally".

Some settings (language) are not saved at all regardless how I close uTox.

Would be nice if settings are saved immediately as they are changed, so that the way I close application doesn't matter anymore.

uTox 0.15.0 (static x86-64)

### PR DESCRIPTION
**Pull request by redmanmale**
Handle termination signals (SIGINT and others) and shutdown uTox gracefully (for example save settings).
Closes #901.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1069)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/xlib/main.c, line 48 at r1](https://reviewable.io:443/reviews/utox/utox/1069#-KutxS1pdTXDzEVV-PTA:-KutxS1pdTXDzEVV-PTB:bsbcwvn) ([raw file](https://github.com/utox/utox/blob/4459c82a451d7e4ae463de1ee3c698617322a631/src/xlib/main.c#L48)):*
> ```C
> XIC xic = NULL;
> static XSizeHints *xsh = NULL;
> static volatile bool shutdown = false;
> ```

Doesn't need to be volatile.

---

*[src/xlib/main.c, line 678 at r1](https://reviewable.io:443/reviews/utox/utox/1069#-KutxLPD8oFUOyADspW0:-KutxLPEWEVhZ0J100hQ:b-6nhlmv) ([raw file](https://github.com/utox/utox/blob/4459c82a451d7e4ae463de1ee3c698617322a631/src/xlib/main.c#L678)):*
> ```C
> static void signal_handler(int UNUSED (signal))
> {
>     LOG_INFO("Main", "Graceful shutdown");
> ```

This should print the signal received 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1069)*

**Comment by redmanmale** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/xlib/main.c, line 48 at r1](https://reviewable.io:443/reviews/utox/utox/1069#-KutxS1pdTXDzEVV-PTA:-Kuu3kD0G3BrCoiVv7_x:b-896fix) ([raw file](https://github.com/utox/utox/blob/4459c82a451d7e4ae463de1ee3c698617322a631/src/xlib/main.c#L48)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Doesn't need to be volatile.
</blockquote></details>

Done.

---

*[src/xlib/main.c, line 678 at r1](https://reviewable.io:443/reviews/utox/utox/1069#-KutxLPD8oFUOyADspW0:-Kuu3kxHcPjaxiioXIbG:b-896fix) ([raw file](https://github.com/utox/utox/blob/4459c82a451d7e4ae463de1ee3c698617322a631/src/xlib/main.c#L678)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

This should print the signal received 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1069)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1069#-:-Kuu8RXDHNlTI44oajWz:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1069#-:-KuwGCumCTRjxnMn2XxP:bnfp4nl)*

**Pull request merged**
