### PR TITLE
Fix fallthrough warnings

### LINKED ISSUE #941: Implicit fallthrough warnings using gcc version 7
We need to decide if we should disable this or fix it. The fix is supposed to be adding comments although I've tried and it didn't work.

### PR DESCRIPTION
**Pull request by endoffile78**
Fixes #941 

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/942)

### CODE REVIEW

**Comment by robinlinden** [comment]
Per IRC, move the stb stuff to a separate folder and include it as a system include. 

---

Reviewed 7 of 8 files at r1, 2 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/messages.c, line 947 at r1](https://reviewable.io:443/reviews/utox/utox/942#-KlUmLNILSUgkwL6Ejs5:-KlUmLNILSUgkwL6Ejs6:bor83yt) ([raw file](https://github.com/utox/utox/blob/fd51c22c66ce8ac2a472e9f3b3427549eef60dc4/src/messages.c#L947)):*
> ```C
> 
> static void messages_time_change(MESSAGES *m, MSG_HEADER *msg, size_t index, int x, int y, int width, int height) {
> ```

No blank lines after `{` or before `}`.

---

*[src/messages.c, line 984 at r1](https://reviewable.io:443/reviews/utox/utox/942#-KlUmbOV9ifdHaAxK5gL:-KlUmbOV9ifdHaAxK5gM:b-4mv86) ([raw file](https://github.com/utox/utox/blob/fd51c22c66ce8ac2a472e9f3b3427549eef60dc4/src/messages.c#L984)):*
> ```C
>     }
> 
>     y = messages_draw_text(msg->via.notice.msg, msg->via.notice.length, msg->height,
> ```

Dead assignment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942#-:-KlUrppLapZ0MSjIjzEF:banwak8)*

**Comment by GrayHatter** [comment]
careful with moving stbi,  folders may conflict with .gitignore

---

Reviewed 6 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942#-:-KlUvnt179Iy1JPh-ddz:bxzayqz)*

**Comment by GrayHatter** [comment]
Reviewed 5 of 6 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942)*

**Comment by endoffile78** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/messages.c, line 947 at r1](https://reviewable.io:443/reviews/utox/utox/942#-KlUmLNILSUgkwL6Ejs5:-KlUyfea0EUHl39SvuRr:b-896fix) ([raw file](https://github.com/utox/utox/blob/fd51c22c66ce8ac2a472e9f3b3427549eef60dc4/src/messages.c#L947)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

No blank lines after `{` or before `}`.
</blockquote></details>

Done.

---

*[src/messages.c, line 984 at r1](https://reviewable.io:443/reviews/utox/utox/942#-KlUmbOV9ifdHaAxK5gL:-KlUyg-07cHWTty0hEY1:b-376vyb) ([raw file](https://github.com/utox/utox/blob/fd51c22c66ce8ac2a472e9f3b3427549eef60dc4/src/messages.c#L984)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Dead assignment.
</blockquote></details>

Done. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 257 at r5](https://reviewable.io:443/reviews/utox/utox/942#-KleQ4Iz8nJeGdnfnjzE:-KleQ4J-5UX9nmKclMhL:b-3pl2by) ([raw file](https://github.com/utox/utox/blob/9e4d7763e704fcff9794a7de88ccd4638e0246d6/CMakeLists.txt#L257)):*
> ```CMake
> endif()
> 
> include_directories(SYSTEM src/stb)
> ```

Excellent change. I wonder what mastermind placed this here.

---

*[src/main.h, line 69 at r5](https://reviewable.io:443/reviews/utox/utox/942#-KleQAGgmO7B8xhiAxdv:-KleQAGgmO7B8xhiAxdw:b-e6vvip) ([raw file](https://github.com/utox/utox/blob/9e4d7763e704fcff9794a7de88ccd4638e0246d6/src/main.h#L69)):*
> ```objc
>                        // seems to be unused?
> 
> #include <stb_image.h>
> ```

This change isn't really required, btw.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942#-:-KleQQAFtOy0HzTwPpZm:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942#-:-Ks-s6KJsCVKlePzA60R:bnfp4nl)*

**Comment by robinlinden** [comment]
This needs a rebase.

**Comment by robinlinden** [comment]
Reviewed 2 of 6 files at r3, 8 of 10 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/Info.plist.in, line 30 at r6](https://reviewable.io:443/reviews/utox/utox/942#-KsjLOP8ASyrg9Hn7tmK:-KsjLOP8ASyrg9Hn7tmL:byx4ujm) ([raw file](https://github.com/utox/utox/blob/49b7d33c4d5a19602b71b5bbf95ce52b47e3aacb/src/cocoa/Info.plist.in#L30)):*
> ```
> 	<string>@CMAKE_OSX_DEPLOYMENT_TARGET@</string>
> 	<key>NSHumanReadableCopyright</key>
> 	<string>Copyleft 2017 uTox contributors. Some rights reserved.</string>
> ```

This change doesn't look right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cocoa/Info.plist.in, line 30 at r6](https://reviewable.io:443/reviews/utox/utox/942#-KsjLOP8ASyrg9Hn7tmK:-KskUPH0Ke3C3Clw2C_z:b-896fix) ([raw file](https://github.com/utox/utox/blob/49b7d33c4d5a19602b71b5bbf95ce52b47e3aacb/src/cocoa/Info.plist.in#L30)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This change doesn't look right.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942#-:-KtD3P7wtju707Kl-vzl:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 6 files at r3, 7 of 10 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 289 at r7](https://reviewable.io:443/reviews/utox/utox/942#-KtYJqH-DsYXAHtD19-O:-KtYJqH-DsYXAHtD19-P:b935rwc) ([raw file](https://github.com/utox/utox/blob/1738750d155a697330fe7f9ffdd55c68e72ab0c3/CMakeLists.txt#L289)):*
> ```CMake
> set(LIBRARIES ${LIBRARIES} ${LIBSODIUM_LIBRARIES})
> 
> include_directories(SYSTEM src/stb)
> ```

IIRC we're planning to submodule this. Could we make that change now?

Also, I don't like the idea of marking anything in src a system directory...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 289 at r7](https://reviewable.io:443/reviews/utox/utox/942#-KtYJqH-DsYXAHtD19-O:-Ktb3xb3sE1HHnX4h-va:b8bp8k6) ([raw file](https://github.com/utox/utox/blob/1738750d155a697330fe7f9ffdd55c68e72ab0c3/CMakeLists.txt#L289)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

IIRC we're planning to submodule this. Could we make that change now?

Also, I don't like the idea of marking anything in src a system directory...
</blockquote></details>

The reason we made it a system header was because we would have to change stb. I think I originally did that but we decided to go with making it a system header instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 289 at r7](https://reviewable.io:443/reviews/utox/utox/942#-KtYJqH-DsYXAHtD19-O:-Ktcw16wmvKbsV32ha8Y:b-lkpx8f) ([raw file](https://github.com/utox/utox/blob/1738750d155a697330fe7f9ffdd55c68e72ab0c3/CMakeLists.txt#L289)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

The reason we made it a system header was because we would have to change stb. I think I originally did that but we decided to go with making it a system header instead.
</blockquote></details>

LGTM, I think it's a good idea to mark it as a system header, but not if it's in `src/` either way. There's already a pending pull for that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/942#-:-Ktcw0OqVaGFC-7wk2UI:bnfp4nl)*

**Pull request merged**
