### PR TITLE
Remove Tox DNS.

### PR DESCRIPTION
**Pull request by robinlinden**
Tox DNS is being stripped from uTox as there are no domains that support it anymore.

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/947)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/947#-:-Kmgew7KOUah4ZMiyO9R:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/947#-:-Kmm7GI1i9CcP2yOQuB0:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/947#-:-KmsYrgY2-2R7aJspLeq:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/947#-:-KmtR5YDqE1WmJieaWvf:bnfp4nl)*

**Pull request merged**
