### PR TITLE
Update Opus download link.

### PR DESCRIPTION
**Pull request by robinlinden**
This should fix Travis failing.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1109)

### CODE REVIEW

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1109#-:-KxUk9ush4i0EJd3zrun:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1109#-:-KxUklC-90lgV_B5g7uL:bnfp4nl)*

**Comment by zoff99** [comment]
@robinlinden why not use github?

https://github.com/xiph/opus/archive/v1.2.1.tar.gz

**Comment by robinlinden** [comment]
@zoff99 No reason in particular. I got this link off of their website.

**Pull request merged**
