### PR TITLE
Add flist_get_friend, flist_get_groupchat, and flist_get_type

### LINKED ISSUE #722: Replace flist_get_selected with flist_get_selected_friend/group/type

### PR DESCRIPTION
**Pull request by endoffile78**
Fixes #722

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/724)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/724#-:-KcPtSfTl5LPARgm-boG:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

this generates a "nice" merge conflict with #550 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/724#-:-KcWZzxUkNU2QGUukm6q:b-3csrw)*

**Comment by GrayHatter** [comment]
probably needs a manual rewrite... sorry @endoffile78 

hopefully it'll just be a simple copy/paste and grep

**Comment by GrayHatter** [comment]
Reviewed 5 of 11 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/layout/friend.c, line 86 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCcixurHICaWZcgWoT:-KdCcixurHICaWZcgWoU:b9wn8mw) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L86)):*
> ```C
> static void draw_friend_deletion(int UNUSED(x), int UNUSED(y), int UNUSED(w), int UNUSED(height)) {
>     FRIEND *f = flist_get_friend();
>     if (f == NULL || flist_get_type() != ITEM_FRIEND) {
> ```

drop this second check, is must be ITEM_FRIEND if `f != null`

---

*[src/layout/friend.c, line 574 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCd1eH-n64uHULXkbv:-KdCd1eIQ7tmTCwsY48N:b-8ji1op) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L574)):*
> ```C
> static void switchfxn_autoaccept_ft(void) {
>     FRIEND *f = flist_get_friend();
>     if (f != NULL && flist_get_type() == ITEM_FRIEND) {
> ```

2nd check not needed

---

*[src/layout/friend.c, line 720 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCd4LWjx28eYtdLKKP:-KdCd4LWjx28eYtdLKKQ:b-8ji1op) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L720)):*
> ```C
> 
>     FRIEND *f = flist_get_friend();
>     if (f != NULL && flist_get_type() == ITEM_FRIEND) {
> ```

2nd check not needed

---

*[src/layout/friend.c, line 733 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCd6bcdx1xnipyTcCz:-KdCd6bcdx1xnipyTcD-:b65u55) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L733)):*
> ```C
> static void e_chat_msg_onchange(EDIT *UNUSED(edit)) {
>     FRIEND *f = flist_get_friend();
>     if (f != NULL && flist_get_type() == ITEM_FRIEND) {
> ```

ditto, no more comments

---

*[src/layout/group.c, line 427 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCdChk6yyhf9yFAJcp:-KdCdChlj6cJjvr5zqaS:bkjbc2z) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/group.c#L427)):*
> ```C
> 
>     GROUPCHAT *g = flist_get_groupchat();
>     if (g != NULL && flist_get_type() == ITEM_GROUP) {
> ```

2nd check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/724)*

**Comment by endoffile78** [comment]
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/layout/friend.c, line 86 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCcixurHICaWZcgWoT:-KdEVJVoU2t2MCtVqdJ7:b-896fix) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L86)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

drop this second check, is must be ITEM_FRIEND if `f != null`
</blockquote></details>

Done.

---

*[src/layout/friend.c, line 574 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCd1eH-n64uHULXkbv:-KdEVLLtTUueAN1qQ5B9:b-896fix) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L574)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

2nd check not needed
</blockquote></details>

Done.

---

*[src/layout/friend.c, line 720 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCd4LWjx28eYtdLKKP:-KdEVNYlFdTlae-ZwaNG:b-896fix) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L720)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

2nd check not needed
</blockquote></details>

Done.

---

*[src/layout/friend.c, line 733 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCd6bcdx1xnipyTcCz:-KdEVP8x2yv191n-mM0A:b-896fix) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/friend.c#L733)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

ditto, no more comments
</blockquote></details>

Done.

---

*[src/layout/group.c, line 427 at r2](https://reviewable.io:443/reviews/utox/utox/724#-KdCdChk6yyhf9yFAJcp:-KdEVRm0AIbKNJyUAkO5:b-896fix) ([raw file](https://github.com/utox/utox/blob/64593c91a15beba51d38a052afc95a3c630ce6b2/src/layout/group.c#L427)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

2nd check
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/724)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 3 of 11 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/724#-:-KdO58cfEmfz-zHcQ349:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/724#-:-KdOaL2BfCF0kTk8n_dX:bnfp4nl)*

**Pull request merged**
