### PR TITLE
Update fingerprint

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1463)

### CODE REVIEW

**Comment by avoidr** [comment]
Why are you deleting @GrayHatter's fingerprint?

**Comment by endoffile78** [comment]
Sorry I accidentally deleted it, fixed it.

**Comment by GrayHatter** [comment]
we're not going to merge this for a week or two

**Comment by avoidr** [comment]
@endoffile78, are you going to share your keys, too?

**Comment by endoffile78** [comment]
@avoidr It should be uploaded now.

**Comment by avoidr** [comment]
Yes, now it worked, thanks!

**Pull request merged**
