### PR TITLE
Save force proxy settings

### LINKED ISSUE #712: uTox doesn't save proxy_force setting

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #712.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1035)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/settings.h, line 127 at r1](https://reviewable.io:443/reviews/utox/utox/1035#-KtN9hwrp3ZE2twyZZ6u:-KtN9hwrp3ZE2twyZZ6v:b3u92bu) ([raw file](https://github.com/utox/utox/blob/7f94d82b074872420afc2007489dea3e36cb3ae6/src/settings.h#L127)):*
> ```objc
>     uint16_t language;
> 
>     uint8_t force_proxy;
> ```

This needs to go after `video_fps`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1035)*

**Comment by redmanmale** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/settings.h, line 127 at r1](https://reviewable.io:443/reviews/utox/utox/1035#-KtN9hwrp3ZE2twyZZ6u:-KtNC6iykASkAyWclO6Y:b-896fix) ([raw file](https://github.com/utox/utox/blob/7f94d82b074872420afc2007489dea3e36cb3ae6/src/settings.h#L127)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This needs to go after `video_fps`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1035)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1035#-:-KtNNc76UaRCUQgKkJGi:bnfp4nl)*

**Comment by GrayHatter** [comment]
ASAN reports issues when loading the video device rapidly, this is OOS for this issue. Just want everyone to be aware.

:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1035#-:-KtYNCNxUXnA0xNZDtcQ:b8l20lg)*

**Pull request merged**
