### PR TITLE
Windows FT fixes

### PR DESCRIPTION
**Pull request by GrayHatter**
I don't like the solution inside ft_decon... we might even be able to drop the wait command now (that I added make_file_transfer()) If it turns out we can't drop it. We need to just delete it and come up with a better solution in general.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/669)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/file_transfers.c, line 113 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLnPfDetXyvYcOT7XY:-KbLnPfDetXyvYcOT7XZ:b-2xx707) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/file_transfers.c#L113)):*
> ```C
>     }
>     /* If the UI is reading this data, we need to wait */
>     unsigned wait = 100;
> ```

Maybe decrease this to 10 and increase yieldcpu to 10? You'd spam the console 10 times instead of 100 and wait the same amount of time.

---

*[src/messages.c, line 1301 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLlzJsNEaAjKwuWzwH:-KbLlzJsNEaAjKwuWzwI:b7qbii3) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/messages.c#L1301)):*
> ```C
>                 uint32_t ft_number = msg->via.ft.file_number;
>                 if (ft_number >= (1 << 16)) {
>                     ft = &(f->file_transfers_incoming[ft_number]); // TODO, abstraction needed
> ```

Remove parentheses.

---

*[src/tox.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLleaXepInZ2v2ySRd:-KbLleaXepInZ2v2ySRe:b-63ro5l) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/tox.c#L298)):*
> ```C
> static void log_callback(Tox *UNUSED(tox), TOX_LOG_LEVEL level, const char *file, uint32_t line,
>                          const char *func, const char *message, void *UNUSED(user_data)) {
>     if (utox_verbosity() <= 8 ) {
> ```

Now instead of 5 levels, we have 8? What level would you say this is? Trace?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by GrayHatter** [comment]
Yeah, this is hacky but needed. It'll go away in the debug branch. Because it's SO noisy it's goona be lib_trace

**Comment by robinlinden** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by fcore117** [comment]
sending and receiving files looks solid to me

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669#-:-KbWqfZUy6NgK4mAYhBg:bd0esf3)*

**Comment by fcore117** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/file_transfers.c, line 113 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLnPfDetXyvYcOT7XY:-KbWresJG2lPYeIFWvaI:b-hfpv0l) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/file_transfers.c#L113)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Maybe decrease this to 10 and increase yieldcpu to 10? You'd spam the console 10 times instead of 100 and wait the same amount of time.
</blockquote></details>

removed

---

*[src/messages.c, line 1301 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLlzJsNEaAjKwuWzwH:-KbTsAizXKUd-zItb6yi:b-896fix) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/messages.c#L1301)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Remove parentheses.
</blockquote></details>

Done.

---

*[src/tox.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLleaXepInZ2v2ySRd:-KbTrblGweynutHfGsMT:bk4cvub) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/tox.c#L298)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Now instead of 5 levels, we have 8? What level would you say this is? Trace?
</blockquote></details>

_TRACE_TOXCORE, or something... It's the MOST annoying level

Either way, I'll get it done in #656 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/tox.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLleaXepInZ2v2ySRd:-KbWuKKGcwMXqw7jMWut:bj4m9y6) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/tox.c#L298)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

_TRACE_TOXCORE, or something... It's the MOST annoying level

Either way, I'll get it done in #656 
</blockquote></details>

Yeah.. It created a uTox log file that was >100 MB before I noticed how spammy it was. :D Happy surprise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669#-:-KbWuW1o4cEBJEMioUU0:bnfp4nl)*

**Comment by endoffile78** [comment]
Reviewed 10 of 10 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/windows/main.c, line 75 at r3](https://reviewable.io:443/reviews/utox/utox/669#-KbWzvbFtkJHz88w8D-O:-KbWzvbFtkJHz88w8D-P:b9wv7ud) ([raw file](https://github.com/utox/utox/blob/87e3dc6356d0b68423fea5bf2b880f6a9c036d57/src/windows/main.c#L75)):*
> ```C
>     if (GetOpenFileName(&ofn)) {
>         FRIEND *f = flist_get_selected()->data;
>         UTOX_MSG_FT *msg = calloc(1, sizeof(UTOX_MSG_FT));
> ```

Make sure memory was allocated for msg.

---

*[src/windows/main.c, line 76 at r3](https://reviewable.io:443/reviews/utox/utox/669#-KbX--ORonowGUiQe18B:-KbX--OSZpm08sXCBNRJ:bs83xdj) ([raw file](https://github.com/utox/utox/blob/87e3dc6356d0b68423fea5bf2b880f6a9c036d57/src/windows/main.c#L76)):*
> ```C
>         FRIEND *f = flist_get_selected()->data;
>         UTOX_MSG_FT *msg = calloc(1, sizeof(UTOX_MSG_FT));
>         msg->file = fopen(filepath, "rb");
> ```

Make sure the file was opened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by fcore117** [comment]
Reviewed 1 of 4 files at r4, 13 of 13 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/tox.c, line 298 at r1](https://reviewable.io:443/reviews/utox/utox/669#-KbLleaXepInZ2v2ySRd:-KbXGsGxgqe2ZDncyKaF:b-4m06fs) ([raw file](https://github.com/utox/utox/blob/2428b35fce9f94c1bb6ea143ad38f728f6c91789/src/tox.c#L298)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Yeah.. It created a uTox log file that was >100 MB before I noticed how spammy it was. :D Happy surprise.
</blockquote></details>

lol NICE!

---

*[src/windows/main.c, line 75 at r3](https://reviewable.io:443/reviews/utox/utox/669#-KbWzvbFtkJHz88w8D-O:-KbXHRybRDEJ2yXKEssm:b-896fix) ([raw file](https://github.com/utox/utox/blob/87e3dc6356d0b68423fea5bf2b880f6a9c036d57/src/windows/main.c#L75)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Make sure memory was allocated for msg.
</blockquote></details>

Done.

---

*[src/windows/main.c, line 76 at r3](https://reviewable.io:443/reviews/utox/utox/669#-KbX--ORonowGUiQe18B:-KbXHTZdw7JkJYkeTT-k:b-61rps0) ([raw file](https://github.com/utox/utox/blob/87e3dc6356d0b68423fea5bf2b880f6a9c036d57/src/windows/main.c#L76)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Make sure the file was opened.
</blockquote></details>

That's done in the receiving code, in file_transfers.c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 9 of 13 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669#-:-KbXMh2GhWibZigXLT3h:bnfp4nl)*

**Comment by fcore117** [comment]
After tests in first view looks ok, no crash

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669#-:-KbXNeHMVJ8WU7SJWipR:b-ihqq2s)*

**Comment by fcore117** [comment]
Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r4, 9 of 13 files at r5, 5 of 5 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/669#-:-KbXjK1XP-Rd62ebuzSX:bnfp4nl)*

**Pull request merged**
