### PR TITLE
Delete util files.

### PR DESCRIPTION
**Pull request by robinlinden**
Moved most functions to files where they belong.
Created src/text for text utilities that have nothing to do with display/ui. (E.g. utf8 validation.)
Deleted the file_text function because it wasn't used anywhere.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/643)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/643#-:-Kb8_kqpwS1kV8e_RmEj:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 20 of 41 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/file_transfers.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/643#-Kb9R0CmSBAKwu2G2GOX:-Kb9R0CmSBAKwu2G2GOY:b-jyq6qs) ([raw file](https://github.com/utox/utox/blob/ef2e1d84f164977f384f79d57e675134fe1494a5/src/file_transfers.c#L15)):*
> ```C
> #define MAX_INLINE_FILESIZE (1024 * 1024 * 4)
> 
> static void fid_to_string(char *dest, uint8_t *src);
> ```

twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/643)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/file_transfers.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/643#-Kb9R0CmSBAKwu2G2GOX:-KbB8kctOsKo9qzAf-_R:bgo1gjp) ([raw file](https://github.com/utox/utox/blob/ef2e1d84f164977f384f79d57e675134fe1494a5/src/file_transfers.c#L15)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

twice?
</blockquote></details>

Declaration and definition. I originally had the function further down the file and then I had to add the declaration so functions knew it existed. Want me to drop the declaration?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/643)*

**Comment by robinlinden** [comment]
Review status: 36 of 41 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/file_transfers.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/643#-Kb9R0CmSBAKwu2G2GOX:-KbBEDCcft6LtfQOUjL3:b6w9tno) ([raw file](https://github.com/utox/utox/blob/ef2e1d84f164977f384f79d57e675134fe1494a5/src/file_transfers.c#L15)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Declaration and definition. I originally had the function further down the file and then I had to add the declaration so functions knew it existed. Want me to drop the declaration?
</blockquote></details>

I went ahead and deleted it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/643)*

**Pull request merged**
