### PR TITLE
Fix some coverity warnings

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/839)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/839#-:-KhzJJfRIQPzHOxQsy_a:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 415 at r1](https://reviewable.io:443/reviews/utox/utox/839#-Khz_jO7r-_q_RI5Ee7p:-Khz_jO8hsWz-PPsyKwo:b-g4opzk) ([raw file](https://github.com/utox/utox/blob/8cb8b6e1c1098041d0d5cbfce2266fdb97ad71e2/src/xlib/main.c#L415)):*
> ```C
>     XImage *img = XCreateImage(display, CopyFromParent, 8, ZPixmap, 0, data, width, height, 8, 0);
> 
>     if (bm < 0){
> ```

this needs to be before XCreateImage

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/839)*

**Comment by endoffile78** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/main.c, line 415 at r1](https://reviewable.io:443/reviews/utox/utox/839#-Khz_jO7r-_q_RI5Ee7p:-KhzaCZc74YQwi7Hn_FX:b-896fix) ([raw file](https://github.com/utox/utox/blob/8cb8b6e1c1098041d0d5cbfce2266fdb97ad71e2/src/xlib/main.c#L415)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this needs to be before XCreateImage
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/839)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/839#-:-KhzaSo80K10sTfzGYnP:bnfp4nl)*

**Pull request merged**
