### PR TITLE
Improve Spanish support

### PR DESCRIPTION
**Pull request by siburec**
Improved Spanish support

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1516)

### CODE REVIEW

**Comment by avoidr** [comment]
Thanks! Looks like Spanish is almost complete now. I saw that a few translations are missing, most of them simple:
```
REQ_ADDED_NO_FREQ_SENT
FRIEND_SETTINGS
LOCK
SHOW
HIDE
EXIT
KEEP
```
Do you mind translating them, too? Then we/you could also add Spanish to the end of the list in the Readme, where it says `µTox is multi-lingual`.

Please squash your two commits into one (`git rebase -i HEAD~2`).

I also have a few minor nitpicks.

**Review by avoidr — CHANGES_REQUESTED** [review]

**Comment by avoidr** [comment]
Actually, I can fix those up myself, just please translate the rest of the strings if you want and can. If not, it's fine, just tell me, then I'll fix up the rest and merge. Thanks.

**Comment by siburec** [comment]
Hi avoidr,

it is the first time that I use github and I don't know how to edit without creating a new branch, so I will reply you here.

REQ_INVALID_ID
"Nota: Se ha añadido a su amigo, pero no se ha enviado la solictud de amistad (falta nospam)"

FRIEND_SETTINGS
"Configuración de amigo"

LOCK -> I am not sure about the most accurate translation. As it is used to set the password, I would say "Bloquear" if you mean block, or "Proteger" if you think that protect is a more accurate term.

SHOW
"Mostrar"

HIDE
"Ocultar"

EXIT
"Salir"

KEEP
"Mantener"

**Comment by avoidr** [comment]
Thank you very much! I'll fix it up today and merge.

>REQ_INVALID_ID

Surely you mean `REQ_ADDED_NO_FREQ_SENT`? :P

**Comment by avoidr** [comment]
Probably "protect" is more accurate.

**Comment by siburec** [comment]
Yes, I meant REQ_ADDED_NO_FREQ_SENT.

**Review by avoidr — APPROVED** [review]

**Comment by avoidr** [comment]
Merged, thanks a lot!

**Pull request merged**
