### PR TITLE
Remove language strings not in use.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/463)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/buttons.c, line 398 at r1](https://reviewable.io:443/reviews/utox/utox/463#-KVlpVhUM90bgquZ90JD:-KVlpVhUM90bgquZ90JE:b-nh2ruy) ([raw file](https://github.com/utox/utox/blob/e938ef9a022bcd0d966b1f1c81ca33d7dc61a330/src/ui/buttons.c#L398)):*
> ```C
> }
> ```

add `// clang-format off` here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/463)*

**Comment by robinlinden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/buttons.c, line 398 at r1](https://reviewable.io:443/reviews/utox/utox/463#-KVlpVhUM90bgquZ90JD:-KVlsVDeJsxY-CDbqDSs:b-896fix) ([raw file](https://github.com/utox/utox/blob/e938ef9a022bcd0d966b1f1c81ca33d7dc61a330/src/ui/buttons.c#L398)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> add `// clang-format off` here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/463)*

**Comment by robinlinden** [comment]
Alright, this should be working now. A few of the enums I removed didn't exist in the code per se, but were constructed by macros. I added those back and removed the language strings referencing the enums and now it seems to work again.

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 28 of 28 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/463#-:-KVv_NqBQuupK_mL-StI:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/463#-:-KWl9YomI3CTl7czuvTl:bnfp4nl)*

**Pull request merged**
