### PR TITLE
Fix autoaccepting file transfers on Windows

### LINKED ISSUE #811: Crash when receiving file with auto accept enabled
**Steps to reproduce**
* open uTox
* receive a file

**Notes**
Only occures on x86 and with auto accept enabled, on x64 everything is good anyway.

[Log](https://gist.github.com/redmanmale/9f677a56cdbd56f1ea587e17fc02dcf7).

**Env**
Win 7 x86, uTox v.0.14.0

### PR DESCRIPTION
**Pull request by robinlinden**
Fix autoaccept path when in portable mode.
Minor cleanup because I looked at a lot of code. (Sorry.)
Fixes #811 

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/806)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 7 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[CMakeLists.txt, line 177 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLO686Lf8RiYAkSk7S:-KhLO686Lf8RiYAkSk7T:bx1gqqf) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/CMakeLists.txt#L177)):*
> ```CMake
> if (ENABLE_ASAN)
>     set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer")
>     if (NOT UTOX_STATIC)
> ```

`message(SEND_ERROR "You can't UTOX_STATIC and ENABLE_ASAN")`

don't do magic when there's incompatible settings

---

*[src/messages.c, line 580 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLOXiYVLS08pxq9-b3:-KhLOXiYVLS08pxq9-b4:bcc1sbz) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/messages.c#L580)):*
> ```C
>                         LOG_TRACE("Messages", "Updating first message -> disk_offset is %lu" , msg->disk_offset);
>                         utox_update_chatlog(hex, msg->disk_offset, data, length);
>                     } else if (settings.logging_enabled) {
> ```

why?

Ixf this is really needed, it should be higher

---

*[src/windows/main.7.c, line 84 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLPFG0gGFc_-oN6vbg:-KhLPFG0gGFc_-oN6vbh:b-8jxl80) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/windows/main.7.c#L84)):*
> ```C
> 
>     if (settings.portable_mode) {
>         autoaccept_folder = calloc(1, UTOX_FILE_NAME_LENGTH);
> ```

`UTOX_FILE_NAME_LENGTH, sizeof(wchar_t)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/windows/main.7.c, line 140 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLe1X8AINF0sz5t5eE:-KhLe1X8AINF0sz5t5eF:b-igpnud) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/windows/main.7.c#L140)):*
> ```C
>             path_length += 2;
> 
>             // 2 bytes per wchar_t
> ```

nope, this is wrong. The code is correct, it it's allocating UTOX_FILE_NAME_LENGTH *2 but it shouldn't be, and array of [size] of wchar is already size*2 bytes, but all the sizes in this area are expecting 2bytes, so it's all just wrong

what ever you do, don't read the git blame

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806)*

**Comment by endoffile78** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/windows/main.XP.c, line 77 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhO_NgtY1_BZOq5_YaJ:-KhO_NgtY1_BZOq5_YaK:bx2ypq7) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/windows/main.XP.c#L77)):*
> ```C
> 
> void native_autoselect_dir_ft(uint32_t fid, FILE_TRANSFER *file) {
>     wchar_t *autoaccept_folder = calloc(1, MAX_PATH);
> ```

Make sure memory was allocated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806)*

**Comment by robinlinden** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/messages.c, line 580 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLOXiYVLS08pxq9-b3:-KhmAV3CEaytY_z0HTty:b-yypjcr) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/messages.c#L580)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why?

Ixf this is really needed, it should be higher
</blockquote></details>

It was to fix uTox complaining about not being able to update chatlogs on every message even if you had them disabled. It shouldn't be done in this PR and it wasn't the proper way to do it. I'm opening an issue for it instead.

---

*[src/windows/main.7.c, line 84 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLPFG0gGFc_-oN6vbg:-Khm8XaOZmp-PR2KAwdE:b-896fix) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/windows/main.7.c#L84)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`UTOX_FILE_NAME_LENGTH, sizeof(wchar_t)`
</blockquote></details>

Done.

---

*[src/windows/main.7.c, line 140 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLe1X8AINF0sz5t5eE:-KhmA3Zf_ezImIAfWDFE:bm78qbo) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/windows/main.7.c#L140)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

nope, this is wrong. The code is correct, it it's allocating UTOX_FILE_NAME_LENGTH *2 but it shouldn't be, and array of [size] of wchar is already size*2 bytes, but all the sizes in this area are expecting 2bytes, so it's all just wrong

what ever you do, don't read the git blame
</blockquote></details>

Yeah, I didn't really read through this code carefully. Just fixed the few obvious problems I saw. The comment was moved because the line was >120 characters. 

---

*[src/windows/main.XP.c, line 77 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhO_NgtY1_BZOq5_YaJ:-Khm8-1s91LApvbEqW6P:b-896fix) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/windows/main.XP.c#L77)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Make sure memory was allocated.
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 177 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLO686Lf8RiYAkSk7S:-Khm79Gea2cRIEWIW_si:bjdr8r0) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/CMakeLists.txt#L177)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`message(SEND_ERROR "You can't UTOX_STATIC and ENABLE_ASAN")`

don't do magic when there's incompatible settings
</blockquote></details>

Done, but moved to a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806#-:-KhmhelaJjPnxmLhKukB:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/windows/main.7.c, line 84 at r1](https://reviewable.io:443/reviews/utox/utox/806#-KhLPFG0gGFc_-oN6vbg:-KhodaYe1J-GYhyO_Vku:bwsoxiz) ([raw file](https://github.com/utox/utox/blob/68d29ba4cf9c305d352898e598f4dc28b18dcc8b/src/windows/main.7.c#L84)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

no, I meant `calloc(UTOX_FILE_NAME_LENGTH, sizeof(wchat_t));`It's the same either way 

---

*[src/windows/main.XP.c, line 83 at r2](https://reviewable.io:443/reviews/utox/utox/806#-KhofVYT0uzubP-vrXVW:-KhofVYT0uzubP-vrXVX:b-5ngyv9) ([raw file](https://github.com/utox/utox/blob/ad8c9905f1c25a2fe3dba1a017c46cb3e697172d/src/windows/main.XP.c#L83)):*
> ```C
>     }
> 
>     if (settings.portable_mode) {
> ```

FYI https://github.com/uTox/uTox/issues/830

---

*[src/windows/main.XP.c, line 91 at r2](https://reviewable.io:443/reviews/utox/utox/806#-KhoeQcP49d9q9HbEyHZ:-KhoeQcQMs2KeSq-pexK:bx2y5wh) ([raw file](https://github.com/utox/utox/blob/ad8c9905f1c25a2fe3dba1a017c46cb3e697172d/src/windows/main.XP.c#L91)):*
> ```C
>     } else if (SHGetFolderPath(NULL, CSIDL_DESKTOP, NULL, 0, autoaccept_folder) != S_OK) {
>         LOG_ERR("WinXP", "Unable to get auto accept file folder!");
>         return;
> ```

autoaccept_folder leaks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806#-:-KhofcrEprXz8VBA586F:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/windows/main.XP.c, line 91 at r2](https://reviewable.io:443/reviews/utox/utox/806#-KhoeQcP49d9q9HbEyHZ:-KhrNN0znPxJHBxhSZ3S:b-896fix) ([raw file](https://github.com/utox/utox/blob/ad8c9905f1c25a2fe3dba1a017c46cb3e697172d/src/windows/main.XP.c#L91)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

autoaccept_folder leaks
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806#-:-Khrd-xmk0siDAtfr1UV:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/806#-:-Khs-azKfHpLX61_lQTL:bnfp4nl)*

**Pull request merged**
