### PR TITLE
Friend request improvements

### LINKED ISSUE #143: Friend request improvements
I just got a friend request from someone unknown.

However I didnt noticed that for a long time. It just appeared in my friendlist suddenly. I expected that linux adds a trigger to the chat (like on qtox). **However a friend request should be highlighted more.**

Also the guy put a long "story" inside the friend request. This text is only shown in the headline. So you better move it into a normal text message. Because otherwise you need to make the windows lager. But there is a limit of the window size, especially for laptops. So you ware not able to read all. Putting it into a normal message would make it better readable and can be logged, so you can look this up afterwards. I always have people asking me things already in the friend request (cause i set tox as my main contact address), and this is quite annoying.

A sound would also be nice. On linux you also have those popups, but i guess that is a bit complicated for now, idk?
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29468453-friend-request-improvements?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #143 (for contact list sorting part there's another issue).

* add incoming friend request message to chat
* add outcoming friend request message to chat
* after adding friend switch to chat with him

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1073)

### CODE REVIEW

**Comment by robinlinden** [comment]
Haven't tested this yet, but the code :lgtm_strong:.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073#-:-KvJU3ah1vHIpPqesI0Y:b-vevbkm)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073#-:-KwwTZUdaVCa6MoUXCap:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utox.c, line 475 at r2](https://reviewable.io:443/reviews/utox/utox/1073#-KxJY-YKgTWONS8neYUC:-KxJY-YKgTWONS8neYUD:b-x2wl8e) ([raw file](https://github.com/utox/utox/blob/fab10930344ede892ee909fefc4bdf8492782626/src/utox.c#L475)):*
> ```C
>                 memcpy(f->id_bin, data, TOX_PUBLIC_KEY_SIZE);
> 
>                 char *request_message = strdup(edit_add_new_friend_msg.data);
> ```

can fail, and will segv in message_add_type_text

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073)*

**Comment by redmanmale** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utox.c, line 475 at r2](https://reviewable.io:443/reviews/utox/utox/1073#-KxJY-YKgTWONS8neYUC:-KxKSOifsM1WKmoylnhO:b-896fix) ([raw file](https://github.com/utox/utox/blob/fab10930344ede892ee909fefc4bdf8492782626/src/utox.c#L475)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

can fail, and will segv in message_add_type_text
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073#-:-KxPEOF64FKIYvnJ9sJJ:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073#-:-KxPKx_h_gGE4Mimzfpr:bnfp4nl)*

**Comment by GrayHatter** [comment]
@redmanmale check the CI, it doesn't compile

**Comment by redmanmale** [comment]
That's strange.
I can compile just fine and in the CI log there's an error with code that didn't exist anymore.
Maybe some caching, can we just re-run?

**Comment by robinlinden** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1073#-:-KyM1u_v-TpKFseJWnF2:bnfp4nl)*

**Pull request merged**
