### PR TITLE
Save datetime format settings

### LINKED ISSUE #1058: Message arrival timestamp state should be saved
Save if the user has hidden the seconds or not.

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #1058.

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1116)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1116#-:-Kz0jCwuhX6tQk-i18eN:b-uwkowd)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1116#-:-KzFDRDwNOXmD5U9vVi8:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/settings.h, line 128 at r1](https://reviewable.io:443/reviews/utox/utox/1116#-L0GrK_zaXSOGHWJPvyu:-L0GrKa0c1Af9-z0oBM3:b2s3uke) ([raw file](https://github.com/utox/utox/blob/4e82bd1ddcc96db336a4fca3507bff6fc0b6e043/src/settings.h#L128)):*
> ```objc
>     uint8_t  video_fps;
>     uint8_t force_proxy;
>     uint8_t use_long_time_msg;
> ```

why not bool?

if you want to be pedantic, why not `uint8_t use_long_time_msg : 1;'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1116)*

**Comment by redmanmale** [comment]
There's no any other bool in `UTOX_SAVE` struct; and we're planning to deprecate the whole struct soon.

**Pull request merged**
