### PR TITLE
Add picture by picture support to uTox

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1045)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/av/video.c, line 278 at r1](https://reviewable.io:443/reviews/utox/utox/1045#-KtY2IvWFM27tKW1o00e:-KtY2IvWFM27tKW1o00f:bx2ypq7) ([raw file](https://github.com/utox/utox/blob/f6acda536ce3153b4bf79cf5206e949e89e3d432/src/av/video.c#L278)):*
> ```C
>                 frame->h    = utox_video_frame.h;
>                 frame->size = utox_video_frame.w * utox_video_frame.h * 4;
>                 frame->img  = malloc(frame->size);
> ```

Make sure memory was allocated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Comment by robinlinden** [comment]
1. This breaks the inline (on Windows at least.)
image
2. This leaks every frame it creates.
image
^ Is after running the video preview window for a few seconds and closing it.
3. There's no picture by picture (on Windows at least.)

**Comment by robinlinden** [comment]
Reviewed 12 of 13 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[src/inline_video.c, line 24 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtajIpCUxe8nyvb2ocl:-KtajIpCUxe8nyvb2ocm:bxxs0et) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L24)):*
> ```C
> 
> #include "native/image.h"
> #include "native/thread.h"
> ```

This include isn't needed.

---

*[src/inline_video.c, line 30 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-Ktaj_CW8nh7rp77RCW0:-Ktaj_CW8nh7rp77RCW1:bqd11jt) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L30)):*
> ```C
> 
> static UTOX_FRAME_PKG *preview_frame = NULL;
> static UTOX_FRAME_PKG *current_frame = NULL;
> ```

static variables are always implicitly set to 0/NULL. (No change needed if you like your initialisations explicit.)

---

*[src/inline_video.c, line 72 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtahxzuXT3QKDACKrif:-KtahxzuXT3QKDACKrig:be9i1rv) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L72)):*
> ```C
>         clone_frame(preview_frame, frame);
>         return true;
>     } else {
> ```

No `else` after return.

---

*[src/layout/friend.c, line 224 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoI59zQshBPq5S5Xh:-KtaoI59zQshBPq5S5Xi:bnq1sj2) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L224)):*
> ```C
>         (PANEL*)&edit_chat_msg_friend, // this needs to be one of the first, to get events before the others
>         (PANEL*)&messages_friend,
>         (PANEL*)&panel_friend_header,
> ```

You don't have to cast it when it's already a PANEL pointer.

---

*[src/layout/friend.c, line 235 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoPcF9E6aGLrJot7L:-KtaoPcF9E6aGLrJot7M:bnq1sj2) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L235)):*
> ```C
>     .disabled = true,
>     .child = (PANEL*[]) {
>         (PANEL*)&panel_friend_header,
> ```

You don't have to cast it when it's already a PANEL pointer.

---

*[src/native/drawing.h, line 8 at r1](https://reviewable.io:443/reviews/utox/utox/1045#-KtY6-aWPb6H0dWsV3xz:-KtY6-aXEYlMCymIhIqL:b3gix01) ([raw file](https://github.com/utox/utox/blob/f6acda536ce3153b4bf79cf5206e949e89e3d432/src/native/drawing.h#L8)):*
> ```objc
> typedef struct native_window UTOX_WINDOW;
> 
> bool draw_set_target(UTOX_WINDOW *new);
> ```

Why stick this in native/ when it's xlib only?

---

*[src/xlib/drawing.c, line 15 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-Ktane6bqdO5EQ73x8GX:-Ktane6bqdO5EQ73x8GY:bapjrvp) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/xlib/drawing.c#L15)):*
> ```C
> 
> static UTOX_WINDOW *curr_win = NULL;
> bool draw_set_target(UTOX_WINDOW *new) {
> ```

Don't use `new` as a name. It's a keyword in C++ and it'd be nice to keep uTox somewhat compatible with it in case we want to use any nice C++ static analysis tools or testing frameworks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Comment by endoffile78** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/inline_video.c, line 93 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-Ktb2s8ft91kDxfH-dnn:-Ktb2s8ft91kDxfH-dno:bq83n4w) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L93)):*
> ```C
>         clone_frame(current_frame, frame);
>         return true;
>     } else {
> ```

No else after a return

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/inline_video.c, line 30 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-Ktaj_CW8nh7rp77RCW0:-Ktcx8zp1GkN8D7D6y1t:b-iu6w51) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L30)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

static variables are always implicitly set to 0/NULL. (No change needed if you like your initialisations explicit.)
</blockquote></details>

I like my globals explicit

---

*[src/av/video.c, line 278 at r1](https://reviewable.io:443/reviews/utox/utox/1045#-KtY2IvWFM27tKW1o00e:-KtcxDiuBDq5kOmRtUPM:b-buffdf) ([raw file](https://github.com/utox/utox/blob/f6acda536ce3153b4bf79cf5206e949e89e3d432/src/av/video.c#L278)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Make sure memory was allocated.
</blockquote></details>

I did, LOG_MALLOC_ERR will exit if malloc fails, that's what we do else where, and I'm okay with that being uTox's default.

---

*[src/layout/friend.c, line 224 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoI59zQshBPq5S5Xh:-KtcxS7IpWNg4ul4mmCR:bkr44jh) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L224)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You don't have to cast it when it's already a PANEL pointer.
</blockquote></details>

I have to, otherwise the alignment will be off....

---

*[src/layout/friend.c, line 235 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoPcF9E6aGLrJot7L:-KtcxVt8DcDM02AY8nrr:b-7ropln) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L235)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You don't have to cast it when it's already a PANEL pointer.
</blockquote></details>

ditto

---

*[src/native/drawing.h, line 8 at r1](https://reviewable.io:443/reviews/utox/utox/1045#-KtY6-aWPb6H0dWsV3xz:-KtcxZCndKBESu3vURLy:b-12mq5r) ([raw file](https://github.com/utox/utox/blob/f6acda536ce3153b4bf79cf5206e949e89e3d432/src/native/drawing.h#L8)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why stick this in native/ when it's xlib only?
</blockquote></details>

Because I thought eventually it would need to be ported to windows, and because it's cleaner this way. I don't like doing things differently for one system. (confining this to XLib only)

---

*[src/xlib/drawing.c, line 15 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-Ktane6bqdO5EQ73x8GX:-Ktcy3c7-DdDDB9Yhi1w:b-45ue72) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/xlib/drawing.c#L15)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Don't use `new` as a name. It's a keyword in C++ and it'd be nice to keep uTox somewhat compatible with it in case we want to use any nice C++ static analysis tools or testing frameworks.
</blockquote></details>

we don't -_-

I know, I know....  I'll fix it....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/layout/friend.c, line 224 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoI59zQshBPq5S5Xh:-KtczinHuWTvtE6nWbV-:bnwfs4g) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L224)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I have to, otherwise the alignment will be off....
</blockquote></details>

That's weird. You shouldn't have to since you specify that this is an array of PANEL pointers.. Should you be casting the pointers in the other panels too? (e.g. panel_friend.)

---

*[src/native/drawing.h, line 8 at r1](https://reviewable.io:443/reviews/utox/utox/1045#-KtY6-aWPb6H0dWsV3xz:-Ktd-ZPtR94OjG1GSeu1:b-9d32qm) ([raw file](https://github.com/utox/utox/blob/f6acda536ce3153b4bf79cf5206e949e89e3d432/src/native/drawing.h#L8)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Because I thought eventually it would need to be ported to windows, and because it's cleaner this way. I don't like doing things differently for one system. (confining this to XLib only)
</blockquote></details>

Well, add a comment or `#ifdef` saying it's xlib only when there's an xlib-only function outside of the xlib folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Comment by GrayHatter** [comment]
I think I fixed the memory leak, but I don't know why windows is screwy when it's drawing the 2nd frame :/

---

Review status: 9 of 17 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/inline_video.c, line 24 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtajIpCUxe8nyvb2ocl:-KtiF3owj10rh1Dvp6sG:b-896fix) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L24)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This include isn't needed.
</blockquote></details>

Done.

---

*[src/inline_video.c, line 72 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtahxzuXT3QKDACKrif:-KtiF4bxZvQyXMVJ0M2-:b-896fix) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L72)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

No `else` after return.
</blockquote></details>

Done.

---

*[src/inline_video.c, line 93 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-Ktb2s8ft91kDxfH-dnn:-KtiF4wgwgpeF9xH3o2q:b-896fix) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/inline_video.c#L93)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

No else after a return
</blockquote></details>

Done.

---

*[src/layout/friend.c, line 224 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoI59zQshBPq5S5Xh:-KtiF7yKE-ijyeRZrRbq:b-88uakv) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L224)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

That's weird. You shouldn't have to since you specify that this is an array of PANEL pointers.. Should you be casting the pointers in the other panels too? (e.g. panel_friend.)
</blockquote></details>

the source code alignment, not the memory alignment. :D

---

*[src/native/drawing.h, line 8 at r1](https://reviewable.io:443/reviews/utox/utox/1045#-KtY6-aWPb6H0dWsV3xz:-KtiKGG839Cv6EUt6Xmc:b-6a772p) ([raw file](https://github.com/utox/utox/blob/f6acda536ce3153b4bf79cf5206e949e89e3d432/src/native/drawing.h#L8)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Well, add a comment or `#ifdef` saying it's xlib only when there's an xlib-only function outside of the xlib folder.
</blockquote></details>

Done.

I replaced the "broken" function I wrote for windows with the better version I wrote for XLib.

---

*[src/xlib/drawing.c, line 15 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-Ktane6bqdO5EQ73x8GX:-KtiF_KTq-pWs1F-cYxa:b-896fix) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/xlib/drawing.c#L15)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

we don't -_-

I know, I know....  I'll fix it....
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045#-:-KtiKQ8HB0nuYv0vVqe0:bt2zdwj)*

**Comment by GrayHatter** [comment]
scratch that, fixed both!

---

Review status: 9 of 17 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045#-:-KtiLC8poWP1VkBxuYk5:b-v94v8y)*

**Comment by endoffile78** [comment]
Reviewed 7 of 8 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/windows/drawing.c, line 14 at r4](https://reviewable.io:443/reviews/utox/utox/1045#-KtvdntZUG-zDJ71SE4E:-KtvdntZUG-zDJ71SE4F:bfc67df) ([raw file](https://github.com/utox/utox/blob/f7bcecee5a492c5874efa7a7e53e8aa9353f972b/src/windows/drawing.c#L14)):*
> ```C
> 
> static UTOX_WINDOW *curr_win = NULL;
> bool draw_set_target(UTOX_WINDOW *next_win) {
> ```

OSX and android need this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Comment by robinlinden** [comment]
Memory leak is still there, but I think it's leaking memory slower than last commit.
image

**Comment by robinlinden** [comment]
Reviewed 8 of 8 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/layout/friend.c, line 224 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoI59zQshBPq5S5Xh:-Ku9ecmXJEFQICkCDRTk:b-ufhzoy) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L224)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

the source code alignment, not the memory alignment. :D
</blockquote></details>

Disgusting. (but no change needed, I guess..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/layout/friend.c, line 224 at r2](https://reviewable.io:443/reviews/utox/utox/1045#-KtaoI59zQshBPq5S5Xh:-KuLXf78RpAgaxSQYHyx:b2nhipw) ([raw file](https://github.com/utox/utox/blob/0dce33ba6c08972698f6dfba76d133cf7536b36c/src/layout/friend.c#L224)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Disgusting. (but no change needed, I guess..)
</blockquote></details>

LOL

---

*[src/windows/drawing.c, line 14 at r4](https://reviewable.io:443/reviews/utox/utox/1045#-KtvdntZUG-zDJ71SE4E:-KuLXhoVFp2vWm-dT_hi:bm5ru4r) ([raw file](https://github.com/utox/utox/blob/f7bcecee5a492c5874efa7a7e53e8aa9353f972b/src/windows/drawing.c#L14)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

OSX and android need this function.
</blockquote></details>

What are those again? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1045)*

**Pull request closed without merging**
