### PR TITLE
update cmake - use find modules and pkg-config - enable static build for macOS and dmg

### PR DESCRIPTION
**Pull request by publicarray**
~~[copy_and_fixup_bundle](https://cmake.org/cmake/help/latest/module/BundleUtilities.html) copies and fixes links on dependent libs so it
becomes a redistributeable app.~~

The mac app can now be compiled as to a static binary with cmake.
WIP because it requires testing on other platforms.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/872)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 93 at r1](https://reviewable.io:443/reviews/utox/utox/872#-Kihb0Eh0hjyxYK8C8Hq:-Kihb0Eh0hjyxYK8C8Hr:b-hyoy0j) ([raw file](https://github.com/utox/utox/blob/94bd175af9c886d8dbaad5c4bbab6f2b37fc8878/CMakeLists.txt#L93)):*
> ```CMake
>                ${uTox_SOURCE_DIR}/src/branding.h)
> configure_file(${uTox_SOURCE_DIR}/src/cocoa/Info.plist.in
>                ${uTox_SOURCE_DIR}/src/cocoa/Info.plist)
> ```

Why was this removed?

---

*[CMakeLists.txt, line 276 at r1](https://reviewable.io:443/reviews/utox/utox/872#-Kihb2LN5VTGmGPJc4UY:-Kihb2LN5VTGmGPJc4UZ:b-lcyqxp) ([raw file](https://github.com/utox/utox/blob/c3fd7dc05bea65a12ece13570ac297411f34c6e6/CMakeLists.txt#L276)):*
> ```CMake
> 
>     find_package(libtoxcore REQUIRED)
>     find_package(libfilteraudio REQUIRED)
> ```

Add a `if(ENABLE_FILTERAUDIO)`  around this. Filteraudio isn't required to build uTox.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 93 at r1](https://reviewable.io:443/reviews/utox/utox/872#-Kihb0Eh0hjyxYK8C8Hq:-KihlsubfnOglq6j7o1Q:b-27bhlf) ([raw file](https://github.com/utox/utox/blob/94bd175af9c886d8dbaad5c4bbab6f2b37fc8878/CMakeLists.txt#L93)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

Ah so all of the `set_target_properties(utox PROPERTIES MACOSX_BUNDLE_FOO BAR)` work is that it leaves cmake to generate the Info.plist from scratch. So the one generated here is ignored.
I think the way it was, was better. I'll make a commit to change it back.
I keep learning more things about cmake.. there are so many different ways to do similar things.

---

*[CMakeLists.txt, line 276 at r1](https://reviewable.io:443/reviews/utox/utox/872#-Kihb2LN5VTGmGPJc4UY:-Kihnr5bfz1gV2LtZmdt:b-e95nt0) ([raw file](https://github.com/utox/utox/blob/c3fd7dc05bea65a12ece13570ac297411f34c6e6/CMakeLists.txt#L276)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Add a `if(ENABLE_FILTERAUDIO)`  around this. Filteraudio isn't required to build uTox.
</blockquote></details>

Thanks I missed that :) should the 2 lines be in an APPLE only block or could they be put up to where the

```
if(ENABLE_FILTERAUDIO)
    add_cflag("-DAUDIO_FILTERING")
endif()
```

block is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by endoffile78** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 276 at r1](https://reviewable.io:443/reviews/utox/utox/872#-Kihb2LN5VTGmGPJc4UY:-KilcUTH7nL0_9A1_n8N:b-ecdcr7) ([raw file](https://github.com/utox/utox/blob/c3fd7dc05bea65a12ece13570ac297411f34c6e6/CMakeLists.txt#L276)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Thanks I missed that :) should the 2 lines be in an APPLE only block or could they be put up to where the

```
if(ENABLE_FILTERAUDIO)
    add_cflag("-DAUDIO_FILTERING")
endif()
```

block is?
</blockquote></details>

Yeah lets try it there. Also move the toxcore one out the if statement. It might now work on windows but lets try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 276 at r1](https://reviewable.io:443/reviews/utox/utox/872#-Kihb2LN5VTGmGPJc4UY:-Kim0UnSoSrvP0rE6ALM:b-p2m6j) ([raw file](https://github.com/utox/utox/blob/c3fd7dc05bea65a12ece13570ac297411f34c6e6/CMakeLists.txt#L276)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Yeah lets try it there. Also move the toxcore one out the if statement. It might now work on windows but lets try.
</blockquote></details>

It builds fine with travis on all platforms, however my detection for filter-audio is incorrect. So please don't merge yet thanks. The CMakeLists looks a little bit cleaner now too :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 276 at r1](https://reviewable.io:443/reviews/utox/utox/872#-Kihb2LN5VTGmGPJc4UY:-Kim2-unriCQbZUJvlzo:bh6i82y) ([raw file](https://github.com/utox/utox/blob/c3fd7dc05bea65a12ece13570ac297411f34c6e6/CMakeLists.txt#L276)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

It builds fine with travis on all platforms, however my detection for filter-audio is incorrect. So please don't merge yet thanks. The CMakeLists looks a little bit cleaner now too :)
</blockquote></details>

for reference: https://travis-ci.org/uTox/uTox/jobs/226633530#L553

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by endoffile78** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by robinlinden** [comment]
Reviewed 2 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/Findlibfilteraudio.cmake, line 1 at r3](https://reviewable.io:443/reviews/utox/utox/872#-KiqBgyVXxxdJxLn-4Dh:-KiqBgyVXxxdJxLn-4Di:b-gtvti4) ([raw file](https://github.com/utox/utox/blob/81fb09d5309af6e0313e13024de02442181c8ac5/cmake/Findlibfilteraudio.cmake#L1)):*
> ```CMake
> # - Try to find ToxCore
> ```

Comments still have to be updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmake/Findlibfilteraudio.cmake, line 1 at r3](https://reviewable.io:443/reviews/utox/utox/872#-KiqBgyVXxxdJxLn-4Dh:-Kir95xqwGj9D90g2UfE:b-ucfknh) ([raw file](https://github.com/utox/utox/blob/81fb09d5309af6e0313e13024de02442181c8ac5/cmake/Findlibfilteraudio.cmake#L1)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Comments still have to be updated.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by robinlinden** [comment]
Reviewed 2 of 5 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
@stal888 I have made a static build using cmake. I would appreciate if you could quickly test out the binary. The build runs smoothly on my machine. But I prefer if someone else took a look 🙉 https://drive.google.com/file/d/0B25hJXEzaTIFVFRPeTZVR1FsOU0
Also what version of macOS are you running?

```sh
$ gsha256sum uTox\ 0.15.0.dmg 
5799df42fc96aacb4bc96637cc1be52a060f29e3e6b03b4fc513d313889432ec  uTox 0.15.0.dmg
```

**Comment by stal888** [comment]
The build works on Sierra (sometimes it just exits immediately, but I don't know why). 

I see that `LC_VERSION_MIN_MACOSX` is set to 10.12. You may want to set it lower (I use 10.6) just to be safe. You can do that by passing `-mmacosx-version-min=10.6` to the compiler/linker.

**Comment by GrayHatter** [comment]
@stal888 @robinlinden 'found' a bug in incoming avatars, I'd put money on that being the crash you're seeing. Once we squish that bug, we should try again just to make sure.

**Comment by publicarray** [comment]
@endoffile78 I'm a bit stumped by the [build log in travis](https://travis-ci.org/uTox/uTox/jobs/231793917#L2363). 😓. I can build uTox on my mac but Travis just prints `write error`. 😕 Any ideas?

**Comment by endoffile78** [comment]
@publicarray This might be the problem: https://github.com/travis-ci/travis-ci/issues/4704. Try it without VERBOSE=1 on the OSX build.

**Comment by endoffile78** [comment]
Reviewed 1 of 5 files at r3, 2 of 10 files at r5, 1 of 2 files at r8, 8 of 10 files at r9, 3 of 3 files at r10.
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[extra/travis/osx-script.sh, line 10 at r10](https://reviewable.io:443/reviews/utox/utox/872#-Kk6kAwP2JMa2WE54bAK:-Kk6kAwP2JMa2WE54bAL:b-icyc3r) ([raw file](https://github.com/utox/utox/blob/fb9019e6f498b9cec83b53aa1911625b016ade8c/extra/travis/osx-script.sh#L10)):*
> ```Shell
>   -DCMAKE_LIBRARY_PATH="$CACHE_DIR/usr/lib" \
>   -DENABLE_WERROR=OFF
> make VERBOSE=1
> ```

Get rid of VERBOSE=1 and see if the write error still happens.

---

*[src/cocoa/Makefile, line 25 at r10](https://reviewable.io:443/reviews/utox/utox/872#-Kk6jSbuq1j3U5VtLEXa:-Kk6jSbvaB66DwpzwaEL:b-6u5klw) ([raw file](https://github.com/utox/utox/blob/fb9019e6f498b9cec83b53aa1911625b016ade8c/src/cocoa/Makefile#L25)):*
> ```Makefile
> LDFLAGS += $(shell pkg-config --libs $(DEPS))
> 
> DESTDIR ?=
> ```

This file can probably be deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by endoffile78** [comment]
Reviewed 1 of 10 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[extra/travis/osx-script.sh, line 10 at r10](https://reviewable.io:443/reviews/utox/utox/872#-Kk6kAwP2JMa2WE54bAK:-Kk7a5Rr3YwpgQ0cGioI:b-8btcsa) ([raw file](https://github.com/utox/utox/blob/fb9019e6f498b9cec83b53aa1911625b016ade8c/extra/travis/osx-script.sh#L10)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Get rid of VERBOSE=1 and see if the write error still happens.
</blockquote></details>

Thanks! That has solved the problem for now

---

*[src/cocoa/Makefile, line 25 at r10](https://reviewable.io:443/reviews/utox/utox/872#-Kk6jSbuq1j3U5VtLEXa:-Kk7aGvpFhW9nh-iPuQ5:b-abfven) ([raw file](https://github.com/utox/utox/blob/fb9019e6f498b9cec83b53aa1911625b016ade8c/src/cocoa/Makefile#L25)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

This file can probably be deleted.
</blockquote></details>

I agree, but it could be used as a fallback? maybe? :thinking: 

If we do remove it I would also remove all related files as well [find_static.sh, make_dmg.sh, make_info_plist.sh, frozen_dmg.tar.bz2]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Should I cleanup my git history? It's a bit of a mess.

**Comment by endoffile78** [comment]
@publicarray Sure. squash it to whatever you think is appropriate.

**Comment by GrayHatter** [comment]
+@endoffile78 

---

Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-Kk7orMKCaHqmyxeq78l:bgs4sbv)*

**Comment by publicarray** [comment]
I think this PR is up for review 👏  and @endoffile78 thanks so much for your help.

**Comment by publicarray** [comment]
Review status: 11 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/Makefile, line 25 at r10](https://reviewable.io:443/reviews/utox/utox/872#-Kk6jSbuq1j3U5VtLEXa:-Kk899KgFdfEf5Zt1WSj:b-896fix) ([raw file](https://github.com/utox/utox/blob/fb9019e6f498b9cec83b53aa1911625b016ade8c/src/cocoa/Makefile#L25)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

I agree, but it could be used as a fallback? maybe? :thinking: 

If we do remove it I would also remove all related files as well [find_static.sh, make_dmg.sh, make_info_plist.sh, frozen_dmg.tar.bz2]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
@stal888 I have a new version for you. 
https://drive.google.com/open?id=0B25hJXEzaTIFR2hXU3NzNmxLMlU
```
$ gsha256sum uTox\ 0.15.1.dmg 
e211acf91c563edb7605ff75ef0553c8ac311d18276ad864f7f65d1f45fa2d2d  uTox 0.15.1.dmg
```

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 7 of 9 files at r11, 5 of 5 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-KkI3pCxd3JCxP8enXQi:bnfp4nl)*

**Comment by endoffile78** [comment]
@GrayHatter and @robinlinden can one of you guys review this when you get the time.

**Comment by robinlinden** [comment]
I had a look, but was unable to get uTox compiling on Windows with this merged. I'll look into it more this weekend if I have time.
I tried setting `CMAKE_PREFIX_PATH`, `CMAKE_INCLUDE_PATH`, `CMAKE_LIBRARY_PATH`, and probably some other things I can't think of off of the top of my head.

**Comment by endoffile78** [comment]
There's an issue with cross compiling, it tries to use the linux version of pkg-config instead of the mingw. This could be just an issue with cmake though.

```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found libtox: /usr/local/lib/libtoxencryptsave.a;/usr/local/lib/libtoxdns.a;/usr/local/lib/libtoxav.a;/usr/local/lib/libtoxcore.a  
-- Configuring incomplete, errors occurred!
See also "/home/endoffile/src/github/tox/utox/build-win/CMakeFiles/CMakeOutput.log".
```

**Comment by publicarray** [comment]
Thanks @robinlinden and  @endoffile78 for investigating. 

@robinlinden I see If I can dust off my old windows VM. From memory I had a problem with it connecting to the internet.

@endoffile78 
Would setting the `PKG_CONFIG_PATH` environment variable help? FYI travis also used `/usr/bin/pkg-config` and [passed](https://travis-ci.org/uTox/uTox/jobs/232229401#L786)

**Comment by publicarray** [comment]
oops I was messing with my local repo. Or so I thought...

**Comment by GrayHatter** [comment]
This commit history is gonna need a rewrite (I know, I can't believe I'm saying this either...) All I care about is that you squash down the renames, and add/deletes.

If you need help battling with git, find me on IRC

---

Reviewed 3 of 10 files at r9, 7 of 9 files at r11, 4 of 5 files at r12, 4 of 4 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/Findlibtox.cmake, line 1 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7sTUmMAktMx0j0aW7:-Kl7sTUmMAktMx0j0aW8:b-mps6g9) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/cmake/Findlibtox.cmake#L1)):*
> ```CMake
> # - Try to find Tox
> ```

BTW This might be a nice file to send upstream to toxcore as well :D

---

*[src/av/CMakeLists.txt, line 22 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7smjPWbhUc9KKyg_j:-Kl7smjPWbhUc9KKyg_k:bqbvf2d) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/av/CMakeLists.txt#L22)):*
> ```CMake
> 
> if(ENABLE_FILTERAUDIO)
>     find_package(libfilteraudio REQUIRED)
> ```

it's not required, it's optional

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-Kl7rTfs34-dwtITKF0j:br9vu4m) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
> ```XML
> 	<string>en</string>
> 	<key>CFBundleExecutable</key>
> 	<string>utox</string>
> ```

This change seems wrong. are you sure this is correct? 

If not, revert this change, and add this file to the .gitignore file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-Kl7s03jdJXTujct3noN:b24dbrg)*

**Comment by publicarray** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/av/CMakeLists.txt, line 22 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7smjPWbhUc9KKyg_j:-Kl8-ohFyGpR8iaQmROl:b-r6qe2t) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/av/CMakeLists.txt#L22)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

it's not required, it's optional
</blockquote></details>

Yea I assumed with the ENABLE_FILTERAUDIO set to true that we should require it? otherwise we silently ignore the user wishes and dreams of filtered audio. IMH I would prefer to be told that I'm missing the lib or that the flag should be turned off. 

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-Kl8159BthUNtW_f2AyH:buwxndp) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

This change seems wrong. are you sure this is correct? 

If not, revert this change, and add this file to the .gitignore file.
</blockquote></details>

Yea the file is auto generated must have missed this in the merge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/av/CMakeLists.txt, line 22 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7smjPWbhUc9KKyg_j:-Kl81jrhxQZStytApmcm:b4sfwbx) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/av/CMakeLists.txt#L22)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Yea I assumed with the ENABLE_FILTERAUDIO set to true that we should require it? otherwise we silently ignore the user wishes and dreams of filtered audio. IMH I would prefer to be told that I'm missing the lib or that the flag should be turned off. 
</blockquote></details>

Oh I totally missed that. You're 100% right :lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
@GrayHatter Agreed! I made a big mess :stuck_out_tongue: Now that I have VM's I don't have to guess anymore. I'll clean it up ASAP 

---

Review status: 18 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-KlcAwb46EK1Ud3Jf24w:b-xyw0d) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Yea the file is auto generated must have missed this in the merge
</blockquote></details>

Since the file is generated at every build. The source is [Info.plist.in](https://github.com/uTox/uTox/blob/develop/src/cocoa/Info.plist.in).  IMHO we can remove it from git and move the generated files into the current build directory (same with AndroidManifest and branding.h) using (${PROJECT_BINARY_DIR}){https://cmake.org/Wiki/CMake_Useful_Variables#Locations} that way git is clean even after a build. what do you guys think? 
i.e from 
```
configure_file(${uTox_SOURCE_DIR}/src/cocoa/Info.plist.in
               ${uTox_SOURCE_DIR}/src/cocoa/Info.plist)
```
to 
```
configure_file(${uTox_SOURCE_DIR}/src/cocoa/Info.plist.in
               ${PROJECT_BINARY_DIR}/Info.plist)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-Klc92usY0bI8zZSVze4:bs4g3yp)*

**Comment by publicarray** [comment]
Review status: 18 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-KlhZEteQUScCY5-Gery:bs2tek8) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Since the file is generated at every build. The source is [Info.plist.in](https://github.com/uTox/uTox/blob/develop/src/cocoa/Info.plist.in).  IMHO we can remove it from git and move the generated files into the current build directory (same with AndroidManifest and branding.h) using (${PROJECT_BINARY_DIR}){https://cmake.org/Wiki/CMake_Useful_Variables#Locations} that way git is clean even after a build. what do you guys think? 
i.e from 
```
configure_file(${uTox_SOURCE_DIR}/src/cocoa/Info.plist.in
               ${uTox_SOURCE_DIR}/src/cocoa/Info.plist)
```
to 
```
configure_file(${uTox_SOURCE_DIR}/src/cocoa/Info.plist.in
               ${PROJECT_BINARY_DIR}/Info.plist)
```
</blockquote></details>

I'm happy to reverse this change. What ever the decision it should probably be handled in a separate Pull Request anyway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by endoffile78** [comment]
Reviewed 1 of 5 files at r3, 3 of 4 files at r13, 6 of 6 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-KllCrC3M0moMoKuMtgQ:bc7yvwu) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

I'm happy to reverse this change. What ever the decision it should probably be handled in a separate Pull Request anyway
</blockquote></details>

That was done at one point but it ended up getting reverted. I'm OK with them being in the .gitignore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Review status: 20 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-KnMoJYieBjT5Kq9sshl:b3qfrp1) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

That was done at one point but it ended up getting reverted. I'm OK with them being in the .gitignore.
</blockquote></details>

Done. 

Because the file is already tracked in git `git update-index --assume-unchanged src/cocoa/Info.plist` will "untrack" the file locally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by publicarray** [comment]
Are there any issues or nitpicks I should fix or are we all happy :)

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r3, 1 of 5 files at r12, 4 of 6 files at r14, 3 of 3 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-KnYM6o3mcLHDYkHU_Ys:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-Kn_jqbkP8bNjJle1Pnu:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 5 files at r3, 1 of 10 files at r5, 1 of 2 files at r8, 8 of 10 files at r9, 1 of 3 files at r10, 7 of 9 files at r11, 5 of 5 files at r12, 2 of 4 files at r13, 4 of 6 files at r14, 3 of 3 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Comment by robinlinden** [comment]
@publicarray Sorry about this not having been merged yet. Can you check the box that allows me to rebase it or do it yourself?

**Comment by publicarray** [comment]
@robinlinden That's fine. I'd love to, but am I going mad or is that checkbox gone? 😕  Anyway I did a rebase I just hope I didn't mess something up 😉

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r17.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-Kr6VACVliT841dqpJUX:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r17.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-Kr71Fkm2jd6I0aWTrbp:b-gyfegl) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
<details><summary><i>Previously, publicarray (Sebastian Schmidt) wrote…</i></summary><blockquote>

Done. 

Because the file is already tracked in git `git update-index --assume-unchanged src/cocoa/Info.plist` will "untrack" the file locally
</blockquote></details>

let's delete it from the repo, add it to .gitignore and make sure it's being generated correctly (i.e. make clean should leave the files intact)

@robinlinden can do this if you don't want to

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-Kr71Tu9ei4Q8yUrwFj8:bnfp4nl)*

**Comment by publicarray** [comment]
@robinlinden I figured it out and I'm not going mad. Because the branch [pkgconfig](https://github.com/uTox/uTox/tree/pkgconfig) is in uTox/uTox you already have the necessary permissions to rebase or otherwise change this PR.

**Comment by robinlinden** [comment]
@publicarray Whoops. Sorry, not used to PRs from uTox to uTox. :P

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r18.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872#-:-Ks-uqygU3KxFhPROZDV:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cocoa/Info.plist, line 8 at r13](https://reviewable.io:443/reviews/utox/utox/872#-Kl7rTfs34-dwtITKF0i:-Ks-wcAWn-C2qI854MEC:bb7f2mf) ([raw file](https://github.com/utox/utox/blob/d5e2e5ad4e144a873d2cae06f581999b1f7a51bf/src/cocoa/Info.plist#L8)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

let's delete it from the repo, add it to .gitignore and make sure it's being generated correctly (i.e. make clean should leave the files intact)

@robinlinden can do this if you don't want to
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/872)*

**Pull request merged**
