### PR TITLE
Update group notifications setting on start

### LINKED ISSUE #935: Group notifications setting dropdown isn't updated on start

### PR DESCRIPTION
**Pull request by redmanmale**
Fix #935.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1007)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1007#-:-KsGN8X_ICJhsGDDSfnp:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/settings.c, line 150 at r1](https://reviewable.io:443/reviews/utox/utox/1007#-KsP4wYbBy3VscK3KZwb:-KsP4wYbBy3VscK3KZwc:b1bippx) ([raw file](https://github.com/utox/utox/blob/bf898e5c8200bb86790a21c044e4644271cd8135/src/settings.c#L150)):*
> ```C
>     switch_auto_update.switch_on        = save->auto_update;
> 
>     dropdown_global_group_notifications.selected = save->group_notifications;
> ```

Set this together with `settings.group_notifications` like how it's done for the theme dropdown and setting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1007)*

**Comment by redmanmale** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/settings.c, line 150 at r1](https://reviewable.io:443/reviews/utox/utox/1007#-KsP4wYbBy3VscK3KZwb:-KsP9kJe4vEMxnWFlRZC:b-896fix) ([raw file](https://github.com/utox/utox/blob/bf898e5c8200bb86790a21c044e4644271cd8135/src/settings.c#L150)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Set this together with `settings.group_notifications` like how it's done for the theme dropdown and setting.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1007)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1007#-:-KsPF_HoVj0wz8GERXDo:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1007#-:-KsPvdkOIQAx-1r5x45w:bnfp4nl)*

**Pull request merged**
