### PR TITLE
fix utox clobbering chatlogs

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/595)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_22_MSAhSzmvoquoKr:bnfp4nl)*

**Comment by cebe** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/595#-K_23OqBQF_ddZvRcq-r:-K_23OqBQF_ddZvRcq-s:b-531197) ([raw file](https://github.com/utox/utox/blob/4033b3ad5925582f44ab081df2cb0877c976c955/src/chatlog.c#L15)):*
> ```C
>     if (append) {
>         file = native_get_file(name, NULL, UTOX_FILE_OPTS_READ | UTOX_FILE_OPTS_APPEND | UTOX_FILE_OPTS_MKDIR);
>         fseek(file, 0, SEEK_END);
> ```

shouldn't this be done by the `native_get_file`, seems that would be expected behavior, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_23SX9v19s6NZ_nOdt:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/595#-K_23OqBQF_ddZvRcq-r:-K_2MdsJd79QX8IIY2TI:bll3jru) ([raw file](https://github.com/utox/utox/blob/4033b3ad5925582f44ab081df2cb0877c976c955/src/chatlog.c#L15)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

shouldn't this be done by the `native_get_file`, seems that would be expected behavior, no?
</blockquote></details>

I don't want to imply anything more than we have to, in this case, the caller shouldn't expect that the file returned is in [location].

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595)*

**Comment by endoffile78** [comment]
The android version of native_get_file needs to be changed too.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_2SkEiSk3HDErTVMgW:brit45s)*

**Comment by GrayHatter** [comment]
@endoffile78 android is done

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_2Yp1hqZrg8Qve18Pn:b-2s0bnp)*

**Comment by endoffile78** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/main.c, line 255 at r4](https://reviewable.io:443/reviews/utox/utox/595#-K_2ZrLPKixFKEpN6Ha3:-K_2ZrLQ0rJfYlWIl9JG:b-lqcal6) ([raw file](https://github.com/utox/utox/blob/4faf45a0dd63315dd4edebe86f664fd6158aedc8/src/android/main.c#L255)):*
> ```C
>     FILE *fp = fopen(path, mode);
> 
>     if (opts & UTOX_FILE_OPTS_WRITE && !fp) {
> ```

Should this also be added to the windows verison?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595)*

**Comment by GrayHatter** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/main.c, line 255 at r4](https://reviewable.io:443/reviews/utox/utox/595#-K_2ZrLPKixFKEpN6Ha3:-K_2uCVC_k3X7nQmLDX9:b-4ehw3k) ([raw file](https://github.com/utox/utox/blob/4faf45a0dd63315dd4edebe86f664fd6158aedc8/src/android/main.c#L255)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Should this also be added to the windows verison?
</blockquote></details>

just tested: windows doesn't have this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595)*

**Comment by robinlinden** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/chatlog.c, line 16 at r5](https://reviewable.io:443/reviews/utox/utox/595#-K_47LH0GnVw0WFDW-Zp:-K_47LH0GnVw0WFDW-Zq:b-8gn6vc) ([raw file](https://github.com/utox/utox/blob/7c304a354f4c7c5e082f98893e4f9533337502cb/src/chatlog.c#L16)):*
> ```C
>         file = native_get_file(name, NULL, UTOX_FILE_OPTS_READ | UTOX_FILE_OPTS_WRITE | UTOX_FILE_OPTS_MKDIR);
>         if (file) {
>             fseek(file, 0, SEEK_END);
> ```

Passing a[+] to fopen forces all writes at EOF. How is this better? 

---

*[src/posix/filesys.c, line 79 at r5](https://reviewable.io:443/reviews/utox/utox/595#-K_45imI2XNtfZ7kD18l:-K_45imI2XNtfZ7kD18m:b84a0jf) ([raw file](https://github.com/utox/utox/blob/7c304a354f4c7c5e082f98893e4f9533337502cb/src/posix/filesys.c#L79)):*
> ```C
>     if (!fp && opts & UTOX_FILE_OPTS_READ && opts & UTOX_FILE_OPTS_WRITE) {
>         debug_notice("POSIX:\tUnable to simple open, falling back to fd\n");
>         // read wont create a file if it doesn't' already exist. If we're allowed to write, lets try
> ```

Read wont, but w+ and a+ will which is why opts_to_sysmode would return a+ or w+ if you passed both read and write/append.

---

*[src/windows/filesys.c, line 14 at r5](https://reviewable.io:443/reviews/utox/utox/595#-K_4709Yw3kow-MWt0Bx:-K_4709Z2GJUBSjg-fbu:bybup7t) ([raw file](https://github.com/utox/utox/blob/7c304a354f4c7c5e082f98893e4f9533337502cb/src/windows/filesys.c#L14)):*
> ```C
>         rw |= GENERIC_READ;
>         mode[0] = 'r';
>     } else if (opts & UTOX_FILE_OPTS_APPEND) {
> ```

Same as with xlib. This should no longer create files if it gets both READ and APPEND/WRITE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595)*

**Comment by robinlinden** [comment]
Looking at this, we should probably add a utox file opt for update and use that when we want to write in the middle of a file. We should probably also have chatlog_get_file take utox file opts and pass them to native_get_file instead of not really appending if we pass append=true. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_4hcsOYaW0PYTNavht:bycdfzk)*

**Comment by GrayHatter** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/chatlog.c, line 16 at r5](https://reviewable.io:443/reviews/utox/utox/595#-K_47LH0GnVw0WFDW-Zp:-K_6aIMLnRVIc4i4dW7n:b-gn2zgr) ([raw file](https://github.com/utox/utox/blob/7c304a354f4c7c5e082f98893e4f9533337502cb/src/chatlog.c#L16)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Passing a[+] to fopen forces all writes at EOF. How is this better? 
</blockquote></details>

This function has two options, readonly, or read and write. Because this is also called when we need to write to the middle of the file. 

So we don't want to force writes to be append only.  The calling functions will always seek on their own anyways. 

---

*[src/posix/filesys.c, line 79 at r5](https://reviewable.io:443/reviews/utox/utox/595#-K_45imI2XNtfZ7kD18l:-K_6amZ60F_C3kb7zN2X:bfz2bx5) ([raw file](https://github.com/utox/utox/blob/7c304a354f4c7c5e082f98893e4f9533337502cb/src/posix/filesys.c#L79)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Read wont, but w+ and a+ will which is why opts_to_sysmode would return a+ or w+ if you passed both read and write/append.
</blockquote></details>

Yes, but I changed it, to default to non clobbering. If you ask for read, you'll get RD or RDWR. Then if the file is unopenable with read write (doesn't exist). It'll try to open for writing, just below.

---

*[src/windows/filesys.c, line 14 at r5](https://reviewable.io:443/reviews/utox/utox/595#-K_4709Yw3kow-MWt0Bx:-K_6dGrRV9LhzUfhlfIb:b-896fix) ([raw file](https://github.com/utox/utox/blob/7c304a354f4c7c5e082f98893e4f9533337502cb/src/windows/filesys.c#L14)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Same as with xlib. This should no longer create files if it gets both READ and APPEND/WRITE.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_6eEZyEqYQ-WTbhk6F:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595)*

**Comment by robinlinden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_U30nXWuMtesbOqRF9:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595#-:-K_aSKIoX_h96cJYi170:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/595)*

**Pull request merged**
