### PR TITLE
Update deprecated debug calls.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/883)

### CODE REVIEW

**Comment by redmanmale** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/os_video.c, line 539 at r1](https://reviewable.io:443/reviews/utox/utox/883#-Kiq6ils3LbZBWV-pAxJ:-Kiq6iltkFR7Q13eQ2AJ:b-f1924a) ([raw file](https://github.com/utox/utox/blob/e4d1e76d784b8a1de192c5d3713e51356227d110/src/windows/os_video.c#L539)):*
> ```C
> 
>     if (FAILED(pGraph->lpVtbl->RemoveFilter(pGraph, pFilter))) {
>         LOG_ERR("Video", "Failed to close webcam (1).");
> ```

Here and below are used a little different formatting (dot at the end).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/883)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/883#-:-Kiq74eZgURrJEs3F6FN:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/883#-:-Kiq7Sct3SnM4nwCCXNr:bnfp4nl)*

**Comment by robinlinden** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/os_video.c, line 539 at r1](https://reviewable.io:443/reviews/utox/utox/883#-Kiq6ils3LbZBWV-pAxJ:-Kiq9L2cW-jjY7zZLMAv:b-896fix) ([raw file](https://github.com/utox/utox/blob/e4d1e76d784b8a1de192c5d3713e51356227d110/src/windows/os_video.c#L539)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Here and below are used a little different formatting (dot at the end).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/883)*

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/883)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/883#-:-KiqAgcB9V8h1VWxe38o:bnfp4nl)*

**Pull request merged**
