### PR TITLE
separated out logging from main.h

### PR DESCRIPTION
**Pull request by cebe**
reduce a lot of dependencies of things on main.h which included it
simply for logging.
This possibly conflicts with #610.
Will rebase when that one is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/617)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 51 of 51 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaP7bZIB95VkKw3PIQW:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 51 of 51 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaPEhCbRZjvFnpvDgb-:bnfp4nl)*

**Comment by endoffile78** [comment]
Windows doesn't build. :lgtm_cancel: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaPFFMseaLfLbrg0nhY:b-mkwxsf)*

**Comment by cebe** [comment]
should be fixed, lets wait for travis to verify. Also added missing headers to OSX and andriod. I have no windows to test on.

---

Review status: 50 of 66 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaPJdzvkJ7chH444Ja5:bh7a7y5)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 15 of 16 files at r2, 13 of 13 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaPfRocEdYix_-1eEma:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaPg_AkSznV5CpDlaTT:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 39 of 51 files at r1, 16 of 16 files at r2, 1 of 1 files at r3, 12 of 13 files at r4, 5 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaQ-BoOYy-HpuDsARwi:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6, 1 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaQ1ZK_CLvp17ThRf8d:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 16 of 16 files at r2, 1 of 1 files at r3, 12 of 13 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, 1 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/617#-:-KaR4ORhqVJW8OYPDE3W:bg7igkv)*

**Pull request merged**
