### PR TITLE
Remove incorrect debug info & fix X11 middle click to paste

### LINKED ISSUE #586: Unencrypted debug info is wrong
when uTox loads an unencrypted save, it says doing is insecure. This is incorrect.

### PR DESCRIPTION
**Pull request by dkmoz**
Fixes #586

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/932)

### CODE REVIEW

**Comment by robinlinden** [comment]
Sweet, thank you! :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932#-:-Kl92UJj_4hIfK0qvmKg:bhgoe23)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932#-:-Kl9CFl10FP4fpjlsn-f:bnfp4nl)*

**Comment by dkmoz** [comment]
Fixes #784

**Comment by redmanmale** [comment]
@dkmoz 
It's better to open a separate PRs for a separate fixes.

**Comment by dkmoz** [comment]
Yeah sorry

**Comment by robinlinden** [comment]
@dkmoz No worries. Feel free to join us on IRC at [#uTox on Freenode](https://webchat.freenode.net/?channels=#utox) if you need any help with git or anything. :) 
That X11 middle click thing is something that's requested a lot, so it's really great that you found and fixed it.

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932)*

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/xlib/event.c, line 105 at r2](https://reviewable.io:443/reviews/utox/utox/932#-Kl9TN8tnKT9KhB0bOUE:-Kl9TN8tnKT9KhB0bOUF:bxkgx5f) ([raw file](https://github.com/utox/utox/blob/ab2d4ebd680203691f7b54e657ed67b0f9c27818/src/xlib/event.c#L105)):*
> ```C
>         }
> 
> 		case Button2: {
> ```

Whitespace needs to be 4 spaces instead of tabs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932#-:-Kl9V6gSMXcniP6w6uEt:bnfp4nl)*

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/932#-:-Kl9ue58xEcQWth9_2OJ:bnfp4nl)*

**Pull request merged**
