### PR TITLE
Removed mix of Spaces+Tabs and switched to tabs only

### PR DESCRIPTION
**Pull request by Vehemos**
@redmanmale refrened this issue here (#1111)

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1155)

### CODE REVIEW

**Comment by GrayHatter** [comment]
I don't want to touch files for only whitespace changes.

Also, I don't like the changes the comment block formatting.

**Comment by redmanmale** [comment]
@GrayHatter 
Do you think it's better to leave things as they are?

@Vehemos 
Also `Info.plist` please.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1155#-:-L19YLKD7e0rk7t_WPld:b-75jhdr)*

**Comment by Vehemos** [comment]
@GrayHatter I just changed the the block to have equal number of characters in all rows not aligning *s, but I can change it back if you want.

@redmanmale ummm Info.plist doesn't exist? I tried searching for it before, but only Info.plist.in exists not Info.plist

**Comment by redmanmale** [comment]
@Vehemos
Yea, you're right.

:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1155#-:-L19d1dL4-EMCJWhZZo3:b-j0deti)*

**Comment by GrayHatter** [comment]
We can't accept any external patches that are white space only changes

**Pull request closed without merging**
