### PR TITLE
Support Toxcore 0.2.0

### PR DESCRIPTION
**Pull request by robinlinden**
This won't pass Travis without #1153.

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1157)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157#-:-L1d2j9ikVqvPw3OmolH:bnfp4nl)*

**Comment by fcore117** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157)*

**Comment by robinlinden** [comment]
Rebased on top of #1153.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157#-:-L3Ac8HHHYzoGW1YhRWS:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157#-:-L3HxFDgNMy3Oknzgm_2:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/main.h, line 23 at r2](https://reviewable.io:443/reviews/utox/utox/1157#-L3dhVp30XrbNa64OJsE:-L3dhVp4j8_c8eLlV5wH:b-orctf2) ([raw file](https://github.com/utox/utox/blob/44c6bc96b88a57f77138e9f5cb902590b3902b6b/src/main.h#L23)):*
> Requires version 2

> Error says requires version 1

Devs: http://i.imgur.com/cHpJWos.gif

Users: https://i.pinimg.com/736x/c2/af/1b/c2af1bab21e977e1967947148ee73494.jpg

Me: http://i.imgur.com/76Eq9gj.gif

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157)*

**Comment by robinlinden** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.h, line 23 at r2](https://reviewable.io:443/reviews/utox/utox/1157#-L3dhVp30XrbNa64OJsE:-L4qdsAOoUXUdbd3rLHe:b-896fix) ([raw file](https://github.com/utox/utox/blob/44c6bc96b88a57f77138e9f5cb902590b3902b6b/src/main.h#L23)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

> Requires version 2

> Error says requires version 1

Devs: http://i.imgur.com/cHpJWos.gif

Users: https://i.pinimg.com/736x/c2/af/1b/c2af1bab21e977e1967947148ee73494.jpg

Me: http://i.imgur.com/76Eq9gj.gif
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157)*

**Comment by GrayHatter** [comment]
I don't approve of this change, I don't think toktok/c-toxcore is safe. You have enough votes to merge it either way, just know that means you're taking over as lead developer.

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157#-:-L4wDpU6eZOsmdEnm4ZG:bh79p2m)*

**Comment by iphydf** [comment]
I'd recommend against using unsafe libraries.

**Comment by redmanmale** [comment]
> I don't approve of this change, I don't think toktok/c-toxcore is safe.

I'm confused a little. Since when core Tox library *is not safe* for using in the Tox clients?
We're using Toxcore v.0.1.4 right now and it's pretty outdated, why do we keep using it?

All our build are broken now; we need to either move to new Tox core or fix using old one.

**Comment by fcore117** [comment]
How it is fixable, what patches are needed for new toxcore? what are current security risk in simple layman terms?

**Comment by Piraty** [comment]
@iphydf as you originally stated toxcore was unsafe, and while you actively [promoted](https://github.com/TokTok/c-toxcore/issues/810) toxcore's 0.2.0 release, what is the current stance on utox and toxcore 0.2?

**Comment by iphydf** [comment]
My recommendation for projects that don't trust the TokTok version is to keep maintaining a fork and update that fork to upstream API changes, i.e. make it compatible, so that users can choose to use either and you don't need to maintain two forks of the client.

**Comment by yurivict** [comment]
@GrayHatter What do you mean when you say that ```c-toxcore``` is unsafe?  They just released 0.2. Is it not a good release?

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157#-:-L7GDHtVWRI3VSrZL6TJ:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157#-:-L7Q2dc3Kd-ZmY2o07r4:bnfp4nl)*

**Comment by eclipseo** [comment]
Any chance of a release using toxcore 0.2.0 soon?

**Comment by endoffile78** [comment]
@robinlinden Some of the travis builds are still building against 0.1.4.

**Comment by robinlinden** [comment]
Thanks. I could've sworn I fixed all of them, but I guess I deleted XP from the fork I did that in.

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1157#-:-L7WS7NKtbyp6M93S4bP:bnfp4nl)*

**Comment by Piraty** [comment]
@iphydf sorry for that unclear question.
ofc @GrayHatter originally stated that `toktok/c-toxcore` were unsafe and you didn't seem to object. i guess you don't share this view, so the question should have been addressed to @GrayHatter.

**Comment by robinlinden** [comment]
@GrayHatter @endoffile78 @redmanmale This passes CI now. Review status?

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1157#-:-L80O5PUAMm2sNRG4URX:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1157#-:-L7Vt3CkeeZkWwnq0vdl:b-uwkowd)*

**Comment by farseerfc** [comment]
Hi, sorry for asking questions in a PR. I want to ask when will this support be included in a future release? I don't see this PR tagged with 0.17 milestone, so may I assume that this will release as a 0.16.x before 0.17 ?
I tried to apply this PR as a patch onto 0.16.1 but resulted a lot of conflicts.

**Comment by endoffile78** [comment]
@farseerfc The next release most likely will be 0.17 and if you want this now you can build the develop branch. Instructions on how to compile uTox are here: https://github.com/uTox/uTox/blob/develop/docs/BUILD.md and if you need any help you can ask in #utox on freenode.

**Pull request merged**
