### PR TITLE
Initial version of chrono

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/846)

### CODE REVIEW

**Comment by GrayHatter** [comment]
This is a good start.

Then next function I need is a simple sleep with a basic callback when done. I'll add more information to IRC later, but it should be able to replace the tooltip threads we're using now.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/chrono.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/846#-KiE0ezGG7eBJF9Rw0UL:-KiE0ezHElcP2eV2N8zg:blbrgni) ([raw file](https://github.com/utox/utox/blob/7f7db68a0271e59381776d81b896f7354604fbfa/src/chrono.c#L15)):*
> ```C
>     chrono_thread_init = true;
>     CHRONO_INFO *info = args;
>     while(!info->finished) {
> ```

for the first one I want to use, I need something like `while (info->current != info->target) ...`

It won't work for every case, but let's start with that one.

---

*[src/chrono.h, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/846#-KiE-lMxzklGYZfGmIuG:-KiE-lMxzklGYZfGmIuH:bnuygjm) ([raw file](https://github.com/utox/utox/blob/7f7db68a0271e59381776d81b896f7354604fbfa/src/chrono.h#L10)):*
> ```objc
>     uint8_t *ptr;
>     int step;
>     uint32_t interval;
> ```

interval should probably be int32 so we can use it to decrement without changing chrono.c internals.

---

*[src/chrono.h, line 27 at r1](https://reviewable.io:443/reviews/utox/utox/846#-KiE0QgjBhhDkVgr1NU8:-KiE0QgjBhhDkVgr1NU9:bb6v925) ([raw file](https://github.com/utox/utox/blob/7f7db68a0271e59381776d81b896f7354604fbfa/src/chrono.h#L27)):*
> ```objc
> 
> /*
>  * Ehds the chrono thread
> ```

Ends

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/846#-:-KiE10OTZ2eTrBDzUhU0:bfawmwd)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/chrono.c, line 15 at r1](https://reviewable.io:443/reviews/utox/utox/846#-KiE0ezGG7eBJF9Rw0UL:-KiHWJtDHoy9xRGE8ujY:b-896fix) ([raw file](https://github.com/utox/utox/blob/7f7db68a0271e59381776d81b896f7354604fbfa/src/chrono.c#L15)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

for the first one I want to use, I need something like `while (info->current != info->target) ...`

It won't work for every case, but let's start with that one.
</blockquote></details>

Done.

---

*[src/chrono.h, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/846#-KiE-lMxzklGYZfGmIuG:-KiHduu96n03rCk2X92C:b3gcdf9) ([raw file](https://github.com/utox/utox/blob/7f7db68a0271e59381776d81b896f7354604fbfa/src/chrono.h#L10)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

interval should probably be int32 so we can use it to decrement without changing chrono.c internals.
</blockquote></details>

`interval` is how long it will sleep. `step` is what increments/decrements the pointer.

---

*[src/chrono.h, line 27 at r1](https://reviewable.io:443/reviews/utox/utox/846#-KiE0QgjBhhDkVgr1NU8:-KiHduWw0k1IxpLQMwn5:b-896fix) ([raw file](https://github.com/utox/utox/blob/7f7db68a0271e59381776d81b896f7354604fbfa/src/chrono.h#L27)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Ends
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/846)*

**Comment by GrayHatter** [comment]
+@grayhatter 

---

Reviewed 1 of 3 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/chrono.h, line 10 at r1](https://reviewable.io:443/reviews/utox/utox/846#-KiE-lMxzklGYZfGmIuG:-KiHp9w8NIUJK8ra9POO:b-pxfhg8) ([raw file](https://github.com/utox/utox/blob/7f7db68a0271e59381776d81b896f7354604fbfa/src/chrono.h#L10)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

`interval` is how long it will sleep. `step` is what increments/decrements the pointer.
</blockquote></details>

LGTM oh... yeah I would have realized that if I could read :/

---

*[src/chrono.h, line 35 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiHprhpV2vPA2d4uTO6:-KiHprhpV2vPA2d4uTO7:b-d1e2ws) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L35)):*
> ```objc
>  * Sleep and then
>  */
> void sleep_callback(uint32_t ms, void func(void *), void *funcargs);
> ```

`chrono_callback()` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/846#-:-KiHq4Qtn1rYM-rmXnzU:b-joyoeb)*

**Comment by robinlinden** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/chrono.c, line 1 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKNgcTW5LYxnqZ4k7h:-KiKNgcTW5LYxnqZ4k7i:b829bw0) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.c#L1)):*
> ```C
> #include "chrono.h"
> ```

Nit: Blank line after main include and sort the includes.

---

*[src/chrono.h, line 5 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKO48Z9PSshjSjRmaL:-KiKO48Z9PSshjSjRmaM:bu2ehre) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L5)):*
> ```objc
> 
> #include <stdint.h>
> #include <stdbool.h>
> ```

Nit: Not sorted.

---

*[src/chrono.h, line 10 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKNvjK48g83K6A4vCd:-KiKNvjK48g83K6A4vCe:b-y3chq2) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L10)):*
> ```objc
>     uint8_t *ptr, *target;
>     int step;
>     uint32_t interval; // in milliseconds
> ```

You could rename this to interval_ms and drop the comment.

---

*[src/chrono.h, line 16 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKO6r3i4mh5DpFwV3a:-KiKO6r3i4mh5DpFwV3b:b-35owuv) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L16)):*
> ```objc
> typedef struct chrono_info CHRONO_INFO;
> 
> bool chrono_thread_init = false;
> ```

`extern bool chrono_thread_init` in chrono.h and `bool chrono_thread_init = false` in chrono.c

---

*[tests/test_chrono.c, line 12 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKOyVoZN6PrKHmTxXC:-KiKOyVoZN6PrKHmTxXD:b-z78ya3) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/tests/test_chrono.c#L12)):*
> ```C
> START_TEST (test_chrono_finished)
> {
>     CHRONO_INFO *info = malloc(sizeof(CHRONO_INFO*));
> ```

I think you meant `sizeof(CHRONO_INFO)`

---

*[tests/test_chrono.c, line 37 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKP2uiIIoKehtzuIZP:-KiKP2uiIIoKehtzuIZQ:b-yuxx97) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/tests/test_chrono.c#L37)):*
> ```C
> START_TEST(test_chrono_target)
> {
>     CHRONO_INFO *info = malloc(sizeof(CHRONO_INFO*));
> ```

I think you meant `sizeof(CHRONO_INFO)`. Otherwise you're only getting the size of a pointer. (Probably way less than you want to allocate.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/846)*

**Comment by endoffile78** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/chrono.c, line 1 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKNgcTW5LYxnqZ4k7h:-KiLloTMBwbLkMlSwGXm:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.c#L1)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Nit: Blank line after main include and sort the includes.
</blockquote></details>

Done.

---

*[src/chrono.h, line 5 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKO48Z9PSshjSjRmaL:-KiLlpGXfHd3BaNZS8Sr:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L5)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Nit: Not sorted.
</blockquote></details>

Done.

---

*[src/chrono.h, line 10 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKNvjK48g83K6A4vCd:-KiLlqqn1-ncQ1cUWdHw:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L10)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You could rename this to interval_ms and drop the comment.
</blockquote></details>

Done.

---

*[src/chrono.h, line 16 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKO6r3i4mh5DpFwV3a:-KiLlrWCpEcw5qGM-y-V:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L16)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

`extern bool chrono_thread_init` in chrono.h and `bool chrono_thread_init = false` in chrono.c
</blockquote></details>

Done.

---

*[src/chrono.h, line 35 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiHprhpV2vPA2d4uTO6:-KiLls1WPTGvgII7Ktwv:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/src/chrono.h#L35)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`chrono_callback()` instead?
</blockquote></details>

Done.

---

*[tests/test_chrono.c, line 12 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKOyVoZN6PrKHmTxXC:-KiLlsp8NvYRVXUVFWlf:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/tests/test_chrono.c#L12)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I think you meant `sizeof(CHRONO_INFO)`
</blockquote></details>

Done.

---

*[tests/test_chrono.c, line 37 at r2](https://reviewable.io:443/reviews/utox/utox/846#-KiKP2uiIIoKehtzuIZP:-KiLlthMVnyVP3VRLLqO:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9168cf2fbba40442ff8946b5b54df4c8cfb8896/tests/test_chrono.c#L37)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

I think you meant `sizeof(CHRONO_INFO)`. Otherwise you're only getting the size of a pointer. (Probably way less than you want to allocate.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/846)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/846#-:-KiQNJLluPH91JofKcbW:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/846#-:-KiQwC8lPCovmB5fmsX2:bnfp4nl)*

**Pull request merged**
