### PR TITLE
Add confirmation to deleting friends

### LINKED ISSUE #615: Delete contacts confirmation
Please prevent accidental removal of contacts by adding confirmation button.

### PR DESCRIPTION
**Pull request by endoffile78**
Fixes #615

This change is [Reviewable](https://reviewable.io/reviews/utox/utox/715)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/flist.c, line 354 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcA9r_JCRbr2KdMm3gH:-KcA9r_JCRbr2KdMm3gI:b-suye3m) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/flist.c#L354)):*
> ```C
>             f->edit_history_length = edit_msg.history_length;
> 
>             panel_chat.disabled                    = true;
> ```

Do we not have a function to disable all panels? (I'm not 100% on this, but I think I've seen one like it.)

---

*[src/ui/draw_helpers.c, line 285 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcA99tYFj5m1doUmIGy:-KcA99tZe_40VknVS1nM:b-qxdzbi) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/draw_helpers.c#L285)):*
> ```C
> 
> void draw_friend_deletion(int UNUSED(x), int UNUSED(y), int UNUSED(w), int UNUSED(height)) {
>     FRIEND *f = (flist_get_selected()->data);
> ```

Remove superfluous parentheses.

---

*[src/ui/draw_helpers.c, line 290 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcA9GKt1gTr1io5XUYy:-KcA9GKt1gTr1io5XUYz:b-oe0rql) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/draw_helpers.c#L290)):*
> ```C
>     setfont(FONT_SELF_NAME);
> 
>     const int push = UTOX_STR_WIDTH(DELETE_MESSAGE);
> ```

This is great. This is what we should be doing. :D

---

*[src/ui/draw_helpers.c, line 292 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcAAemWijO3Pi7A5qhH:-KcAAemWijO3Pi7A5qhI:b-jl78ru) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/draw_helpers.c#L292)):*
> ```C
>     const int push = UTOX_STR_WIDTH(DELETE_MESSAGE);
>     drawstr(MAIN_LEFT + SCALE(10), SCALE(70), DELETE_MESSAGE);
>     drawtextrange(push + MAIN_LEFT + SCALE(20), settings.window_width, SCALE(70), f->name, f->name_length);
> ```

Do we need to add a question-mark after this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ui.c, line 306 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcC9a3rlUEVgs-_uT7K:-KcC9a3rlUEVgs-_uT7L:b-vwz2xp) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui.c#L306)):*
> ```C
> 
>     /* Confirm deletion */
>     CREATE_BUTTON(confirm_deletion, SCALE(10), MAIN_TOP + SCALE(40), SCALE(10), SCALE(40));
> ```

the button width is broken on my xlib, buttons will auto resize by the text, copy the width/height from how the "copy" button next to the ToxID.

Line 115 according to reviewable.

---

*[src/ui/buttons.c, line 671 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcC8wgjcjESAEqhOqcz:-KcC8wgjcjESAEqhOqd-:bwlxuwh) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/buttons.c#L671)):*
> ```C
>     .tooltip_text = {.i18nal = STR_YES},
>     .button_text  = {.i18nal = STR_YES},
>     .on_mup       = button_confirm_deletion_on_mup,
> ```

Both colors shouldn't be green. 

Also consider adding additional text; `Yes -- Really delete.`  `No -- keep friend` English is confusing enough, but other languages have different rules/traditions about, answering questions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by endoffile78** [comment]
Review status: 6 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/flist.c, line 354 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcA9r_JCRbr2KdMm3gH:-KcExv6qFWX7stRYKUhH:bsaob1s) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/flist.c#L354)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Do we not have a function to disable all panels? (I'm not 100% on this, but I think I've seen one like it.)
</blockquote></details>

There doesn't seem to be function that does that.

---

*[src/ui.c, line 306 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcC9a3rlUEVgs-_uT7K:-KcExyo8rzE1KYyNrB7Y:b-896fix) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui.c#L306)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

the button width is broken on my xlib, buttons will auto resize by the text, copy the width/height from how the "copy" button next to the ToxID.

Line 115 according to reviewable.
</blockquote></details>

Done.

---

*[src/ui/buttons.c, line 671 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcC8wgjcjESAEqhOqcz:-KcExzO5vYjYX3AFrSEc:b-896fix) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/buttons.c#L671)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Both colors shouldn't be green. 

Also consider adding additional text; `Yes -- Really delete.`  `No -- keep friend` English is confusing enough, but other languages have different rules/traditions about, answering questions.
</blockquote></details>

Done.

---

*[src/ui/draw_helpers.c, line 285 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcA99tYFj5m1doUmIGy:-KcEy-MnzFUAvbozdwGS:b-896fix) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/draw_helpers.c#L285)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Remove superfluous parentheses.
</blockquote></details>

Done.

---

*[src/ui/draw_helpers.c, line 290 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcA9GKt1gTr1io5XUYy:-KcEy-r-zxrXTh_iOIcq:b-rau31a) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/draw_helpers.c#L290)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This is great. This is what we should be doing. :D
</blockquote></details>

I think grayhatter was the first to do it. I just copied it. :P

---

*[src/ui/draw_helpers.c, line 292 at r1](https://reviewable.io:443/reviews/utox/utox/715#-KcAAemWijO3Pi7A5qhH:-KcEy7I-puReu79jLG1c:b-896fix) ([raw file](https://github.com/utox/utox/blob/1b89fcd2423b62e781777fce4d2f12e8ed1b5cc1/src/ui/draw_helpers.c#L292)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Do we need to add a question-mark after this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715#-:-KcEzpUusqTnoibV3GO_:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 6 of 11 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/draw_helpers.c, line 285 at r2](https://reviewable.io:443/reviews/utox/utox/715#-KcF8Jil4HWme2OMXoyN:-KcF8Jil4HWme2OMXoyO:b6hasye) ([raw file](https://github.com/utox/utox/blob/f9c81cff973e62fdba8aab651827604a7ef9f1ac/src/ui/draw_helpers.c#L285)):*
> ```C
> 
> void draw_friend_deletion(int UNUSED(x), int UNUSED(y), int UNUSED(w), int UNUSED(height)) {
>     FRIEND *f = flist_get_selected()->data;
> ```

make sure a friend is currently selected or you'll segv

---

*[src/ui/draw_helpers.c, line 291 at r2](https://reviewable.io:443/reviews/utox/utox/715#-KcF8F1E3hFmqMOd7mVD:-KcF8F1FTs_-vglyOQoI:bngkt9t) ([raw file](https://github.com/utox/utox/blob/f9c81cff973e62fdba8aab651827604a7ef9f1ac/src/ui/draw_helpers.c#L291)):*
> ```C
> 
>     char str[f->name_length + 1];
>     sprintf(str, "%s?", f->name);
> ```

use snprintf, && this will overrun

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by endoffile78** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/draw_helpers.c, line 285 at r2](https://reviewable.io:443/reviews/utox/utox/715#-KcF8Jil4HWme2OMXoyN:-KcGNovz2rKOH0AYhdTh:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9c81cff973e62fdba8aab651827604a7ef9f1ac/src/ui/draw_helpers.c#L285)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

make sure a friend is currently selected or you'll segv
</blockquote></details>

Done.

---

*[src/ui/draw_helpers.c, line 291 at r2](https://reviewable.io:443/reviews/utox/utox/715#-KcF8F1E3hFmqMOd7mVD:-KcGNpNm2XxfN2KCQn-i:b-896fix) ([raw file](https://github.com/utox/utox/blob/f9c81cff973e62fdba8aab651827604a7ef9f1ac/src/ui/draw_helpers.c#L291)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

use snprintf, && this will overrun
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by GrayHatter** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/draw_helpers.c, line 286 at r3](https://reviewable.io:443/reviews/utox/utox/715#-KcGSeyeCm1mIxvk4103:-KcGSeyfpcylzfGQpUOs:bi0a2dt) ([raw file](https://github.com/utox/utox/blob/fc62edc8f0532966b6ce6a5742e31dd76b93a3b3/src/ui/draw_helpers.c#L286)):*
> ```C
> void draw_friend_deletion(int UNUSED(x), int UNUSED(y), int UNUSED(w), int UNUSED(height)) {
>     FRIEND *f = flist_get_selected()->data;
>     if (f == NULL) {
> ```

`if (f == NULL || flist_get_selected()->item != ITEM_FRIEND) {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by endoffile78** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/draw_helpers.c, line 286 at r3](https://reviewable.io:443/reviews/utox/utox/715#-KcGSeyeCm1mIxvk4103:-KcGZrQuqXD7NI0lmAuB:b-896fix) ([raw file](https://github.com/utox/utox/blob/fc62edc8f0532966b6ce6a5742e31dd76b93a3b3/src/ui/draw_helpers.c#L286)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

`if (f == NULL || flist_get_selected()->item != ITEM_FRIEND) {`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715#-:-KcG_BVGmgw00Q9rzbtN:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/715#-:-KcLKly5n9zijxsJsqw8:bnfp4nl)*

**Pull request merged**
