### PR TITLE
Fixes for video not showing up on windows

### LINKED ISSUE #804: Video window doesn't open on Windows
Reported by Emcy on IRC.

Using Windows 7 uTox v0.14

### PR DESCRIPTION
**Pull request by GrayHatter**
closes #804

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/805)

### CODE REVIEW

**Comment by GrayHatter** [comment]
also

closes #790

**Comment by endoffile78** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/windows/os_video.c, line 87 at r1](https://reviewable.io:443/reviews/utox/utox/805#-KhAnIVu6sR9uc3wkwNM:-KhAnIVu6sR9uc3wkwNN:bslf2pn) ([raw file](https://github.com/utox/utox/blob/4019a88c55e52a44e42785bd700425aae14dd226/src/windows/os_video.c#L87)):*
> ```C
> 
> void video_end(uint32_t id) {
>     if (id == UINT16_MAX) {
> ```

Should == be >=?

---

*[src/windows/window.c, line 85 at r1](https://reviewable.io:443/reviews/utox/utox/805#-KhAnYInEl2xh3Mffsnu:-KhAnYInEl2xh3Mffsnv:byk0ozb) ([raw file](https://github.com/utox/utox/blob/4019a88c55e52a44e42785bd700425aae14dd226/src/windows/window.c#L85)):*
> ```C
>     if (!win) {
>         LOG_ERR("Windows WM", "ERROR trying to create video window");
>         LOG_ERR("debug", "%u", GetLastError());
> ```

Should there be a return here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/805)*

**Comment by GrayHatter** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/windows/os_video.c, line 87 at r1](https://reviewable.io:443/reviews/utox/utox/805#-KhAnIVu6sR9uc3wkwNM:-KhAydilA0IJ3Pz6MIBi:b-896fix) ([raw file](https://github.com/utox/utox/blob/4019a88c55e52a44e42785bd700425aae14dd226/src/windows/os_video.c#L87)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Should == be >=?
</blockquote></details>

Done.

---

*[src/windows/window.c, line 85 at r1](https://reviewable.io:443/reviews/utox/utox/805#-KhAnYInEl2xh3Mffsnu:-KhAyeOc-g6be6bccPpf:bq76gdd) ([raw file](https://github.com/utox/utox/blob/4019a88c55e52a44e42785bd700425aae14dd226/src/windows/window.c#L85)):*
<details><summary><i>Previously, endoffile78 (Endoffile) wrote…</i></summary><blockquote>

Should there be a return here?
</blockquote></details>

No, win is a null pointer, which is what I'd return anyways. so there's no point

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/805)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/native/video.h, line 13 at r2](https://reviewable.io:443/reviews/utox/utox/805#-KhC8MLLuY1O4xUjQXQg:-KhC8MLLuY1O4xUjQXQh:b-jzuswc) ([raw file](https://github.com/utox/utox/blob/44cae802ca0cd920d64e9d4f7b14e9f2ae5d90d7/src/native/video.h#L13)):*
> ```objc
>  * @param id          The id number of the friend
>  *                    Use UINT16_MAX for the preview window
>  *                    currently any value > UINT16_MAX will be treaded as the
> ```

Nit: s/treaded/treated
(Feel free to leave nits and someone can fix it the next time they touch the file.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/805#-:-KhC9_4FTpCAPDPF25QX:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/805#-:-KhCgCMXtr-gkRjztv8I:bnfp4nl)*

**Pull request merged**
