### PR TITLE
Don't leak memory if realloc fails.

### PR DESCRIPTION
**Pull request by robinlinden**
Doesn't really matter at this point, but maybe in the future, we don't want to exit() uTox when groupchats can't realloc.

Also adds more error-checks.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/746)

### CODE REVIEW

**Comment by cebe** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/groups.c, line 185 at r1](https://reviewable.io:443/reviews/utox/utox/746#-Kd3MOoBtxIeEUc3TsyQ:-Kd3MOoCpFSn10_4JKY9:b-adauw5) ([raw file](https://github.com/utox/utox/blob/8022bf1783c1f085749643343761de85f6ae497a/src/groups.c#L185)):*
> ```C
>             free(peer);
>             LOG_ERR("Groupchat", "Couldn't realloc for group peer name!");
>             exit(40);
> ```

shouldn't this be LOG_FATAL_ERR with exit code then? Also how do you decide for the 40, random?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/746)*

**Comment by robinlinden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/groups.c, line 185 at r1](https://reviewable.io:443/reviews/utox/utox/746#-Kd3MOoBtxIeEUc3TsyQ:-Kd3PX3ObThy4luWdm4Q:b-yoooo9) ([raw file](https://github.com/utox/utox/blob/8022bf1783c1f085749643343761de85f6ae497a/src/groups.c#L185)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

shouldn't this be LOG_FATAL_ERR with exit code then? Also how do you decide for the 40, random?
</blockquote></details>

You're right. We should also fix LOG_FATAL_ERR so it does its thing even if the verbosity level is 0. Right now it's just a worse LOG_ERR since we have to write the exit code twice.

Right now we don't have a system for error codes. A TODO is to add them to the debug header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/746)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/746)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/groups.c, line 185 at r1](https://reviewable.io:443/reviews/utox/utox/746#-Kd3MOoBtxIeEUc3TsyQ:-Kd4a1ns5K8xN50jqYe5:buqx099) ([raw file](https://github.com/utox/utox/blob/8022bf1783c1f085749643343761de85f6ae497a/src/groups.c#L185)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You're right. We should also fix LOG_FATAL_ERR so it does its thing even if the verbosity level is 0. Right now it's just a worse LOG_ERR since we have to write the exit code twice.

Right now we don't have a system for error codes. A TODO is to add them to the debug header.
</blockquote></details>

We should use `FATAL_ERR()` then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/746#-:-Kd4a9KeQWHfOSXpgB9A:bg7igkv)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/groups.c, line 185 at r1](https://reviewable.io:443/reviews/utox/utox/746#-Kd3MOoBtxIeEUc3TsyQ:-Kd6pSyRlb8P0I8EZcAl:b-896fix) ([raw file](https://github.com/utox/utox/blob/8022bf1783c1f085749643343761de85f6ae497a/src/groups.c#L185)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

We should use `FATAL_ERR()` then.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/746)*

**Pull request merged**
