### PR TITLE
Fix switches

### PR DESCRIPTION
**Pull request by tsudoko**
Sort of depends on #425
See #421 for more information, still WIP

image

Current progress:
- [x] ~~draw two vertical lines on top of the inner part~~
- [x] use disabled color when off
- [x] make the inner part smaller
- [x] make the outer part's edges rounded
- [x] add `on`/`off` icons (not sure if needed)
- [x] de-hardcode toggle positions
- [x] de-hardcode icon styles
- [x] ~~make the `on` icon not inverted~~ see #429

---
This change is [Reviewable](https://reviewable.io/reviews/grayhatter/utox/426)

### CODE REVIEW

**Comment by GrayHatter** [comment]
So far, I haven't seen anything worrying, but you're starting to get close to options overload.

I like everything so far, but I don't want to add too many decisions to switches, because they're supposed to be an easy UI element.

---

Reviewed 6 of 6 files at r1, 6 of 6 files at r2.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/426#-:-KR8cTbKf-SPnHz7xiEh:bsty52l)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/426)*

**Comment by tsudoko** [comment]
Do you think some graphics should be hardcoded? I can leave on/off icons as the only changeable graphics if the number of options is an issue.

**Comment by GrayHatter** [comment]
I thought I should say yes, even started writing a comment as such. But
before I could hit submit, it always seems like a better idea to have the
options.  Some toggles (in the future should/could be styled to be ON when
on the left, or red when you're specifically blocking some actions) In
those cases they way you're writing it makes much more sense.

**Comment by tsudoko** [comment]
What about the outer part and the toggle? I can't think of any case where using different outer/toggle graphics only for some switches would make sense.

**Comment by GrayHatter** [comment]
@tsudoko so I'm thinking of merging this ≈soon unless you want to add a few more commits/LOC?

**Pull request merged**
