### PR TITLE
Move copyright info to cmake.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/884)

### CODE REVIEW

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/884#-:-KiqBOcB4FM6uiF4V7zn:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/884#-:-KiqqpxVkx4fnyRzAx2f:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/884#-:-KivS0eq8vLHczRQBKVu:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

why?

---

Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/884#-:-KiwbwZIftZH7oKzT3fi:b-jwovug)*

**Comment by robinlinden** [comment]
We had the copyright notice in multiple places and they were starting to diverge. Better to make it easy for everyone and move it to one central location. :P

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/884#-:-Kj-9JQVD1qWLXZ1mFkp:b-amz2fs)*

**Pull request merged**
