### PR TITLE
Copy text from chat without nicks via CTRL-C in Windows

### PR DESCRIPTION
**Pull request by redmanmale**
the same as in Unix.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1504)

### CODE REVIEW

**Comment by avoidr** [comment]
Does Windows have "copy with names" in its context menu?

**Comment by avoidr** [comment]
You can actually say in commit message that it's now the same as in Unix.

**Comment by redmanmale** [comment]
>Does Windows have "copy with names" in its context menu?

Yes, but it's very annoying.

**Comment by avoidr** [comment]
What is annoying? I just want to know if users still have a way to copy with names after this patch.

Also, I think `s/username/nicks/` could be better. Shorter, and clearer.
And maybe also `s/shortcut/ctrl-c/`?

**Comment by redmanmale** [comment]
I mean "yes, there's a context menu item to copy with names".
This patch is to use "copy without names" with ctrl-c.

**Comment by avoidr** [comment]
My point is, can users still copy with names after this patch? It seems so, via right-click. The sane behaviour is to not copy names via ctrl-c, which this patch does. So this patch is fine and you're free to merge (preferably without merge commit for single commits).

**Pull request merged**
