### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1208)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 101 of 101 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1208#-:-LAeUX2R4IT9eKElXYar:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 101 of 101 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/utox/utox/1208#-:-LAitwP-8_us6uQ0biL2:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 92 of 101 files at r1, 4 of 12 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1208#-:-LD2tRDk38n4MkKqS7OV:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 92 of 101 files at r1, 4 of 12 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1208)*

**Pull request merged**
