### PR TITLE
Update de.h

### PR DESCRIPTION
**Pull request by avoidr**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1215)

### CODE REVIEW

**Comment by redmanmale** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[langs/de.h, line 390 at r1](https://reviewable.io/reviews/utox/utox/1215#-LBtwqb28eH3xaKPGmpO:-LBtwqb28eH3xaKPGmpP:bm5vtrt) ([raw file](https://github.com/utox/utox/blob/d96d309496d41c06eece682f9ae19ee79e541701/langs/de.h#L390)):*
> ```objc
> 
> msgid(COPY_TOX_ID)
> msgstr("Kopieren")
> ```

Same as just `Copy`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1215)*

**Comment by GrayHatter** [comment]
:lgtm:

+@cebe 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1215#-:-LBvrcAC0MX67mxOjAOI:brwa9n9)*

**Comment by avoidr** [comment]
>Same as just Copy?

Yes, I did this intentionally, because I find that "als Text kopieren" sounds much weirder than in English. And I find that "copy" is associated with text anyway, especially in this case which seems to make it obvious enough.

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1215#-:-LC38pvJ1NYaRVHmjQdj:bnfp4nl)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[langs/de.h, line 390 at r1](https://reviewable.io/reviews/utox/utox/1215#-LBtwqb28eH3xaKPGmpO:-LC395PpBBWRAAlgAOMw:bpd108f) ([raw file](https://github.com/utox/utox/blob/d96d309496d41c06eece682f9ae19ee79e541701/langs/de.h#L390)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

Same as just `Copy`?
</blockquote></details>

it's fine in that context

---


*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1215)*

**Comment by redmanmale** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/utox/utox/1215#-:-LC3BDqn5be54wA6FNCh:bnfp4nl)*

**Comment by avoidr** [comment]
Missing msgids:
REQ_ADDED_NO_FREQ_SENT
CALL_ENDED
STATUS_MESSAGE

Why the colons here? Doesn't seem to make sense:
```
msgid(IPV6)
msgstr("IPv6:")
msgid(UDP)
msgstr("UDP:")
```

For the english version, I would also write "QR code" as opposed to only "QR", even if it may be colloquial speech, since it's as wrong as only "IP" when "IP address" is meant, and as wrong as "LCD display".

```
msgid(DELETE_MESSAGE)
msgstr("Are you sure you want to delete ")
```
I found no german translation for this so that the friend is at the end of the sentence.
Possible translation:
`Bist du sicher, dass du %s löschen möchtest?`

What's the difference between `REMOVE_FRIEND` and `DELETE_FRIEND`?

Should I open a new issue with this?

**Comment by cebe** [comment]
> Should I open a new issue with this?

yes, comments on closed issues are likely to be forgotten soon.

**Pull request merged**
