### PR TITLE
Clean up and refactor UI code

### PR DESCRIPTION
**Pull request by robinlinden**
Removed the UTOX_SCALE macro (it was deprecated in favour of SCALE)

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/492)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 11 of 14 files at r1.
Review status: 7 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ui.h, line 171 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2VlS9jUgGMwOTyTWQ:-KX2VlS9jUgGMwOTyTWR:b-634f7t) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/ui.h#L171)):*
> ```objc
> 
> /* Main panel defines */
> #define MAIN_LEFT (SCALE(230)) + 1
> ```

What happens if you drop the +1?

---

*[src/ui.h, line 181 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2VrLeLoDAJVh8rTkA:-KX2VrLeLoDAJVh8rTkB:b-lgay6c) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/ui.h#L181)):*
> ```objc
> #define TIME_WIDTH (SCALE(40))
> #define ACTUAL_TIME_WIDTH (SCALE(32))
> #define NAME_OFFSET (SCALE(14))
> ```

none of the above need the surrounding `()`

---

*[src/windows/main.c, line 752 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2XFRitNaqe1DndylC:-KX2XFRitNaqe1DndylD:b-hgab4k) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/windows/main.c#L752)):*
> ```C
>     };
> 
> #define F(x) ((SCALE(-x * 2) - 1) / 2)
> ```

removed elsewhere but not here?

---

*[src/xlib/freetype.c, line 389 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2XRotg9vEJ4Rq8pUj:-KX2XRotg9vEJ4Rq8pUk:bef6fvg) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/xlib/freetype.c#L389)):*
> ```C
>     }
> 
> #define F(x) (SCALE(x) * 1.0)
> ```

is it *1.0 to make it a float? if so, typecast?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/492)*

**Comment by GrayHatter** [comment]
Reviewed 4 of 7 files at r2, 1 of 1 files at r3.
Review status: 12 of 14 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/492)*

**Comment by robinlinden** [comment]
Review status: 11 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/ui.h, line 171 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2VlS9jUgGMwOTyTWQ:-KX5QMOsBvLUwscp8aMn:b-sroizv) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/ui.h#L171)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> What happens if you drop the +1?
</details>
[These](http://i.imgur.com/tWvl3hE.png) 1px borders to the left of the right panel, by the message box and the friend header disappear. 

---

*[src/ui.h, line 181 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2VrLeLoDAJVh8rTkA:-KX5O0NfVgXq7afsnJWs:b-896fix) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/ui.h#L181)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> none of the above need the surrounding `()`
</details>
Done.

---

*[src/windows/main.c, line 752 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2XFRitNaqe1DndylC:-KX5TmREaXmRIobg6F6j:b-v6s1r5) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/windows/main.c#L752)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> removed elsewhere but not here?
</details>
Removed*.

---

*[src/xlib/freetype.c, line 389 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2XRotg9vEJ4Rq8pUj:-KX5NsHj8nZhGzCV5QYd:b-442hu5) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/xlib/freetype.c#L389)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> is it *1.0 to make it a float? if so, typecast?
</details>
I found that we have a macro called UI_FSCALE that returns a float, so no typecasting needed after all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/492)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 14 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui.h, line 171 at r1](https://reviewable.io:443/reviews/utox/utox/492#-KX2VlS9jUgGMwOTyTWQ:-KX5_xAWvZcjQdjRnMcL:b-ktfnsl) ([raw file](https://github.com/utox/utox/blob/b12e90f972015fa93709a83d0cfa016edc9f7fd6/src/ui.h#L171)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary>
> [These](http://i.imgur.com/tWvl3hE.png) 1px borders to the left of the right panel, by the message box and the friend header disappear. 
</details>
good, kill it with fire. That's a ui bug that shouldn't exist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/492#-:-KX5aPLZMt3XXaUYQdlT:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/492#-:-KX5aWghnvWaHpwFZC5X:b-uwkowd)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/492)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/492)*

**Pull request merged**
