### PR TITLE
[Windows] Allow multiple portable instances of uTox to run concurrently

### LINKED ISSUE #898: Allow multiple portable instances of uTox to run concurrently
https://github.com/uTox/uTox/blob/develop/src/windows/main.c#L811
`static bool win_init_mutex(HANDLE *mutex, HINSTANCE hInstance, PSTR cmd)` needs to be updated. Wouldn't be much work. Check if we're in portable mode or something along those lines and use pwd for the mutex if we are.

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #898.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1061)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 844 at r1](https://reviewable.io:443/reviews/utox/utox/1061#-KuQtVMlzOCLRmLkqmZz:-KuQtVMlzOCLRmLkqm_-:b7nq2e4) ([raw file](https://github.com/utox/utox/blob/d4a114768a2221762f35a5a63d33154582ed05e4/src/windows/main.c#L844)):*
> ```C
>         GetModuleFileName(hModule, path, MAX_PATH);
> 
>         char *utox_folder = dirname(strdup(path));
> ```

does this leak?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061#-:-KuQt_gHcpnK8vLu0hP-:bnfp4nl)*

**Comment by redmanmale** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/windows/main.c, line 844 at r1](https://reviewable.io:443/reviews/utox/utox/1061#-KuQtVMlzOCLRmLkqmZz:-KuR-kMOdbHe0B0AWc7T:bf0tujz) ([raw file](https://github.com/utox/utox/blob/d4a114768a2221762f35a5a63d33154582ed05e4/src/windows/main.c#L844)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

does this leak?
</blockquote></details>

If got it right, it doesn't.

https://linux.die.net/man/3/dirname
Both dirname() and basename() return pointers to null-terminated strings. Do not pass these pointers to `free`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061)*

**Comment by robinlinden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/windows/main.c, line 844 at r1](https://reviewable.io:443/reviews/utox/utox/1061#-KuQtVMlzOCLRmLkqmZz:-KuR219DbzvqPTuqcbEA:b-se7114) ([raw file](https://github.com/utox/utox/blob/d4a114768a2221762f35a5a63d33154582ed05e4/src/windows/main.c#L844)):*
<details><summary><i>Previously, redmanmale (redmanmale) wrote…</i></summary><blockquote>

If got it right, it doesn't.

https://linux.die.net/man/3/dirname
Both dirname() and basename() return pointers to null-terminated strings. Do not pass these pointers to `free`.
</blockquote></details>

The return value of strdup has to be freed.

---

*[src/windows/main.c, line 849 at r1](https://reviewable.io:443/reviews/utox/utox/1061#-KuR2UkEPcYNvbxObhJX:-KuR2UkEPcYNvbxObhJY:b-45locp) ([raw file](https://github.com/utox/utox/blob/d4a114768a2221762f35a5a63d33154582ed05e4/src/windows/main.c#L849)):*
> ```C
>         strcpy(portable_mode_save_path, utox_folder);
>     } else {
>         GetModuleFileName(NULL, path, MAX_PATH);
> ```

This will still let me open 2 instances of uTox using my `%APPDATA%\tox`profile for as long as I open them from different folders. Maybe rename `path` to `instance_id` or something and give it "uTox" if we're not in portable mode. Or you could always use the path of the `tox_save.tox` we're loading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061)*

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061)*

**Comment by redmanmale** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/windows/main.c, line 844 at r1](https://reviewable.io:443/reviews/utox/utox/1061#-KuQtVMlzOCLRmLkqmZz:-KuV_n9EXBaGr_838B3h:b-896fix) ([raw file](https://github.com/utox/utox/blob/d4a114768a2221762f35a5a63d33154582ed05e4/src/windows/main.c#L844)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

The return value of strdup has to be freed.
</blockquote></details>

Done.

---

*[src/windows/main.c, line 849 at r1](https://reviewable.io:443/reviews/utox/utox/1061#-KuR2UkEPcYNvbxObhJX:-KuV_o7CDjTpWdAkKmIZ:b-896fix) ([raw file](https://github.com/utox/utox/blob/d4a114768a2221762f35a5a63d33154582ed05e4/src/windows/main.c#L849)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This will still let me open 2 instances of uTox using my `%APPDATA%\tox`profile for as long as I open them from different folders. Maybe rename `path` to `instance_id` or something and give it "uTox" if we're not in portable mode. Or you could always use the path of the `tox_save.tox` we're loading.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061#-:-KuVhKTWh4NpbZwXU2b9:bnfp4nl)*

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/1061#-:-KxGdsHqdpEbi79sTUxl:bnfp4nl)*

**Pull request merged**
