### PR TITLE
Remove files generated by cmake from git.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/885)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/885#-:-KiqBsBGLc-7GYfd_-Cd:bnfp4nl)*

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/885#-:-KiqBbXP_qC4bFk9KsGt:bnfp4nl)*

**Comment by GrayHatter** [comment]
This shouldn't have been merged. 

The android file is used outside of cmake.

The branding file is greppable and should be committed to the repo.

No comment on the macOS file, but likely ditto of the above.

**Comment by GrayHatter** [comment]
#895

**Pull request merged**
