### PR TITLE
Close dropdowns on changing tabs

### LINKED ISSUE #1244: Dropdown lists stay displayed when changing setting tabs
### Overview

1. uTox version: 234f027a9f2a93596ecfd543c98131b8673b8d2d
2. Operating system: GNU+Linux
3. Desktop Environment/Window Manager (Linux/BSD only): dwm

### Issue

When activating a dropdown list to show all items and clicking on another tab, the dropdown list stays expanded and displayed, but isn't clickable. The dropdown list undisplays/unexpands, when going back to the tab that the dropdown list originally comes from.

### PR DESCRIPTION
**Pull request by redmanmale**
Fixes #1244.

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1296)

### CODE REVIEW

**Comment by avoidr** [comment]
Yes, it closes dropdowns when changing setting tabs. But it doesn't close dropdowns when clicking on a friend on the friend list.

Also the password and nospam buttons that I mentioned in the issue; they bug when you switch to a friend, too. I wasn't clear enough, sorry.

**Comment by avoidr** [comment]
`close_dropdowns_recursively`: I would `s/_recursively//`; I would write it as a comment, rather than encode it in the name.

Perhaps the `while` could be a `for` and be a little more idiomatic?

**Comment by redmanmale** [comment]
@robinlinden
Could you take a look?

**Comment by redmanmale** [comment]
Bump.

**Pull request merged**
