### PR TITLE
Fix warnings part 2

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/657)

### CODE REVIEW

**Comment by endoffile78** [comment]
:lgtm:

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/657#-:-KbCIMI4wksh3aYn9IIO:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/flist.c, line 704 at r1](https://reviewable.io:443/reviews/utox/utox/657#-KbCGuQd_9XRd5StdMoI:-KbCGuQd_9XRd5StdMoJ:bbln7v6) ([raw file](https://github.com/utox/utox/blob/2cd74bdaef5b9dc29fc80b492ad420151878854f/src/flist.c#L704)):*
> ```C
> }
> 
> void flist_selectchat(int index) {
> ```

Maybe this should accept an uint instead. A negative index wouldn't make much sense.

---

*[src/xlib/event.c, line 75 at r1](https://reviewable.io:443/reviews/utox/utox/657#-KbCL-fL6jB1PY2pjnxo:-KbCL-fMfZswmJRLUerl:bjwuxr5) ([raw file](https://github.com/utox/utox/blob/2cd74bdaef5b9dc29fc80b492ad420151878854f/src/xlib/event.c#L75)):*
> ```C
> 
>             havefocus      = 1;
>             XWMHints hints = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
> ```

The C standard says that `{ 0 }` is enough. A warning on this is a bug. (it's apparently reported too. See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119 )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/657#-:-KbCMcDxy5dFXSRh-D1n:bnfp4nl)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/flist.c, line 704 at r1](https://reviewable.io:443/reviews/utox/utox/657#-KbCGuQd_9XRd5StdMoI:-KbE2E2tWd9MtYKOXQQt:bamuqwh) ([raw file](https://github.com/utox/utox/blob/2cd74bdaef5b9dc29fc80b492ad420151878854f/src/flist.c#L704)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Maybe this should accept an uint instead. A negative index wouldn't make much sense.
</blockquote></details>

that's what I was going to do, but I decided aginst it because I didn't want to spend the time proving that it wouldn't try to send -1 if the mouse was just over the first entry in the list.

---

*[src/xlib/event.c, line 75 at r1](https://reviewable.io:443/reviews/utox/utox/657#-KbCL-fL6jB1PY2pjnxo:-KbESLchCE4ho2Whc_2f:bgfc1cr) ([raw file](https://github.com/utox/utox/blob/2cd74bdaef5b9dc29fc80b492ad420151878854f/src/xlib/event.c#L75)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

The C standard says that `{ 0 }` is enough. A warning on this is a bug. (it's apparently reported too. See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119 )
</blockquote></details>

This is still correct either way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/657)*

**Comment by cebe** [comment]
:lgtm:

---

Reviewed 20 of 21 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/657#-:-KbEW_yug6swsmYYQZ4p:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 11 of 15 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/657#-:-KbF8fzr6Zg-dA6KW5wd:bnfp4nl)*

**Pull request merged**
