### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by endoffile78**
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/799)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799#-:-Kh9gMD0T30l9pm7FGz0:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799#-:-Kh9iS8D6zfHIZWsv-zK:bnfp4nl)*

**Comment by robinlinden** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r3, 1 of 5 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[extra/common/filter_audio.sh, line 5 at r5](https://reviewable.io:443/reviews/utox/utox/799#-KhjPKMUjBUZ-3W6zWCC:-KhjPKMVAZnHSp3xg9Jv:bktsana) ([raw file](https://github.com/utox/utox/blob/17363ba60ddc8fa56fcc2b92eab1b64563422985/extra/common/filter_audio.sh#L5)):*
> ```Shell
> set -eux
> 
> . ./extra/travis/env.sh
> ```

don't include travis/ from common

---

*[extra/travis/windows-before.sh, line 75 at r5](https://reviewable.io:443/reviews/utox/utox/799#-KhjPlK8piETCmXxvp3k:-KhjPlK8piETCmXxvp3l:b-l0sksg) ([raw file](https://github.com/utox/utox/blob/17363ba60ddc8fa56fcc2b92eab1b64563422985/extra/travis/windows-before.sh#L75)):*
> ```Shell
> 
> # filter_audio
> export CC=x86_64-w64-mingw32-gcc
> ```

I'm not sure about this, let me look into it

---

*[src/tox.c, line 36 at r5](https://reviewable.io:443/reviews/utox/utox/799#-KhjQ0xul4e3EA_PODgn:-KhjQ0xul4e3EA_PODgo:b-ja4mr1) ([raw file](https://github.com/utox/utox/blob/17363ba60ddc8fa56fcc2b92eab1b64563422985/src/tox.c#L36)):*
> ```C
> #include <stdlib.h>
> #include <string.h>
> #include <tox/tox.h>
> ```

why wasn't this failing before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[extra/common/filter_audio.sh, line 5 at r5](https://reviewable.io:443/reviews/utox/utox/799#-KhjPKMUjBUZ-3W6zWCC:-KhjSM_2fA-wIRd3Lh7Z:bb6ywmx) ([raw file](https://github.com/utox/utox/blob/17363ba60ddc8fa56fcc2b92eab1b64563422985/extra/common/filter_audio.sh#L5)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

don't include travis/ from common
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 5 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799)*

**Comment by endoffile78** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[extra/common/filter_audio.sh, line 5 at r5](https://reviewable.io:443/reviews/utox/utox/799#-KhjPKMUjBUZ-3W6zWCC:-KhjS6WPBZxbkvyhP8sX:b-896fix) ([raw file](https://github.com/utox/utox/blob/17363ba60ddc8fa56fcc2b92eab1b64563422985/extra/common/filter_audio.sh#L5)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

don't include travis/ from common
</blockquote></details>

Done.

---

*[extra/travis/windows-before.sh, line 75 at r5](https://reviewable.io:443/reviews/utox/utox/799#-KhjPlK8piETCmXxvp3k:-KhjSQzjoaqJ0FLNSYjN:b1zfqug) ([raw file](https://github.com/utox/utox/blob/17363ba60ddc8fa56fcc2b92eab1b64563422985/extra/travis/windows-before.sh#L75)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I'm not sure about this, let me look into it
</blockquote></details>

Yeah I'm not really sure why its that way I just copied that part over from the gitlab script.

---

*[src/tox.c, line 36 at r5](https://reviewable.io:443/reviews/utox/utox/799#-KhjQ0xul4e3EA_PODgn:-KhjS8WeWpMAhrjlw-kW:b4cqxyf) ([raw file](https://github.com/utox/utox/blob/17363ba60ddc8fa56fcc2b92eab1b64563422985/src/tox.c#L36)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

why wasn't this failing before?
</blockquote></details>

This actually isnt needed main.h includes tox.h. I added it when I was trying to find the fix for the toxencryptsave linker error. I can get rid of if you want me to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799#-:-KhrPF0jk6GgTLecfcEG:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/799#-:-Khta_z-3kJH2wN3oOJ8:bnfp4nl)*

**Pull request merged**
