### PR TITLE
update macOS release link

### PR DESCRIPTION
**Pull request by publicarray**
also OSX is now macOS 

https://www.apple.com/au/macos/sierra/

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/999)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 18 at r1](https://reviewable.io:443/reviews/utox/utox/999#-KsAbf_V6dnA9LRG5M-M:-KsAbf_V6dnA9LRG5M-N:bufbc07) ([raw file](https://github.com/utox/utox/blob/e87540cff771a1461c775be321eacb61c53062c0/README.md#L18)):*
> ```Markdown
>  * [static x86](https://build.tox.chat/view/uTox/job/uTox_build_linux_x86_release/lastSuccessfulBuild/artifact/utox_linux_x86.tar.xz)
> * **macOS**
>  * [Last Updated .dmg](https://github.com/uTox/uTox/releases/download/v0.16.0/uTox-0.16.0.dmg) -- *could be out of date, check the version list below*
> ```

Should we add a latest folder for OSX so we dont have to update the link every release?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/999)*

**Comment by robinlinden** [comment]
@endoffile78 I think ideally we'd host it on https://utox.io the same way we do for the other builds.

**Comment by redmanmale** [comment]
Update this section too: https://github.com/uTox/uTox/blob/develop/docs/INSTALL.md#os-x

**Comment by redmanmale** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/999#-:-KsXWvtIE3yLZBmAgMAx:bnfp4nl)*

**Comment by robinlinden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/utox/utox/999#-:-KsYO-55o7cR3hCB3ZSi:bnfp4nl)*

**Pull request merged**
